/*
 * dmpr_pes_desc.h
 * Copyright (C) 2007-2010 ACCESS CO.,LTD.
 * All rights are reserved by ACCESS CO.,LTD.,
 * whether the whole or part of the source code
 * including any modifications is concerned.
 *
 * This is an unpublished source code of ACCESS CO.,LTD., and must be
 * treated as confidential material.  The above copyright notice does
 * not evidence any actual or intended publication of this source code.
 */

#ifndef DMPR_PES_DESC_H_
#define DMPR_PES_DESC_H_
#define DMPR_PES_DESC SLIM_T(\
"<?xml version=\"1.0\"?>\n"\
"<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">\n"\
"<specVersion>\n"\
"<major>1</major>\n"\
"<minor>0</minor>\n"\
"</specVersion>\n"\
"<actionList>\n"\
"<action>\n"\
"<name>CancelJob</name>\n"\
"<argumentList>\n"\
"<argument>\n"\
"<name>JobId</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>JobId</relatedStateVariable>\n"\
"</argument>\n"\
"</argumentList>\n"\
"</action>\n"\
"<action>\n"\
"<name>CreateJob</name>\n"\
"<argumentList>\n"\
"<argument>\n"\
"<name>JobName</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>JobName</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>JobOriginatingUserName</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>JobOriginatingUserName</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>DocumentFormat</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>DocumentFormat</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>Copies</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>Copies</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>Sides</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>Sides</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>NumberUp</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>NumberUp</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>OrientationRequested</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>OrientationRequested</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>MediaSize</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>MediaSize</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>MediaType</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>MediaType</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>PrintQuality</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>PrintQuality</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>JobId</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>JobId</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>DataSink</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>DataSink</relatedStateVariable>\n"\
"</argument>\n"\
"</argumentList>\n"\
"</action>\n"\
"<action>\n"\
"<name>CreateJobV2</name>\n"\
"<argumentList>\n"\
"<argument>\n"\
"<name>JobName</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>JobName</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>JobOriginatingUserName</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>JobOriginatingUserName</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>DocumentFormat</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>DocumentFormat</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>Copies</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>Copies</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>Sides</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>Sides</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>NumberUp</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>NumberUp</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>OrientationRequested</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>OrientationRequested</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>MediaSize</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>MediaSize</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>MediaType</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>MediaType</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>PrintQuality</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>PrintQuality</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>CriticalAttributesList</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>A_ARG_TYPE_CriticalAttribList</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>JobId</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>JobId</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>DataSink</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>DataSink</relatedStateVariable>\n"\
"</argument>\n"\
"</argumentList>\n"\
"</action>\n"\
"<action>\n"\
"<name>CreateURIJob</name>\n"\
"<argumentList>\n"\
"<argument>\n"\
"<name>JobName</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>JobName</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>JobOriginatingUserName</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>JobOriginatingUserName</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>DocumentFormat</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>DocumentFormat</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>Copies</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>Copies</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>Sides</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>Sides</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>NumberUp</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>NumberUp</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>OrientationRequested</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>OrientationRequested</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>MediaSize</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>MediaSize</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>MediaType</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>MediaType</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>PrintQuality</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>PrintQuality</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>CriticalAttributesList</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>A_ARG_TYPE_CriticalAttribList</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>SourceURI</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>SourceURI</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>JobId</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>JobId</relatedStateVariable>\n"\
"</argument>\n"\
"</argumentList>\n"\
"</action>\n"\
"<action>\n"\
"<name>GetJobAttributes</name>\n"\
"<argumentList>\n"\
"<argument>\n"\
"<name>JobId</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>JobId</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>JobName</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>JobName</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>JobOriginatingUserName</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>JobOriginatingUserName</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>JobMediaSheetsCompleted</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>JobMediaSheetsCompleted</relatedStateVariable>\n"\
"</argument>\n"\
"</argumentList>\n"\
"</action>\n"\
"<action>\n"\
"<name>GetMargins</name>\n"\
"<argumentList>\n"\
"<argument>\n"\
"<name>MediaSize</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>MediaSize</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>MediaType</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>MediaType</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>PageMargins</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>PageMargins</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>FullBleedSupported</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>FullBleedSupported</relatedStateVariable>\n"\
"</argument>\n"\
"</argumentList>\n"\
"</action>\n"\
"<action>\n"\
"<name>GetMediaList</name>\n"\
"<argumentList>\n"\
"<argument>\n"\
"<name>MediaSize</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>MediaSize</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>MediaType</name>\n"\
"<direction>in</direction>\n"\
"<relatedStateVariable>MediaType</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>MediaList</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>A_ARG_TYPE_MediaList</relatedStateVariable>\n"\
"</argument>\n"\
"</argumentList>\n"\
"</action>\n"\
"<action>\n"\
"<name>GetPrinterAttributes</name>\n"\
"<argumentList>\n"\
"<argument>\n"\
"<name>PrinterState</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>PrinterState</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>PrinterStateReasons</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>PrinterStateReasons</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>JobIdList</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>JobIdList</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>JobId</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>JobId</relatedStateVariable>\n"\
"</argument>\n"\
"</argumentList>\n"\
"</action>\n"\
"<action>\n"\
"<name>GetPrinterAttributesV2</name>\n"\
"<argumentList>\n"\
"<argument>\n"\
"<name>PrinterState</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>PrinterState</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>PrinterStateReasons</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>PrinterStateReasons</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>JobIdList</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>JobIdList</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>JobId</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>JobId</relatedStateVariable>\n"\
"</argument>\n"\
"<argument>\n"\
"<name>InternetConnectState</name>\n"\
"<direction>out</direction>\n"\
"<relatedStateVariable>InternetConnectState</relatedStateVariable>\n"\
"</argument>\n"\
"</argumentList>\n"\
"</action>\n"\
"</actionList>\n"\
"<serviceStateTable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>A_ARG_TYPE_CriticalAttribList</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue>none</defaultValue>\n"\
"<allowedValueList>\n"\
"<allowedValue>none</allowedValue>\n"\
"<allowedValue>copies</allowedValue>\n"\
"<allowedValue>sides</allowedValue>\n"\
"<allowedValue>number-up</allowedValue>\n"\
"<allowedValue>orientation-requested</allowedValue>\n"\
"<allowedValue>media-size</allowedValue>\n"\
"<allowedValue>media-type</allowedValue>\n"\
"<allowedValue>print-quality</allowedValue>\n"\
"<allowedValue>text-layout</allowedValue>\n"\
"<allowedValue>image-layout</allowedValue>\n"\
"<allowedValue>image-orientation</allowedValue>\n"\
"<allowedValue>pdl-fidelity</allowedValue>\n"\
"<allowedValue>font-family</allowedValue>\n"\
"<allowedValue>font-size</allowedValue>\n"\
"</allowedValueList>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>A_ARG_TYPE_MediaList</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue></defaultValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>A_ARG_TYPE_PrinterAbortReason</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue></defaultValue>\n"\
"<allowedValueList>\n"\
"<allowedValue>hardware-error</allowedValue>\n"\
"<allowedValue>external-access-uri-not-found</allowedValue>\n"\
"<allowedValue>external-access-object-failure</allowedValue>\n"\
"<allowedValue>external-access-doc-format-err</allowedValue>\n"\
"<allowedValue>external-access-http-error</allowedValue>\n"\
"</allowedValueList>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>CharRepSupported</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue></defaultValue>\n"\
"<allowedValue>iana_iso_8859-1</allowedValue>\n"\
"<allowedValue>iana_Shift_JIS</allowedValue>\n"\
"<allowedValue>unicode_katakana</allowedValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>ColorSupported</name>\n"\
"<dataType>boolean</dataType>\n"\
"<defaultValue>0</defaultValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"yes\">\n"\
"<name>ContentCompleteList</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue></defaultValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>Copies</name>\n"\
"<dataType>i4</dataType>\n"\
"<defaultValue>1</defaultValue>\n"\
"<allowedValueRange>\n"\
"<minimum>0</minimum>\n"\
"<maximum>2147483647</maximum>\n"\
"<step>1</step>\n"\
"</allowedValueRange>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>CriticalAttributesSupported</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue>none</defaultValue>\n"\
"<allowedValueList>\n"\
"<allowedValue>none</allowedValue>\n"\
"<allowedValue>copies</allowedValue>\n"\
"<allowedValue>sides</allowedValue>\n"\
"<allowedValue>number-up</allowedValue>\n"\
"<allowedValue>orientation-requested</allowedValue>\n"\
"<allowedValue>media-size</allowedValue>\n"\
"<allowedValue>media-type</allowedValue>\n"\
"<allowedValue>print-quality</allowedValue>\n"\
"<allowedValue>text-layout</allowedValue>\n"\
"<allowedValue>image-layout</allowedValue>\n"\
"<allowedValue>image-orientation</allowedValue>\n"\
"<allowedValue>pdl-fidelity</allowedValue>\n"\
"<allowedValue>font-family</allowedValue>\n"\
"<allowedValue>font-size</allowedValue>\n"\
"</allowedValueList>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>DataSink</name>\n"\
"<dataType>uri</dataType>\n"\
"<defaultValue></defaultValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>DeviceId</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue>MANUFACTURER:ACCESS CO.,LTD.;\n"\
"COMMAND SET:XHTML-Print;\n"\
"MODEL:Access default printer;\n"\
"COMMENT:ACCESS CO.,LTD.;\n"\
"ACTIVE COMMAND SET:XHTML-Print;</defaultValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>DocumentFormat</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue>application/xhtml-print</defaultValue>\n"\
"<allowedValueList>\n"\
"<allowedValue>unknown</allowedValue>\n"\
"<allowedValue>application/xhtml-print</allowedValue>\n"\
"<allowedValue>application/xhtml-print-e</allowedValue>\n"\
"<allowedValue>application/vnd.pwg-xhtml-print</allowedValue>\n"\
"<allowedValue>application/octet-stream</allowedValue>\n"\
"<allowedValue>text/plain</allowedValue>\n"\
"<allowedValue>text/plain;charset=utf-8</allowedValue>\n"\
"<allowedValue>application/postscript</allowedValue>\n"\
"<allowedValue>application/vnd.hp-PCL</allowedValue>\n"\
"</allowedValueList>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>DocumentUTF16Supported</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue></defaultValue>\n"\
"<allowedValueList>\n"\
"<allowedValue>none</allowedValue>\n"\
"<allowedValue>all</allowedValue>\n"\
"<allowedValue>application/xhtml-print</allowedValue>\n"\
"<allowedValue>application/xhtml-print-e</allowedValue>\n"\
"<allowedValue>application/octet-stream</allowedValue>\n"\
"<allowedValue>text/plain</allowedValue>\n"\
"<allowedValue>text/plain;charset=utf-8</allowedValue>\n"\
"<allowedValue>application/postscript</allowedValue>\n"\
"<allowedValue>application/vnd.hp-PCL</allowedValue>\n"\
"</allowedValueList>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>FullBleedSupported</name>\n"\
"<dataType>boolean</dataType>\n"\
"<defaultValue>0</defaultValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>InternetConnectState</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue>unknown</defaultValue>\n"\
"<allowedValueList>\n"\
"<allowedValue>unknown</allowedValue>\n"\
"<allowedValue>connected</allowedValue>\n"\
"<allowedValue>not-connected</allowedValue>\n"\
"</allowedValueList>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"yes\">\n"\
"<name>JobAbortState</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue></defaultValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"yes\">\n"\
"<name>JobEndState</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue></defaultValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>JobId</name>\n"\
"<dataType>i4</dataType>\n"\
"<defaultValue>0</defaultValue>\n"\
"<allowedValueRange>\n"\
"<minimum>0</minimum>\n"\
"<maximum>2147483647</maximum>\n"\
"<step>1</step>\n"\
"</allowedValueRange>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"yes\">\n"\
"<name>JobIdList</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue></defaultValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"yes\">\n"\
"<name>JobMediaSheetsCompleted</name>\n"\
"<dataType>i4</dataType>\n"\
"<defaultValue>0</defaultValue>\n"\
"<allowedValueRange>\n"\
"<minimum>-1</minimum>\n"\
"<maximum>2147483647</maximum>\n"\
"<step>1</step>\n"\
"</allowedValueRange>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>JobName</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue></defaultValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>JobOriginatingUserName</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue></defaultValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>MediaSize</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue>none</defaultValue>\n"\
"<allowedValueList>\n"\
"<allowedValue>none</allowedValue>\n"\
"<allowedValue>device-setting</allowedValue>\n"\
"</allowedValueList>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>MediaType</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue>stationery</defaultValue>\n"\
"<allowedValueList>\n"\
"<allowedValue>none</allowedValue>\n"\
"<allowedValue>stationery</allowedValue>\n"\
"<allowedValue>stationery-inkjet</allowedValue>\n"\
"<allowedValue>transparency</allowedValue>\n"\
"<allowedValue>envelope</allowedValue>\n"\
"<allowedValue>labels</allowedValue>\n"\
"<allowedValue>photographic</allowedValue>\n"\
"<allowedValue>photographic-glossy</allowedValue>\n"\
"<allowedValue>photographic-matte</allowedValue>\n"\
"<allowedValue>cardstock</allowedValue>\n"\
"<allowedValue>device-setting</allowedValue>\n"\
"</allowedValueList>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>NumberUp</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue>1</defaultValue>\n"\
"<allowedValueList>\n"\
"<allowedValue>1</allowedValue>\n"\
"<allowedValue>2</allowedValue>\n"\
"<allowedValue>4</allowedValue>\n"\
"<allowedValue>device-setting</allowedValue>\n"\
"</allowedValueList>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>OrientationRequested</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue>portrait</defaultValue>\n"\
"<allowedValueList>\n"\
"<allowedValue>portrait</allowedValue>\n"\
"<allowedValue>landscape</allowedValue>\n"\
"<allowedValue>reverse-landscape</allowedValue>\n"\
"<allowedValue>reverse-portrait</allowedValue>\n"\
"<allowedValue>device-setting</allowedValue>\n"\
"</allowedValueList>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>PageMargins</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue></defaultValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>PrinterLocation</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue></defaultValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>PrinterName</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue></defaultValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>PrintQuality</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue>normal</defaultValue>\n"\
"<allowedValueList>\n"\
"<allowedValue>draft</allowedValue>\n"\
"<allowedValue>normal</allowedValue>\n"\
"<allowedValue>high</allowedValue>\n"\
"<allowedValue>device-setting</allowedValue>\n"\
"</allowedValueList>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"yes\">\n"\
"<name>PrinterState</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue>idle</defaultValue>\n"\
"<allowedValueList>\n"\
"<allowedValue>idle</allowedValue>\n"\
"<allowedValue>processing</allowedValue>\n"\
"<allowedValue>stopped</allowedValue>\n"\
"</allowedValueList>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"yes\">\n"\
"<name>PrinterStateReasons</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue>none</defaultValue>\n"\
"<allowedValueList>\n"\
"<allowedValue>none</allowedValue>\n"\
"<allowedValue>attention-required</allowedValue>\n"\
"<allowedValue>media-jam</allowedValue>\n"\
"<allowedValue>paused</allowedValue>\n"\
"<allowedValue>door-open</allowedValue>\n"\
"<allowedValue>media-low</allowedValue>\n"\
"<allowedValue>media-empty</allowedValue>\n"\
"<allowedValue>output-area-almost-full</allowedValue>\n"\
"<allowedValue>output-area-full</allowedValue>\n"\
"<allowedValue>marker-supply-low</allowedValue>\n"\
"<allowedValue>marker-supply-empty</allowedValue>\n"\
"<allowedValue>marker-failure</allowedValue>\n"\
"<allowedValue>media-change-request</allowedValue>\n"\
"</allowedValueList>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>Sides</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue>one-sided</defaultValue>\n"\
"<allowedValueList>\n"\
"<allowedValue>one-sided</allowedValue>\n"\
"<allowedValue>two-sided-long-edge</allowedValue>\n"\
"<allowedValue>two-sided-short-edge</allowedValue>\n"\
"<allowedValue>device-setting</allowedValue>\n"\
"</allowedValueList>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>SourceURI</name>\n"\
"<dataType>uri</dataType>\n"\
"<defaultValue></defaultValue>\n"\
"</stateVariable>\n"\
"<stateVariable sendEvents=\"no\">\n"\
"<name>XHTMLImageSupported</name>\n"\
"<dataType>string</dataType>\n"\
"<defaultValue>image/jpeg</defaultValue>\n"\
"<allowedValueList>\n"\
"<allowedValue>image/jpeg</allowedValue>\n"\
"<allowedValue>image/png</allowedValue>\n"\
"</allowedValueList>\n"\
"</stateVariable>\n"\
"</serviceStateTable>\n"\
"</scpd>\n")

#endif /* DMPR_PES_DESC_H_ */
