#ifndef DMR_BMS_DESC_H
#define DMR_BMS_DESC_H

#define DMR_BMS_DESC SLIM_T(\
"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" \
"<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">\n" \
"<specVersion>\n" \
"<major>1</major>\n" \
"<minor>0</minor>\n" \
"</specVersion>\n" \
"<serviceStateTable>\n" \
"<stateVariable sendEvents=\"yes\">\n" \
"<name>DeviceStatus</name>\n" \
"<dataType>string</dataType>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"yes\">\n" \
"<name>TestIDs</name>\n" \
"<dataType>string</dataType>\n" \
"<defaultValue/>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"yes\">\n" \
"<name>ActiveTestIDs</name>\n" \
"<dataType>string</dataType>\n" \
"<defaultValue/>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"no\">\n" \
"<name>A_ARG_TYPE_String</name>\n" \
"<dataType>string</dataType>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"no\">\n" \
"<name>A_ARG_TYPE_UShort</name>\n" \
"<dataType>ui2</dataType>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"no\">\n" \
"<name>A_ARG_TYPE_UInt</name>\n" \
"<dataType>ui4</dataType>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"no\">\n" \
"<name>A_ARG_TYPE_MSecs</name>\n" \
"<dataType>ui4</dataType>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"no\">\n" \
"<name>A_ARG_TYPE_TestID</name>\n" \
"<dataType>ui4</dataType>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"no\">\n" \
"<name>A_ARG_TYPE_TestType</name>\n" \
"<dataType>string</dataType>\n" \
"<allowedValueList>\n" \
"<allowedValue>NSLookup</allowedValue>\n" \
"<allowedValue>Ping</allowedValue>\n" \
"<allowedValue>Traceroute</allowedValue>\n" \
"</allowedValueList>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"no\">\n" \
"<name>A_ARG_TYPE_TestState</name>\n" \
"<dataType>string</dataType>\n" \
"<allowedValueList>\n" \
"<allowedValue>Requested</allowedValue>\n" \
"<allowedValue>InProgress</allowedValue>\n" \
"<allowedValue>Canceled</allowedValue>\n" \
"<allowedValue>Completed</allowedValue>\n" \
"</allowedValueList>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"no\">\n" \
"<name>A_ARG_TYPE_DSCP</name>\n" \
"<dataType>ui1</dataType>\n" \
"<allowedValueRange>\n" \
"<minimum>0</minimum>\n" \
"<maximum>63</maximum>\n" \
"</allowedValueRange>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"no\">\n" \
"<name>A_ARG_TYPE_Host</name>\n" \
"<dataType>string</dataType>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"no\">\n" \
"<name>A_ARG_TYPE_Hosts</name>\n" \
"<dataType>string</dataType>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"no\">\n" \
"<name>A_ARG_TYPE_HostName</name>\n" \
"<dataType>string</dataType>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"no\">\n" \
"<name>A_ARG_TYPE_PingStatus</name>\n" \
"<dataType>string</dataType>\n" \
"<allowedValueList>\n" \
"<allowedValue>Success</allowedValue>\n" \
"<allowedValue>Error_CannotResolveHostName</allowedValue>\n" \
"<allowedValue>Error_Internal</allowedValue>\n" \
"<allowedValue>Error_Other</allowedValue>\n" \
"</allowedValueList>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"no\">\n" \
"<name>A_ARG_TYPE_NSLookupStatus</name>\n" \
"<dataType>string</dataType>\n" \
"<allowedValueList>\n" \
"<allowedValue>Success</allowedValue>\n" \
"<allowedValue>Error_DNSServerNotResolved</allowedValue>\n" \
"<allowedValue>Error_Internal</allowedValue>\n" \
"<allowedValue>Error_Other</allowedValue>\n" \
"</allowedValueList>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"no\">\n" \
"<name>A_ARG_TYPE_NSLookupResult</name>\n" \
"<dataType>string</dataType>\n" \
"</stateVariable>\n" \
"<stateVariable sendEvents=\"no\">\n" \
"<name>A_ARG_TYPE_TracerouteStatus</name>\n" \
"<dataType>string</dataType>\n" \
"<allowedValueList>\n" \
"<allowedValue>Success</allowedValue>\n" \
"<allowedValue>Error_CannotResolveHostName</allowedValue>\n" \
"<allowedValue>Error_MaxHopCountExceeded</allowedValue>\n" \
"<allowedValue>Error_Internal</allowedValue>\n" \
"<allowedValue>Error_Other</allowedValue>\n" \
"</allowedValueList>\n" \
"</stateVariable>\n" \
"</serviceStateTable>\n" \
"<actionList>\n" \
"<action>\n" \
"<name>GetDeviceStatus</name>\n" \
"<argumentList>\n" \
"<argument>\n" \
"<name>DeviceStatus</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>DeviceStatus</relatedStateVariable>\n" \
"</argument>\n" \
"</argumentList>\n" \
"</action>\n" \
"<action>\n" \
"<name>Ping</name>\n" \
"<argumentList>\n" \
"<argument>\n" \
"<name>Host</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_Host</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>NumberOfRepetitions</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_UInt</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>Timeout</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_MSecs</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>DataBlockSize</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_UShort</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>DSCP</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_DSCP</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>TestID</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_TestID</relatedStateVariable>\n" \
"</argument>\n" \
"</argumentList>\n" \
"</action>\n" \
"<action>\n" \
"<name>GetPingResult</name>\n" \
"<argumentList>\n" \
"<argument>\n" \
"<name>TestID</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_TestID</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>Status</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_PingStatus</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>AdditionalInfo</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_String</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>SuccessCount</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_UInt</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>FailureCount</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_UInt</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>AverageResponseTime</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_MSecs</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>MinimumResponseTime</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_MSecs</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>MaximumResponseTime</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_MSecs</relatedStateVariable>\n" \
"</argument>\n" \
"</argumentList>\n" \
"</action>\n" \
"<action>\n" \
"<name>NSLookup</name>\n" \
"<argumentList>\n" \
"<argument>\n" \
"<name>HostName</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_HostName</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>DNSServer</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_Host</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>NumberOfRepetitions</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_UInt</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>Timeout</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_MSecs</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>TestID</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_TestID</relatedStateVariable>\n" \
"</argument>\n" \
"</argumentList>\n" \
"</action>\n" \
"<action>\n" \
"<name>GetNSLookupResult</name>\n" \
"<argumentList>\n" \
"<argument>\n" \
"<name>TestID</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_TestID</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>Status</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_NSLookupStatus</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>AdditionalInfo</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_String</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>SuccessCount</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_UInt</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>Result</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_NSLookupResult</relatedStateVariable>\n" \
"</argument>\n" \
"</argumentList>\n" \
"</action>\n" \
"<action>\n" \
"<name>Traceroute</name>\n" \
"<argumentList>\n" \
"<argument>\n" \
"<name>Host</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_Host</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>Timeout</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_MSecs</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>DataBlockSize</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_UShort</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>MaxHopCount</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_UInt</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>DSCP</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_DSCP</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>TestID</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_TestID</relatedStateVariable>\n" \
"</argument>\n" \
"</argumentList>\n" \
"</action>\n" \
"<action>\n" \
"<name>GetTracerouteResult</name>\n" \
"<argumentList>\n" \
"<argument>\n" \
"<name>TestID</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_TestID</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>Status</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_TracerouteStatus</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>AdditionalInfo</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_String</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>ResponseTime</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_MSecs</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>HopHosts</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_Hosts</relatedStateVariable>\n" \
"</argument>\n" \
"</argumentList>\n" \
"</action>\n" \
"<action>\n" \
"<name>GetTestIDs</name>\n" \
"<argumentList>\n" \
"<argument>\n" \
"<name>TestIDs</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>TestIDs</relatedStateVariable>\n" \
"</argument>\n" \
"</argumentList>\n" \
"</action>\n" \
"<action>\n" \
"<name>GetActiveTestIDs</name>\n" \
"<argumentList>\n" \
"<argument>\n" \
"<name>TestIDs</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>ActiveTestIDs</relatedStateVariable>\n" \
"</argument>\n" \
"</argumentList>\n" \
"</action>\n" \
"<action>\n" \
"<name>GetTestInfo</name>\n" \
"<argumentList>\n" \
"<argument>\n" \
"<name>TestID</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_TestID</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>Type</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_TestType</relatedStateVariable>\n" \
"</argument>\n" \
"<argument>\n" \
"<name>State</name>\n" \
"<direction>out</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_TestState</relatedStateVariable>\n" \
"</argument>\n" \
"</argumentList>\n" \
"</action>\n" \
"<action>\n" \
"<name>CancelTest</name>\n" \
"<argumentList>\n" \
"<argument>\n" \
"<name>TestID</name>\n" \
"<direction>in</direction>\n" \
"<relatedStateVariable>A_ARG_TYPE_TestID</relatedStateVariable>\n" \
"</argument>\n" \
"</argumentList>\n" \
"</action>\n" \
"</actionList>\n" \
"</scpd>\n" \
)

#endif /* DMR_BMS_DESC_H */
