/*
 * info_mpe_def.h
 * Copyright (C) 2008 ACCESS CO.,LTD.
 * All rights are reserved by ACCESS CO.,LTD.,
 * whether the whole or part of the source code
 * including any modifications is concerned.
 *
 * This is an unpublished source code of ACCESS CO.,LTD., and must be
 * treated as confidential material.  The above copyright notice does
 * not evidence any actual or intended publication of this source code.
 */

/* mpe types file support for NFLC. */

#define OGG_VIDEO_MIMETYPE_STR "video/ogg"
#define OGG_AUDIO_MIMETYPE_STR "audio/ogg"
#define REAL_AUDIO_MIMETYPE_STR "audio/x-realaudio"
#define REAL_VIDEO_MIMETYPE_STR "video/x-realvideo"
#define TGA_MIMETYPE_STR "video/image2_targa"
#define TP_MIMETYPE_STR "application/octet-stream"
#define VOC_MIMETYPE_STR "audio/voc"
#define PCX_MIMETYPE_STR "image/x-pcx"
#define ROQ_MIMETYPE_STR "video/RoQ"
#define SND_MIMETYPE_STR "audio/ea"
#define MXF_MIMETYPE_STR "video/mxf"
#define MLP_MIMETYPE_STR "audio/vnd.dolby.mlp"
#define MJPG_MIMETYPE_STR "video/x-motion-jpeg"
#define MJPEG_MIMETYPE_STR "video/mjpeg"
#define MID_MIMETYPE_STR "audio/midi"
#define DPX_MIMETYPE_STR "video/image2_dpx"
#define DV_MIMETYPE_STR "video/dv"
#define AU_MIMETYPE_STR "audio/au"
#define AT3P_MIMETYPE_STR "audio/x-atrac3"
#define ID_3GPP_MIMETYPE_STR "audio/3gpp"

#define REAL_AUDIO_PINFO_STR "http-get:*:" REAL_AUDIO_MIMETYPE_STR ":DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define REAL_VIDEO_PINFO_STR "http-get:*:" REAL_VIDEO_MIMETYPE_STR ":DLNA.ORG_OP=11;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define OGG_VIDEO_PINFO_STR "http-get:*:" OGG_VIDEO_MIMETYPE_STR ":DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define OGG_AUDIO_PINFO_STR "http-get:*:" OGG_AUDIO_MIMETYPE_STR ":DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define TGA_PINFO_STR "http-get:*:" TGA_MIMETYPE_STR ":DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_IMAGE
#define TP_PINFO_STR "http-get:*:" TP_MIMETYPE_STR ":DLNA.ORG_OP=11;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define VOC_PINFO_STR "http-get:*:" VOC_MIMETYPE_STR ":DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define PCX_PINFO_STR "http-get:*:" PCX_MIMETYPE_STR ":DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_IMAGE
#define ROQ_PINFO_STR "http-get:*:" ROQ_MIMETYPE_STR ":DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define SND_PINFO_STR "http-get:*:" SND_MIMETYPE_STR ":DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define MXF_PINFO_STR "http-get:*:" MXF_MIMETYPE_STR ":DLNA.ORG_OP=11;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define MLP_PINFO_STR "http-get:*:" MLP_MIMETYPE_STR ":DLNA.ORG_PN=MLP;DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define MJPG_PINFO_STR "http-get:*:" MJPG_MIMETYPE_STR ":DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define MJPEG_PINFO_STR "http-get:*:" MJPEG_MIMETYPE_STR ":DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define MID_PINFO_STR "http-get:*:" MID_MIMETYPE_STR ":DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define DPX_PINFO_STR "http-get:*:" DPX_MIMETYPE_STR ":DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define DV_PINFO_STR "http-get:*:" DV_MIMETYPE_STR ":DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define AU_PINFO_STR "http-get:*:" AU_MIMETYPE_STR ":DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define AT3P_PINFO_STR "http-get:*:" AT3P_MIMETYPE_STR ":DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
#define ID_3GPP_PINFO_STR "http-get:*:" ID_3GPP_MIMETYPE_STR ":DLNA.ORG_PN=AMR_3GPP;DLNA.ORG_OP=01;DLNA.ORG_CI=0" PROTOCOL_INFO_DLNA_ORG_FLAGS_FOR_AUDIO_VIDEO
