/*
	a1oidid.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/ssl/a1oidid.h 6     06/03/07 18:16 Nagamati $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_A1OIDID_H
#define SLIM_TOKEN_A1OIDID_H


SLIM_BEGIN_C_LINKAGE

enum {
	SLIM_TKID_A1OID_id_at_name = 0,
	SLIM_TKID_A1OID_id_at_surname,
	SLIM_TKID_A1OID_id_at_givenName,
	SLIM_TKID_A1OID_id_at_initials,
	SLIM_TKID_A1OID_id_at_generationQualifier,
	SLIM_TKID_A1OID_id_at_commonName,
	SLIM_TKID_A1OID_id_at_localityName,
	SLIM_TKID_A1OID_id_at_stateOrProvinceName,
	SLIM_TKID_A1OID_id_at_orgName,
	SLIM_TKID_A1OID_id_at_orgUnitName,
	SLIM_TKID_A1OID_id_at_title,
	SLIM_TKID_A1OID_id_at_dnQualifier,
	SLIM_TKID_A1OID_id_at_countryName,
	SLIM_TKID_A1OID_id_at_serialNumber,
	SLIM_TKID_A1OID_id_at_pseudonym,
	SLIM_TKID_A1OID_id_domainComponent,
	SLIM_TKID_A1OID_id_ce_subjectDirectoryAttributes,
	SLIM_TKID_A1OID_id_ce_subjectKeyIdentifier,
	SLIM_TKID_A1OID_id_ce_keyUsage,
	SLIM_TKID_A1OID_id_ce_privateKeyUsagePeriod,
	SLIM_TKID_A1OID_id_ce_subjectAltName,
	SLIM_TKID_A1OID_id_ce_issuerAltName,
	SLIM_TKID_A1OID_id_ce_basicConstraints,
	SLIM_TKID_A1OID_id_ce_cRLNumber,
	SLIM_TKID_A1OID_id_ce_cRLReason,
	SLIM_TKID_A1OID_id_ce_invalidityDate,
	SLIM_TKID_A1OID_id_ce_deltaCRLIndicator,
	SLIM_TKID_A1OID_id_ce_issuingDistributionPoint,
	SLIM_TKID_A1OID_id_ce_certificateIssuer,
	SLIM_TKID_A1OID_id_ce_nameConstraints,
	SLIM_TKID_A1OID_id_ce_cRLDistributionPoints,
	SLIM_TKID_A1OID_id_ce_certificatePolicies,
	SLIM_TKID_A1OID_id_ce_policyMappings,
	SLIM_TKID_A1OID_id_ce_authorityKeyIdentifier,
	SLIM_TKID_A1OID_id_ce_policyConstraints,
	SLIM_TKID_A1OID_id_ce_extKeyUsage,
	SLIM_TKID_A1OID_id_ce_freshestCRL,
	SLIM_TKID_A1OID_id_ce_inhibitAnyPolicy,
	SLIM_TKID_A1OID_id_pe_authorityInfoAccess,
	SLIM_TKID_A1OID_id_pe_subjectInfoAccess,
	SLIM_TKID_A1OID_id_ad_ocsp,
	SLIM_TKID_A1OID_id_ad_caIssuers,
	SLIM_TKID_A1OID_id_ad_timeStamping,
	SLIM_TKID_A1OID_id_ad_caRepository,
	SLIM_TKID_A1OID_rsaEncryption,
	SLIM_TKID_A1OID_md2WithRSAEncryption,
	SLIM_TKID_A1OID_md5WithRSAEncryption,
	SLIM_TKID_A1OID_sha1WithRSAEncryption,
	SLIM_TKID_A1OID_id_sha1,
	SLIM_TKID_A1OID_id_md2,
	SLIM_TKID_A1OID_id_md5,
	SLIM_TKID_A1OID_pkcs_9_1_at_emailAddress,
	SLIM_TKID_A1OID_pkcs_9_3_at_contentType,
	SLIM_TKID_A1OID_pkcs_9_4_at_messageDigest,
	SLIM_TKID_A1OID_pkcs_9_5_at_signingTime,
	SLIM_TKID_A1OID_pkcs_9_at_friendlyName,
	SLIM_TKID_A1OID_pkcs_9_at_localKeyId,
	SLIM_TKID_A1OID_pkcs_9_at_randomNonce,
	SLIM_TKID_A1OID_pkcs_9_at_sequenceNumber,
	SLIM_TKID_A1OID_sha_1WithRSAEncription,
#ifdef SLIM_CONFIG_USE_PKCS12
	SLIM_TKID_A1OID_pbe_SHA_128BitRC4,
	SLIM_TKID_A1OID_pbe_SHA_40BitRC4,
	SLIM_TKID_A1OID_pbe_SHA_3KeyTripleDES_CBC,
	SLIM_TKID_A1OID_pbe_SHA_2KeyTripleDES_CBC,
	SLIM_TKID_A1OID_pbe_SHA_128BitRC2_CBC,
	SLIM_TKID_A1OID_pbe_SHA_40BitRC2_CBC,
	SLIM_TKID_A1OID_keyBag,
	SLIM_TKID_A1OID_pkcs8ShroudedKeyBag,
	SLIM_TKID_A1OID_certBag,
	SLIM_TKID_A1OID_crlBag,
	SLIM_TKID_A1OID_secretBag,
	SLIM_TKID_A1OID_safeContentsBag,
	SLIM_TKID_A1OID_x509Certificate,
	SLIM_TKID_A1OID_sdsiCertificate,
	SLIM_TKID_A1OID_x509CRL,
#endif /* SLIM_CONFIG_USE_PKCS12 */
#ifdef SLIM_CONFIG_USE_PKCS5
	SLIM_TKID_A1OID_pkcs_5_1_pbeWithMD2AndDES_CBC,
	SLIM_TKID_A1OID_pkcs_5_3_pbeWithMD5AndDES_CBC,
	SLIM_TKID_A1OID_pkcs_5_4_pbeWithMD2AndRC2_CBC,
	SLIM_TKID_A1OID_pkcs_5_6_pbeWithMD5AndRC2_CBC,
	SLIM_TKID_A1OID_pkcs_5_10_pbeWithSHA1AndDES_CBC,
	SLIM_TKID_A1OID_pkcs_5_11_pbeWithSHA1AndRC2_CBC,
#endif /* SLIM_CONFIG_USE_PKCS5 */
#ifdef SLIM_CONFIG_USE_PKCS7
	SLIM_TKID_A1OID_data,
	SLIM_TKID_A1OID_signedData,
	SLIM_TKID_A1OID_envelopedData,
	SLIM_TKID_A1OID_signedAndEnvelopedData,
	SLIM_TKID_A1OID_digestedData,
	SLIM_TKID_A1OID_encryptedData,
#endif /* SLIM_CONFIG_USE_PKCS7 */
	SLIM_TKID_A1OID_ENUMS
};

#define SLIM_TOKEN_A1OID_TOKENS SLIM_TKID_A1OID_ENUMS
#define SLIM_TOKEN_A1OID_ENUMS SLIM_TKID_A1OID_ENUMS


#define SLIM_A1OID_id_at_name SLIM_TKID_A1OID_id_at_name
#define SLIM_A1OID_id_at_surname SLIM_TKID_A1OID_id_at_surname
#define SLIM_A1OID_id_at_givenName SLIM_TKID_A1OID_id_at_givenName
#define SLIM_A1OID_id_at_initials SLIM_TKID_A1OID_id_at_initials
#define SLIM_A1OID_id_at_generationQualifier SLIM_TKID_A1OID_id_at_generationQualifier
#define SLIM_A1OID_id_at_commonName SLIM_TKID_A1OID_id_at_commonName
#define SLIM_A1OID_id_at_localityName SLIM_TKID_A1OID_id_at_localityName
#define SLIM_A1OID_id_at_stateOrProvinceName SLIM_TKID_A1OID_id_at_stateOrProvinceName
#define SLIM_A1OID_id_at_orgName SLIM_TKID_A1OID_id_at_orgName
#define SLIM_A1OID_id_at_orgUnitName SLIM_TKID_A1OID_id_at_orgUnitName
#define SLIM_A1OID_id_at_title SLIM_TKID_A1OID_id_at_title
#define SLIM_A1OID_id_at_dnQualifier SLIM_TKID_A1OID_id_at_dnQualifier
#define SLIM_A1OID_id_at_countryName SLIM_TKID_A1OID_id_at_countryName
#define SLIM_A1OID_id_at_serialNumber SLIM_TKID_A1OID_id_at_serialNumber
#define SLIM_A1OID_id_at_pseudonym SLIM_TKID_A1OID_id_at_pseudonym
#define SLIM_A1OID_id_domainComponent SLIM_TKID_A1OID_id_domainComponent
#define SLIM_A1OID_id_ce_subjectDirectoryAttributes SLIM_TKID_A1OID_id_ce_subjectDirectoryAttributes
#define SLIM_A1OID_id_ce_subjectKeyIdentifier SLIM_TKID_A1OID_id_ce_subjectKeyIdentifier
#define SLIM_A1OID_id_ce_keyUsage SLIM_TKID_A1OID_id_ce_keyUsage
#define SLIM_A1OID_id_ce_privateKeyUsagePeriod SLIM_TKID_A1OID_id_ce_privateKeyUsagePeriod
#define SLIM_A1OID_id_ce_subjectAltName SLIM_TKID_A1OID_id_ce_subjectAltName
#define SLIM_A1OID_id_ce_issuerAltName SLIM_TKID_A1OID_id_ce_issuerAltName
#define SLIM_A1OID_id_ce_basicConstraints SLIM_TKID_A1OID_id_ce_basicConstraints
#define SLIM_A1OID_id_ce_cRLNumber SLIM_TKID_A1OID_id_ce_cRLNumber
#define SLIM_A1OID_id_ce_cRLReason SLIM_TKID_A1OID_id_ce_cRLReason
#define SLIM_A1OID_id_ce_invalidityDate SLIM_TKID_A1OID_id_ce_invalidityDate
#define SLIM_A1OID_id_ce_deltaCRLIndicator SLIM_TKID_A1OID_id_ce_deltaCRLIndicator
#define SLIM_A1OID_id_ce_issuingDistributionPoint SLIM_TKID_A1OID_id_ce_issuingDistributionPoint
#define SLIM_A1OID_id_ce_certificateIssuer SLIM_TKID_A1OID_id_ce_certificateIssuer
#define SLIM_A1OID_id_ce_nameConstraints SLIM_TKID_A1OID_id_ce_nameConstraints
#define SLIM_A1OID_id_ce_cRLDistributionPoints SLIM_TKID_A1OID_id_ce_cRLDistributionPoints
#define SLIM_A1OID_id_ce_certificatePolicies SLIM_TKID_A1OID_id_ce_certificatePolicies
#define SLIM_A1OID_id_ce_policyMappings SLIM_TKID_A1OID_id_ce_policyMappings
#define SLIM_A1OID_id_ce_authorityKeyIdentifier SLIM_TKID_A1OID_id_ce_authorityKeyIdentifier
#define SLIM_A1OID_id_ce_policyConstraints SLIM_TKID_A1OID_id_ce_policyConstraints
#define SLIM_A1OID_id_ce_extKeyUsage SLIM_TKID_A1OID_id_ce_extKeyUsage
#define SLIM_A1OID_id_ce_freshestCRL SLIM_TKID_A1OID_id_ce_freshestCRL
#define SLIM_A1OID_id_ce_inhibitAnyPolicy SLIM_TKID_A1OID_id_ce_inhibitAnyPolicy
#define SLIM_A1OID_id_pe_authorityInfoAccess SLIM_TKID_A1OID_id_pe_authorityInfoAccess
#define SLIM_A1OID_id_pe_subjectInfoAccess SLIM_TKID_A1OID_id_pe_subjectInfoAccess
#define SLIM_A1OID_id_ad_ocsp SLIM_TKID_A1OID_id_ad_ocsp
#define SLIM_A1OID_id_ad_caIssuers SLIM_TKID_A1OID_id_ad_caIssuers
#define SLIM_A1OID_id_ad_timeStamping SLIM_TKID_A1OID_id_ad_timeStamping
#define SLIM_A1OID_id_ad_caRepository SLIM_TKID_A1OID_id_ad_caRepository
#define SLIM_A1OID_rsaEncryption SLIM_TKID_A1OID_rsaEncryption
#define SLIM_A1OID_md2WithRSAEncryption SLIM_TKID_A1OID_md2WithRSAEncryption
#define SLIM_A1OID_md5WithRSAEncryption SLIM_TKID_A1OID_md5WithRSAEncryption
#define SLIM_A1OID_sha1WithRSAEncryption SLIM_TKID_A1OID_sha1WithRSAEncryption
#define SLIM_A1OID_id_sha1 SLIM_TKID_A1OID_id_sha1
#define SLIM_A1OID_id_md2 SLIM_TKID_A1OID_id_md2
#define SLIM_A1OID_id_md5 SLIM_TKID_A1OID_id_md5
#define SLIM_A1OID_pkcs_9_1_at_emailAddress SLIM_TKID_A1OID_pkcs_9_1_at_emailAddress
#define SLIM_A1OID_pkcs_9_3_at_contentType SLIM_TKID_A1OID_pkcs_9_3_at_contentType
#define SLIM_A1OID_pkcs_9_4_at_messageDigest SLIM_TKID_A1OID_pkcs_9_4_at_messageDigest
#define SLIM_A1OID_pkcs_9_5_at_signingTime SLIM_TKID_A1OID_pkcs_9_5_at_signingTime
#define SLIM_A1OID_pkcs_9_at_friendlyName SLIM_TKID_A1OID_pkcs_9_at_friendlyName
#define SLIM_A1OID_pkcs_9_at_localKeyId SLIM_TKID_A1OID_pkcs_9_at_localKeyId
#define SLIM_A1OID_pkcs_9_at_randomNonce SLIM_TKID_A1OID_pkcs_9_at_randomNonce
#define SLIM_A1OID_pkcs_9_at_sequenceNumber SLIM_TKID_A1OID_pkcs_9_at_sequenceNumber
#define SLIM_A1OID_sha_1WithRSAEncription SLIM_TKID_A1OID_sha_1WithRSAEncription
#ifdef SLIM_CONFIG_USE_PKCS12
#define SLIM_A1OID_pbe_SHA_128BitRC4 SLIM_TKID_A1OID_pbe_SHA_128BitRC4
#define SLIM_A1OID_pbe_SHA_40BitRC4 SLIM_TKID_A1OID_pbe_SHA_40BitRC4
#define SLIM_A1OID_pbe_SHA_3KeyTripleDES_CBC SLIM_TKID_A1OID_pbe_SHA_3KeyTripleDES_CBC
#define SLIM_A1OID_pbe_SHA_2KeyTripleDES_CBC SLIM_TKID_A1OID_pbe_SHA_2KeyTripleDES_CBC
#define SLIM_A1OID_pbe_SHA_128BitRC2_CBC SLIM_TKID_A1OID_pbe_SHA_128BitRC2_CBC
#define SLIM_A1OID_pbe_SHA_40BitRC2_CBC SLIM_TKID_A1OID_pbe_SHA_40BitRC2_CBC
#define SLIM_A1OID_keyBag SLIM_TKID_A1OID_keyBag
#define SLIM_A1OID_pkcs8ShroudedKeyBag SLIM_TKID_A1OID_pkcs8ShroudedKeyBag
#define SLIM_A1OID_certBag SLIM_TKID_A1OID_certBag
#define SLIM_A1OID_crlBag SLIM_TKID_A1OID_crlBag
#define SLIM_A1OID_secretBag SLIM_TKID_A1OID_secretBag
#define SLIM_A1OID_safeContentsBag SLIM_TKID_A1OID_safeContentsBag
#define SLIM_A1OID_x509Certificate SLIM_TKID_A1OID_x509Certificate
#define SLIM_A1OID_sdsiCertificate SLIM_TKID_A1OID_sdsiCertificate
#define SLIM_A1OID_x509CRL SLIM_TKID_A1OID_x509CRL
#endif /* SLIM_CONFIG_USE_PKCS12 */
#ifdef SLIM_CONFIG_USE_PKCS5
#define SLIM_A1OID_pkcs_5_1_pbeWithMD2AndDES_CBC SLIM_TKID_A1OID_pkcs_5_1_pbeWithMD2AndDES_CBC
#define SLIM_A1OID_pkcs_5_3_pbeWithMD5AndDES_CBC SLIM_TKID_A1OID_pkcs_5_3_pbeWithMD5AndDES_CBC
#define SLIM_A1OID_pkcs_5_4_pbeWithMD2AndRC2_CBC SLIM_TKID_A1OID_pkcs_5_4_pbeWithMD2AndRC2_CBC
#define SLIM_A1OID_pkcs_5_6_pbeWithMD5AndRC2_CBC SLIM_TKID_A1OID_pkcs_5_6_pbeWithMD5AndRC2_CBC
#define SLIM_A1OID_pkcs_5_10_pbeWithSHA1AndDES_CBC SLIM_TKID_A1OID_pkcs_5_10_pbeWithSHA1AndDES_CBC
#define SLIM_A1OID_pkcs_5_11_pbeWithSHA1AndRC2_CBC SLIM_TKID_A1OID_pkcs_5_11_pbeWithSHA1AndRC2_CBC
#endif /* SLIM_CONFIG_USE_PKCS5 */
#ifdef SLIM_CONFIG_USE_PKCS7
#define SLIM_A1OID_data SLIM_TKID_A1OID_data
#define SLIM_A1OID_signedData SLIM_TKID_A1OID_signedData
#define SLIM_A1OID_envelopedData SLIM_TKID_A1OID_envelopedData
#define SLIM_A1OID_signedAndEnvelopedData SLIM_TKID_A1OID_signedAndEnvelopedData
#define SLIM_A1OID_digestedData SLIM_TKID_A1OID_digestedData
#define SLIM_A1OID_encryptedData SLIM_TKID_A1OID_encryptedData
#endif /* SLIM_CONFIG_USE_PKCS7 */
#define SLIM_A1OID_UNKNOWN (-1)
#define SLIM_A1OID_UNDEFINED (-2)

SLIM_END_C_LINKAGE
#endif
