/*
 * nflc_upnp_api.h
 * Copyright (C) 2009-2010 ACCESS CO.,LTD.
 * All rights are reserved by ACCESS CO.,LTD.,
 * whether the whole or part of the source code
 * including any modifications is concerned.
 *
 * This is an unpublished source code of ACCESS CO.,LTD., and must be
 * treated as confidential material.  The above copyright notice does
 * not evidence any actual or intended publication of this source code.
 */

#ifndef NFLC_UPNP_API_H
#define NFLC_UPNP_API_H

/* UPnP library error codes.  */
enum upnp_return_ {
  UPNP_SUCCESS           = 0,
  UPNP_API_SUCCESS       = UPNP_SUCCESS,
  UPNP_WOULDBLOCK        = -2,
  UPNP_PLAYER_ERROR      = -1,
  UPNP_GENERIC_ERROR     = -3,
  UPNP_METHOD_ERROR      = -4,
  UPNP_XML_ERROR         = -5,
  UPNP_OUT_OF_MEMORY     = -65535,
  UPNP_BAD_SID,
  UPNP_BAD_HTTP_RESPONSE,
  UPNP_BAD_HTTP_MESSAGE,
  UPNP_SOCKET_ERROR,
  UPNP_SOCKET_TIMEOUT,
  UPNP_SOCKET_CONNECTED,
  UPNP_SOCKET_NOT_CONNECTED,
  UPNP_CANT_CONNECT,
  UPNP_SELECT_ERROR,
  UPNP_READ_ERROR,
  UPNP_OUTOF_BOUNDS,
  UPNP_INVALID_HANDLE,
  UPNP_INVALID_PARAM,
  UPNP_INVALID_DESC,
  UPNP_INVALID_URL,
  UPNP_INVALID_SID,
  UPNP_INVALID_ACTION,
  UPNP_INVALID_DESCRIPTION,
  UPNP_INVALID_SERVICE,
  UPNP_INVALID_INTERFACE,
  UPNP_INVALID_DEVICE_TYPE,
  UPNP_INVALID_STATE,
  UPNP_PINFO_MISMATCH,
  UPNP_PINFO_NOT_EXIST,
  UPNP_PINFO_NOT_SUPPORT_SEEK,
  UPNP_INIT_FAILED,
  UPNP_IF_INIT_FAILED,
  UPNP_ALREADY_REGISTERED,
  UPNP_SUBSCRIBE_UNACCEPTED,
  UPNP_UNSUBSCRIBE_UNACCEPTED,
  UPNP_NOTIFY_UNACCEPTED,
  UPNP_UPLOAD_CANCEL,
  UPNP_UPLOAD_EOS,
  UPNP_ACCESS_ACCEPT,
  UPNP_ACCESS_DENY,
  UPNP_NOT_SUPPORTED,
  UPNP_PLAYER_BUSY,
  UPNP_FILE_NOT_EXIST,
  UPNP_ALREADY_STARTED,
  UPNP_MEMORY_FREED,
  UPNP_STORAGE_NOT_EXISTS,
  UPNP_RETURN_enum_end
};

typedef enum upnp_return_ upnp_return_t;

enum upnp_content_access_event_ {
  UPNP_CONTENT_ACCESS_OPEN_PLAY,
  UPNP_CONTENT_ACCESS_OPEN_DOWNLOAD,
  UPNP_CONTENT_ACCESS_OPEN_UPLOAD,
  UPNP_CONTENT_ACCESS_UPDATE,
  UPNP_CONTENT_ACCESS_CLOSE,
  UPNP_CONTENT_ACCESS_CANCEL,
  UPNP_CONTENT_ACCESS_RSPTO_TIMEOUT,
  UPNP_CONTENT_ACCESS_ERROR_COMM,
  UPNP_CONTENT_ACCESS_ERROR_FILE,
  UPNP_CONTENT_ACCESS_ERROR_ETC,
  UPNP_CONTENT_ACCESS_END
};

typedef enum upnp_content_access_event_ upnp_content_access_event_t;

/* DMR supported seek mode */
#define DEVICE_SEEK_MODE_SUPPORT_ABS_TIME  0x01
#define DEVICE_SEEK_MODE_SUPPORT_REL_TIME  0x02
#define DEVICE_SEEK_MODE_SUPPORT_ABS_COUNT 0x04
#define DEVICE_SEEK_MODE_SUPPORT_REL_COUNT 0x08
#define DEVICE_SEEK_MODE_SUPPORT_TRACK_NR  0x10

#endif /* NFLC_UPNP_API_H */
