/*
	from.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/private/basis/from.h 46    05/12/28 12:08 Someya $ */

#ifndef SLIM_FROM_H_PRIVATE
#define SLIM_FROM_H_PRIVATE

/*            */
/* from where */
/*            */

/* may be used for debug only... */

#ifdef SLIM_CONFIG_MEMORY_DEBUG
#define SLIM_FROM_PUSH(from) (SLIM_ASSERT(((from) & 0xffffff00) == 0), \
	(SLIM_RESOLVE_GLOBAL_VAR(gSlim_MemoryFrom) = (SLIM_RESOLVE_GLOBAL_VAR(gSlim_MemoryFrom) << 8) | (from)))
#define SLIM_FROM_POP() (SLIM_RESOLVE_GLOBAL_VAR(gSlim_MemoryFrom) >>= 8)
#define SLIM_FROM_SAVE(from, save) (*(save) = SLIM_RESOLVE_GLOBAL_VAR(gSlim_MemoryFrom), SLIM_RESOLVE_GLOBAL_VAR(gSlim_MemoryFrom) = (from))
#define SLIM_FROM_RESTORE(save) (SLIM_RESOLVE_GLOBAL_VAR(gSlim_MemoryFrom) = (save))
#else
#define SLIM_FROM_PUSH(from)
#define SLIM_FROM_POP()
#define SLIM_FROM_SAVE(from, save)
#define SLIM_FROM_RESTORE(save)
#endif

enum {

	/* be careful!! slim_get_memory_from_name() in slim_memory.c depends on this enumeration */

	SLIM_FROM_ANON					= 1,

	SLIM_MEMORY_FROM_HEADER,
	SLIM_MEMORY_FROM_MPTR,
	SLIM_MEMORY_FROM_TMEMNODE,
	SLIM_MEMORY_FROM_TPTRMEMNODE,

	SLIM_COLL_FROM_BAG,
	SLIM_COLL_FROM_SPECLIST,
	SLIM_COLL_FROM_OPAQUELIST,
	SLIM_COLL_FROM_SPECARRAY,
	SLIM_COLL_FROM_OPAQUEARRAY,
	SLIM_COLL_FROM_LINEARARRAY,
	SLIM_COLL_FROM_FASTVARBAG,
	SLIM_COLL_FROM_VARBAG,
	SLIM_COLL_FROM_TREE,

	SLIM_STRING_FROM_TSTRING,
	SLIM_STRING_FROM_TFIXEDSTRING,
	SLIM_STRING_FROM_TURLSTRING,

	SLIM_CONTENT_FROM_TCONTENT,
	SLIM_CONTENT_FROM_TCONTENTSPEC,
	SLIM_CONTENT_FROM_CORESPEC,
	SLIM_CONTENT_FROM_THTTPCHANNEL,
	SLIM_CONTENT_FROM_TFILEPCHANNEL,
	SLIM_CONTENT_FROM_TDATAPCHANNEL,
	SLIM_CONTENT_FROM_CONTENTBUF,

	SLIM_GUIBASE_FROM_REGION,
	SLIM_GUIBASE_FROM_PIXELMAP,

	SLIM_HTTP_FROM_STREAM,
	SLIM_HTTP_FROM_DNS_CACHE,
	SLIM_HTTP_FROM_AUTH_CACHE,
	SLIM_HTTP_FROM_HTTP_CACHE,
	SLIM_HTTP_FROM_RECEIVED_HEADER,
	SLIM_HTTP_FROM_COOKIES,
	SLIM_HTTP_FROM_CREDENTIALTMP,

	SLIM_SSL_FROM_SSL,
	SLIM_SSL_FROM_ASN1,
	SLIM_SSL_FROM_PKCS,
	
	SLIM_CODEC_FROM_GIF,
	SLIM_CODEC_FROM_PNG,
	SLIM_CODEC_FROM_MNG,
	SLIM_CODEC_FROM_JPG,
	SLIM_CODEC_FROM_BMP,
	SLIM_CODEC_FROM_ICO,

	SLIM_BROWSER_FROM_BROWSER,
	SLIM_BROWSER_FROM_CSSDICT,
	SLIM_BROWSER_FROM_DOM,
	SLIM_BROWSER_FROM_HISTORY,
	SLIM_BROWSER_FROM_PAGE_DEPOT,

	SLIM_NETDOC_FROM_DOC_TREE,
	
	SLIM_LAYOUT_FROM_PAGE_LAYOUT,
	SLIM_LAYOUT_FROM_ELEMENT_STYLE,
	SLIM_LAYOUT_FROM_BOX_TREE,
	SLIM_LAYOUT_FROM_EDITOR,

	SLIM_WAVE_FROM_WND,
	SLIM_WAVE_FROM_GRAPHICS,
	SLIM_WAVE_FROM_EVENT,
	SLIM_WAVE_FROM_TIMER,
	SLIM_WAVE_FROM_CURSOR,
	SLIM_WAVE_FROM_COMPO_LIST,

	SLIM_JS_FROM_JS,
	SLIM_JS_FROM_TJSSTRING,
	SLIM_JS_FROM_TJSLISTCONTAINER,

	SLIM_REGEXP_FROM_REGEXP,

	SLIM_NSPLUGIN_FROM_BROWSER,
	SLIM_NSPLUGIN_FROM_PLUGIN,

	SLIM_FROM_DEBUG,

	SLIM_FROMS

};


#endif
