/*
	token.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/private/basis/token.h 27    05/12/28 12:08 Someya $ */

#ifndef SLIM_TOKEN_H_PRIVATE
#define SLIM_TOKEN_H_PRIVATE

SLIM_BEGIN_C_LINKAGE

#define SLIM_TOKEN_UNKNOWN slim_nil
#define SLIM_TOKEN_ID_UNKNOWN (-1)


/*                  */
/* token dictionary */
/*                  */

	/* Because an instance of inherited type of this type is usually generated by some scripts,
	   there is no initializer nor finalizer */


SLIM_END_C_LINKAGE

#endif
