/*
	config0.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

#ifndef SLIM_CONFIG0_H
#define SLIM_CONFIG0_H

/* Automatically definable configurations */

/* Browser */

#ifndef SLIM_CONFIG_BROWSER_NAME
#define SLIM_CONFIG_BROWSER_NAME		("NetFront")
#endif

/* memory */

#ifdef SLIM_CONFIG_MEMORY_EXTERNAL
#undef SLIM_CONFIG_MOD_MEMORY
#undef SLIM_CONFIG_MEMORY_ALTERNATIVE
#undef SLIM_CONFIG_MEMORY_STANDARD
#endif

#ifdef SLIM_CONFIG_MEMORY_ALTERNATIVE
#undef SLIM_CONFIG_MOD_MEMORY
#undef SLIM_CONFIG_MEMORY_STANDARD
#undef SLIM_CONFIG_POINTER_MEMNODE
#endif

#ifndef SLIM_CONFIG_MEMORY_ALTERNATIVE
/* Ugh!: this config shold be removed */
#define SLIM_CONFIG_MEMORY_NOALTERNATIVE
#endif

#ifndef SLIM_CONFIG_MOD_MEMORY
#ifndef SLIM_CONFIG_MEMORY_ALTERNATIVE
#ifndef SLIM_CONFIG_MEMORY_EXTERNAL
#define SLIM_CONFIG_MEMORY_STANDARD
#endif
#endif
#endif

/* debug */

#ifndef SLIM_CONFIG_MOD_MEMORY
#ifndef SLIM_CONFIG_MEMORY_STANDARD
#undef SLIM_CONFIG_MEMORY_DEBUG
#undef SLIM_CONFIG_MEMNODE_DEBUG
#endif /* !defined(SLIM_CONFIG_MEMORY_STANDARD) */
#endif /* !defined(SLIM_CONFIG_MOD_MEMORY) */

#ifndef SLIM_CONFIG_DEBUG
#define SLIM_CONFIG_NODEBUG
#endif
#ifndef SLIM_CONFIG_MEMORY_DEBUG
#define SLIM_CONFIG_MEMORY_NODEBUG
#endif
#ifndef SLIM_CONFIG_MEMORY_CHECKOW_DEBUG
#define SLIM_CONFIG_MEMORY_CHECKOW_NODEBUG
#endif
#ifndef SLIM_CONFIG_MEMNODE_DEBUG
#define SLIM_CONFIG_MEMNODE_NODEBUG
#undef SLIM_CONFIG_MEMNODE_DEBUG_ID
#endif
#ifndef SLIM_CONFIG_MEMNODE_DEBUG_ID
#define SLIM_CONFIG_MEMNODE_NODEBUG_ID
#endif
#ifndef SLIM_CONFIG_MORECOMPACT
#define SLIM_CONFIG_MORESPEED
#endif
#ifndef SLIM_CONFIG_NOMULTITHREAD
#define SLIM_CONFIG_MULTITHREAD
#endif

/* coll */

#ifdef SLIM_CONFIG_DEBUG
#define SLIM_CONFIG_DEBUG_COLL_STRICTTYPE
#endif

/* HTTP */
#ifndef SLIM_CONFIG_HTTP_STREAM_USE_PIPELINE
#define SLIM_CONFIG_HTTP_STREAM_NOUSE_PIPELINE
#endif

/* SSL */
#ifndef SLIM_CONFIG_USE_SSL
#define SLIM_CONFIG_NOUSE_SSL
#endif

/* CSS */
#ifndef SLIM_CONFIG_CSS_LEVEL_1_POSITIONING
#define SLIM_CONFIG_CSS_NOLEVEL_1_POSITIONING
#endif
#ifndef SLIM_CONFIG_CSS_LEVEL_2
#define SLIM_CONFIG_CSS_NOLEVEL_2
#endif
#ifndef SLIM_CONFIG_CSS_LEVEL_2_WITH_AURAL
#define SLIM_CONFIG_CSS_NOLEVEL_2_WITH_AURAL
#endif
#ifndef SLIM_CONFIG_CSS_NOSUPPORT_FONT_FACE
#define SLIM_CONFIG_CSS_SUPPORT_FONT_FACE
#endif
#ifndef SLIM_CONFIG_CSS_LEVEL_3
#define SLIM_CONFIG_CSS_NOLEVEL_3
#endif

/* Markup */
#ifdef SLIM_CONFIG_USE_RSS
#ifndef SLIM_CONFIG_USE_RDF
#define SLIM_CONFIG_USE_RDF
#endif
#endif

#ifdef SLIM_CONFIG_USE_RDF
#ifndef SLIM_CONFIG_USE_FEED
#define SLIM_CONFIG_USE_FEED
#endif
#ifndef SLIM_CONFIG_USE_XML
#define SLIM_CONFIG_USE_XML
#endif
#endif

#ifdef SLIM_CONFIG_USE_ATOM
#ifndef SLIM_CONFIG_USE_FEED
#define SLIM_CONFIG_USE_FEED
#endif
#ifndef SLIM_CONFIG_USE_XML
#define SLIM_CONFIG_USE_XML
#endif
#endif

/* WML Script */
#ifdef SLIM_CONFIG_USE_WMLSCRIPT
#ifndef SLIM_CONFIG_USE_WML
#define SLIM_CONFIG_USE_WML
#endif
#endif

#ifdef SLIM_CONFIG_USE_WML
#ifndef SLIM_CONFIG_USE_XML
#define SLIM_CONFIG_USE_XML
#endif
#endif

#ifdef SLIM_CONFIG_USE_SMIL
#ifndef SLIM_CONFIG_USE_XML
#define SLIM_CONFIG_USE_XML
#endif
#endif

#ifdef SLIM_CONFIG_USE_SVG
#ifndef SLIM_CONFIG_USE_XML
#define SLIM_CONFIG_USE_XML
#endif
#ifndef SLIM_CONFIG_USE_DATAP
#define SLIM_CONFIG_USE_DATAP
#endif
#endif

#ifdef SLIM_CONFIG_USE_XML_WRITER
#ifndef SLIM_CONFIG_USE_XML
#define SLIM_CONFIG_USE_XML
#endif
#endif

/* image decoders */
#ifndef SLIM_CONFIG_USE_GIF
#define SLIM_CONFIG_NOUSE_GIF
#endif
#ifndef SLIM_CONFIG_USE_JPEG
#define SLIM_CONFIG_NOUSE_JPEG
#endif
#ifndef SLIM_CONFIG_USE_PNG
#define SLIM_CONFIG_NOUSE_PNG
#endif
#ifndef SLIM_CONFIG_USE_MNG
#define SLIM_CONFIG_NOUSE_MNG
#endif
#ifndef SLIM_CONFIG_USE_WBMP
#define SLIM_CONFIG_NOUSE_WBMP
#endif

/* image encoder */
#ifdef SLIM_CONFIG_USE_PNG_ENCODER
#ifndef SLIM_CONFIG_USE_PNG
#define SLIM_CONFIG_USE_PNG
#endif
#ifndef SLIM_CONFIG_USE_ZLIB_DEFLATE
#define SLIM_CONFIG_USE_ZLIB_DEFLATE
#endif
#endif

/* page save */

/* for backward compatibility */
#ifdef SLIM_CONFIG_USE_PAGESAVE_MTH
#define SLIM_CONFIG_USE_PAGESAVE_MHT
#endif

#ifndef SLIM_CONFIG_USE_PAGESAVE_SLIM
#ifndef SLIM_CONFIG_USE_PAGESAVE_MHT
#undef SLIM_CONFIG_USE_PAGESAVE_CACHE
#endif
#endif

#ifndef SLIM_CONFIG_USE_PAGESAVE
#ifdef SLIM_CONFIG_USE_PAGESAVE_SLIM
#define SLIM_CONFIG_USE_PAGESAVE
#endif
#ifdef SLIM_CONFIG_USE_PAGESAVE_MHT
#define SLIM_CONFIG_USE_PAGESAVE
#endif
#endif

#ifndef SLIM_CONFIG_USE_PAGESAVE_SLIM
#ifndef SLIM_CONFIG_USE_PAGESAVE_MHT
#ifndef SLIM_CONFIG_USE_PAGESAVE_CACHE
#undef SLIM_CONFIG_USE_PAGESAVE
#endif
#endif
#endif

/* Netscape Plug-in */
#ifdef SLIM_CONFIG_NSPLUGIN_UNIX
#define XP_UNIX
#endif

#ifdef SLIM_CONFIG_USE_DOM_CRYPTO
#ifndef SLIM_CONFIG_DOM
#define SLIM_CONFIG_DOM
#endif
#endif

/* DOM, JavaScript */
#ifndef SLIM_CONFIG_DOM
#undef SLIM_CONFIG_JS_DEBUG
#undef SLIM_CONFIG_USE_DOM_CRYPTO
#endif

#ifdef SLIM_CONFIG_DOM
#ifndef SLIM_CONFIG_USE_XML
#define SLIM_CONFIG_USE_XML
#endif
#endif

/* I18N */
/* for backward compatibility and convenience */
#ifdef SLIM_CONFIG_DISABLE_CJK
#ifdef SLIM_CONFIG_USE_JAPANESE
#undef SLIM_CONFIG_USE_JAPANESE
#endif	/* SLIM_CONFIG_USE_JAPANESE */
#ifdef SLIM_CONFIG_USE_KOREAN
#undef SLIM_CONFIG_USE_KOREAN
#endif	/* SLIM_CONFIG_USE_KOREAN */
#ifdef SLIM_CONFIG_USE_SIMPLIFIED_CHINESE
#undef SLIM_CONFIG_USE_SIMPLIFIED_CHINESE
#endif	/* SLIM_CONFIG_USE_SIMPLIFIED_CHINESE */
#ifdef SLIM_CONFIG_USE_TRADITIONAL_CHINESE
#undef SLIM_CONFIG_USE_TRADITIONAL_CHINESE
#endif	/* SLIM_CONFIG_USE_TRADITIONAL_CHINESE */
#endif	/* SLIM_CONFIG_DISABLE_CJK */

/* Cryptography */
#ifdef SLIM_CONFIG_CRYPT_EXPORT_RESTRICTION
#undef SLIM_CONFIG_CRYPT_USE_PRBG
#undef SLIM_CONFIG_CRYPT_USE_RC4
#undef SLIM_CONFIG_CRYPT_USE_RC2
#undef SLIM_CONFIG_CRYPT_USE_DES
#undef SLIM_CONFIG_CRYPT_USE_2KEYDES3
#undef SLIM_CONFIG_CRYPT_USE_DES3
#undef SLIM_CONFIG_CRYPT_USE_AES
#undef SLIM_CONFIG_CRYPT_USE_ECB_MODE
#undef SLIM_CONFIG_CRYPT_USE_CBC_MODE
#undef SLIM_CONFIG_CRYPT_USE_STRM
#undef SLIM_CONFIG_CRYPT_USE_BLK
#undef SLIM_CONFIG_CRYPT_USE_SYM
#undef SLIM_CONFIG_CRYPT_USE_RSA
#endif

#ifdef SLIM_CONFIG_CRYPT_USE_PRBG
#define SLIM_CONFIG_CRYPT_USE_MD5
#define SLIM_CONFIG_CRYPT_USE_SHA1
#define SLIM_CONFIG_CRYPT_USE_RC4
#endif

#ifdef SLIM_CONFIG_CRYPT_USE_HMAC
#define SLIM_CONFIG_CRYPT_USE_MD
#endif

#ifdef SLIM_CONFIG_CRYPT_USE_SYM
#define SLIM_CONFIG_CRYPT_USE_STRM
#define SLIM_CONFIG_CRYPT_USE_BLK
#endif

/* PKCS */
#ifdef SLIM_CONFIG_USE_PKCS12
#define SLIM_CONFIG_USE_PKCS7
#define SLIM_CONFIG_USE_ASN1
#endif

#ifdef SLIM_CONFIG_USE_PKCS7
#define SLIM_CONFIG_USE_PKCS5
#define SLIM_CONFIG_USE_ASN1
#endif

/* Rapid Rendering */
#ifdef SLIM_CONFIG_USE_RAPID_RENDERING
#define SLIM_CONFIG_USE_TINYHTML
#endif

/* Version */
#ifndef SLIM_CONFIG_VERSION_EXTENSION
#define SLIM_CONFIG_VERSION_EXTENSION ("")
#endif

/* plate */
#ifdef SLIM_CONFIG_DISABLE_PLATE
#undef SLIM_CONFIG_USE_PLATE
#undef SLIM_CONFIG_USE_PWSPATCH
#endif

#endif
