/*
	archchst.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

#ifndef SLIM_ARCHCHSET_CONF_H
#define SLIM_ARCHCHSET_CONF_H

SLIM_BEGIN_C_LINKAGE

#ifdef SLIM_CONFIG_ARCHCHARSET_UTF_8
#define SLIM_I18N_LANGSET_WESTERN_ARCHCHSET				SLIM_CHARSET_UTF_8
#else	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#define SLIM_I18N_LANGSET_WESTERN_ARCHCHSET				SLIM_CHARSET_ISO_8859_1
#endif	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */

#ifdef SLIM_CONFIG_USE_JAPANESE
#ifdef SLIM_CONFIG_ARCHCHARSET_UTF_8
#define SLIM_I18N_LANGSET_JAPANESE_ARCHCHSET			SLIM_CHARSET_UTF_8
#else	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#ifdef SLIM_CONFIG_LANGSET_JAPANESE_EUC
#define SLIM_I18N_LANGSET_JAPANESE_ARCHCHSET			SLIM_CHARSET_EUC_JP
#else	/* SLIM_CONFIG_LANGSET_JAPANESE_EUC */
#define SLIM_I18N_LANGSET_JAPANESE_ARCHCHSET			SLIM_CHARSET_SHIFT_JIS
#endif	/* SLIM_CONFIG_LANGSET_JAPANESE_EUC */
#endif 	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#else	/* SLIM_CONFIG_USE_JAPANESE */
#define SLIM_I18N_LANGSET_JAPANESE_ARCHCHSET			SLIM_CHARSET_US_ASCII
#endif	/* SLIM_CONFIG_USE_JAPANESE */

#ifdef SLIM_CONFIG_USE_KOREAN
#ifdef SLIM_CONFIG_ARCHCHARSET_UTF_8
#define SLIM_I18N_LANGSET_KOREAN_ARCHCHSET				SLIM_CHARSET_UTF_8
#else	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#define SLIM_I18N_LANGSET_KOREAN_ARCHCHSET				SLIM_CHARSET_EUC_KR
#endif 	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#else	/* SLIM_CONFIG_USE_KOREAN */
#define SLIM_I18N_LANGSET_KOREAN_ARCHCHSET				SLIM_CHARSET_US_ASCII
#endif	/* SLIM_CONFIG_USE_KOREAN */

#ifdef SLIM_CONFIG_USE_SIMPLIFIED_CHINESE
#ifdef SLIM_CONFIG_ARCHCHARSET_UTF_8
#define SLIM_I18N_LANGSET_SIMPLCHINESE_ARCHCHSET		SLIM_CHARSET_UTF_8
#else	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#define SLIM_I18N_LANGSET_SIMPLCHINESE_ARCHCHSET		SLIM_CHARSET_GB2312
#endif 	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#else	/* SLIM_CONFIG_USE_SIMPLIFIED_CHINESE */
#define SLIM_I18N_LANGSET_SIMPLCHINESE_ARCHCHSET		SLIM_CHARSET_US_ASCII
#endif	/* SLIM_CONFIG_USE_SIMPLIFIED_CHINESE */

#ifdef SLIM_CONFIG_USE_TRADITIONAL_CHINESE
#ifdef SLIM_CONFIG_ARCHCHARSET_UTF_8
#define SLIM_I18N_LANGSET_TRADCHINESE_ARCHCHSET			SLIM_CHARSET_UTF_8
#else	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#define SLIM_I18N_LANGSET_TRADCHINESE_ARCHCHSET			SLIM_CHARSET_BIG5
#endif 	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#else	/* SLIM_CONFIG_USE_TRADITIONAL_CHINESE */
#define SLIM_I18N_LANGSET_TRADCHINESE_ARCHCHSET			SLIM_CHARSET_US_ASCII
#endif	/* SLIM_CONFIG_USE_TRADITIONAL_CHINESE */

#define SLIM_I18N_LANGSET_ARMENIAN_ARCHCHSET			SLIM_CHARSET_UNKNOWN

#ifdef SLIM_CONFIG_USE_BALTIC
#ifdef SLIM_CONFIG_ARCHCHARSET_UTF_8
#define SLIM_I18N_LANGSET_BALTIC_ARCHCHSET				SLIM_CHARSET_UTF_8
#else	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#define SLIM_I18N_LANGSET_BALTIC_ARCHCHSET				SLIM_CHARSET_WINDOWS_1257
#endif 	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#else	/* SLIM_CONFIG_USE_BALTIC */
#define SLIM_I18N_LANGSET_BALTIC_ARCHCHSET				SLIM_CHARSET_US_ASCII
#endif	/* SLIM_CONFIG_USE_BALTIC */

#define SLIM_I18N_LANGSET_CELTIC_ARCHCHSET				SLIM_CHARSET_UNKNOWN

#ifdef SLIM_CONFIG_USE_CENTRAL_EUROPEAN
#ifdef SLIM_CONFIG_ARCHCHARSET_UTF_8
#define SLIM_I18N_LANGSET_CENTRAL_EUROPEAN_ARCHCHSET	SLIM_CHARSET_UTF_8
#else	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#define SLIM_I18N_LANGSET_CENTRAL_EUROPEAN_ARCHCHSET	SLIM_CHARSET_WINDOWS_1250
#endif 	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#else	/* SLIM_CONFIG_USE_CENTRAL_EUROPEAN */
#define SLIM_I18N_LANGSET_CENTRAL_EUROPEAN_ARCHCHSET	SLIM_CHARSET_US_ASCII
#endif	/* SLIM_CONFIG_USE_CENTRAL_EUROPEAN */

#define SLIM_I18N_LANGSET_CROATIAN_ARCHCHSET			SLIM_CHARSET_UNKNOWN

#ifdef SLIM_CONFIG_USE_CYRILLIC
#ifdef SLIM_CONFIG_ARCHCHARSET_UTF_8
#define SLIM_I18N_LANGSET_CYRILLIC_ARCHCHSET			SLIM_CHARSET_UTF_8
#else	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#define SLIM_I18N_LANGSET_CYRILLIC_ARCHCHSET			SLIM_CHARSET_WINDOWS_1251
#endif 	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#else	/* SLIM_CONFIG_USE_CYRILLIC */
#define SLIM_I18N_LANGSET_CYRILLIC_ARCHCHSET			SLIM_CHARSET_US_ASCII
#endif	/* SLIM_CONFIG_USE_CYRILLIC */

#define SLIM_I18N_LANGSET_RUSSIAN_CYRILLIC_ARCHCHSET	SLIM_CHARSET_UNKNOWN
#define SLIM_I18N_LANGSET_UKRANIAN_CYRILLIC_ARCHCHSET	SLIM_CHARSET_UNKNOWN

#ifdef SLIM_CONFIG_USE_GREEK
#ifdef SLIM_CONFIG_ARCHCHARSET_UTF_8
#define SLIM_I18N_LANGSET_GREEK_ARCHCHSET				SLIM_CHARSET_UTF_8
#else	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#define SLIM_I18N_LANGSET_GREEK_ARCHCHSET				SLIM_CHARSET_WINDOWS_1253
#endif 	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#else	/* SLIM_CONFIG_USE_GREEK */
#define SLIM_I18N_LANGSET_GREEK_ARCHCHSET				SLIM_CHARSET_US_ASCII
#endif	/* SLIM_CONFIG_USE_GREEK */

#define SLIM_I18N_LANGSET_ICELANDIC_ARCHCHSET			SLIM_CHARSET_UNKNOWN

#ifdef SLIM_CONFIG_USE_NORDIC
#ifdef SLIM_CONFIG_ARCHCHARSET_UTF_8
#define SLIM_I18N_LANGSET_NORDIC_ARCHCHSET				SLIM_CHARSET_UTF_8
#else	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#define SLIM_I18N_LANGSET_NORDIC_ARCHCHSET				SLIM_CHARSET_ISO_8859_10
#endif 	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#else	/* SLIM_CONFIG_USE_NORDIC */
#define SLIM_I18N_LANGSET_NORDIC_ARCHCHSET				SLIM_CHARSET_US_ASCII
#endif	/* SLIM_CONFIG_USE_NORDIC */

#define SLIM_I18N_LANGSET_ROMANIAN_ARCHCHSET			SLIM_CHARSET_UNKNOWN

#ifdef SLIM_CONFIG_USE_SOUTH_EUROPEAN
#ifdef SLIM_CONFIG_ARCHCHARSET_UTF_8
#define SLIM_I18N_LANGSET_SOUTH_EUROPEAN_ARCHCHSET		SLIM_CHARSET_UTF_8
#else	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#define SLIM_I18N_LANGSET_SOUTH_EUROPEAN_ARCHCHSET		SLIM_CHARSET_ISO_8859_3
#endif 	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#else	/* SLIM_CONFIG_USE_SOUTH_EUROPEAN */
#define SLIM_I18N_LANGSET_SOUTH_EUROPEAN_ARCHCHSET		SLIM_CHARSET_US_ASCII
#endif	/* SLIM_CONFIG_USE_SOUTH_EUROPEAN */

#ifdef SLIM_CONFIG_USE_THAI
#ifdef SLIM_CONFIG_ARCHCHARSET_UTF_8
#define SLIM_I18N_LANGSET_THAI_ARCHCHSET				SLIM_CHARSET_UTF_8
#else	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#define SLIM_I18N_LANGSET_THAI_ARCHCHSET				SLIM_CHARSET_WINDOWS_874
#endif 	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#else	/* SLIM_CONFIG_USE_THAI */
#define SLIM_I18N_LANGSET_THAI_ARCHCHSET				SLIM_CHARSET_US_ASCII
#endif	/* SLIM_CONFIG_USE_THAI */

#ifdef SLIM_CONFIG_USE_TURKISH
#ifdef SLIM_CONFIG_ARCHCHARSET_UTF_8
#define SLIM_I18N_LANGSET_TURKISH_ARCHCHSET				SLIM_CHARSET_UTF_8
#else	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#define SLIM_I18N_LANGSET_TURKISH_ARCHCHSET				SLIM_CHARSET_WINDOWS_1254
#endif 	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#else	/* SLIM_CONFIG_USE_TURKISH */
#define SLIM_I18N_LANGSET_TURKISH_ARCHCHSET				SLIM_CHARSET_US_ASCII
#endif	/* SLIM_CONFIG_USE_TURKISH */

#define SLIM_I18N_LANGSET_VIETNAMESE_ARCHCHSET			SLIM_CHARSET_UNKNOWN

#ifdef SLIM_CONFIG_USE_ARABIC
#ifdef SLIM_CONFIG_ARCHCHARSET_UTF_8
#define SLIM_I18N_LANGSET_ARABIC_ARCHCHSET				SLIM_CHARSET_UTF_8
#else	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#define SLIM_I18N_LANGSET_ARABIC_ARCHCHSET				SLIM_CHARSET_WINDOWS_1256
#endif 	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#else	/* SLIM_CONFIG_USE_ARABIC */
#define SLIM_I18N_LANGSET_ARABIC_ARCHCHSET				SLIM_CHARSET_US_ASCII
#endif	/* SLIM_CONFIG_USE_ARABIC */

#ifdef SLIM_CONFIG_USE_HEBREW
#ifdef SLIM_CONFIG_ARCHCHARSET_UTF_8
#define SLIM_I18N_LANGSET_HEBREW_ARCHCHSET				SLIM_CHARSET_UTF_8
#else	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#define SLIM_I18N_LANGSET_HEBREW_ARCHCHSET				SLIM_CHARSET_WINDOWS_1255
#endif 	/* SLIM_CONFIG_ARCHCHARSET_UTF_8 */
#else	/* SLIM_CONFIG_USE_HEBREW */
#define SLIM_I18N_LANGSET_HEBREW_ARCHCHSET				SLIM_CHARSET_US_ASCII
#endif	/* SLIM_CONFIG_USE_HEBREW */

#define SLIM_I18N_LANGSET_UNIVERSAL_ARCHCHSET			SLIM_CHARSET_UTF_8

SLIM_END_C_LINKAGE
#endif
