/*
	chsetid.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/token/chsetid.h 10    06/07/31 9:20 Someya $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_CHSETID_H
#define SLIM_TOKEN_CHSETID_H


SLIM_BEGIN_C_LINKAGE

enum {
	SLIM_TKID_CHSET_US_ASCII = 0,
	SLIM_TKID_CHSET_Shift_JIS,
	SLIM_TKID_CHSET_EUC_JP,
	SLIM_TKID_CHSET_ISO_2022_JP,
	SLIM_TKID_CHSET_ISO_8859_1,
	SLIM_TKID_CHSET_ISO_8859_15,
	SLIM_TKID_CHSET_windows_1252,
	SLIM_TKID_CHSET_EUC_KR,
	SLIM_TKID_CHSET_KS_C_5601_1987,
	SLIM_TKID_CHSET_GB2312,
	SLIM_TKID_CHSET_GBK,
	SLIM_TKID_CHSET_GB18030,
	SLIM_TKID_CHSET_Big5,
	SLIM_TKID_CHSET_ISO_8859_4,
	SLIM_TKID_CHSET_windows_1257,
	SLIM_TKID_CHSET_ISO_8859_2,
	SLIM_TKID_CHSET_windows_1250,
	SLIM_TKID_CHSET_ISO_8859_5,
	SLIM_TKID_CHSET_windows_1251,
	SLIM_TKID_CHSET_koi8_r,
	SLIM_TKID_CHSET_ISO_8859_7,
	SLIM_TKID_CHSET_windows_1253,
	SLIM_TKID_CHSET_ISO_8859_10,
	SLIM_TKID_CHSET_ISO_8859_3,
	SLIM_TKID_CHSET_windows_874,
	SLIM_TKID_CHSET_ISO_8859_9,
	SLIM_TKID_CHSET_windows_1254,
	SLIM_TKID_CHSET_ISO_8859_6,
	SLIM_TKID_CHSET_windows_1256,
	SLIM_TKID_CHSET_ISO_8859_8,
	SLIM_TKID_CHSET_ISO_8859_8_i,
	SLIM_TKID_CHSET_windows_1255,
	SLIM_TKID_CHSET_UTF_8,
	SLIM_TKID_CHSET_UTF_16BE,
	SLIM_TKID_CHSET_UTF_16LE,
	SLIM_TKID_CHSET_ISO_10646_UCS_2,
	SLIM_TKID_CHSET_ISO_10646_UCS_2_LE,
	SLIM_TKID_CHSET_ISO_10646_UCS_4,
	SLIM_TKID_CHSET_ISO_10646_UCS_4_LE,
	SLIM_TKID_CHSET_ENUMS
};

#define SLIM_TOKEN_CHSET_TOKENS SLIM_TKID_CHSET_ENUMS
#define SLIM_TOKEN_CHSET_ENUMS SLIM_TKID_CHSET_ENUMS


SLIM_END_C_LINKAGE
#endif
