/*
	cssp.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/private/token/cssp.h 49    06/07/11 2:23 Yamabuti $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_CSSP_H
#define SLIM_TOKEN_CSSP_H

#include <slim/basis/base.h>
#include <slim/basis/token.h>
#include <slim/private/token/csspid.h>

SLIM_BEGIN_C_LINKAGE

#define SLIM_CSS_PINFO_PV_INDEX	0
#define SLIM_CSS_PINFO_FUNC_INDEX	13
#define SLIM_CSS_PINFO_SYMVAL_INDEX	19
#define SLIM_CSS_PINFO_PV_TOKENS	13
#define SLIM_CSS_PINFO_FUNC_TOKENS	6
#define SLIM_CSS_PINFO_SYMVAL_TOKENS	248
#ifndef SLIM_WWW_WWWBASE_H
#include <slim/www/wwwbase.h>
#endif
struct TCSSParser_;
struct TCSSPropInfo_ {
	TToken fBase;	/* must be the first field */
	slim_int fMediaGroups;
	slim_short fStyleName;
	slim_byte fStyleType;
	slim_byte fRestrictions;
	slim_word fValueInfo[10];
};

#define SLIM_TKOFF_BASE_CSSP0	(0)
#define SLIM_TKNAM_BASE_CSSP0	((slim_char *)cSlim_TokenName_CSSP)
#define SLIM_TKOFF_CSSP_background	(SLIM_TKOFF_BASE_CSSP0 + 0)
#define SLIM_TKNAM_CSSP_background	(SLIM_TKNAM_BASE_CSSP0 + 0)
#define SLIM_TKLEN_CSSP_background	(10)
#define SLIM_TOKEN_CSSP_background	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_background))
#define SLIM_TKOFF_CSSP_background_attachment	(SLIM_TKOFF_BASE_CSSP0 + 11)
#define SLIM_TKNAM_CSSP_background_attachment	(SLIM_TKNAM_BASE_CSSP0 + 11)
#define SLIM_TKLEN_CSSP_background_attachment	(21)
#define SLIM_TOKEN_CSSP_background_attachment	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_background_attachment))
#define SLIM_TKOFF_CSSP_background_color	(SLIM_TKOFF_BASE_CSSP0 + 33)
#define SLIM_TKNAM_CSSP_background_color	(SLIM_TKNAM_BASE_CSSP0 + 33)
#define SLIM_TKLEN_CSSP_background_color	(16)
#define SLIM_TOKEN_CSSP_background_color	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_background_color))
#define SLIM_TKOFF_CSSP_background_image	(SLIM_TKOFF_BASE_CSSP0 + 50)
#define SLIM_TKNAM_CSSP_background_image	(SLIM_TKNAM_BASE_CSSP0 + 50)
#define SLIM_TKLEN_CSSP_background_image	(16)
#define SLIM_TOKEN_CSSP_background_image	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_background_image))
#define SLIM_TKOFF_CSSP_background_position	(SLIM_TKOFF_BASE_CSSP0 + 67)
#define SLIM_TKNAM_CSSP_background_position	(SLIM_TKNAM_BASE_CSSP0 + 67)
#define SLIM_TKLEN_CSSP_background_position	(19)
#define SLIM_TOKEN_CSSP_background_position	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_background_position))
#define SLIM_TKOFF_CSSP_background_repeat	(SLIM_TKOFF_BASE_CSSP0 + 87)
#define SLIM_TKNAM_CSSP_background_repeat	(SLIM_TKNAM_BASE_CSSP0 + 87)
#define SLIM_TKLEN_CSSP_background_repeat	(17)
#define SLIM_TOKEN_CSSP_background_repeat	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_background_repeat))
#define SLIM_TKOFF_CSSP_border	(SLIM_TKOFF_BASE_CSSP0 + 105)
#define SLIM_TKNAM_CSSP_border	(SLIM_TKNAM_BASE_CSSP0 + 105)
#define SLIM_TKLEN_CSSP_border	(6)
#define SLIM_TOKEN_CSSP_border	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border))
#define SLIM_TKOFF_CSSP_border_bottom	(SLIM_TKOFF_BASE_CSSP0 + 112)
#define SLIM_TKNAM_CSSP_border_bottom	(SLIM_TKNAM_BASE_CSSP0 + 112)
#define SLIM_TKLEN_CSSP_border_bottom	(13)
#define SLIM_TOKEN_CSSP_border_bottom	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_bottom))
#define SLIM_TKOFF_CSSP_border_bottom_width	(SLIM_TKOFF_BASE_CSSP0 + 126)
#define SLIM_TKNAM_CSSP_border_bottom_width	(SLIM_TKNAM_BASE_CSSP0 + 126)
#define SLIM_TKLEN_CSSP_border_bottom_width	(19)
#define SLIM_TOKEN_CSSP_border_bottom_width	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_bottom_width))
#define SLIM_TKOFF_CSSP_border_color	(SLIM_TKOFF_BASE_CSSP0 + 146)
#define SLIM_TKNAM_CSSP_border_color	(SLIM_TKNAM_BASE_CSSP0 + 146)
#define SLIM_TKLEN_CSSP_border_color	(12)
#define SLIM_TOKEN_CSSP_border_color	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_color))
#define SLIM_TKOFF_CSSP_border_left	(SLIM_TKOFF_BASE_CSSP0 + 159)
#define SLIM_TKNAM_CSSP_border_left	(SLIM_TKNAM_BASE_CSSP0 + 159)
#define SLIM_TKLEN_CSSP_border_left	(11)
#define SLIM_TOKEN_CSSP_border_left	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_left))
#define SLIM_TKOFF_CSSP_border_left_width	(SLIM_TKOFF_BASE_CSSP0 + 171)
#define SLIM_TKNAM_CSSP_border_left_width	(SLIM_TKNAM_BASE_CSSP0 + 171)
#define SLIM_TKLEN_CSSP_border_left_width	(17)
#define SLIM_TOKEN_CSSP_border_left_width	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_left_width))
#define SLIM_TKOFF_CSSP_border_right	(SLIM_TKOFF_BASE_CSSP0 + 189)
#define SLIM_TKNAM_CSSP_border_right	(SLIM_TKNAM_BASE_CSSP0 + 189)
#define SLIM_TKLEN_CSSP_border_right	(12)
#define SLIM_TOKEN_CSSP_border_right	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_right))
#define SLIM_TKOFF_CSSP_border_right_width	(SLIM_TKOFF_BASE_CSSP0 + 202)
#define SLIM_TKNAM_CSSP_border_right_width	(SLIM_TKNAM_BASE_CSSP0 + 202)
#define SLIM_TKLEN_CSSP_border_right_width	(18)
#define SLIM_TOKEN_CSSP_border_right_width	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_right_width))
#define SLIM_TKOFF_CSSP_border_style	(SLIM_TKOFF_BASE_CSSP0 + 221)
#define SLIM_TKNAM_CSSP_border_style	(SLIM_TKNAM_BASE_CSSP0 + 221)
#define SLIM_TKLEN_CSSP_border_style	(12)
#define SLIM_TOKEN_CSSP_border_style	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_style))
#define SLIM_TKOFF_CSSP_border_top	(SLIM_TKOFF_BASE_CSSP0 + 234)
#define SLIM_TKNAM_CSSP_border_top	(SLIM_TKNAM_BASE_CSSP0 + 234)
#define SLIM_TKLEN_CSSP_border_top	(10)
#define SLIM_TOKEN_CSSP_border_top	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_top))
#define SLIM_TKOFF_CSSP_border_top_width	(SLIM_TKOFF_BASE_CSSP0 + 245)
#define SLIM_TKNAM_CSSP_border_top_width	(SLIM_TKNAM_BASE_CSSP0 + 245)
#define SLIM_TKLEN_CSSP_border_top_width	(16)
#define SLIM_TOKEN_CSSP_border_top_width	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_top_width))
#define SLIM_TKOFF_CSSP_border_width	(SLIM_TKOFF_BASE_CSSP0 + 262)
#define SLIM_TKNAM_CSSP_border_width	(SLIM_TKNAM_BASE_CSSP0 + 262)
#define SLIM_TKLEN_CSSP_border_width	(12)
#define SLIM_TOKEN_CSSP_border_width	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_width))
#define SLIM_TKOFF_CSSP_color	(SLIM_TKOFF_BASE_CSSP0 + 275)
#define SLIM_TKNAM_CSSP_color	(SLIM_TKNAM_BASE_CSSP0 + 275)
#define SLIM_TKLEN_CSSP_color	(5)
#define SLIM_TOKEN_CSSP_color	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_color))
#define SLIM_TKOFF_CSSP_font	(SLIM_TKOFF_BASE_CSSP0 + 281)
#define SLIM_TKNAM_CSSP_font	(SLIM_TKNAM_BASE_CSSP0 + 281)
#define SLIM_TKLEN_CSSP_font	(4)
#define SLIM_TOKEN_CSSP_font	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_font))
#define SLIM_TKOFF_CSSP_font_family	(SLIM_TKOFF_BASE_CSSP0 + 286)
#define SLIM_TKNAM_CSSP_font_family	(SLIM_TKNAM_BASE_CSSP0 + 286)
#define SLIM_TKLEN_CSSP_font_family	(11)
#define SLIM_TOKEN_CSSP_font_family	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_font_family))
#define SLIM_TKOFF_CSSP_font_size	(SLIM_TKOFF_BASE_CSSP0 + 298)
#define SLIM_TKNAM_CSSP_font_size	(SLIM_TKNAM_BASE_CSSP0 + 298)
#define SLIM_TKLEN_CSSP_font_size	(9)
#define SLIM_TOKEN_CSSP_font_size	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_font_size))
#define SLIM_TKOFF_CSSP_font_style	(SLIM_TKOFF_BASE_CSSP0 + 308)
#define SLIM_TKNAM_CSSP_font_style	(SLIM_TKNAM_BASE_CSSP0 + 308)
#define SLIM_TKLEN_CSSP_font_style	(10)
#define SLIM_TOKEN_CSSP_font_style	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_font_style))
#define SLIM_TKOFF_CSSP_font_variant	(SLIM_TKOFF_BASE_CSSP0 + 319)
#define SLIM_TKNAM_CSSP_font_variant	(SLIM_TKNAM_BASE_CSSP0 + 319)
#define SLIM_TKLEN_CSSP_font_variant	(12)
#define SLIM_TOKEN_CSSP_font_variant	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_font_variant))
#define SLIM_TKOFF_CSSP_font_weight	(SLIM_TKOFF_BASE_CSSP0 + 332)
#define SLIM_TKNAM_CSSP_font_weight	(SLIM_TKNAM_BASE_CSSP0 + 332)
#define SLIM_TKLEN_CSSP_font_weight	(11)
#define SLIM_TOKEN_CSSP_font_weight	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_font_weight))
#define SLIM_TKOFF_CSSP_height	(SLIM_TKOFF_BASE_CSSP0 + 344)
#define SLIM_TKNAM_CSSP_height	(SLIM_TKNAM_BASE_CSSP0 + 344)
#define SLIM_TKLEN_CSSP_height	(6)
#define SLIM_TOKEN_CSSP_height	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_height))
#define SLIM_TKOFF_CSSP_list_style	(SLIM_TKOFF_BASE_CSSP0 + 351)
#define SLIM_TKNAM_CSSP_list_style	(SLIM_TKNAM_BASE_CSSP0 + 351)
#define SLIM_TKLEN_CSSP_list_style	(10)
#define SLIM_TOKEN_CSSP_list_style	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_list_style))
#define SLIM_TKOFF_CSSP_list_style_image	(SLIM_TKOFF_BASE_CSSP0 + 362)
#define SLIM_TKNAM_CSSP_list_style_image	(SLIM_TKNAM_BASE_CSSP0 + 362)
#define SLIM_TKLEN_CSSP_list_style_image	(16)
#define SLIM_TOKEN_CSSP_list_style_image	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_list_style_image))
#define SLIM_TKOFF_CSSP_list_style_position	(SLIM_TKOFF_BASE_CSSP0 + 379)
#define SLIM_TKNAM_CSSP_list_style_position	(SLIM_TKNAM_BASE_CSSP0 + 379)
#define SLIM_TKLEN_CSSP_list_style_position	(19)
#define SLIM_TOKEN_CSSP_list_style_position	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_list_style_position))
#define SLIM_TKOFF_CSSP_list_style_type	(SLIM_TKOFF_BASE_CSSP0 + 399)
#define SLIM_TKNAM_CSSP_list_style_type	(SLIM_TKNAM_BASE_CSSP0 + 399)
#define SLIM_TKLEN_CSSP_list_style_type	(15)
#define SLIM_TOKEN_CSSP_list_style_type	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_list_style_type))
#define SLIM_TKOFF_CSSP_margin	(SLIM_TKOFF_BASE_CSSP0 + 415)
#define SLIM_TKNAM_CSSP_margin	(SLIM_TKNAM_BASE_CSSP0 + 415)
#define SLIM_TKLEN_CSSP_margin	(6)
#define SLIM_TOKEN_CSSP_margin	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_margin))
#define SLIM_TKOFF_CSSP_margin_bottom	(SLIM_TKOFF_BASE_CSSP0 + 422)
#define SLIM_TKNAM_CSSP_margin_bottom	(SLIM_TKNAM_BASE_CSSP0 + 422)
#define SLIM_TKLEN_CSSP_margin_bottom	(13)
#define SLIM_TOKEN_CSSP_margin_bottom	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_margin_bottom))
#define SLIM_TKOFF_CSSP_margin_left	(SLIM_TKOFF_BASE_CSSP0 + 436)
#define SLIM_TKNAM_CSSP_margin_left	(SLIM_TKNAM_BASE_CSSP0 + 436)
#define SLIM_TKLEN_CSSP_margin_left	(11)
#define SLIM_TOKEN_CSSP_margin_left	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_margin_left))
#define SLIM_TKOFF_CSSP_margin_right	(SLIM_TKOFF_BASE_CSSP0 + 448)
#define SLIM_TKNAM_CSSP_margin_right	(SLIM_TKNAM_BASE_CSSP0 + 448)
#define SLIM_TKLEN_CSSP_margin_right	(12)
#define SLIM_TOKEN_CSSP_margin_right	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_margin_right))
#define SLIM_TKOFF_CSSP_margin_top	(SLIM_TKOFF_BASE_CSSP0 + 461)
#define SLIM_TKNAM_CSSP_margin_top	(SLIM_TKNAM_BASE_CSSP0 + 461)
#define SLIM_TKLEN_CSSP_margin_top	(10)
#define SLIM_TOKEN_CSSP_margin_top	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_margin_top))
#define SLIM_TKOFF_CSSP_padding	(SLIM_TKOFF_BASE_CSSP0 + 472)
#define SLIM_TKNAM_CSSP_padding	(SLIM_TKNAM_BASE_CSSP0 + 472)
#define SLIM_TKLEN_CSSP_padding	(7)
#define SLIM_TOKEN_CSSP_padding	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_padding))
#define SLIM_TKOFF_CSSP_padding_bottom	(SLIM_TKOFF_BASE_CSSP0 + 480)
#define SLIM_TKNAM_CSSP_padding_bottom	(SLIM_TKNAM_BASE_CSSP0 + 480)
#define SLIM_TKLEN_CSSP_padding_bottom	(14)
#define SLIM_TOKEN_CSSP_padding_bottom	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_padding_bottom))
#define SLIM_TKOFF_CSSP_padding_left	(SLIM_TKOFF_BASE_CSSP0 + 495)
#define SLIM_TKNAM_CSSP_padding_left	(SLIM_TKNAM_BASE_CSSP0 + 495)
#define SLIM_TKLEN_CSSP_padding_left	(12)
#define SLIM_TOKEN_CSSP_padding_left	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_padding_left))
#define SLIM_TKOFF_CSSP_padding_right	(SLIM_TKOFF_BASE_CSSP0 + 508)
#define SLIM_TKNAM_CSSP_padding_right	(SLIM_TKNAM_BASE_CSSP0 + 508)
#define SLIM_TKLEN_CSSP_padding_right	(13)
#define SLIM_TOKEN_CSSP_padding_right	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_padding_right))
#define SLIM_TKOFF_CSSP_padding_top	(SLIM_TKOFF_BASE_CSSP0 + 522)
#define SLIM_TKNAM_CSSP_padding_top	(SLIM_TKNAM_BASE_CSSP0 + 522)
#define SLIM_TKLEN_CSSP_padding_top	(11)
#define SLIM_TOKEN_CSSP_padding_top	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_padding_top))
#define SLIM_TKOFF_CSSP_text_align	(SLIM_TKOFF_BASE_CSSP0 + 534)
#define SLIM_TKNAM_CSSP_text_align	(SLIM_TKNAM_BASE_CSSP0 + 534)
#define SLIM_TKLEN_CSSP_text_align	(10)
#define SLIM_TOKEN_CSSP_text_align	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_text_align))
#define SLIM_TKOFF_CSSP_text_decoration	(SLIM_TKOFF_BASE_CSSP0 + 545)
#define SLIM_TKNAM_CSSP_text_decoration	(SLIM_TKNAM_BASE_CSSP0 + 545)
#define SLIM_TKLEN_CSSP_text_decoration	(15)
#define SLIM_TOKEN_CSSP_text_decoration	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_text_decoration))
#define SLIM_TKOFF_CSSP_text_indent	(SLIM_TKOFF_BASE_CSSP0 + 561)
#define SLIM_TKNAM_CSSP_text_indent	(SLIM_TKNAM_BASE_CSSP0 + 561)
#define SLIM_TKLEN_CSSP_text_indent	(11)
#define SLIM_TOKEN_CSSP_text_indent	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_text_indent))
#define SLIM_TKOFF_CSSP_text_transform	(SLIM_TKOFF_BASE_CSSP0 + 573)
#define SLIM_TKNAM_CSSP_text_transform	(SLIM_TKNAM_BASE_CSSP0 + 573)
#define SLIM_TKLEN_CSSP_text_transform	(14)
#define SLIM_TOKEN_CSSP_text_transform	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_text_transform))
#define SLIM_TKOFF_CSSP_vertical_align	(SLIM_TKOFF_BASE_CSSP0 + 588)
#define SLIM_TKNAM_CSSP_vertical_align	(SLIM_TKNAM_BASE_CSSP0 + 588)
#define SLIM_TKLEN_CSSP_vertical_align	(14)
#define SLIM_TOKEN_CSSP_vertical_align	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_vertical_align))
#define SLIM_TKOFF_CSSP_white_space	(SLIM_TKOFF_BASE_CSSP0 + 603)
#define SLIM_TKNAM_CSSP_white_space	(SLIM_TKNAM_BASE_CSSP0 + 603)
#define SLIM_TKLEN_CSSP_white_space	(11)
#define SLIM_TOKEN_CSSP_white_space	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_white_space))
#define SLIM_TKOFF_CSSP_width	(SLIM_TKOFF_BASE_CSSP0 + 615)
#define SLIM_TKNAM_CSSP_width	(SLIM_TKNAM_BASE_CSSP0 + 615)
#define SLIM_TKLEN_CSSP_width	(5)
#define SLIM_TOKEN_CSSP_width	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_width))
#define SLIM_TKOFF_CSSP_display	(SLIM_TKOFF_BASE_CSSP0 + 621)
#define SLIM_TKNAM_CSSP_display	(SLIM_TKNAM_BASE_CSSP0 + 621)
#define SLIM_TKLEN_CSSP_display	(7)
#define SLIM_TOKEN_CSSP_display	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_display))
#define SLIM_TKOFF_CSSP_clear	(SLIM_TKOFF_BASE_CSSP0 + 629)
#define SLIM_TKNAM_CSSP_clear	(SLIM_TKNAM_BASE_CSSP0 + 629)
#define SLIM_TKLEN_CSSP_clear	(5)
#define SLIM_TOKEN_CSSP_clear	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_clear))
#define SLIM_TKOFF_CSSP_float	(SLIM_TKOFF_BASE_CSSP0 + 635)
#define SLIM_TKNAM_CSSP_float	(SLIM_TKNAM_BASE_CSSP0 + 635)
#define SLIM_TKLEN_CSSP_float	(5)
#define SLIM_TOKEN_CSSP_float	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_float))
#define SLIM_TKOFF_CSSP_letter_spacing	(SLIM_TKOFF_BASE_CSSP0 + 641)
#define SLIM_TKNAM_CSSP_letter_spacing	(SLIM_TKNAM_BASE_CSSP0 + 641)
#define SLIM_TKLEN_CSSP_letter_spacing	(14)
#define SLIM_TOKEN_CSSP_letter_spacing	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_letter_spacing))
#define SLIM_TKOFF_CSSP_line_height	(SLIM_TKOFF_BASE_CSSP0 + 656)
#define SLIM_TKNAM_CSSP_line_height	(SLIM_TKNAM_BASE_CSSP0 + 656)
#define SLIM_TKLEN_CSSP_line_height	(11)
#define SLIM_TOKEN_CSSP_line_height	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_line_height))
#define SLIM_TKOFF_CSSP_word_spacing	(SLIM_TKOFF_BASE_CSSP0 + 668)
#define SLIM_TKNAM_CSSP_word_spacing	(SLIM_TKNAM_BASE_CSSP0 + 668)
#define SLIM_TKLEN_CSSP_word_spacing	(12)
#define SLIM_TOKEN_CSSP_word_spacing	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_word_spacing))
#define SLIM_TKOFF_CSSP_border_bottom_color	(SLIM_TKOFF_BASE_CSSP0 + 681)
#define SLIM_TKNAM_CSSP_border_bottom_color	(SLIM_TKNAM_BASE_CSSP0 + 681)
#define SLIM_TKLEN_CSSP_border_bottom_color	(19)
#define SLIM_TOKEN_CSSP_border_bottom_color	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_bottom_color))
#define SLIM_TKOFF_CSSP_border_bottom_style	(SLIM_TKOFF_BASE_CSSP0 + 701)
#define SLIM_TKNAM_CSSP_border_bottom_style	(SLIM_TKNAM_BASE_CSSP0 + 701)
#define SLIM_TKLEN_CSSP_border_bottom_style	(19)
#define SLIM_TOKEN_CSSP_border_bottom_style	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_bottom_style))
#define SLIM_TKOFF_CSSP_border_left_color	(SLIM_TKOFF_BASE_CSSP0 + 721)
#define SLIM_TKNAM_CSSP_border_left_color	(SLIM_TKNAM_BASE_CSSP0 + 721)
#define SLIM_TKLEN_CSSP_border_left_color	(17)
#define SLIM_TOKEN_CSSP_border_left_color	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_left_color))
#define SLIM_TKOFF_CSSP_border_left_style	(SLIM_TKOFF_BASE_CSSP0 + 739)
#define SLIM_TKNAM_CSSP_border_left_style	(SLIM_TKNAM_BASE_CSSP0 + 739)
#define SLIM_TKLEN_CSSP_border_left_style	(17)
#define SLIM_TOKEN_CSSP_border_left_style	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_left_style))
#define SLIM_TKOFF_CSSP_border_right_color	(SLIM_TKOFF_BASE_CSSP0 + 757)
#define SLIM_TKNAM_CSSP_border_right_color	(SLIM_TKNAM_BASE_CSSP0 + 757)
#define SLIM_TKLEN_CSSP_border_right_color	(18)
#define SLIM_TOKEN_CSSP_border_right_color	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_right_color))
#define SLIM_TKOFF_CSSP_border_right_style	(SLIM_TKOFF_BASE_CSSP0 + 776)
#define SLIM_TKNAM_CSSP_border_right_style	(SLIM_TKNAM_BASE_CSSP0 + 776)
#define SLIM_TKLEN_CSSP_border_right_style	(18)
#define SLIM_TOKEN_CSSP_border_right_style	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_right_style))
#define SLIM_TKOFF_CSSP_border_top_color	(SLIM_TKOFF_BASE_CSSP0 + 795)
#define SLIM_TKNAM_CSSP_border_top_color	(SLIM_TKNAM_BASE_CSSP0 + 795)
#define SLIM_TKLEN_CSSP_border_top_color	(16)
#define SLIM_TOKEN_CSSP_border_top_color	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_top_color))
#define SLIM_TKOFF_CSSP_border_top_style	(SLIM_TKOFF_BASE_CSSP0 + 812)
#define SLIM_TKNAM_CSSP_border_top_style	(SLIM_TKNAM_BASE_CSSP0 + 812)
#define SLIM_TKLEN_CSSP_border_top_style	(16)
#define SLIM_TOKEN_CSSP_border_top_style	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_top_style))
#define SLIM_TKOFF_CSSP_font_size_adjust	(SLIM_TKOFF_BASE_CSSP0 + 829)
#define SLIM_TKNAM_CSSP_font_size_adjust	(SLIM_TKNAM_BASE_CSSP0 + 829)
#define SLIM_TKLEN_CSSP_font_size_adjust	(16)
#define SLIM_TOKEN_CSSP_font_size_adjust	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_font_size_adjust))
#define SLIM_TKOFF_CSSP_font_stretch	(SLIM_TKOFF_BASE_CSSP0 + 846)
#define SLIM_TKNAM_CSSP_font_stretch	(SLIM_TKNAM_BASE_CSSP0 + 846)
#define SLIM_TKLEN_CSSP_font_stretch	(12)
#define SLIM_TOKEN_CSSP_font_stretch	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_font_stretch))
#define SLIM_TKOFF_CSSP__wap_marquee_style	(SLIM_TKOFF_BASE_CSSP0 + 859)
#define SLIM_TKNAM_CSSP__wap_marquee_style	(SLIM_TKNAM_BASE_CSSP0 + 859)
#define SLIM_TKLEN_CSSP__wap_marquee_style	(18)
#define SLIM_TOKEN_CSSP__wap_marquee_style	(CSSPropInfo_GetItem(SLIM_TKID_CSSP__wap_marquee_style))
#define SLIM_TKOFF_CSSP__wap_marquee_loop	(SLIM_TKOFF_BASE_CSSP0 + 878)
#define SLIM_TKNAM_CSSP__wap_marquee_loop	(SLIM_TKNAM_BASE_CSSP0 + 878)
#define SLIM_TKLEN_CSSP__wap_marquee_loop	(17)
#define SLIM_TOKEN_CSSP__wap_marquee_loop	(CSSPropInfo_GetItem(SLIM_TKID_CSSP__wap_marquee_loop))
#define SLIM_TKOFF_CSSP__wap_marquee_dir	(SLIM_TKOFF_BASE_CSSP0 + 896)
#define SLIM_TKNAM_CSSP__wap_marquee_dir	(SLIM_TKNAM_BASE_CSSP0 + 896)
#define SLIM_TKLEN_CSSP__wap_marquee_dir	(16)
#define SLIM_TOKEN_CSSP__wap_marquee_dir	(CSSPropInfo_GetItem(SLIM_TKID_CSSP__wap_marquee_dir))
#define SLIM_TKOFF_CSSP__wap_marquee_speed	(SLIM_TKOFF_BASE_CSSP0 + 913)
#define SLIM_TKNAM_CSSP__wap_marquee_speed	(SLIM_TKNAM_BASE_CSSP0 + 913)
#define SLIM_TKLEN_CSSP__wap_marquee_speed	(18)
#define SLIM_TOKEN_CSSP__wap_marquee_speed	(CSSPropInfo_GetItem(SLIM_TKID_CSSP__wap_marquee_speed))
#define SLIM_TKOFF_CSSP__wap_accesskey	(SLIM_TKOFF_BASE_CSSP0 + 932)
#define SLIM_TKNAM_CSSP__wap_accesskey	(SLIM_TKNAM_BASE_CSSP0 + 932)
#define SLIM_TKLEN_CSSP__wap_accesskey	(14)
#define SLIM_TOKEN_CSSP__wap_accesskey	(CSSPropInfo_GetItem(SLIM_TKID_CSSP__wap_accesskey))
#define SLIM_TKOFF_CSSP__wap_input_format	(SLIM_TKOFF_BASE_CSSP0 + 947)
#define SLIM_TKNAM_CSSP__wap_input_format	(SLIM_TKNAM_BASE_CSSP0 + 947)
#define SLIM_TKLEN_CSSP__wap_input_format	(17)
#define SLIM_TOKEN_CSSP__wap_input_format	(CSSPropInfo_GetItem(SLIM_TKID_CSSP__wap_input_format))
#define SLIM_TKOFF_CSSP__wap_input_required	(SLIM_TKOFF_BASE_CSSP0 + 965)
#define SLIM_TKNAM_CSSP__wap_input_required	(SLIM_TKNAM_BASE_CSSP0 + 965)
#define SLIM_TKLEN_CSSP__wap_input_required	(19)
#define SLIM_TOKEN_CSSP__wap_input_required	(CSSPropInfo_GetItem(SLIM_TKID_CSSP__wap_input_required))
#define SLIM_TKOFF_BASE_CSSP1	(SLIM_TKOFF_BASE_CSSP0 + 985)
#define SLIM_TKNAM_BASE_CSSP1	(SLIM_TKNAM_BASE_CSSP0 + SLIM_TKOFF_BASE_CSSP1)
#ifdef SLIM_CONFIG_CSS_EXTENSION_BROADCAST
#define SLIM_TKOFF_CSSP_used_key_list	(SLIM_TKOFF_BASE_CSSP1 + 0)
#define SLIM_TKNAM_CSSP_used_key_list	(SLIM_TKNAM_BASE_CSSP1 + 0)
#define SLIM_TKLEN_CSSP_used_key_list	(13)
#define SLIM_TOKEN_CSSP_used_key_list	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_used_key_list))
#define SLIM_TKOFF_CSSP_resolution	(SLIM_TKOFF_BASE_CSSP1 + 14)
#define SLIM_TKNAM_CSSP_resolution	(SLIM_TKNAM_BASE_CSSP1 + 14)
#define SLIM_TKLEN_CSSP_resolution	(10)
#define SLIM_TOKEN_CSSP_resolution	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_resolution))
#define SLIM_TKOFF_CSSP_resolution_width	(SLIM_TKOFF_BASE_CSSP1 + 25)
#define SLIM_TKNAM_CSSP_resolution_width	(SLIM_TKNAM_BASE_CSSP1 + 25)
#define SLIM_TKLEN_CSSP_resolution_width	(16)
#define SLIM_TOKEN_CSSP_resolution_width	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_resolution_width))
#define SLIM_TKOFF_CSSP_resolution_height	(SLIM_TKOFF_BASE_CSSP1 + 42)
#define SLIM_TKNAM_CSSP_resolution_height	(SLIM_TKNAM_BASE_CSSP1 + 42)
#define SLIM_TKLEN_CSSP_resolution_height	(17)
#define SLIM_TOKEN_CSSP_resolution_height	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_resolution_height))
#define SLIM_TKOFF_BASE_CSSP2	(SLIM_TKOFF_BASE_CSSP1 + 60)
#else /* SLIM_CONFIG_CSS_EXTENSION_BROADCAST */
#define SLIM_TKOFF_BASE_CSSP2	(SLIM_TKOFF_BASE_CSSP1)
#endif /* SLIM_CONFIG_CSS_EXTENSION_BROADCAST */
#define SLIM_TKNAM_BASE_CSSP2	(SLIM_TKNAM_BASE_CSSP0 + SLIM_TKOFF_BASE_CSSP2)
#ifdef SLIM_CONFIG_CSS_LEVEL_1_POSITIONING
#define SLIM_TKOFF_CSSP_bottom	(SLIM_TKOFF_BASE_CSSP2 + 0)
#define SLIM_TKNAM_CSSP_bottom	(SLIM_TKNAM_BASE_CSSP2 + 0)
#define SLIM_TKLEN_CSSP_bottom	(6)
#define SLIM_TOKEN_CSSP_bottom	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_bottom))
#define SLIM_TKOFF_CSSP_clip	(SLIM_TKOFF_BASE_CSSP2 + 7)
#define SLIM_TKNAM_CSSP_clip	(SLIM_TKNAM_BASE_CSSP2 + 7)
#define SLIM_TKLEN_CSSP_clip	(4)
#define SLIM_TOKEN_CSSP_clip	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_clip))
#define SLIM_TKOFF_CSSP_left	(SLIM_TKOFF_BASE_CSSP2 + 12)
#define SLIM_TKNAM_CSSP_left	(SLIM_TKNAM_BASE_CSSP2 + 12)
#define SLIM_TKLEN_CSSP_left	(4)
#define SLIM_TOKEN_CSSP_left	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_left))
#define SLIM_TKOFF_CSSP_overflow	(SLIM_TKOFF_BASE_CSSP2 + 17)
#define SLIM_TKNAM_CSSP_overflow	(SLIM_TKNAM_BASE_CSSP2 + 17)
#define SLIM_TKLEN_CSSP_overflow	(8)
#define SLIM_TOKEN_CSSP_overflow	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_overflow))
#define SLIM_TKOFF_CSSP_position	(SLIM_TKOFF_BASE_CSSP2 + 26)
#define SLIM_TKNAM_CSSP_position	(SLIM_TKNAM_BASE_CSSP2 + 26)
#define SLIM_TKLEN_CSSP_position	(8)
#define SLIM_TOKEN_CSSP_position	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_position))
#define SLIM_TKOFF_CSSP_right	(SLIM_TKOFF_BASE_CSSP2 + 35)
#define SLIM_TKNAM_CSSP_right	(SLIM_TKNAM_BASE_CSSP2 + 35)
#define SLIM_TKLEN_CSSP_right	(5)
#define SLIM_TOKEN_CSSP_right	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_right))
#define SLIM_TKOFF_CSSP_top	(SLIM_TKOFF_BASE_CSSP2 + 41)
#define SLIM_TKNAM_CSSP_top	(SLIM_TKNAM_BASE_CSSP2 + 41)
#define SLIM_TKLEN_CSSP_top	(3)
#define SLIM_TOKEN_CSSP_top	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_top))
#define SLIM_TKOFF_CSSP_visibility	(SLIM_TKOFF_BASE_CSSP2 + 45)
#define SLIM_TKNAM_CSSP_visibility	(SLIM_TKNAM_BASE_CSSP2 + 45)
#define SLIM_TKLEN_CSSP_visibility	(10)
#define SLIM_TOKEN_CSSP_visibility	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_visibility))
#define SLIM_TKOFF_CSSP_z_index	(SLIM_TKOFF_BASE_CSSP2 + 56)
#define SLIM_TKNAM_CSSP_z_index	(SLIM_TKNAM_BASE_CSSP2 + 56)
#define SLIM_TKLEN_CSSP_z_index	(7)
#define SLIM_TOKEN_CSSP_z_index	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_z_index))
#define SLIM_TKOFF_BASE_CSSP3	(SLIM_TKOFF_BASE_CSSP2 + 64)
#else /* SLIM_CONFIG_CSS_LEVEL_1_POSITIONING */
#define SLIM_TKOFF_BASE_CSSP3	(SLIM_TKOFF_BASE_CSSP2)
#endif /* SLIM_CONFIG_CSS_LEVEL_1_POSITIONING */
#define SLIM_TKNAM_BASE_CSSP3	(SLIM_TKNAM_BASE_CSSP0 + SLIM_TKOFF_BASE_CSSP3)
#ifdef SLIM_CONFIG_CSS_LEVEL_2
#define SLIM_TKOFF_CSSP_border_collapse	(SLIM_TKOFF_BASE_CSSP3 + 0)
#define SLIM_TKNAM_CSSP_border_collapse	(SLIM_TKNAM_BASE_CSSP3 + 0)
#define SLIM_TKLEN_CSSP_border_collapse	(15)
#define SLIM_TOKEN_CSSP_border_collapse	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_collapse))
#define SLIM_TKOFF_CSSP_border_spacing	(SLIM_TKOFF_BASE_CSSP3 + 16)
#define SLIM_TKNAM_CSSP_border_spacing	(SLIM_TKNAM_BASE_CSSP3 + 16)
#define SLIM_TKLEN_CSSP_border_spacing	(14)
#define SLIM_TOKEN_CSSP_border_spacing	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_border_spacing))
#define SLIM_TKOFF_CSSP_caption_side	(SLIM_TKOFF_BASE_CSSP3 + 31)
#define SLIM_TKNAM_CSSP_caption_side	(SLIM_TKNAM_BASE_CSSP3 + 31)
#define SLIM_TKLEN_CSSP_caption_side	(12)
#define SLIM_TOKEN_CSSP_caption_side	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_caption_side))
#define SLIM_TKOFF_CSSP_direction	(SLIM_TKOFF_BASE_CSSP3 + 44)
#define SLIM_TKNAM_CSSP_direction	(SLIM_TKNAM_BASE_CSSP3 + 44)
#define SLIM_TKLEN_CSSP_direction	(9)
#define SLIM_TOKEN_CSSP_direction	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_direction))
#define SLIM_TKOFF_CSSP_empty_cells	(SLIM_TKOFF_BASE_CSSP3 + 54)
#define SLIM_TKNAM_CSSP_empty_cells	(SLIM_TKNAM_BASE_CSSP3 + 54)
#define SLIM_TKLEN_CSSP_empty_cells	(11)
#define SLIM_TOKEN_CSSP_empty_cells	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_empty_cells))
#define SLIM_TKOFF_CSSP_marker_offset	(SLIM_TKOFF_BASE_CSSP3 + 66)
#define SLIM_TKNAM_CSSP_marker_offset	(SLIM_TKNAM_BASE_CSSP3 + 66)
#define SLIM_TKLEN_CSSP_marker_offset	(13)
#define SLIM_TOKEN_CSSP_marker_offset	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_marker_offset))
#define SLIM_TKOFF_CSSP_max_height	(SLIM_TKOFF_BASE_CSSP3 + 80)
#define SLIM_TKNAM_CSSP_max_height	(SLIM_TKNAM_BASE_CSSP3 + 80)
#define SLIM_TKLEN_CSSP_max_height	(10)
#define SLIM_TOKEN_CSSP_max_height	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_max_height))
#define SLIM_TKOFF_CSSP_max_width	(SLIM_TKOFF_BASE_CSSP3 + 91)
#define SLIM_TKNAM_CSSP_max_width	(SLIM_TKNAM_BASE_CSSP3 + 91)
#define SLIM_TKLEN_CSSP_max_width	(9)
#define SLIM_TOKEN_CSSP_max_width	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_max_width))
#define SLIM_TKOFF_CSSP_min_height	(SLIM_TKOFF_BASE_CSSP3 + 101)
#define SLIM_TKNAM_CSSP_min_height	(SLIM_TKNAM_BASE_CSSP3 + 101)
#define SLIM_TKLEN_CSSP_min_height	(10)
#define SLIM_TOKEN_CSSP_min_height	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_min_height))
#define SLIM_TKOFF_CSSP_min_width	(SLIM_TKOFF_BASE_CSSP3 + 112)
#define SLIM_TKNAM_CSSP_min_width	(SLIM_TKNAM_BASE_CSSP3 + 112)
#define SLIM_TKLEN_CSSP_min_width	(9)
#define SLIM_TOKEN_CSSP_min_width	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_min_width))
#define SLIM_TKOFF_CSSP_quotes	(SLIM_TKOFF_BASE_CSSP3 + 122)
#define SLIM_TKNAM_CSSP_quotes	(SLIM_TKNAM_BASE_CSSP3 + 122)
#define SLIM_TKLEN_CSSP_quotes	(6)
#define SLIM_TOKEN_CSSP_quotes	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_quotes))
#define SLIM_TKOFF_CSSP_table_layout	(SLIM_TKOFF_BASE_CSSP3 + 129)
#define SLIM_TKNAM_CSSP_table_layout	(SLIM_TKNAM_BASE_CSSP3 + 129)
#define SLIM_TKLEN_CSSP_table_layout	(12)
#define SLIM_TOKEN_CSSP_table_layout	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_table_layout))
#define SLIM_TKOFF_CSSP_text_shadow	(SLIM_TKOFF_BASE_CSSP3 + 142)
#define SLIM_TKNAM_CSSP_text_shadow	(SLIM_TKNAM_BASE_CSSP3 + 142)
#define SLIM_TKLEN_CSSP_text_shadow	(11)
#define SLIM_TOKEN_CSSP_text_shadow	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_text_shadow))
#define SLIM_TKOFF_CSSP_unicode_bidi	(SLIM_TKOFF_BASE_CSSP3 + 154)
#define SLIM_TKNAM_CSSP_unicode_bidi	(SLIM_TKNAM_BASE_CSSP3 + 154)
#define SLIM_TKLEN_CSSP_unicode_bidi	(12)
#define SLIM_TOKEN_CSSP_unicode_bidi	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_unicode_bidi))
#define SLIM_TKOFF_CSSP_cursor	(SLIM_TKOFF_BASE_CSSP3 + 167)
#define SLIM_TKNAM_CSSP_cursor	(SLIM_TKNAM_BASE_CSSP3 + 167)
#define SLIM_TKLEN_CSSP_cursor	(6)
#define SLIM_TOKEN_CSSP_cursor	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_cursor))
#define SLIM_TKOFF_CSSP_outline	(SLIM_TKOFF_BASE_CSSP3 + 174)
#define SLIM_TKNAM_CSSP_outline	(SLIM_TKNAM_BASE_CSSP3 + 174)
#define SLIM_TKLEN_CSSP_outline	(7)
#define SLIM_TOKEN_CSSP_outline	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_outline))
#define SLIM_TKOFF_CSSP_outline_color	(SLIM_TKOFF_BASE_CSSP3 + 182)
#define SLIM_TKNAM_CSSP_outline_color	(SLIM_TKNAM_BASE_CSSP3 + 182)
#define SLIM_TKLEN_CSSP_outline_color	(13)
#define SLIM_TOKEN_CSSP_outline_color	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_outline_color))
#define SLIM_TKOFF_CSSP_outline_style	(SLIM_TKOFF_BASE_CSSP3 + 196)
#define SLIM_TKNAM_CSSP_outline_style	(SLIM_TKNAM_BASE_CSSP3 + 196)
#define SLIM_TKLEN_CSSP_outline_style	(13)
#define SLIM_TOKEN_CSSP_outline_style	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_outline_style))
#define SLIM_TKOFF_CSSP_outline_width	(SLIM_TKOFF_BASE_CSSP3 + 210)
#define SLIM_TKNAM_CSSP_outline_width	(SLIM_TKNAM_BASE_CSSP3 + 210)
#define SLIM_TKLEN_CSSP_outline_width	(13)
#define SLIM_TOKEN_CSSP_outline_width	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_outline_width))
#define SLIM_TKOFF_CSSP_marks	(SLIM_TKOFF_BASE_CSSP3 + 224)
#define SLIM_TKNAM_CSSP_marks	(SLIM_TKNAM_BASE_CSSP3 + 224)
#define SLIM_TKLEN_CSSP_marks	(5)
#define SLIM_TOKEN_CSSP_marks	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_marks))
#define SLIM_TKOFF_CSSP_orphans	(SLIM_TKOFF_BASE_CSSP3 + 230)
#define SLIM_TKNAM_CSSP_orphans	(SLIM_TKNAM_BASE_CSSP3 + 230)
#define SLIM_TKLEN_CSSP_orphans	(7)
#define SLIM_TOKEN_CSSP_orphans	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_orphans))
#define SLIM_TKOFF_CSSP_page	(SLIM_TKOFF_BASE_CSSP3 + 238)
#define SLIM_TKNAM_CSSP_page	(SLIM_TKNAM_BASE_CSSP3 + 238)
#define SLIM_TKLEN_CSSP_page	(4)
#define SLIM_TOKEN_CSSP_page	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_page))
#define SLIM_TKOFF_CSSP_page_break_after	(SLIM_TKOFF_BASE_CSSP3 + 243)
#define SLIM_TKNAM_CSSP_page_break_after	(SLIM_TKNAM_BASE_CSSP3 + 243)
#define SLIM_TKLEN_CSSP_page_break_after	(16)
#define SLIM_TOKEN_CSSP_page_break_after	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_page_break_after))
#define SLIM_TKOFF_CSSP_page_break_before	(SLIM_TKOFF_BASE_CSSP3 + 260)
#define SLIM_TKNAM_CSSP_page_break_before	(SLIM_TKNAM_BASE_CSSP3 + 260)
#define SLIM_TKLEN_CSSP_page_break_before	(17)
#define SLIM_TOKEN_CSSP_page_break_before	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_page_break_before))
#define SLIM_TKOFF_CSSP_page_break_inside	(SLIM_TKOFF_BASE_CSSP3 + 278)
#define SLIM_TKNAM_CSSP_page_break_inside	(SLIM_TKNAM_BASE_CSSP3 + 278)
#define SLIM_TKLEN_CSSP_page_break_inside	(17)
#define SLIM_TOKEN_CSSP_page_break_inside	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_page_break_inside))
#define SLIM_TKOFF_CSSP_size	(SLIM_TKOFF_BASE_CSSP3 + 296)
#define SLIM_TKNAM_CSSP_size	(SLIM_TKNAM_BASE_CSSP3 + 296)
#define SLIM_TKLEN_CSSP_size	(4)
#define SLIM_TOKEN_CSSP_size	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_size))
#define SLIM_TKOFF_CSSP_widows	(SLIM_TKOFF_BASE_CSSP3 + 301)
#define SLIM_TKNAM_CSSP_widows	(SLIM_TKNAM_BASE_CSSP3 + 301)
#define SLIM_TKLEN_CSSP_widows	(6)
#define SLIM_TOKEN_CSSP_widows	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_widows))
#define SLIM_TKOFF_CSSP_content	(SLIM_TKOFF_BASE_CSSP3 + 308)
#define SLIM_TKNAM_CSSP_content	(SLIM_TKNAM_BASE_CSSP3 + 308)
#define SLIM_TKLEN_CSSP_content	(7)
#define SLIM_TOKEN_CSSP_content	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_content))
#define SLIM_TKOFF_CSSP_counter_increment	(SLIM_TKOFF_BASE_CSSP3 + 316)
#define SLIM_TKNAM_CSSP_counter_increment	(SLIM_TKNAM_BASE_CSSP3 + 316)
#define SLIM_TKLEN_CSSP_counter_increment	(17)
#define SLIM_TOKEN_CSSP_counter_increment	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_counter_increment))
#define SLIM_TKOFF_CSSP_counter_reset	(SLIM_TKOFF_BASE_CSSP3 + 334)
#define SLIM_TKNAM_CSSP_counter_reset	(SLIM_TKNAM_BASE_CSSP3 + 334)
#define SLIM_TKLEN_CSSP_counter_reset	(13)
#define SLIM_TOKEN_CSSP_counter_reset	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_counter_reset))
#define SLIM_TKOFF_BASE_CSSP4	(SLIM_TKOFF_BASE_CSSP3 + 348)
#else /* SLIM_CONFIG_CSS_LEVEL_2 */
#define SLIM_TKOFF_BASE_CSSP4	(SLIM_TKOFF_BASE_CSSP3)
#endif /* SLIM_CONFIG_CSS_LEVEL_2 */
#define SLIM_TKNAM_BASE_CSSP4	(SLIM_TKNAM_BASE_CSSP0 + SLIM_TKOFF_BASE_CSSP4)
#ifdef SLIM_CONFIG_CSS_LEVEL_2_WITH_AURAL
#define SLIM_TKOFF_CSSP_azimuth	(SLIM_TKOFF_BASE_CSSP4 + 0)
#define SLIM_TKNAM_CSSP_azimuth	(SLIM_TKNAM_BASE_CSSP4 + 0)
#define SLIM_TKLEN_CSSP_azimuth	(7)
#define SLIM_TOKEN_CSSP_azimuth	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_azimuth))
#define SLIM_TKOFF_CSSP_cue	(SLIM_TKOFF_BASE_CSSP4 + 8)
#define SLIM_TKNAM_CSSP_cue	(SLIM_TKNAM_BASE_CSSP4 + 8)
#define SLIM_TKLEN_CSSP_cue	(3)
#define SLIM_TOKEN_CSSP_cue	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_cue))
#define SLIM_TKOFF_CSSP_cue_after	(SLIM_TKOFF_BASE_CSSP4 + 12)
#define SLIM_TKNAM_CSSP_cue_after	(SLIM_TKNAM_BASE_CSSP4 + 12)
#define SLIM_TKLEN_CSSP_cue_after	(9)
#define SLIM_TOKEN_CSSP_cue_after	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_cue_after))
#define SLIM_TKOFF_CSSP_cue_before	(SLIM_TKOFF_BASE_CSSP4 + 22)
#define SLIM_TKNAM_CSSP_cue_before	(SLIM_TKNAM_BASE_CSSP4 + 22)
#define SLIM_TKLEN_CSSP_cue_before	(10)
#define SLIM_TOKEN_CSSP_cue_before	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_cue_before))
#define SLIM_TKOFF_CSSP_elevation	(SLIM_TKOFF_BASE_CSSP4 + 33)
#define SLIM_TKNAM_CSSP_elevation	(SLIM_TKNAM_BASE_CSSP4 + 33)
#define SLIM_TKLEN_CSSP_elevation	(9)
#define SLIM_TOKEN_CSSP_elevation	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_elevation))
#define SLIM_TKOFF_CSSP_pause	(SLIM_TKOFF_BASE_CSSP4 + 43)
#define SLIM_TKNAM_CSSP_pause	(SLIM_TKNAM_BASE_CSSP4 + 43)
#define SLIM_TKLEN_CSSP_pause	(5)
#define SLIM_TOKEN_CSSP_pause	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_pause))
#define SLIM_TKOFF_CSSP_pause_after	(SLIM_TKOFF_BASE_CSSP4 + 49)
#define SLIM_TKNAM_CSSP_pause_after	(SLIM_TKNAM_BASE_CSSP4 + 49)
#define SLIM_TKLEN_CSSP_pause_after	(11)
#define SLIM_TOKEN_CSSP_pause_after	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_pause_after))
#define SLIM_TKOFF_CSSP_pause_before	(SLIM_TKOFF_BASE_CSSP4 + 61)
#define SLIM_TKNAM_CSSP_pause_before	(SLIM_TKNAM_BASE_CSSP4 + 61)
#define SLIM_TKLEN_CSSP_pause_before	(12)
#define SLIM_TOKEN_CSSP_pause_before	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_pause_before))
#define SLIM_TKOFF_CSSP_pitch	(SLIM_TKOFF_BASE_CSSP4 + 74)
#define SLIM_TKNAM_CSSP_pitch	(SLIM_TKNAM_BASE_CSSP4 + 74)
#define SLIM_TKLEN_CSSP_pitch	(5)
#define SLIM_TOKEN_CSSP_pitch	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_pitch))
#define SLIM_TKOFF_CSSP_pitch_range	(SLIM_TKOFF_BASE_CSSP4 + 80)
#define SLIM_TKNAM_CSSP_pitch_range	(SLIM_TKNAM_BASE_CSSP4 + 80)
#define SLIM_TKLEN_CSSP_pitch_range	(11)
#define SLIM_TOKEN_CSSP_pitch_range	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_pitch_range))
#define SLIM_TKOFF_CSSP_play_during	(SLIM_TKOFF_BASE_CSSP4 + 92)
#define SLIM_TKNAM_CSSP_play_during	(SLIM_TKNAM_BASE_CSSP4 + 92)
#define SLIM_TKLEN_CSSP_play_during	(11)
#define SLIM_TOKEN_CSSP_play_during	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_play_during))
#define SLIM_TKOFF_CSSP_richness	(SLIM_TKOFF_BASE_CSSP4 + 104)
#define SLIM_TKNAM_CSSP_richness	(SLIM_TKNAM_BASE_CSSP4 + 104)
#define SLIM_TKLEN_CSSP_richness	(8)
#define SLIM_TOKEN_CSSP_richness	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_richness))
#define SLIM_TKOFF_CSSP_speak	(SLIM_TKOFF_BASE_CSSP4 + 113)
#define SLIM_TKNAM_CSSP_speak	(SLIM_TKNAM_BASE_CSSP4 + 113)
#define SLIM_TKLEN_CSSP_speak	(5)
#define SLIM_TOKEN_CSSP_speak	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_speak))
#define SLIM_TKOFF_CSSP_speak_header	(SLIM_TKOFF_BASE_CSSP4 + 119)
#define SLIM_TKNAM_CSSP_speak_header	(SLIM_TKNAM_BASE_CSSP4 + 119)
#define SLIM_TKLEN_CSSP_speak_header	(12)
#define SLIM_TOKEN_CSSP_speak_header	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_speak_header))
#define SLIM_TKOFF_CSSP_speak_numeral	(SLIM_TKOFF_BASE_CSSP4 + 132)
#define SLIM_TKNAM_CSSP_speak_numeral	(SLIM_TKNAM_BASE_CSSP4 + 132)
#define SLIM_TKLEN_CSSP_speak_numeral	(13)
#define SLIM_TOKEN_CSSP_speak_numeral	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_speak_numeral))
#define SLIM_TKOFF_CSSP_speak_punctuation	(SLIM_TKOFF_BASE_CSSP4 + 146)
#define SLIM_TKNAM_CSSP_speak_punctuation	(SLIM_TKNAM_BASE_CSSP4 + 146)
#define SLIM_TKLEN_CSSP_speak_punctuation	(17)
#define SLIM_TOKEN_CSSP_speak_punctuation	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_speak_punctuation))
#define SLIM_TKOFF_CSSP_speech_rate	(SLIM_TKOFF_BASE_CSSP4 + 164)
#define SLIM_TKNAM_CSSP_speech_rate	(SLIM_TKNAM_BASE_CSSP4 + 164)
#define SLIM_TKLEN_CSSP_speech_rate	(11)
#define SLIM_TOKEN_CSSP_speech_rate	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_speech_rate))
#define SLIM_TKOFF_CSSP_stress	(SLIM_TKOFF_BASE_CSSP4 + 176)
#define SLIM_TKNAM_CSSP_stress	(SLIM_TKNAM_BASE_CSSP4 + 176)
#define SLIM_TKLEN_CSSP_stress	(6)
#define SLIM_TOKEN_CSSP_stress	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_stress))
#define SLIM_TKOFF_CSSP_voice_family	(SLIM_TKOFF_BASE_CSSP4 + 183)
#define SLIM_TKNAM_CSSP_voice_family	(SLIM_TKNAM_BASE_CSSP4 + 183)
#define SLIM_TKLEN_CSSP_voice_family	(12)
#define SLIM_TOKEN_CSSP_voice_family	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_voice_family))
#define SLIM_TKOFF_CSSP_volume	(SLIM_TKOFF_BASE_CSSP4 + 196)
#define SLIM_TKNAM_CSSP_volume	(SLIM_TKNAM_BASE_CSSP4 + 196)
#define SLIM_TKLEN_CSSP_volume	(6)
#define SLIM_TOKEN_CSSP_volume	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_volume))
#define SLIM_TKOFF_BASE_CSSP5	(SLIM_TKOFF_BASE_CSSP4 + 203)
#else /* SLIM_CONFIG_CSS_LEVEL_2_WITH_AURAL */
#define SLIM_TKOFF_BASE_CSSP5	(SLIM_TKOFF_BASE_CSSP4)
#endif /* SLIM_CONFIG_CSS_LEVEL_2_WITH_AURAL */
#define SLIM_TKNAM_BASE_CSSP5	(SLIM_TKNAM_BASE_CSSP0 + SLIM_TKOFF_BASE_CSSP5)
#ifdef SLIM_CONFIG_CSS_LEVEL_3
#define SLIM_TKOFF_CSSP_box_sizing	(SLIM_TKOFF_BASE_CSSP5 + 0)
#define SLIM_TKNAM_CSSP_box_sizing	(SLIM_TKNAM_BASE_CSSP5 + 0)
#define SLIM_TKLEN_CSSP_box_sizing	(10)
#define SLIM_TOKEN_CSSP_box_sizing	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_box_sizing))
#define SLIM_TKOFF_CSSP_opacity	(SLIM_TKOFF_BASE_CSSP5 + 11)
#define SLIM_TKNAM_CSSP_opacity	(SLIM_TKNAM_BASE_CSSP5 + 11)
#define SLIM_TKLEN_CSSP_opacity	(7)
#define SLIM_TOKEN_CSSP_opacity	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_opacity))
#define SLIM_TKOFF_CSSP_overflow_x	(SLIM_TKOFF_BASE_CSSP5 + 19)
#define SLIM_TKNAM_CSSP_overflow_x	(SLIM_TKNAM_BASE_CSSP5 + 19)
#define SLIM_TKLEN_CSSP_overflow_x	(10)
#define SLIM_TOKEN_CSSP_overflow_x	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_overflow_x))
#define SLIM_TKOFF_CSSP_overflow_y	(SLIM_TKOFF_BASE_CSSP5 + 30)
#define SLIM_TKNAM_CSSP_overflow_y	(SLIM_TKNAM_BASE_CSSP5 + 30)
#define SLIM_TKLEN_CSSP_overflow_y	(10)
#define SLIM_TOKEN_CSSP_overflow_y	(CSSPropInfo_GetItem(SLIM_TKID_CSSP_overflow_y))
#define SLIM_TKOFF_BASE_CSSP6	(SLIM_TKOFF_BASE_CSSP5 + 41)
#else /* SLIM_CONFIG_CSS_LEVEL_3 */
#define SLIM_TKOFF_BASE_CSSP6	(SLIM_TKOFF_BASE_CSSP5)
#endif /* SLIM_CONFIG_CSS_LEVEL_3 */
#define SLIM_TKNAM_BASE_CSSP6	(SLIM_TKNAM_BASE_CSSP0 + SLIM_TKOFF_BASE_CSSP6)
#define SLIM_TKLEN_TOTAL_CSSP	SLIM_TKOFF_BASE_CSSP6

extern SLIM_ROM slim_char cSlim_TokenName_CSSP[SLIM_TKLEN_TOTAL_CSSP];

extern SLIM_ROM TCSSPropInfo cSlim_Token_CSSP[SLIM_TOKEN_CSSP_TOKENS];
#define CSSPropInfo_GetItem(id)		((TCSSPropInfo *)&cSlim_Token_CSSP[(id)])
#define CSSPropInfo_GetItemName(id)	((slim_char *)cSlim_TokenName_CSSP + ((TToken *)&cSlim_Token_CSSP[(id)])->fOffset)
#define CSSPropInfo_GetItemNameLen(id)	(((TToken *)&cSlim_Token_CSSP[(id)])->fLength)

TCSSPropInfo *CSSPropInfo_FindSS(slim_char *in_s, slim_int in_slen);

SLIM_END_C_LINKAGE
#endif
