/*
	csssv.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/private/token/csssv.h 32    06/07/11 2:23 Yamabuti $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_CSSSV_H
#define SLIM_TOKEN_CSSSV_H

#include <slim/basis/base.h>
#include <slim/basis/token.h>
#include <slim/private/token/csssvid.h>

SLIM_BEGIN_C_LINKAGE

struct TCSSSymValInfo_ {
	TToken fBase;	/* must be the first field */
	slim_int fSymType;
	slim_int fStyleEnum;
};
typedef struct TCSSSymValInfo_ TCSSSymValInfo;

#define SLIM_TKOFF_BASE_CSSSV0	(0)
#define SLIM_TKNAM_BASE_CSSSV0	((slim_char *)cSlim_TokenName_CSSSV)
#define SLIM_TKOFF_CSSSV_inherit	(SLIM_TKOFF_BASE_CSSSV0 + 0)
#define SLIM_TKNAM_CSSSV_inherit	(SLIM_TKNAM_BASE_CSSSV0 + 0)
#define SLIM_TKLEN_CSSSV_inherit	(7)
#define SLIM_TOKEN_CSSSV_inherit	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_inherit))
#define SLIM_TKOFF_CSSSV_block	(SLIM_TKOFF_BASE_CSSSV0 + 8)
#define SLIM_TKNAM_CSSSV_block	(SLIM_TKNAM_BASE_CSSSV0 + 8)
#define SLIM_TKLEN_CSSSV_block	(5)
#define SLIM_TOKEN_CSSSV_block	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_block))
#define SLIM_TKOFF_CSSSV_compact	(SLIM_TKOFF_BASE_CSSSV0 + 14)
#define SLIM_TKNAM_CSSSV_compact	(SLIM_TKNAM_BASE_CSSSV0 + 14)
#define SLIM_TKLEN_CSSSV_compact	(7)
#define SLIM_TOKEN_CSSSV_compact	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_compact))
#define SLIM_TKOFF_CSSSV_inline	(SLIM_TKOFF_BASE_CSSSV0 + 22)
#define SLIM_TKNAM_CSSSV_inline	(SLIM_TKNAM_BASE_CSSSV0 + 22)
#define SLIM_TKLEN_CSSSV_inline	(6)
#define SLIM_TOKEN_CSSSV_inline	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_inline))
#define SLIM_TKOFF_CSSSV_marker	(SLIM_TKOFF_BASE_CSSSV0 + 29)
#define SLIM_TKNAM_CSSSV_marker	(SLIM_TKNAM_BASE_CSSSV0 + 29)
#define SLIM_TKLEN_CSSSV_marker	(6)
#define SLIM_TOKEN_CSSSV_marker	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_marker))
#define SLIM_TKOFF_CSSSV_run_in	(SLIM_TKOFF_BASE_CSSSV0 + 36)
#define SLIM_TKNAM_CSSSV_run_in	(SLIM_TKNAM_BASE_CSSSV0 + 36)
#define SLIM_TKLEN_CSSSV_run_in	(6)
#define SLIM_TOKEN_CSSSV_run_in	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_run_in))
#define SLIM_TKOFF_CSSSV_table	(SLIM_TKOFF_BASE_CSSSV0 + 43)
#define SLIM_TKNAM_CSSSV_table	(SLIM_TKNAM_BASE_CSSSV0 + 43)
#define SLIM_TKLEN_CSSSV_table	(5)
#define SLIM_TOKEN_CSSSV_table	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_table))
#define SLIM_TKOFF_CSSSV_close_quote	(SLIM_TKOFF_BASE_CSSSV0 + 49)
#define SLIM_TKNAM_CSSSV_close_quote	(SLIM_TKNAM_BASE_CSSSV0 + 49)
#define SLIM_TKLEN_CSSSV_close_quote	(11)
#define SLIM_TOKEN_CSSSV_close_quote	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_close_quote))
#define SLIM_TKOFF_CSSSV_inline_block	(SLIM_TKOFF_BASE_CSSSV0 + 61)
#define SLIM_TKNAM_CSSSV_inline_block	(SLIM_TKNAM_BASE_CSSSV0 + 61)
#define SLIM_TKLEN_CSSSV_inline_block	(12)
#define SLIM_TOKEN_CSSSV_inline_block	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_inline_block))
#define SLIM_TKOFF_CSSSV_inline_table	(SLIM_TKOFF_BASE_CSSSV0 + 74)
#define SLIM_TKNAM_CSSSV_inline_table	(SLIM_TKNAM_BASE_CSSSV0 + 74)
#define SLIM_TKLEN_CSSSV_inline_table	(12)
#define SLIM_TOKEN_CSSSV_inline_table	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_inline_table))
#define SLIM_TKOFF_CSSSV_list_item	(SLIM_TKOFF_BASE_CSSSV0 + 87)
#define SLIM_TKNAM_CSSSV_list_item	(SLIM_TKNAM_BASE_CSSSV0 + 87)
#define SLIM_TKLEN_CSSSV_list_item	(9)
#define SLIM_TOKEN_CSSSV_list_item	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_list_item))
#define SLIM_TKOFF_CSSSV_no_close_quote	(SLIM_TKOFF_BASE_CSSSV0 + 97)
#define SLIM_TKNAM_CSSSV_no_close_quote	(SLIM_TKNAM_BASE_CSSSV0 + 97)
#define SLIM_TKLEN_CSSSV_no_close_quote	(14)
#define SLIM_TOKEN_CSSSV_no_close_quote	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_no_close_quote))
#define SLIM_TKOFF_CSSSV_no_open_quote	(SLIM_TKOFF_BASE_CSSSV0 + 112)
#define SLIM_TKNAM_CSSSV_no_open_quote	(SLIM_TKNAM_BASE_CSSSV0 + 112)
#define SLIM_TKLEN_CSSSV_no_open_quote	(13)
#define SLIM_TOKEN_CSSSV_no_open_quote	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_no_open_quote))
#define SLIM_TKOFF_CSSSV_open_quote	(SLIM_TKOFF_BASE_CSSSV0 + 126)
#define SLIM_TKNAM_CSSSV_open_quote	(SLIM_TKNAM_BASE_CSSSV0 + 126)
#define SLIM_TKLEN_CSSSV_open_quote	(10)
#define SLIM_TOKEN_CSSSV_open_quote	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_open_quote))
#define SLIM_TKOFF_CSSSV_table_caption	(SLIM_TKOFF_BASE_CSSSV0 + 137)
#define SLIM_TKNAM_CSSSV_table_caption	(SLIM_TKNAM_BASE_CSSSV0 + 137)
#define SLIM_TKLEN_CSSSV_table_caption	(13)
#define SLIM_TOKEN_CSSSV_table_caption	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_table_caption))
#define SLIM_TKOFF_CSSSV_table_cell	(SLIM_TKOFF_BASE_CSSSV0 + 151)
#define SLIM_TKNAM_CSSSV_table_cell	(SLIM_TKNAM_BASE_CSSSV0 + 151)
#define SLIM_TKLEN_CSSSV_table_cell	(10)
#define SLIM_TOKEN_CSSSV_table_cell	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_table_cell))
#define SLIM_TKOFF_CSSSV_table_column	(SLIM_TKOFF_BASE_CSSSV0 + 162)
#define SLIM_TKNAM_CSSSV_table_column	(SLIM_TKNAM_BASE_CSSSV0 + 162)
#define SLIM_TKLEN_CSSSV_table_column	(12)
#define SLIM_TOKEN_CSSSV_table_column	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_table_column))
#define SLIM_TKOFF_CSSSV_table_row	(SLIM_TKOFF_BASE_CSSSV0 + 175)
#define SLIM_TKNAM_CSSSV_table_row	(SLIM_TKNAM_BASE_CSSSV0 + 175)
#define SLIM_TKLEN_CSSSV_table_row	(9)
#define SLIM_TOKEN_CSSSV_table_row	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_table_row))
#define SLIM_TKOFF_CSSSV_table_column_group	(SLIM_TKOFF_BASE_CSSSV0 + 185)
#define SLIM_TKNAM_CSSSV_table_column_group	(SLIM_TKNAM_BASE_CSSSV0 + 185)
#define SLIM_TKLEN_CSSSV_table_column_group	(18)
#define SLIM_TOKEN_CSSSV_table_column_group	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_table_column_group))
#define SLIM_TKOFF_CSSSV_table_footer_group	(SLIM_TKOFF_BASE_CSSSV0 + 204)
#define SLIM_TKNAM_CSSSV_table_footer_group	(SLIM_TKNAM_BASE_CSSSV0 + 204)
#define SLIM_TKLEN_CSSSV_table_footer_group	(18)
#define SLIM_TOKEN_CSSSV_table_footer_group	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_table_footer_group))
#define SLIM_TKOFF_CSSSV_table_header_group	(SLIM_TKOFF_BASE_CSSSV0 + 223)
#define SLIM_TKNAM_CSSSV_table_header_group	(SLIM_TKNAM_BASE_CSSSV0 + 223)
#define SLIM_TKLEN_CSSSV_table_header_group	(18)
#define SLIM_TOKEN_CSSSV_table_header_group	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_table_header_group))
#define SLIM_TKOFF_CSSSV_table_row_group	(SLIM_TKOFF_BASE_CSSSV0 + 242)
#define SLIM_TKNAM_CSSSV_table_row_group	(SLIM_TKNAM_BASE_CSSSV0 + 242)
#define SLIM_TKLEN_CSSSV_table_row_group	(15)
#define SLIM_TOKEN_CSSSV_table_row_group	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_table_row_group))
#define SLIM_TKOFF_CSSSV_blink	(SLIM_TKOFF_BASE_CSSSV0 + 258)
#define SLIM_TKNAM_CSSSV_blink	(SLIM_TKNAM_BASE_CSSSV0 + 258)
#define SLIM_TKLEN_CSSSV_blink	(5)
#define SLIM_TOKEN_CSSSV_blink	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_blink))
#define SLIM_TKOFF_CSSSV_bolder	(SLIM_TKOFF_BASE_CSSSV0 + 264)
#define SLIM_TKNAM_CSSSV_bolder	(SLIM_TKNAM_BASE_CSSSV0 + 264)
#define SLIM_TKLEN_CSSSV_bolder	(6)
#define SLIM_TOKEN_CSSSV_bolder	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_bolder))
#define SLIM_TKOFF_CSSSV_both	(SLIM_TKOFF_BASE_CSSSV0 + 271)
#define SLIM_TKNAM_CSSSV_both	(SLIM_TKNAM_BASE_CSSSV0 + 271)
#define SLIM_TKLEN_CSSSV_both	(4)
#define SLIM_TOKEN_CSSSV_both	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_both))
#define SLIM_TKOFF_CSSSV_bottom	(SLIM_TKOFF_BASE_CSSSV0 + 276)
#define SLIM_TKNAM_CSSSV_bottom	(SLIM_TKNAM_BASE_CSSSV0 + 276)
#define SLIM_TKLEN_CSSSV_bottom	(6)
#define SLIM_TOKEN_CSSSV_bottom	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_bottom))
#define SLIM_TKOFF_CSSSV_caption	(SLIM_TKOFF_BASE_CSSSV0 + 283)
#define SLIM_TKNAM_CSSSV_caption	(SLIM_TKNAM_BASE_CSSSV0 + 283)
#define SLIM_TKLEN_CSSSV_caption	(7)
#define SLIM_TOKEN_CSSSV_caption	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_caption))
#define SLIM_TKOFF_CSSSV_circle	(SLIM_TKOFF_BASE_CSSSV0 + 291)
#define SLIM_TKNAM_CSSSV_circle	(SLIM_TKNAM_BASE_CSSSV0 + 291)
#define SLIM_TKLEN_CSSSV_circle	(6)
#define SLIM_TOKEN_CSSSV_circle	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_circle))
#define SLIM_TKOFF_CSSSV_decimal	(SLIM_TKOFF_BASE_CSSSV0 + 298)
#define SLIM_TKNAM_CSSSV_decimal	(SLIM_TKNAM_BASE_CSSSV0 + 298)
#define SLIM_TKLEN_CSSSV_decimal	(7)
#define SLIM_TOKEN_CSSSV_decimal	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_decimal))
#define SLIM_TKOFF_CSSSV_disc	(SLIM_TKOFF_BASE_CSSSV0 + 306)
#define SLIM_TKNAM_CSSSV_disc	(SLIM_TKNAM_BASE_CSSSV0 + 306)
#define SLIM_TKLEN_CSSSV_disc	(4)
#define SLIM_TOKEN_CSSSV_disc	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_disc))
#define SLIM_TKOFF_CSSSV_embed	(SLIM_TKOFF_BASE_CSSSV0 + 311)
#define SLIM_TKNAM_CSSSV_embed	(SLIM_TKNAM_BASE_CSSSV0 + 311)
#define SLIM_TKLEN_CSSSV_embed	(5)
#define SLIM_TOKEN_CSSSV_embed	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_embed))
#define SLIM_TKOFF_CSSSV_fixed	(SLIM_TKOFF_BASE_CSSSV0 + 317)
#define SLIM_TKNAM_CSSSV_fixed	(SLIM_TKNAM_BASE_CSSSV0 + 317)
#define SLIM_TKLEN_CSSSV_fixed	(5)
#define SLIM_TOKEN_CSSSV_fixed	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_fixed))
#define SLIM_TKOFF_CSSSV_hebrew	(SLIM_TKOFF_BASE_CSSSV0 + 323)
#define SLIM_TKNAM_CSSSV_hebrew	(SLIM_TKNAM_BASE_CSSSV0 + 323)
#define SLIM_TKLEN_CSSSV_hebrew	(6)
#define SLIM_TOKEN_CSSSV_hebrew	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_hebrew))
#define SLIM_TKOFF_CSSSV_hide	(SLIM_TKOFF_BASE_CSSSV0 + 330)
#define SLIM_TKNAM_CSSSV_hide	(SLIM_TKNAM_BASE_CSSSV0 + 330)
#define SLIM_TKLEN_CSSSV_hide	(4)
#define SLIM_TOKEN_CSSSV_hide	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_hide))
#define SLIM_TKOFF_CSSSV_icon	(SLIM_TKOFF_BASE_CSSSV0 + 335)
#define SLIM_TKNAM_CSSSV_icon	(SLIM_TKNAM_BASE_CSSSV0 + 335)
#define SLIM_TKLEN_CSSSV_icon	(4)
#define SLIM_TOKEN_CSSSV_icon	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_icon))
#define SLIM_TKOFF_CSSSV_inside	(SLIM_TKOFF_BASE_CSSSV0 + 340)
#define SLIM_TKNAM_CSSSV_inside	(SLIM_TKNAM_BASE_CSSSV0 + 340)
#define SLIM_TKLEN_CSSSV_inside	(6)
#define SLIM_TOKEN_CSSSV_inside	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_inside))
#define SLIM_TKOFF_CSSSV_justify	(SLIM_TKOFF_BASE_CSSSV0 + 347)
#define SLIM_TKNAM_CSSSV_justify	(SLIM_TKNAM_BASE_CSSSV0 + 347)
#define SLIM_TKLEN_CSSSV_justify	(7)
#define SLIM_TOKEN_CSSSV_justify	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_justify))
#define SLIM_TKOFF_CSSSV_large	(SLIM_TKOFF_BASE_CSSSV0 + 355)
#define SLIM_TKNAM_CSSSV_large	(SLIM_TKNAM_BASE_CSSSV0 + 355)
#define SLIM_TKLEN_CSSSV_large	(5)
#define SLIM_TOKEN_CSSSV_large	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_large))
#define SLIM_TKOFF_CSSSV_larger	(SLIM_TKOFF_BASE_CSSSV0 + 361)
#define SLIM_TKNAM_CSSSV_larger	(SLIM_TKNAM_BASE_CSSSV0 + 361)
#define SLIM_TKLEN_CSSSV_larger	(6)
#define SLIM_TOKEN_CSSSV_larger	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_larger))
#define SLIM_TKOFF_CSSSV_lighter	(SLIM_TKOFF_BASE_CSSSV0 + 368)
#define SLIM_TKNAM_CSSSV_lighter	(SLIM_TKNAM_BASE_CSSSV0 + 368)
#define SLIM_TKLEN_CSSSV_lighter	(7)
#define SLIM_TOKEN_CSSSV_lighter	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_lighter))
#define SLIM_TKOFF_CSSSV_ltr	(SLIM_TKOFF_BASE_CSSSV0 + 376)
#define SLIM_TKNAM_CSSSV_ltr	(SLIM_TKNAM_BASE_CSSSV0 + 376)
#define SLIM_TKLEN_CSSSV_ltr	(3)
#define SLIM_TOKEN_CSSSV_ltr	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_ltr))
#define SLIM_TKOFF_CSSSV_menu	(SLIM_TKOFF_BASE_CSSSV0 + 380)
#define SLIM_TKNAM_CSSSV_menu	(SLIM_TKNAM_BASE_CSSSV0 + 380)
#define SLIM_TKLEN_CSSSV_menu	(4)
#define SLIM_TOKEN_CSSSV_menu	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_menu))
#define SLIM_TKOFF_CSSSV_middle	(SLIM_TKOFF_BASE_CSSSV0 + 385)
#define SLIM_TKNAM_CSSSV_middle	(SLIM_TKNAM_BASE_CSSSV0 + 385)
#define SLIM_TKLEN_CSSSV_middle	(6)
#define SLIM_TOKEN_CSSSV_middle	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_middle))
#define SLIM_TKOFF_CSSSV_nowrap	(SLIM_TKOFF_BASE_CSSSV0 + 392)
#define SLIM_TKNAM_CSSSV_nowrap	(SLIM_TKNAM_BASE_CSSSV0 + 392)
#define SLIM_TKLEN_CSSSV_nowrap	(6)
#define SLIM_TOKEN_CSSSV_nowrap	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_nowrap))
#define SLIM_TKOFF_CSSSV_outside	(SLIM_TKOFF_BASE_CSSSV0 + 399)
#define SLIM_TKNAM_CSSSV_outside	(SLIM_TKNAM_BASE_CSSSV0 + 399)
#define SLIM_TKLEN_CSSSV_outside	(7)
#define SLIM_TOKEN_CSSSV_outside	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_outside))
#define SLIM_TKOFF_CSSSV_pre	(SLIM_TKOFF_BASE_CSSSV0 + 407)
#define SLIM_TKNAM_CSSSV_pre	(SLIM_TKNAM_BASE_CSSSV0 + 407)
#define SLIM_TKLEN_CSSSV_pre	(3)
#define SLIM_TOKEN_CSSSV_pre	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_pre))
#define SLIM_TKOFF_CSSSV_pre_line	(SLIM_TKOFF_BASE_CSSSV0 + 411)
#define SLIM_TKNAM_CSSSV_pre_line	(SLIM_TKNAM_BASE_CSSSV0 + 411)
#define SLIM_TKLEN_CSSSV_pre_line	(8)
#define SLIM_TOKEN_CSSSV_pre_line	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_pre_line))
#define SLIM_TKOFF_CSSSV_pre_wrap	(SLIM_TKOFF_BASE_CSSSV0 + 420)
#define SLIM_TKNAM_CSSSV_pre_wrap	(SLIM_TKNAM_BASE_CSSSV0 + 420)
#define SLIM_TKLEN_CSSSV_pre_wrap	(8)
#define SLIM_TOKEN_CSSSV_pre_wrap	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_pre_wrap))
#define SLIM_TKOFF_CSSSV_repeat_x	(SLIM_TKOFF_BASE_CSSSV0 + 429)
#define SLIM_TKNAM_CSSSV_repeat_x	(SLIM_TKNAM_BASE_CSSSV0 + 429)
#define SLIM_TKLEN_CSSSV_repeat_x	(8)
#define SLIM_TOKEN_CSSSV_repeat_x	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_repeat_x))
#define SLIM_TKOFF_CSSSV_repeat_y	(SLIM_TKOFF_BASE_CSSSV0 + 438)
#define SLIM_TKNAM_CSSSV_repeat_y	(SLIM_TKNAM_BASE_CSSSV0 + 438)
#define SLIM_TKLEN_CSSSV_repeat_y	(8)
#define SLIM_TOKEN_CSSSV_repeat_y	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_repeat_y))
#define SLIM_TKOFF_CSSSV_rtl	(SLIM_TKOFF_BASE_CSSSV0 + 447)
#define SLIM_TKNAM_CSSSV_rtl	(SLIM_TKNAM_BASE_CSSSV0 + 447)
#define SLIM_TKLEN_CSSSV_rtl	(3)
#define SLIM_TOKEN_CSSSV_rtl	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_rtl))
#define SLIM_TKOFF_CSSSV_scroll	(SLIM_TKOFF_BASE_CSSSV0 + 451)
#define SLIM_TKNAM_CSSSV_scroll	(SLIM_TKNAM_BASE_CSSSV0 + 451)
#define SLIM_TKLEN_CSSSV_scroll	(6)
#define SLIM_TOKEN_CSSSV_scroll	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_scroll))
#define SLIM_TKOFF_CSSSV_show	(SLIM_TKOFF_BASE_CSSSV0 + 458)
#define SLIM_TKNAM_CSSSV_show	(SLIM_TKNAM_BASE_CSSSV0 + 458)
#define SLIM_TKLEN_CSSSV_show	(4)
#define SLIM_TOKEN_CSSSV_show	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_show))
#define SLIM_TKOFF_CSSSV_small	(SLIM_TKOFF_BASE_CSSSV0 + 463)
#define SLIM_TKNAM_CSSSV_small	(SLIM_TKNAM_BASE_CSSSV0 + 463)
#define SLIM_TKLEN_CSSSV_small	(5)
#define SLIM_TOKEN_CSSSV_small	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_small))
#define SLIM_TKOFF_CSSSV_smaller	(SLIM_TKOFF_BASE_CSSSV0 + 469)
#define SLIM_TKNAM_CSSSV_smaller	(SLIM_TKNAM_BASE_CSSSV0 + 469)
#define SLIM_TKLEN_CSSSV_smaller	(7)
#define SLIM_TOKEN_CSSSV_smaller	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_smaller))
#define SLIM_TKOFF_CSSSV_square	(SLIM_TKOFF_BASE_CSSSV0 + 477)
#define SLIM_TKNAM_CSSSV_square	(SLIM_TKNAM_BASE_CSSSV0 + 477)
#define SLIM_TKLEN_CSSSV_square	(6)
#define SLIM_TOKEN_CSSSV_square	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_square))
#define SLIM_TKOFF_CSSSV_static	(SLIM_TKOFF_BASE_CSSSV0 + 484)
#define SLIM_TKNAM_CSSSV_static	(SLIM_TKNAM_BASE_CSSSV0 + 484)
#define SLIM_TKLEN_CSSSV_static	(6)
#define SLIM_TOKEN_CSSSV_static	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_static))
#define SLIM_TKOFF_CSSSV_sub	(SLIM_TKOFF_BASE_CSSSV0 + 491)
#define SLIM_TKNAM_CSSSV_sub	(SLIM_TKNAM_BASE_CSSSV0 + 491)
#define SLIM_TKLEN_CSSSV_sub	(3)
#define SLIM_TOKEN_CSSSV_sub	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_sub))
#define SLIM_TKOFF_CSSSV_super	(SLIM_TKOFF_BASE_CSSSV0 + 495)
#define SLIM_TKNAM_CSSSV_super	(SLIM_TKNAM_BASE_CSSSV0 + 495)
#define SLIM_TKLEN_CSSSV_super	(5)
#define SLIM_TOKEN_CSSSV_super	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_super))
#define SLIM_TKOFF_CSSSV_text_top	(SLIM_TKOFF_BASE_CSSSV0 + 501)
#define SLIM_TKNAM_CSSSV_text_top	(SLIM_TKNAM_BASE_CSSSV0 + 501)
#define SLIM_TKLEN_CSSSV_text_top	(8)
#define SLIM_TOKEN_CSSSV_text_top	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_text_top))
#define SLIM_TKOFF_CSSSV_top	(SLIM_TKOFF_BASE_CSSSV0 + 510)
#define SLIM_TKNAM_CSSSV_top	(SLIM_TKNAM_BASE_CSSSV0 + 510)
#define SLIM_TKLEN_CSSSV_top	(3)
#define SLIM_TOKEN_CSSSV_top	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_top))
#define SLIM_TKOFF_CSSSV_visible	(SLIM_TKOFF_BASE_CSSSV0 + 514)
#define SLIM_TKNAM_CSSSV_visible	(SLIM_TKNAM_BASE_CSSSV0 + 514)
#define SLIM_TKLEN_CSSSV_visible	(7)
#define SLIM_TOKEN_CSSSV_visible	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_visible))
#define SLIM_TKOFF_CSSSV_wider	(SLIM_TKOFF_BASE_CSSSV0 + 522)
#define SLIM_TKNAM_CSSSV_wider	(SLIM_TKNAM_BASE_CSSSV0 + 522)
#define SLIM_TKLEN_CSSSV_wider	(5)
#define SLIM_TOKEN_CSSSV_wider	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_wider))
#define SLIM_TKOFF_CSSSV_x_large	(SLIM_TKOFF_BASE_CSSSV0 + 528)
#define SLIM_TKNAM_CSSSV_x_large	(SLIM_TKNAM_BASE_CSSSV0 + 528)
#define SLIM_TKLEN_CSSSV_x_large	(7)
#define SLIM_TOKEN_CSSSV_x_large	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_x_large))
#define SLIM_TKOFF_CSSSV_x_small	(SLIM_TKOFF_BASE_CSSSV0 + 536)
#define SLIM_TKNAM_CSSSV_x_small	(SLIM_TKNAM_BASE_CSSSV0 + 536)
#define SLIM_TKLEN_CSSSV_x_small	(7)
#define SLIM_TOKEN_CSSSV_x_small	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_x_small))
#define SLIM_TKOFF_CSSSV_xx_large	(SLIM_TKOFF_BASE_CSSSV0 + 544)
#define SLIM_TKNAM_CSSSV_xx_large	(SLIM_TKNAM_BASE_CSSSV0 + 544)
#define SLIM_TKLEN_CSSSV_xx_large	(8)
#define SLIM_TOKEN_CSSSV_xx_large	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_xx_large))
#define SLIM_TKOFF_CSSSV_xx_small	(SLIM_TKOFF_BASE_CSSSV0 + 553)
#define SLIM_TKNAM_CSSSV_xx_small	(SLIM_TKNAM_BASE_CSSSV0 + 553)
#define SLIM_TKLEN_CSSSV_xx_small	(8)
#define SLIM_TOKEN_CSSSV_xx_small	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_xx_small))
#define SLIM_TKOFF_CSSSV_absolute	(SLIM_TKOFF_BASE_CSSSV0 + 562)
#define SLIM_TKNAM_CSSSV_absolute	(SLIM_TKNAM_BASE_CSSSV0 + 562)
#define SLIM_TKLEN_CSSSV_absolute	(8)
#define SLIM_TOKEN_CSSSV_absolute	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_absolute))
#define SLIM_TKOFF_CSSSV_armenian	(SLIM_TKOFF_BASE_CSSSV0 + 571)
#define SLIM_TKNAM_CSSSV_armenian	(SLIM_TKNAM_BASE_CSSSV0 + 571)
#define SLIM_TKLEN_CSSSV_armenian	(8)
#define SLIM_TOKEN_CSSSV_armenian	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_armenian))
#define SLIM_TKOFF_CSSSV_baseline	(SLIM_TKOFF_BASE_CSSSV0 + 580)
#define SLIM_TKNAM_CSSSV_baseline	(SLIM_TKNAM_BASE_CSSSV0 + 580)
#define SLIM_TKLEN_CSSSV_baseline	(8)
#define SLIM_TOKEN_CSSSV_baseline	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_baseline))
#define SLIM_TKOFF_CSSSV_bidi_override	(SLIM_TKOFF_BASE_CSSSV0 + 589)
#define SLIM_TKNAM_CSSSV_bidi_override	(SLIM_TKNAM_BASE_CSSSV0 + 589)
#define SLIM_TKLEN_CSSSV_bidi_override	(13)
#define SLIM_TOKEN_CSSSV_bidi_override	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_bidi_override))
#define SLIM_TKOFF_CSSSV_capitalize	(SLIM_TKOFF_BASE_CSSSV0 + 603)
#define SLIM_TKNAM_CSSSV_capitalize	(SLIM_TKNAM_BASE_CSSSV0 + 603)
#define SLIM_TKLEN_CSSSV_capitalize	(10)
#define SLIM_TOKEN_CSSSV_capitalize	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_capitalize))
#define SLIM_TKOFF_CSSSV_cjk_ideographic	(SLIM_TKOFF_BASE_CSSSV0 + 614)
#define SLIM_TKNAM_CSSSV_cjk_ideographic	(SLIM_TKNAM_BASE_CSSSV0 + 614)
#define SLIM_TKLEN_CSSSV_cjk_ideographic	(15)
#define SLIM_TOKEN_CSSSV_cjk_ideographic	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_cjk_ideographic))
#define SLIM_TKOFF_CSSSV_collapse	(SLIM_TKOFF_BASE_CSSSV0 + 630)
#define SLIM_TKNAM_CSSSV_collapse	(SLIM_TKNAM_BASE_CSSSV0 + 630)
#define SLIM_TKLEN_CSSSV_collapse	(8)
#define SLIM_TOKEN_CSSSV_collapse	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_collapse))
#define SLIM_TKOFF_CSSSV_decimal_leading_zero	(SLIM_TKOFF_BASE_CSSSV0 + 639)
#define SLIM_TKNAM_CSSSV_decimal_leading_zero	(SLIM_TKNAM_BASE_CSSSV0 + 639)
#define SLIM_TKLEN_CSSSV_decimal_leading_zero	(20)
#define SLIM_TOKEN_CSSSV_decimal_leading_zero	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_decimal_leading_zero))
#define SLIM_TKOFF_CSSSV_georgian	(SLIM_TKOFF_BASE_CSSSV0 + 660)
#define SLIM_TKNAM_CSSSV_georgian	(SLIM_TKNAM_BASE_CSSSV0 + 660)
#define SLIM_TKLEN_CSSSV_georgian	(8)
#define SLIM_TOKEN_CSSSV_georgian	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_georgian))
#define SLIM_TKOFF_CSSSV_hiragana	(SLIM_TKOFF_BASE_CSSSV0 + 669)
#define SLIM_TKNAM_CSSSV_hiragana	(SLIM_TKNAM_BASE_CSSSV0 + 669)
#define SLIM_TKLEN_CSSSV_hiragana	(8)
#define SLIM_TOKEN_CSSSV_hiragana	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_hiragana))
#define SLIM_TKOFF_CSSSV_hiragana_iroha	(SLIM_TKOFF_BASE_CSSSV0 + 678)
#define SLIM_TKNAM_CSSSV_hiragana_iroha	(SLIM_TKNAM_BASE_CSSSV0 + 678)
#define SLIM_TKLEN_CSSSV_hiragana_iroha	(14)
#define SLIM_TOKEN_CSSSV_hiragana_iroha	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_hiragana_iroha))
#define SLIM_TKOFF_CSSSV_katakana	(SLIM_TKOFF_BASE_CSSSV0 + 693)
#define SLIM_TKNAM_CSSSV_katakana	(SLIM_TKNAM_BASE_CSSSV0 + 693)
#define SLIM_TKLEN_CSSSV_katakana	(8)
#define SLIM_TOKEN_CSSSV_katakana	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_katakana))
#define SLIM_TKOFF_CSSSV_katakana_iroha	(SLIM_TKOFF_BASE_CSSSV0 + 702)
#define SLIM_TKNAM_CSSSV_katakana_iroha	(SLIM_TKNAM_BASE_CSSSV0 + 702)
#define SLIM_TKLEN_CSSSV_katakana_iroha	(14)
#define SLIM_TOKEN_CSSSV_katakana_iroha	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_katakana_iroha))
#define SLIM_TKOFF_CSSSV_line_through	(SLIM_TKOFF_BASE_CSSSV0 + 717)
#define SLIM_TKNAM_CSSSV_line_through	(SLIM_TKNAM_BASE_CSSSV0 + 717)
#define SLIM_TKLEN_CSSSV_line_through	(12)
#define SLIM_TOKEN_CSSSV_line_through	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_line_through))
#define SLIM_TKOFF_CSSSV_lower_alpha	(SLIM_TKOFF_BASE_CSSSV0 + 730)
#define SLIM_TKNAM_CSSSV_lower_alpha	(SLIM_TKNAM_BASE_CSSSV0 + 730)
#define SLIM_TKLEN_CSSSV_lower_alpha	(11)
#define SLIM_TOKEN_CSSSV_lower_alpha	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_lower_alpha))
#define SLIM_TKOFF_CSSSV_lower_greek	(SLIM_TKOFF_BASE_CSSSV0 + 742)
#define SLIM_TKNAM_CSSSV_lower_greek	(SLIM_TKNAM_BASE_CSSSV0 + 742)
#define SLIM_TKLEN_CSSSV_lower_greek	(11)
#define SLIM_TOKEN_CSSSV_lower_greek	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_lower_greek))
#define SLIM_TKOFF_CSSSV_lower_latin	(SLIM_TKOFF_BASE_CSSSV0 + 754)
#define SLIM_TKNAM_CSSSV_lower_latin	(SLIM_TKNAM_BASE_CSSSV0 + 754)
#define SLIM_TKLEN_CSSSV_lower_latin	(11)
#define SLIM_TOKEN_CSSSV_lower_latin	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_lower_latin))
#define SLIM_TKOFF_CSSSV_lower_roman	(SLIM_TKOFF_BASE_CSSSV0 + 766)
#define SLIM_TKNAM_CSSSV_lower_roman	(SLIM_TKNAM_BASE_CSSSV0 + 766)
#define SLIM_TKLEN_CSSSV_lower_roman	(11)
#define SLIM_TOKEN_CSSSV_lower_roman	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_lower_roman))
#define SLIM_TKOFF_CSSSV_lowercase	(SLIM_TKOFF_BASE_CSSSV0 + 778)
#define SLIM_TKNAM_CSSSV_lowercase	(SLIM_TKNAM_BASE_CSSSV0 + 778)
#define SLIM_TKLEN_CSSSV_lowercase	(9)
#define SLIM_TOKEN_CSSSV_lowercase	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_lowercase))
#define SLIM_TKOFF_CSSSV_message_box	(SLIM_TKOFF_BASE_CSSSV0 + 788)
#define SLIM_TKNAM_CSSSV_message_box	(SLIM_TKNAM_BASE_CSSSV0 + 788)
#define SLIM_TKLEN_CSSSV_message_box	(11)
#define SLIM_TOKEN_CSSSV_message_box	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_message_box))
#define SLIM_TKOFF_CSSSV_narrower	(SLIM_TKOFF_BASE_CSSSV0 + 800)
#define SLIM_TKNAM_CSSSV_narrower	(SLIM_TKNAM_BASE_CSSSV0 + 800)
#define SLIM_TKLEN_CSSSV_narrower	(8)
#define SLIM_TOKEN_CSSSV_narrower	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_narrower))
#define SLIM_TKOFF_CSSSV_no_repeat	(SLIM_TKOFF_BASE_CSSSV0 + 809)
#define SLIM_TKNAM_CSSSV_no_repeat	(SLIM_TKNAM_BASE_CSSSV0 + 809)
#define SLIM_TKLEN_CSSSV_no_repeat	(9)
#define SLIM_TOKEN_CSSSV_no_repeat	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_no_repeat))
#define SLIM_TKOFF_CSSSV_overline	(SLIM_TKOFF_BASE_CSSSV0 + 819)
#define SLIM_TKNAM_CSSSV_overline	(SLIM_TKNAM_BASE_CSSSV0 + 819)
#define SLIM_TKLEN_CSSSV_overline	(8)
#define SLIM_TOKEN_CSSSV_overline	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_overline))
#define SLIM_TKOFF_CSSSV_relative	(SLIM_TKOFF_BASE_CSSSV0 + 828)
#define SLIM_TKNAM_CSSSV_relative	(SLIM_TKNAM_BASE_CSSSV0 + 828)
#define SLIM_TKLEN_CSSSV_relative	(8)
#define SLIM_TOKEN_CSSSV_relative	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_relative))
#define SLIM_TKOFF_CSSSV_separate	(SLIM_TKOFF_BASE_CSSSV0 + 837)
#define SLIM_TKNAM_CSSSV_separate	(SLIM_TKNAM_BASE_CSSSV0 + 837)
#define SLIM_TKLEN_CSSSV_separate	(8)
#define SLIM_TOKEN_CSSSV_separate	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_separate))
#define SLIM_TKOFF_CSSSV_small_caption	(SLIM_TKOFF_BASE_CSSSV0 + 846)
#define SLIM_TKNAM_CSSSV_small_caption	(SLIM_TKNAM_BASE_CSSSV0 + 846)
#define SLIM_TKLEN_CSSSV_small_caption	(13)
#define SLIM_TOKEN_CSSSV_small_caption	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_small_caption))
#define SLIM_TKOFF_CSSSV_status_bar	(SLIM_TKOFF_BASE_CSSSV0 + 860)
#define SLIM_TKNAM_CSSSV_status_bar	(SLIM_TKNAM_BASE_CSSSV0 + 860)
#define SLIM_TKLEN_CSSSV_status_bar	(10)
#define SLIM_TOKEN_CSSSV_status_bar	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_status_bar))
#define SLIM_TKOFF_CSSSV_text_bottom	(SLIM_TKOFF_BASE_CSSSV0 + 871)
#define SLIM_TKNAM_CSSSV_text_bottom	(SLIM_TKNAM_BASE_CSSSV0 + 871)
#define SLIM_TKLEN_CSSSV_text_bottom	(11)
#define SLIM_TOKEN_CSSSV_text_bottom	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_text_bottom))
#define SLIM_TKOFF_CSSSV_transparent	(SLIM_TKOFF_BASE_CSSSV0 + 883)
#define SLIM_TKNAM_CSSSV_transparent	(SLIM_TKNAM_BASE_CSSSV0 + 883)
#define SLIM_TKLEN_CSSSV_transparent	(11)
#define SLIM_TOKEN_CSSSV_transparent	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_transparent))
#define SLIM_TKOFF_CSSSV_underline	(SLIM_TKOFF_BASE_CSSSV0 + 895)
#define SLIM_TKNAM_CSSSV_underline	(SLIM_TKNAM_BASE_CSSSV0 + 895)
#define SLIM_TKLEN_CSSSV_underline	(9)
#define SLIM_TOKEN_CSSSV_underline	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_underline))
#define SLIM_TKOFF_CSSSV_upper_alpha	(SLIM_TKOFF_BASE_CSSSV0 + 905)
#define SLIM_TKNAM_CSSSV_upper_alpha	(SLIM_TKNAM_BASE_CSSSV0 + 905)
#define SLIM_TKLEN_CSSSV_upper_alpha	(11)
#define SLIM_TOKEN_CSSSV_upper_alpha	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_upper_alpha))
#define SLIM_TKOFF_CSSSV_upper_latin	(SLIM_TKOFF_BASE_CSSSV0 + 917)
#define SLIM_TKNAM_CSSSV_upper_latin	(SLIM_TKNAM_BASE_CSSSV0 + 917)
#define SLIM_TKLEN_CSSSV_upper_latin	(11)
#define SLIM_TOKEN_CSSSV_upper_latin	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_upper_latin))
#define SLIM_TKOFF_CSSSV_upper_roman	(SLIM_TKOFF_BASE_CSSSV0 + 929)
#define SLIM_TKNAM_CSSSV_upper_roman	(SLIM_TKNAM_BASE_CSSSV0 + 929)
#define SLIM_TKLEN_CSSSV_upper_roman	(11)
#define SLIM_TOKEN_CSSSV_upper_roman	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_upper_roman))
#define SLIM_TKOFF_CSSSV_uppercase	(SLIM_TKOFF_BASE_CSSSV0 + 941)
#define SLIM_TKNAM_CSSSV_uppercase	(SLIM_TKNAM_BASE_CSSSV0 + 941)
#define SLIM_TKLEN_CSSSV_uppercase	(9)
#define SLIM_TOKEN_CSSSV_uppercase	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_uppercase))
#define SLIM_TKOFF_CSSSV_none	(SLIM_TKOFF_BASE_CSSSV0 + 951)
#define SLIM_TKNAM_CSSSV_none	(SLIM_TKNAM_BASE_CSSSV0 + 951)
#define SLIM_TKLEN_CSSSV_none	(4)
#define SLIM_TOKEN_CSSSV_none	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_none))
#define SLIM_TKOFF_CSSSV_center	(SLIM_TKOFF_BASE_CSSSV0 + 956)
#define SLIM_TKNAM_CSSSV_center	(SLIM_TKNAM_BASE_CSSSV0 + 956)
#define SLIM_TKLEN_CSSSV_center	(6)
#define SLIM_TOKEN_CSSSV_center	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_center))
#define SLIM_TKOFF_CSSSV_repeat	(SLIM_TKOFF_BASE_CSSSV0 + 963)
#define SLIM_TKNAM_CSSSV_repeat	(SLIM_TKNAM_BASE_CSSSV0 + 963)
#define SLIM_TKLEN_CSSSV_repeat	(6)
#define SLIM_TOKEN_CSSSV_repeat	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_repeat))
#define SLIM_TKOFF_CSSSV_dashed	(SLIM_TKOFF_BASE_CSSSV0 + 970)
#define SLIM_TKNAM_CSSSV_dashed	(SLIM_TKNAM_BASE_CSSSV0 + 970)
#define SLIM_TKLEN_CSSSV_dashed	(6)
#define SLIM_TOKEN_CSSSV_dashed	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_dashed))
#define SLIM_TKOFF_CSSSV_dotted	(SLIM_TKOFF_BASE_CSSSV0 + 977)
#define SLIM_TKNAM_CSSSV_dotted	(SLIM_TKNAM_BASE_CSSSV0 + 977)
#define SLIM_TKLEN_CSSSV_dotted	(6)
#define SLIM_TOKEN_CSSSV_dotted	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_dotted))
#define SLIM_TKOFF_CSSSV_double	(SLIM_TKOFF_BASE_CSSSV0 + 984)
#define SLIM_TKNAM_CSSSV_double	(SLIM_TKNAM_BASE_CSSSV0 + 984)
#define SLIM_TKLEN_CSSSV_double	(6)
#define SLIM_TOKEN_CSSSV_double	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_double))
#define SLIM_TKOFF_CSSSV_groove	(SLIM_TKOFF_BASE_CSSSV0 + 991)
#define SLIM_TKNAM_CSSSV_groove	(SLIM_TKNAM_BASE_CSSSV0 + 991)
#define SLIM_TKLEN_CSSSV_groove	(6)
#define SLIM_TOKEN_CSSSV_groove	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_groove))
#define SLIM_TKOFF_CSSSV_hidden	(SLIM_TKOFF_BASE_CSSSV0 + 998)
#define SLIM_TKNAM_CSSSV_hidden	(SLIM_TKNAM_BASE_CSSSV0 + 998)
#define SLIM_TKLEN_CSSSV_hidden	(6)
#define SLIM_TOKEN_CSSSV_hidden	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_hidden))
#define SLIM_TKOFF_CSSSV_inset	(SLIM_TKOFF_BASE_CSSSV0 + 1005)
#define SLIM_TKNAM_CSSSV_inset	(SLIM_TKNAM_BASE_CSSSV0 + 1005)
#define SLIM_TKLEN_CSSSV_inset	(5)
#define SLIM_TOKEN_CSSSV_inset	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_inset))
#define SLIM_TKOFF_CSSSV_outset	(SLIM_TKOFF_BASE_CSSSV0 + 1011)
#define SLIM_TKNAM_CSSSV_outset	(SLIM_TKNAM_BASE_CSSSV0 + 1011)
#define SLIM_TKLEN_CSSSV_outset	(6)
#define SLIM_TOKEN_CSSSV_outset	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_outset))
#define SLIM_TKOFF_CSSSV_ridge	(SLIM_TKOFF_BASE_CSSSV0 + 1018)
#define SLIM_TKNAM_CSSSV_ridge	(SLIM_TKNAM_BASE_CSSSV0 + 1018)
#define SLIM_TKLEN_CSSSV_ridge	(5)
#define SLIM_TOKEN_CSSSV_ridge	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_ridge))
#define SLIM_TKOFF_CSSSV_solid	(SLIM_TKOFF_BASE_CSSSV0 + 1024)
#define SLIM_TKNAM_CSSSV_solid	(SLIM_TKNAM_BASE_CSSSV0 + 1024)
#define SLIM_TKLEN_CSSSV_solid	(5)
#define SLIM_TOKEN_CSSSV_solid	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_solid))
#define SLIM_TKOFF_CSSSV_thick	(SLIM_TKOFF_BASE_CSSSV0 + 1030)
#define SLIM_TKNAM_CSSSV_thick	(SLIM_TKNAM_BASE_CSSSV0 + 1030)
#define SLIM_TKLEN_CSSSV_thick	(5)
#define SLIM_TOKEN_CSSSV_thick	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_thick))
#define SLIM_TKOFF_CSSSV_thin	(SLIM_TKOFF_BASE_CSSSV0 + 1036)
#define SLIM_TKNAM_CSSSV_thin	(SLIM_TKNAM_BASE_CSSSV0 + 1036)
#define SLIM_TKLEN_CSSSV_thin	(4)
#define SLIM_TOKEN_CSSSV_thin	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_thin))
#define SLIM_TKOFF_CSSSV_medium	(SLIM_TKOFF_BASE_CSSSV0 + 1041)
#define SLIM_TKNAM_CSSSV_medium	(SLIM_TKNAM_BASE_CSSSV0 + 1041)
#define SLIM_TKLEN_CSSSV_medium	(6)
#define SLIM_TOKEN_CSSSV_medium	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_medium))
#define SLIM_TKOFF_CSSSV_auto	(SLIM_TKOFF_BASE_CSSSV0 + 1048)
#define SLIM_TKNAM_CSSSV_auto	(SLIM_TKNAM_BASE_CSSSV0 + 1048)
#define SLIM_TKLEN_CSSSV_auto	(4)
#define SLIM_TOKEN_CSSSV_auto	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_auto))
#define SLIM_TKOFF_CSSSV_left	(SLIM_TKOFF_BASE_CSSSV0 + 1053)
#define SLIM_TKNAM_CSSSV_left	(SLIM_TKNAM_BASE_CSSSV0 + 1053)
#define SLIM_TKLEN_CSSSV_left	(4)
#define SLIM_TOKEN_CSSSV_left	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_left))
#define SLIM_TKOFF_CSSSV_right	(SLIM_TKOFF_BASE_CSSSV0 + 1058)
#define SLIM_TKNAM_CSSSV_right	(SLIM_TKNAM_BASE_CSSSV0 + 1058)
#define SLIM_TKLEN_CSSSV_right	(5)
#define SLIM_TOKEN_CSSSV_right	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_right))
#define SLIM_TKOFF_CSSSV_default	(SLIM_TKOFF_BASE_CSSSV0 + 1064)
#define SLIM_TKNAM_CSSSV_default	(SLIM_TKNAM_BASE_CSSSV0 + 1064)
#define SLIM_TKLEN_CSSSV_default	(7)
#define SLIM_TOKEN_CSSSV_default	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_default))
#define SLIM_TKOFF_CSSSV_e_resize	(SLIM_TKOFF_BASE_CSSSV0 + 1072)
#define SLIM_TKNAM_CSSSV_e_resize	(SLIM_TKNAM_BASE_CSSSV0 + 1072)
#define SLIM_TKLEN_CSSSV_e_resize	(8)
#define SLIM_TOKEN_CSSSV_e_resize	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_e_resize))
#define SLIM_TKOFF_CSSSV_help	(SLIM_TKOFF_BASE_CSSSV0 + 1081)
#define SLIM_TKNAM_CSSSV_help	(SLIM_TKNAM_BASE_CSSSV0 + 1081)
#define SLIM_TKLEN_CSSSV_help	(4)
#define SLIM_TOKEN_CSSSV_help	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_help))
#define SLIM_TKOFF_CSSSV_invert	(SLIM_TKOFF_BASE_CSSSV0 + 1086)
#define SLIM_TKNAM_CSSSV_invert	(SLIM_TKNAM_BASE_CSSSV0 + 1086)
#define SLIM_TKLEN_CSSSV_invert	(6)
#define SLIM_TOKEN_CSSSV_invert	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_invert))
#define SLIM_TKOFF_CSSSV_move	(SLIM_TKOFF_BASE_CSSSV0 + 1093)
#define SLIM_TKNAM_CSSSV_move	(SLIM_TKNAM_BASE_CSSSV0 + 1093)
#define SLIM_TKLEN_CSSSV_move	(4)
#define SLIM_TOKEN_CSSSV_move	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_move))
#define SLIM_TKOFF_CSSSV_n_resize	(SLIM_TKOFF_BASE_CSSSV0 + 1098)
#define SLIM_TKNAM_CSSSV_n_resize	(SLIM_TKNAM_BASE_CSSSV0 + 1098)
#define SLIM_TKLEN_CSSSV_n_resize	(8)
#define SLIM_TOKEN_CSSSV_n_resize	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_n_resize))
#define SLIM_TKOFF_CSSSV_pointer	(SLIM_TKOFF_BASE_CSSSV0 + 1107)
#define SLIM_TKNAM_CSSSV_pointer	(SLIM_TKNAM_BASE_CSSSV0 + 1107)
#define SLIM_TKLEN_CSSSV_pointer	(7)
#define SLIM_TOKEN_CSSSV_pointer	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_pointer))
#define SLIM_TKOFF_CSSSV_progress	(SLIM_TKOFF_BASE_CSSSV0 + 1115)
#define SLIM_TKNAM_CSSSV_progress	(SLIM_TKNAM_BASE_CSSSV0 + 1115)
#define SLIM_TKLEN_CSSSV_progress	(8)
#define SLIM_TOKEN_CSSSV_progress	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_progress))
#define SLIM_TKOFF_CSSSV_s_resize	(SLIM_TKOFF_BASE_CSSSV0 + 1124)
#define SLIM_TKNAM_CSSSV_s_resize	(SLIM_TKNAM_BASE_CSSSV0 + 1124)
#define SLIM_TKLEN_CSSSV_s_resize	(8)
#define SLIM_TOKEN_CSSSV_s_resize	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_s_resize))
#define SLIM_TKOFF_CSSSV_text	(SLIM_TKOFF_BASE_CSSSV0 + 1133)
#define SLIM_TKNAM_CSSSV_text	(SLIM_TKNAM_BASE_CSSSV0 + 1133)
#define SLIM_TKLEN_CSSSV_text	(4)
#define SLIM_TOKEN_CSSSV_text	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_text))
#define SLIM_TKOFF_CSSSV_w_resize	(SLIM_TKOFF_BASE_CSSSV0 + 1138)
#define SLIM_TKNAM_CSSSV_w_resize	(SLIM_TKNAM_BASE_CSSSV0 + 1138)
#define SLIM_TKLEN_CSSSV_w_resize	(8)
#define SLIM_TOKEN_CSSSV_w_resize	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_w_resize))
#define SLIM_TKOFF_CSSSV_wait	(SLIM_TKOFF_BASE_CSSSV0 + 1147)
#define SLIM_TKNAM_CSSSV_wait	(SLIM_TKNAM_BASE_CSSSV0 + 1147)
#define SLIM_TKLEN_CSSSV_wait	(4)
#define SLIM_TOKEN_CSSSV_wait	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_wait))
#define SLIM_TKOFF_CSSSV_crosshair	(SLIM_TKOFF_BASE_CSSSV0 + 1152)
#define SLIM_TKNAM_CSSSV_crosshair	(SLIM_TKNAM_BASE_CSSSV0 + 1152)
#define SLIM_TKLEN_CSSSV_crosshair	(9)
#define SLIM_TOKEN_CSSSV_crosshair	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_crosshair))
#define SLIM_TKOFF_CSSSV_ne_resize	(SLIM_TKOFF_BASE_CSSSV0 + 1162)
#define SLIM_TKNAM_CSSSV_ne_resize	(SLIM_TKNAM_BASE_CSSSV0 + 1162)
#define SLIM_TKLEN_CSSSV_ne_resize	(9)
#define SLIM_TOKEN_CSSSV_ne_resize	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_ne_resize))
#define SLIM_TKOFF_CSSSV_nw_resize	(SLIM_TKOFF_BASE_CSSSV0 + 1172)
#define SLIM_TKNAM_CSSSV_nw_resize	(SLIM_TKNAM_BASE_CSSSV0 + 1172)
#define SLIM_TKLEN_CSSSV_nw_resize	(9)
#define SLIM_TOKEN_CSSSV_nw_resize	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_nw_resize))
#define SLIM_TKOFF_CSSSV_se_resize	(SLIM_TKOFF_BASE_CSSSV0 + 1182)
#define SLIM_TKNAM_CSSSV_se_resize	(SLIM_TKNAM_BASE_CSSSV0 + 1182)
#define SLIM_TKLEN_CSSSV_se_resize	(9)
#define SLIM_TOKEN_CSSSV_se_resize	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_se_resize))
#define SLIM_TKOFF_CSSSV_sw_resize	(SLIM_TKOFF_BASE_CSSSV0 + 1192)
#define SLIM_TKNAM_CSSSV_sw_resize	(SLIM_TKNAM_BASE_CSSSV0 + 1192)
#define SLIM_TKLEN_CSSSV_sw_resize	(9)
#define SLIM_TOKEN_CSSSV_sw_resize	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_sw_resize))
#define SLIM_TKOFF_CSSSV_landscape	(SLIM_TKOFF_BASE_CSSSV0 + 1202)
#define SLIM_TKNAM_CSSSV_landscape	(SLIM_TKNAM_BASE_CSSSV0 + 1202)
#define SLIM_TKLEN_CSSSV_landscape	(9)
#define SLIM_TOKEN_CSSSV_landscape	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_landscape))
#define SLIM_TKOFF_CSSSV_portrait	(SLIM_TKOFF_BASE_CSSSV0 + 1212)
#define SLIM_TKNAM_CSSSV_portrait	(SLIM_TKNAM_BASE_CSSSV0 + 1212)
#define SLIM_TKLEN_CSSSV_portrait	(8)
#define SLIM_TOKEN_CSSSV_portrait	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_portrait))
#define SLIM_TKOFF_CSSSV_avoid	(SLIM_TKOFF_BASE_CSSSV0 + 1221)
#define SLIM_TKNAM_CSSSV_avoid	(SLIM_TKNAM_BASE_CSSSV0 + 1221)
#define SLIM_TKLEN_CSSSV_avoid	(5)
#define SLIM_TOKEN_CSSSV_avoid	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_avoid))
#define SLIM_TKOFF_CSSSV_crop	(SLIM_TKOFF_BASE_CSSSV0 + 1227)
#define SLIM_TKNAM_CSSSV_crop	(SLIM_TKNAM_BASE_CSSSV0 + 1227)
#define SLIM_TKLEN_CSSSV_crop	(4)
#define SLIM_TOKEN_CSSSV_crop	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_crop))
#define SLIM_TKOFF_CSSSV_cross	(SLIM_TKOFF_BASE_CSSSV0 + 1232)
#define SLIM_TKNAM_CSSSV_cross	(SLIM_TKNAM_BASE_CSSSV0 + 1232)
#define SLIM_TKLEN_CSSSV_cross	(5)
#define SLIM_TOKEN_CSSSV_cross	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_cross))
#define SLIM_TKOFF_CSSSV_always	(SLIM_TKOFF_BASE_CSSSV0 + 1238)
#define SLIM_TKNAM_CSSSV_always	(SLIM_TKNAM_BASE_CSSSV0 + 1238)
#define SLIM_TKLEN_CSSSV_always	(6)
#define SLIM_TOKEN_CSSSV_always	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_always))
#define SLIM_TKOFF_CSSSV_above	(SLIM_TKOFF_BASE_CSSSV0 + 1245)
#define SLIM_TKNAM_CSSSV_above	(SLIM_TKNAM_BASE_CSSSV0 + 1245)
#define SLIM_TKLEN_CSSSV_above	(5)
#define SLIM_TOKEN_CSSSV_above	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_above))
#define SLIM_TKOFF_CSSSV_behind	(SLIM_TKOFF_BASE_CSSSV0 + 1251)
#define SLIM_TKNAM_CSSSV_behind	(SLIM_TKNAM_BASE_CSSSV0 + 1251)
#define SLIM_TKLEN_CSSSV_behind	(6)
#define SLIM_TOKEN_CSSSV_behind	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_behind))
#define SLIM_TKOFF_CSSSV_below	(SLIM_TKOFF_BASE_CSSSV0 + 1258)
#define SLIM_TKNAM_CSSSV_below	(SLIM_TKNAM_BASE_CSSSV0 + 1258)
#define SLIM_TKLEN_CSSSV_below	(5)
#define SLIM_TOKEN_CSSSV_below	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_below))
#define SLIM_TKOFF_CSSSV_child	(SLIM_TKOFF_BASE_CSSSV0 + 1264)
#define SLIM_TKNAM_CSSSV_child	(SLIM_TKNAM_BASE_CSSSV0 + 1264)
#define SLIM_TKLEN_CSSSV_child	(5)
#define SLIM_TOKEN_CSSSV_child	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_child))
#define SLIM_TKOFF_CSSSV_code	(SLIM_TKOFF_BASE_CSSSV0 + 1270)
#define SLIM_TKNAM_CSSSV_code	(SLIM_TKNAM_BASE_CSSSV0 + 1270)
#define SLIM_TKLEN_CSSSV_code	(4)
#define SLIM_TOKEN_CSSSV_code	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_code))
#define SLIM_TKOFF_CSSSV_digits	(SLIM_TKOFF_BASE_CSSSV0 + 1275)
#define SLIM_TKNAM_CSSSV_digits	(SLIM_TKNAM_BASE_CSSSV0 + 1275)
#define SLIM_TKLEN_CSSSV_digits	(6)
#define SLIM_TOKEN_CSSSV_digits	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_digits))
#define SLIM_TKOFF_CSSSV_far_left	(SLIM_TKOFF_BASE_CSSSV0 + 1282)
#define SLIM_TKNAM_CSSSV_far_left	(SLIM_TKNAM_BASE_CSSSV0 + 1282)
#define SLIM_TKLEN_CSSSV_far_left	(8)
#define SLIM_TOKEN_CSSSV_far_left	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_far_left))
#define SLIM_TKOFF_CSSSV_fast	(SLIM_TKOFF_BASE_CSSSV0 + 1291)
#define SLIM_TKNAM_CSSSV_fast	(SLIM_TKNAM_BASE_CSSSV0 + 1291)
#define SLIM_TKLEN_CSSSV_fast	(4)
#define SLIM_TOKEN_CSSSV_fast	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_fast))
#define SLIM_TKOFF_CSSSV_faster	(SLIM_TKOFF_BASE_CSSSV0 + 1296)
#define SLIM_TKNAM_CSSSV_faster	(SLIM_TKNAM_BASE_CSSSV0 + 1296)
#define SLIM_TKLEN_CSSSV_faster	(6)
#define SLIM_TOKEN_CSSSV_faster	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_faster))
#define SLIM_TKOFF_CSSSV_female	(SLIM_TKOFF_BASE_CSSSV0 + 1303)
#define SLIM_TKNAM_CSSSV_female	(SLIM_TKNAM_BASE_CSSSV0 + 1303)
#define SLIM_TKLEN_CSSSV_female	(6)
#define SLIM_TOKEN_CSSSV_female	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_female))
#define SLIM_TKOFF_CSSSV_high	(SLIM_TKOFF_BASE_CSSSV0 + 1310)
#define SLIM_TKNAM_CSSSV_high	(SLIM_TKNAM_BASE_CSSSV0 + 1310)
#define SLIM_TKLEN_CSSSV_high	(4)
#define SLIM_TOKEN_CSSSV_high	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_high))
#define SLIM_TKOFF_CSSSV_higher	(SLIM_TKOFF_BASE_CSSSV0 + 1315)
#define SLIM_TKNAM_CSSSV_higher	(SLIM_TKNAM_BASE_CSSSV0 + 1315)
#define SLIM_TKLEN_CSSSV_higher	(6)
#define SLIM_TOKEN_CSSSV_higher	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_higher))
#define SLIM_TKOFF_CSSSV_level	(SLIM_TKOFF_BASE_CSSSV0 + 1322)
#define SLIM_TKNAM_CSSSV_level	(SLIM_TKNAM_BASE_CSSSV0 + 1322)
#define SLIM_TKLEN_CSSSV_level	(5)
#define SLIM_TOKEN_CSSSV_level	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_level))
#define SLIM_TKOFF_CSSSV_loud	(SLIM_TKOFF_BASE_CSSSV0 + 1328)
#define SLIM_TKNAM_CSSSV_loud	(SLIM_TKNAM_BASE_CSSSV0 + 1328)
#define SLIM_TKLEN_CSSSV_loud	(4)
#define SLIM_TOKEN_CSSSV_loud	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_loud))
#define SLIM_TKOFF_CSSSV_low	(SLIM_TKOFF_BASE_CSSSV0 + 1333)
#define SLIM_TKNAM_CSSSV_low	(SLIM_TKNAM_BASE_CSSSV0 + 1333)
#define SLIM_TKLEN_CSSSV_low	(3)
#define SLIM_TOKEN_CSSSV_low	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_low))
#define SLIM_TKOFF_CSSSV_lower	(SLIM_TKOFF_BASE_CSSSV0 + 1337)
#define SLIM_TKNAM_CSSSV_lower	(SLIM_TKNAM_BASE_CSSSV0 + 1337)
#define SLIM_TKLEN_CSSSV_lower	(5)
#define SLIM_TOKEN_CSSSV_lower	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_lower))
#define SLIM_TKOFF_CSSSV_male	(SLIM_TKOFF_BASE_CSSSV0 + 1343)
#define SLIM_TKNAM_CSSSV_male	(SLIM_TKNAM_BASE_CSSSV0 + 1343)
#define SLIM_TKLEN_CSSSV_male	(4)
#define SLIM_TOKEN_CSSSV_male	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_male))
#define SLIM_TKOFF_CSSSV_mix	(SLIM_TKOFF_BASE_CSSSV0 + 1348)
#define SLIM_TKNAM_CSSSV_mix	(SLIM_TKNAM_BASE_CSSSV0 + 1348)
#define SLIM_TKLEN_CSSSV_mix	(3)
#define SLIM_TOKEN_CSSSV_mix	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_mix))
#define SLIM_TKOFF_CSSSV_once	(SLIM_TKOFF_BASE_CSSSV0 + 1352)
#define SLIM_TKNAM_CSSSV_once	(SLIM_TKNAM_BASE_CSSSV0 + 1352)
#define SLIM_TKLEN_CSSSV_once	(4)
#define SLIM_TOKEN_CSSSV_once	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_once))
#define SLIM_TKOFF_CSSSV_silent	(SLIM_TKOFF_BASE_CSSSV0 + 1357)
#define SLIM_TKNAM_CSSSV_silent	(SLIM_TKNAM_BASE_CSSSV0 + 1357)
#define SLIM_TKLEN_CSSSV_silent	(6)
#define SLIM_TOKEN_CSSSV_silent	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_silent))
#define SLIM_TKOFF_CSSSV_slow	(SLIM_TKOFF_BASE_CSSSV0 + 1364)
#define SLIM_TKNAM_CSSSV_slow	(SLIM_TKNAM_BASE_CSSSV0 + 1364)
#define SLIM_TKLEN_CSSSV_slow	(4)
#define SLIM_TOKEN_CSSSV_slow	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_slow))
#define SLIM_TKOFF_CSSSV_slower	(SLIM_TKOFF_BASE_CSSSV0 + 1369)
#define SLIM_TKNAM_CSSSV_slower	(SLIM_TKNAM_BASE_CSSSV0 + 1369)
#define SLIM_TKLEN_CSSSV_slower	(6)
#define SLIM_TOKEN_CSSSV_slower	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_slower))
#define SLIM_TKOFF_CSSSV_soft	(SLIM_TKOFF_BASE_CSSSV0 + 1376)
#define SLIM_TKNAM_CSSSV_soft	(SLIM_TKNAM_BASE_CSSSV0 + 1376)
#define SLIM_TKLEN_CSSSV_soft	(4)
#define SLIM_TOKEN_CSSSV_soft	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_soft))
#define SLIM_TKOFF_CSSSV_x_fast	(SLIM_TKOFF_BASE_CSSSV0 + 1381)
#define SLIM_TKNAM_CSSSV_x_fast	(SLIM_TKNAM_BASE_CSSSV0 + 1381)
#define SLIM_TKLEN_CSSSV_x_fast	(6)
#define SLIM_TOKEN_CSSSV_x_fast	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_x_fast))
#define SLIM_TKOFF_CSSSV_x_high	(SLIM_TKOFF_BASE_CSSSV0 + 1388)
#define SLIM_TKNAM_CSSSV_x_high	(SLIM_TKNAM_BASE_CSSSV0 + 1388)
#define SLIM_TKLEN_CSSSV_x_high	(6)
#define SLIM_TOKEN_CSSSV_x_high	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_x_high))
#define SLIM_TKOFF_CSSSV_x_loud	(SLIM_TKOFF_BASE_CSSSV0 + 1395)
#define SLIM_TKNAM_CSSSV_x_loud	(SLIM_TKNAM_BASE_CSSSV0 + 1395)
#define SLIM_TKLEN_CSSSV_x_loud	(6)
#define SLIM_TOKEN_CSSSV_x_loud	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_x_loud))
#define SLIM_TKOFF_CSSSV_x_low	(SLIM_TKOFF_BASE_CSSSV0 + 1402)
#define SLIM_TKNAM_CSSSV_x_low	(SLIM_TKNAM_BASE_CSSSV0 + 1402)
#define SLIM_TKLEN_CSSSV_x_low	(5)
#define SLIM_TOKEN_CSSSV_x_low	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_x_low))
#define SLIM_TKOFF_CSSSV_x_slow	(SLIM_TKOFF_BASE_CSSSV0 + 1408)
#define SLIM_TKNAM_CSSSV_x_slow	(SLIM_TKNAM_BASE_CSSSV0 + 1408)
#define SLIM_TKLEN_CSSSV_x_slow	(6)
#define SLIM_TOKEN_CSSSV_x_slow	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_x_slow))
#define SLIM_TKOFF_CSSSV_x_soft	(SLIM_TKOFF_BASE_CSSSV0 + 1415)
#define SLIM_TKNAM_CSSSV_x_soft	(SLIM_TKNAM_BASE_CSSSV0 + 1415)
#define SLIM_TKLEN_CSSSV_x_soft	(6)
#define SLIM_TOKEN_CSSSV_x_soft	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_x_soft))
#define SLIM_TKOFF_CSSSV_center_left	(SLIM_TKOFF_BASE_CSSSV0 + 1422)
#define SLIM_TKNAM_CSSSV_center_left	(SLIM_TKNAM_BASE_CSSSV0 + 1422)
#define SLIM_TKLEN_CSSSV_center_left	(11)
#define SLIM_TOKEN_CSSSV_center_left	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_center_left))
#define SLIM_TKOFF_CSSSV_center_right	(SLIM_TKOFF_BASE_CSSSV0 + 1434)
#define SLIM_TKNAM_CSSSV_center_right	(SLIM_TKNAM_BASE_CSSSV0 + 1434)
#define SLIM_TKLEN_CSSSV_center_right	(12)
#define SLIM_TOKEN_CSSSV_center_right	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_center_right))
#define SLIM_TKOFF_CSSSV_continuous	(SLIM_TKOFF_BASE_CSSSV0 + 1447)
#define SLIM_TKNAM_CSSSV_continuous	(SLIM_TKNAM_BASE_CSSSV0 + 1447)
#define SLIM_TKLEN_CSSSV_continuous	(10)
#define SLIM_TOKEN_CSSSV_continuous	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_continuous))
#define SLIM_TKOFF_CSSSV_far_right	(SLIM_TKOFF_BASE_CSSSV0 + 1458)
#define SLIM_TKNAM_CSSSV_far_right	(SLIM_TKNAM_BASE_CSSSV0 + 1458)
#define SLIM_TKLEN_CSSSV_far_right	(9)
#define SLIM_TOKEN_CSSSV_far_right	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_far_right))
#define SLIM_TKOFF_CSSSV_left_side	(SLIM_TKOFF_BASE_CSSSV0 + 1468)
#define SLIM_TKNAM_CSSSV_left_side	(SLIM_TKNAM_BASE_CSSSV0 + 1468)
#define SLIM_TKLEN_CSSSV_left_side	(9)
#define SLIM_TOKEN_CSSSV_left_side	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_left_side))
#define SLIM_TKOFF_CSSSV_leftwards	(SLIM_TKOFF_BASE_CSSSV0 + 1478)
#define SLIM_TKNAM_CSSSV_leftwards	(SLIM_TKNAM_BASE_CSSSV0 + 1478)
#define SLIM_TKLEN_CSSSV_leftwards	(9)
#define SLIM_TOKEN_CSSSV_leftwards	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_leftwards))
#define SLIM_TKOFF_CSSSV_right_side	(SLIM_TKOFF_BASE_CSSSV0 + 1488)
#define SLIM_TKNAM_CSSSV_right_side	(SLIM_TKNAM_BASE_CSSSV0 + 1488)
#define SLIM_TKLEN_CSSSV_right_side	(10)
#define SLIM_TOKEN_CSSSV_right_side	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_right_side))
#define SLIM_TKOFF_CSSSV_rightwards	(SLIM_TKOFF_BASE_CSSSV0 + 1499)
#define SLIM_TKNAM_CSSSV_rightwards	(SLIM_TKNAM_BASE_CSSSV0 + 1499)
#define SLIM_TKLEN_CSSSV_rightwards	(10)
#define SLIM_TOKEN_CSSSV_rightwards	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_rightwards))
#define SLIM_TKOFF_CSSSV_spell_out	(SLIM_TKOFF_BASE_CSSSV0 + 1510)
#define SLIM_TKNAM_CSSSV_spell_out	(SLIM_TKNAM_BASE_CSSSV0 + 1510)
#define SLIM_TKLEN_CSSSV_spell_out	(9)
#define SLIM_TOKEN_CSSSV_spell_out	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_spell_out))
#define SLIM_TKOFF_CSSSV_all	(SLIM_TKOFF_BASE_CSSSV0 + 1520)
#define SLIM_TKNAM_CSSSV_all	(SLIM_TKNAM_BASE_CSSSV0 + 1520)
#define SLIM_TKLEN_CSSSV_all	(3)
#define SLIM_TOKEN_CSSSV_all	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_all))
#define SLIM_TKOFF_CSSSV_bold	(SLIM_TKOFF_BASE_CSSSV0 + 1524)
#define SLIM_TKNAM_CSSSV_bold	(SLIM_TKNAM_BASE_CSSSV0 + 1524)
#define SLIM_TKLEN_CSSSV_bold	(4)
#define SLIM_TOKEN_CSSSV_bold	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_bold))
#define SLIM_TKOFF_CSSSV_condensed	(SLIM_TKOFF_BASE_CSSSV0 + 1529)
#define SLIM_TKNAM_CSSSV_condensed	(SLIM_TKNAM_BASE_CSSSV0 + 1529)
#define SLIM_TKLEN_CSSSV_condensed	(9)
#define SLIM_TOKEN_CSSSV_condensed	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_condensed))
#define SLIM_TKOFF_CSSSV_expanded	(SLIM_TKOFF_BASE_CSSSV0 + 1539)
#define SLIM_TKNAM_CSSSV_expanded	(SLIM_TKNAM_BASE_CSSSV0 + 1539)
#define SLIM_TKLEN_CSSSV_expanded	(8)
#define SLIM_TOKEN_CSSSV_expanded	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_expanded))
#define SLIM_TKOFF_CSSSV_extra_condensed	(SLIM_TKOFF_BASE_CSSSV0 + 1548)
#define SLIM_TKNAM_CSSSV_extra_condensed	(SLIM_TKNAM_BASE_CSSSV0 + 1548)
#define SLIM_TKLEN_CSSSV_extra_condensed	(15)
#define SLIM_TOKEN_CSSSV_extra_condensed	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_extra_condensed))
#define SLIM_TKOFF_CSSSV_extra_expanded	(SLIM_TKOFF_BASE_CSSSV0 + 1564)
#define SLIM_TKNAM_CSSSV_extra_expanded	(SLIM_TKNAM_BASE_CSSSV0 + 1564)
#define SLIM_TKLEN_CSSSV_extra_expanded	(14)
#define SLIM_TOKEN_CSSSV_extra_expanded	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_extra_expanded))
#define SLIM_TKOFF_CSSSV_italic	(SLIM_TKOFF_BASE_CSSSV0 + 1579)
#define SLIM_TKNAM_CSSSV_italic	(SLIM_TKNAM_BASE_CSSSV0 + 1579)
#define SLIM_TKLEN_CSSSV_italic	(6)
#define SLIM_TOKEN_CSSSV_italic	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_italic))
#define SLIM_TKOFF_CSSSV_normal	(SLIM_TKOFF_BASE_CSSSV0 + 1586)
#define SLIM_TKNAM_CSSSV_normal	(SLIM_TKNAM_BASE_CSSSV0 + 1586)
#define SLIM_TKLEN_CSSSV_normal	(6)
#define SLIM_TOKEN_CSSSV_normal	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_normal))
#define SLIM_TKOFF_CSSSV_oblique	(SLIM_TKOFF_BASE_CSSSV0 + 1593)
#define SLIM_TKNAM_CSSSV_oblique	(SLIM_TKNAM_BASE_CSSSV0 + 1593)
#define SLIM_TKLEN_CSSSV_oblique	(7)
#define SLIM_TOKEN_CSSSV_oblique	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_oblique))
#define SLIM_TKOFF_CSSSV_semi_condensed	(SLIM_TKOFF_BASE_CSSSV0 + 1601)
#define SLIM_TKNAM_CSSSV_semi_condensed	(SLIM_TKNAM_BASE_CSSSV0 + 1601)
#define SLIM_TKLEN_CSSSV_semi_condensed	(14)
#define SLIM_TOKEN_CSSSV_semi_condensed	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_semi_condensed))
#define SLIM_TKOFF_CSSSV_semi_expanded	(SLIM_TKOFF_BASE_CSSSV0 + 1616)
#define SLIM_TKNAM_CSSSV_semi_expanded	(SLIM_TKNAM_BASE_CSSSV0 + 1616)
#define SLIM_TKLEN_CSSSV_semi_expanded	(13)
#define SLIM_TOKEN_CSSSV_semi_expanded	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_semi_expanded))
#define SLIM_TKOFF_CSSSV_small_caps	(SLIM_TKOFF_BASE_CSSSV0 + 1630)
#define SLIM_TKNAM_CSSSV_small_caps	(SLIM_TKNAM_BASE_CSSSV0 + 1630)
#define SLIM_TKLEN_CSSSV_small_caps	(10)
#define SLIM_TOKEN_CSSSV_small_caps	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_small_caps))
#define SLIM_TKOFF_CSSSV_ultra_condensed	(SLIM_TKOFF_BASE_CSSSV0 + 1641)
#define SLIM_TKNAM_CSSSV_ultra_condensed	(SLIM_TKNAM_BASE_CSSSV0 + 1641)
#define SLIM_TKLEN_CSSSV_ultra_condensed	(15)
#define SLIM_TOKEN_CSSSV_ultra_condensed	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_ultra_condensed))
#define SLIM_TKOFF_CSSSV_ultra_expanded	(SLIM_TKOFF_BASE_CSSSV0 + 1657)
#define SLIM_TKNAM_CSSSV_ultra_expanded	(SLIM_TKNAM_BASE_CSSSV0 + 1657)
#define SLIM_TKLEN_CSSSV_ultra_expanded	(14)
#define SLIM_TOKEN_CSSSV_ultra_expanded	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_ultra_expanded))
#define SLIM_TKOFF_CSSSV_100	(SLIM_TKOFF_BASE_CSSSV0 + 1672)
#define SLIM_TKNAM_CSSSV_100	(SLIM_TKNAM_BASE_CSSSV0 + 1672)
#define SLIM_TKLEN_CSSSV_100	(3)
#define SLIM_TOKEN_CSSSV_100	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_100))
#define SLIM_TKOFF_CSSSV_200	(SLIM_TKOFF_BASE_CSSSV0 + 1676)
#define SLIM_TKNAM_CSSSV_200	(SLIM_TKNAM_BASE_CSSSV0 + 1676)
#define SLIM_TKLEN_CSSSV_200	(3)
#define SLIM_TOKEN_CSSSV_200	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_200))
#define SLIM_TKOFF_CSSSV_300	(SLIM_TKOFF_BASE_CSSSV0 + 1680)
#define SLIM_TKNAM_CSSSV_300	(SLIM_TKNAM_BASE_CSSSV0 + 1680)
#define SLIM_TKLEN_CSSSV_300	(3)
#define SLIM_TOKEN_CSSSV_300	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_300))
#define SLIM_TKOFF_CSSSV_400	(SLIM_TKOFF_BASE_CSSSV0 + 1684)
#define SLIM_TKNAM_CSSSV_400	(SLIM_TKNAM_BASE_CSSSV0 + 1684)
#define SLIM_TKLEN_CSSSV_400	(3)
#define SLIM_TOKEN_CSSSV_400	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_400))
#define SLIM_TKOFF_CSSSV_500	(SLIM_TKOFF_BASE_CSSSV0 + 1688)
#define SLIM_TKNAM_CSSSV_500	(SLIM_TKNAM_BASE_CSSSV0 + 1688)
#define SLIM_TKLEN_CSSSV_500	(3)
#define SLIM_TOKEN_CSSSV_500	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_500))
#define SLIM_TKOFF_CSSSV_600	(SLIM_TKOFF_BASE_CSSSV0 + 1692)
#define SLIM_TKNAM_CSSSV_600	(SLIM_TKNAM_BASE_CSSSV0 + 1692)
#define SLIM_TKLEN_CSSSV_600	(3)
#define SLIM_TOKEN_CSSSV_600	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_600))
#define SLIM_TKOFF_CSSSV_700	(SLIM_TKOFF_BASE_CSSSV0 + 1696)
#define SLIM_TKNAM_CSSSV_700	(SLIM_TKNAM_BASE_CSSSV0 + 1696)
#define SLIM_TKLEN_CSSSV_700	(3)
#define SLIM_TOKEN_CSSSV_700	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_700))
#define SLIM_TKOFF_CSSSV_800	(SLIM_TKOFF_BASE_CSSSV0 + 1700)
#define SLIM_TKNAM_CSSSV_800	(SLIM_TKNAM_BASE_CSSSV0 + 1700)
#define SLIM_TKLEN_CSSSV_800	(3)
#define SLIM_TOKEN_CSSSV_800	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_800))
#define SLIM_TKOFF_CSSSV_900	(SLIM_TKOFF_BASE_CSSSV0 + 1704)
#define SLIM_TKNAM_CSSSV_900	(SLIM_TKNAM_BASE_CSSSV0 + 1704)
#define SLIM_TKLEN_CSSSV_900	(3)
#define SLIM_TOKEN_CSSSV_900	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_900))
#define SLIM_TKOFF_CSSSV_alias	(SLIM_TKOFF_BASE_CSSSV0 + 1708)
#define SLIM_TKNAM_CSSSV_alias	(SLIM_TKNAM_BASE_CSSSV0 + 1708)
#define SLIM_TKLEN_CSSSV_alias	(5)
#define SLIM_TOKEN_CSSSV_alias	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_alias))
#define SLIM_TKOFF_CSSSV_all_scroll	(SLIM_TKOFF_BASE_CSSSV0 + 1714)
#define SLIM_TKNAM_CSSSV_all_scroll	(SLIM_TKNAM_BASE_CSSSV0 + 1714)
#define SLIM_TKLEN_CSSSV_all_scroll	(10)
#define SLIM_TOKEN_CSSSV_all_scroll	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_all_scroll))
#define SLIM_TKOFF_CSSSV_border_box	(SLIM_TKOFF_BASE_CSSSV0 + 1725)
#define SLIM_TKNAM_CSSSV_border_box	(SLIM_TKNAM_BASE_CSSSV0 + 1725)
#define SLIM_TKLEN_CSSSV_border_box	(10)
#define SLIM_TOKEN_CSSSV_border_box	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_border_box))
#define SLIM_TKOFF_CSSSV_cell	(SLIM_TKOFF_BASE_CSSSV0 + 1736)
#define SLIM_TKNAM_CSSSV_cell	(SLIM_TKNAM_BASE_CSSSV0 + 1736)
#define SLIM_TKLEN_CSSSV_cell	(4)
#define SLIM_TOKEN_CSSSV_cell	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_cell))
#define SLIM_TKOFF_CSSSV_col_resize	(SLIM_TKOFF_BASE_CSSSV0 + 1741)
#define SLIM_TKNAM_CSSSV_col_resize	(SLIM_TKNAM_BASE_CSSSV0 + 1741)
#define SLIM_TKLEN_CSSSV_col_resize	(10)
#define SLIM_TOKEN_CSSSV_col_resize	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_col_resize))
#define SLIM_TKOFF_CSSSV_content_box	(SLIM_TKOFF_BASE_CSSSV0 + 1752)
#define SLIM_TKNAM_CSSSV_content_box	(SLIM_TKNAM_BASE_CSSSV0 + 1752)
#define SLIM_TKLEN_CSSSV_content_box	(11)
#define SLIM_TOKEN_CSSSV_content_box	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_content_box))
#define SLIM_TKOFF_CSSSV_context_menu	(SLIM_TKOFF_BASE_CSSSV0 + 1764)
#define SLIM_TKNAM_CSSSV_context_menu	(SLIM_TKNAM_BASE_CSSSV0 + 1764)
#define SLIM_TKLEN_CSSSV_context_menu	(12)
#define SLIM_TOKEN_CSSSV_context_menu	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_context_menu))
#define SLIM_TKOFF_CSSSV_copy	(SLIM_TKOFF_BASE_CSSSV0 + 1777)
#define SLIM_TKNAM_CSSSV_copy	(SLIM_TKNAM_BASE_CSSSV0 + 1777)
#define SLIM_TKLEN_CSSSV_copy	(4)
#define SLIM_TOKEN_CSSSV_copy	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_copy))
#define SLIM_TKOFF_CSSSV_ew_resize	(SLIM_TKOFF_BASE_CSSSV0 + 1782)
#define SLIM_TKNAM_CSSSV_ew_resize	(SLIM_TKNAM_BASE_CSSSV0 + 1782)
#define SLIM_TKLEN_CSSSV_ew_resize	(9)
#define SLIM_TOKEN_CSSSV_ew_resize	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_ew_resize))
#define SLIM_TKOFF_CSSSV_nesw_resize	(SLIM_TKOFF_BASE_CSSSV0 + 1792)
#define SLIM_TKNAM_CSSSV_nesw_resize	(SLIM_TKNAM_BASE_CSSSV0 + 1792)
#define SLIM_TKLEN_CSSSV_nesw_resize	(11)
#define SLIM_TOKEN_CSSSV_nesw_resize	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_nesw_resize))
#define SLIM_TKOFF_CSSSV_no_drop	(SLIM_TKOFF_BASE_CSSSV0 + 1804)
#define SLIM_TKNAM_CSSSV_no_drop	(SLIM_TKNAM_BASE_CSSSV0 + 1804)
#define SLIM_TKLEN_CSSSV_no_drop	(7)
#define SLIM_TOKEN_CSSSV_no_drop	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_no_drop))
#define SLIM_TKOFF_CSSSV_not_allowed	(SLIM_TKOFF_BASE_CSSSV0 + 1812)
#define SLIM_TKNAM_CSSSV_not_allowed	(SLIM_TKNAM_BASE_CSSSV0 + 1812)
#define SLIM_TKLEN_CSSSV_not_allowed	(11)
#define SLIM_TOKEN_CSSSV_not_allowed	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_not_allowed))
#define SLIM_TKOFF_CSSSV_ns_resize	(SLIM_TKOFF_BASE_CSSSV0 + 1824)
#define SLIM_TKNAM_CSSSV_ns_resize	(SLIM_TKNAM_BASE_CSSSV0 + 1824)
#define SLIM_TKLEN_CSSSV_ns_resize	(9)
#define SLIM_TOKEN_CSSSV_ns_resize	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_ns_resize))
#define SLIM_TKOFF_CSSSV_nwse_resize	(SLIM_TKOFF_BASE_CSSSV0 + 1834)
#define SLIM_TKNAM_CSSSV_nwse_resize	(SLIM_TKNAM_BASE_CSSSV0 + 1834)
#define SLIM_TKLEN_CSSSV_nwse_resize	(11)
#define SLIM_TOKEN_CSSSV_nwse_resize	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_nwse_resize))
#define SLIM_TKOFF_CSSSV_row_resize	(SLIM_TKOFF_BASE_CSSSV0 + 1846)
#define SLIM_TKNAM_CSSSV_row_resize	(SLIM_TKNAM_BASE_CSSSV0 + 1846)
#define SLIM_TKLEN_CSSSV_row_resize	(10)
#define SLIM_TOKEN_CSSSV_row_resize	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_row_resize))
#define SLIM_TKOFF_CSSSV_vertical_text	(SLIM_TKOFF_BASE_CSSSV0 + 1857)
#define SLIM_TKNAM_CSSSV_vertical_text	(SLIM_TKNAM_BASE_CSSSV0 + 1857)
#define SLIM_TKLEN_CSSSV_vertical_text	(13)
#define SLIM_TOKEN_CSSSV_vertical_text	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_vertical_text))
#define SLIM_TKOFF_CSSSV__wap_marquee	(SLIM_TKOFF_BASE_CSSSV0 + 1871)
#define SLIM_TKNAM_CSSSV__wap_marquee	(SLIM_TKNAM_BASE_CSSSV0 + 1871)
#define SLIM_TKLEN_CSSSV__wap_marquee	(12)
#define SLIM_TOKEN_CSSSV__wap_marquee	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV__wap_marquee))
#define SLIM_TKOFF_CSSSV_slide	(SLIM_TKOFF_BASE_CSSSV0 + 1884)
#define SLIM_TKNAM_CSSSV_slide	(SLIM_TKNAM_BASE_CSSSV0 + 1884)
#define SLIM_TKLEN_CSSSV_slide	(5)
#define SLIM_TOKEN_CSSSV_slide	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_slide))
#define SLIM_TKOFF_CSSSV_alternate	(SLIM_TKOFF_BASE_CSSSV0 + 1890)
#define SLIM_TKNAM_CSSSV_alternate	(SLIM_TKNAM_BASE_CSSSV0 + 1890)
#define SLIM_TKLEN_CSSSV_alternate	(9)
#define SLIM_TOKEN_CSSSV_alternate	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_alternate))
#define SLIM_TKOFF_CSSSV_infinite	(SLIM_TKOFF_BASE_CSSSV0 + 1900)
#define SLIM_TKNAM_CSSSV_infinite	(SLIM_TKNAM_BASE_CSSSV0 + 1900)
#define SLIM_TKLEN_CSSSV_infinite	(8)
#define SLIM_TOKEN_CSSSV_infinite	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_infinite))
#define SLIM_TKOFF_CSSSV_true	(SLIM_TKOFF_BASE_CSSSV0 + 1909)
#define SLIM_TKNAM_CSSSV_true	(SLIM_TKNAM_BASE_CSSSV0 + 1909)
#define SLIM_TKLEN_CSSSV_true	(4)
#define SLIM_TOKEN_CSSSV_true	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_true))
#define SLIM_TKOFF_CSSSV_false	(SLIM_TKOFF_BASE_CSSSV0 + 1914)
#define SLIM_TKNAM_CSSSV_false	(SLIM_TKNAM_BASE_CSSSV0 + 1914)
#define SLIM_TKLEN_CSSSV_false	(5)
#define SLIM_TOKEN_CSSSV_false	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_false))
#define SLIM_TKOFF_CSSSV_hand	(SLIM_TKOFF_BASE_CSSSV0 + 1920)
#define SLIM_TKNAM_CSSSV_hand	(SLIM_TKNAM_BASE_CSSSV0 + 1920)
#define SLIM_TKLEN_CSSSV_hand	(4)
#define SLIM_TOKEN_CSSSV_hand	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_hand))
#define SLIM_TKOFF_CSSSV_grab	(SLIM_TKOFF_BASE_CSSSV0 + 1925)
#define SLIM_TKNAM_CSSSV_grab	(SLIM_TKNAM_BASE_CSSSV0 + 1925)
#define SLIM_TKLEN_CSSSV_grab	(4)
#define SLIM_TOKEN_CSSSV_grab	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_grab))
#define SLIM_TKOFF_CSSSV_grabbing	(SLIM_TKOFF_BASE_CSSSV0 + 1930)
#define SLIM_TKNAM_CSSSV_grabbing	(SLIM_TKNAM_BASE_CSSSV0 + 1930)
#define SLIM_TKLEN_CSSSV_grabbing	(8)
#define SLIM_TOKEN_CSSSV_grabbing	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_grabbing))
#define SLIM_TKOFF_CSSSV_zoom_in	(SLIM_TKOFF_BASE_CSSSV0 + 1939)
#define SLIM_TKNAM_CSSSV_zoom_in	(SLIM_TKNAM_BASE_CSSSV0 + 1939)
#define SLIM_TKLEN_CSSSV_zoom_in	(7)
#define SLIM_TOKEN_CSSSV_zoom_in	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_zoom_in))
#define SLIM_TKOFF_CSSSV_zoom_out	(SLIM_TKOFF_BASE_CSSSV0 + 1947)
#define SLIM_TKNAM_CSSSV_zoom_out	(SLIM_TKNAM_BASE_CSSSV0 + 1947)
#define SLIM_TKLEN_CSSSV_zoom_out	(8)
#define SLIM_TOKEN_CSSSV_zoom_out	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_zoom_out))
#define SLIM_TKOFF_CSSSV_basic	(SLIM_TKOFF_BASE_CSSSV0 + 1956)
#define SLIM_TKNAM_CSSSV_basic	(SLIM_TKNAM_BASE_CSSSV0 + 1956)
#define SLIM_TKLEN_CSSSV_basic	(5)
#define SLIM_TOKEN_CSSSV_basic	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_basic))
#define SLIM_TKOFF_CSSSV_data_button	(SLIM_TKOFF_BASE_CSSSV0 + 1962)
#define SLIM_TKNAM_CSSSV_data_button	(SLIM_TKNAM_BASE_CSSSV0 + 1962)
#define SLIM_TKLEN_CSSSV_data_button	(11)
#define SLIM_TOKEN_CSSSV_data_button	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_data_button))
#define SLIM_TKOFF_CSSSV_numeric_tuning	(SLIM_TKOFF_BASE_CSSSV0 + 1974)
#define SLIM_TKNAM_CSSSV_numeric_tuning	(SLIM_TKNAM_BASE_CSSSV0 + 1974)
#define SLIM_TKLEN_CSSSV_numeric_tuning	(14)
#define SLIM_TOKEN_CSSSV_numeric_tuning	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_numeric_tuning))
#define SLIM_TKOFF_CSSSV_other_tuning	(SLIM_TKOFF_BASE_CSSSV0 + 1989)
#define SLIM_TKNAM_CSSSV_other_tuning	(SLIM_TKNAM_BASE_CSSSV0 + 1989)
#define SLIM_TKLEN_CSSSV_other_tuning	(12)
#define SLIM_TOKEN_CSSSV_other_tuning	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_other_tuning))
#define SLIM_TKOFF_CSSSV_special_1	(SLIM_TKOFF_BASE_CSSSV0 + 2002)
#define SLIM_TKNAM_CSSSV_special_1	(SLIM_TKNAM_BASE_CSSSV0 + 2002)
#define SLIM_TKLEN_CSSSV_special_1	(9)
#define SLIM_TOKEN_CSSSV_special_1	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_special_1))
#define SLIM_TKOFF_CSSSV_special_2	(SLIM_TKOFF_BASE_CSSSV0 + 2012)
#define SLIM_TKNAM_CSSSV_special_2	(SLIM_TKNAM_BASE_CSSSV0 + 2012)
#define SLIM_TKLEN_CSSSV_special_2	(9)
#define SLIM_TOKEN_CSSSV_special_2	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_special_2))
#define SLIM_TKOFF_CSSSV_special_3	(SLIM_TKOFF_BASE_CSSSV0 + 2022)
#define SLIM_TKNAM_CSSSV_special_3	(SLIM_TKNAM_BASE_CSSSV0 + 2022)
#define SLIM_TKLEN_CSSSV_special_3	(9)
#define SLIM_TOKEN_CSSSV_special_3	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_special_3))
#define SLIM_TKOFF_CSSSV_special_4	(SLIM_TKOFF_BASE_CSSSV0 + 2032)
#define SLIM_TKNAM_CSSSV_special_4	(SLIM_TKNAM_BASE_CSSSV0 + 2032)
#define SLIM_TKLEN_CSSSV_special_4	(9)
#define SLIM_TOKEN_CSSSV_special_4	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_special_4))
#define SLIM_TKOFF_CSSSV_misc	(SLIM_TKOFF_BASE_CSSSV0 + 2042)
#define SLIM_TKNAM_CSSSV_misc	(SLIM_TKNAM_BASE_CSSSV0 + 2042)
#define SLIM_TKLEN_CSSSV_misc	(4)
#define SLIM_TOKEN_CSSSV_misc	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_misc))
#define SLIM_TKOFF_CSSSV_240x160	(SLIM_TKOFF_BASE_CSSSV0 + 2047)
#define SLIM_TKNAM_CSSSV_240x160	(SLIM_TKNAM_BASE_CSSSV0 + 2047)
#define SLIM_TKLEN_CSSSV_240x160	(7)
#define SLIM_TOKEN_CSSSV_240x160	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_240x160))
#define SLIM_TKOFF_CSSSV_240x320	(SLIM_TKOFF_BASE_CSSSV0 + 2055)
#define SLIM_TKNAM_CSSSV_240x320	(SLIM_TKNAM_BASE_CSSSV0 + 2055)
#define SLIM_TKLEN_CSSSV_240x320	(7)
#define SLIM_TOKEN_CSSSV_240x320	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_240x320))
#define SLIM_TKOFF_CSSSV_240x480	(SLIM_TKOFF_BASE_CSSSV0 + 2063)
#define SLIM_TKNAM_CSSSV_240x480	(SLIM_TKNAM_BASE_CSSSV0 + 2063)
#define SLIM_TKLEN_CSSSV_240x480	(7)
#define SLIM_TOKEN_CSSSV_240x480	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_240x480))
#define SLIM_TKOFF_CSSSV_240x640	(SLIM_TKOFF_BASE_CSSSV0 + 2071)
#define SLIM_TKNAM_CSSSV_240x640	(SLIM_TKNAM_BASE_CSSSV0 + 2071)
#define SLIM_TKLEN_CSSSV_240x640	(7)
#define SLIM_TOKEN_CSSSV_240x640	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_240x640))
#define SLIM_TKOFF_CSSSV_240x800	(SLIM_TKOFF_BASE_CSSSV0 + 2079)
#define SLIM_TKNAM_CSSSV_240x800	(SLIM_TKNAM_BASE_CSSSV0 + 2079)
#define SLIM_TKLEN_CSSSV_240x800	(7)
#define SLIM_TOKEN_CSSSV_240x800	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_240x800))
#define SLIM_TKOFF_CSSSV_960x540	(SLIM_TKOFF_BASE_CSSSV0 + 2087)
#define SLIM_TKNAM_CSSSV_960x540	(SLIM_TKNAM_BASE_CSSSV0 + 2087)
#define SLIM_TKLEN_CSSSV_960x540	(7)
#define SLIM_TOKEN_CSSSV_960x540	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_960x540))
#define SLIM_TKOFF_CSSSV_720x480	(SLIM_TKOFF_BASE_CSSSV0 + 2095)
#define SLIM_TKNAM_CSSSV_720x480	(SLIM_TKNAM_BASE_CSSSV0 + 2095)
#define SLIM_TKLEN_CSSSV_720x480	(7)
#define SLIM_TOKEN_CSSSV_720x480	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_720x480))
#define SLIM_TKOFF_CSSSV_160x120	(SLIM_TKOFF_BASE_CSSSV0 + 2103)
#define SLIM_TKNAM_CSSSV_160x120	(SLIM_TKNAM_BASE_CSSSV0 + 2103)
#define SLIM_TKLEN_CSSSV_160x120	(7)
#define SLIM_TOKEN_CSSSV_160x120	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_160x120))
#define SLIM_TKOFF_CSSSV_160x240	(SLIM_TKOFF_BASE_CSSSV0 + 2111)
#define SLIM_TKNAM_CSSSV_160x240	(SLIM_TKNAM_BASE_CSSSV0 + 2111)
#define SLIM_TKLEN_CSSSV_160x240	(7)
#define SLIM_TOKEN_CSSSV_160x240	(CSSSymValInfo_GetItem(SLIM_TKID_CSSSV_160x240))
#define SLIM_TKOFF_BASE_CSSSV1	(SLIM_TKOFF_BASE_CSSSV0 + 2119)
#define SLIM_TKNAM_BASE_CSSSV1	(SLIM_TKNAM_BASE_CSSSV0 + SLIM_TKOFF_BASE_CSSSV1)
#define SLIM_TKLEN_TOTAL_CSSSV	SLIM_TKOFF_BASE_CSSSV1

extern SLIM_ROM slim_char cSlim_TokenName_CSSSV[SLIM_TKLEN_TOTAL_CSSSV];

extern SLIM_ROM TCSSSymValInfo cSlim_Token_CSSSV[SLIM_TOKEN_CSSSV_TOKENS];
#define CSSSymValInfo_GetItem(id)		((TCSSSymValInfo *)&cSlim_Token_CSSSV[(id)])
#define CSSSymValInfo_GetItemName(id)	((slim_char *)cSlim_TokenName_CSSSV + ((TToken *)&cSlim_Token_CSSSV[(id)])->fOffset)
#define CSSSymValInfo_GetItemNameLen(id)	(((TToken *)&cSlim_Token_CSSSV[(id)])->fLength)

TCSSSymValInfo *CSSSymValInfo_FindSS(slim_char *in_s, slim_int in_slen);

SLIM_END_C_LINKAGE
#endif
