/*
	dom0m.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_DOM0M_H
#define SLIM_TOKEN_DOM0M_H

#include <slim/basis/base.h>
#include <slim/basis/token.h>
#include <slim/private/token/dom0mid.h>

SLIM_BEGIN_C_LINKAGE

#include <slim/www/dom.h>

void TDOMModuleEntry_SetDOM0IFNameTable(TDOMModuleEntry *self);
void TDOMModuleEntry_SetDOM0MethodProcTable(TDOMModuleEntry *self);

struct TDOM0IFInfo_ {
    slim_int fNodeType;
    slim_int fBaseIFType;
    slim_int fChildren[1];
};
typedef struct TDOM0IFInfo_ TDOM0IFInfo;
extern SLIM_ROM TDOM0IFInfo gSlim_DOM0IFInfo[];
struct TDOM0MethodInfo_ {
    TToken fBase;	/* must be the first field */
    slim_int fArgs;
    slim_int fFlags[1];
};
typedef struct TDOM0MethodInfo_ TDOM0MethodInfo;
slim_bool TDOM0MethodAttrInfo_CheckIF(slim_int* in_flags, slim_int in_iftype);

#define SLIM_TKOFF_BASE_DOM0M0	(0)
#define SLIM_TKNAM_BASE_DOM0M0	((slim_char *)cSlim_TokenName_DOM0M)
#define SLIM_TKOFF_DOM0M_addEventListener	(SLIM_TKOFF_BASE_DOM0M0 + 0)
#define SLIM_TKNAM_DOM0M_addEventListener	(SLIM_TKNAM_BASE_DOM0M0 + 0)
#define SLIM_TKLEN_DOM0M_addEventListener	(16)
#define SLIM_TOKEN_DOM0M_addEventListener	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_addEventListener))
#define SLIM_TKOFF_DOM0M_alert	(SLIM_TKOFF_BASE_DOM0M0 + 17)
#define SLIM_TKNAM_DOM0M_alert	(SLIM_TKNAM_BASE_DOM0M0 + 17)
#define SLIM_TKLEN_DOM0M_alert	(5)
#define SLIM_TOKEN_DOM0M_alert	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_alert))
#define SLIM_TKOFF_DOM0M_assign	(SLIM_TKOFF_BASE_DOM0M0 + 23)
#define SLIM_TKNAM_DOM0M_assign	(SLIM_TKNAM_BASE_DOM0M0 + 23)
#define SLIM_TKLEN_DOM0M_assign	(6)
#define SLIM_TOKEN_DOM0M_assign	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_assign))
#define SLIM_TKOFF_DOM0M_attachEvent	(SLIM_TKOFF_BASE_DOM0M0 + 30)
#define SLIM_TKNAM_DOM0M_attachEvent	(SLIM_TKNAM_BASE_DOM0M0 + 30)
#define SLIM_TKLEN_DOM0M_attachEvent	(11)
#define SLIM_TOKEN_DOM0M_attachEvent	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_attachEvent))
#define SLIM_TKOFF_DOM0M_back	(SLIM_TKOFF_BASE_DOM0M0 + 42)
#define SLIM_TKNAM_DOM0M_back	(SLIM_TKNAM_BASE_DOM0M0 + 42)
#define SLIM_TKLEN_DOM0M_back	(4)
#define SLIM_TOKEN_DOM0M_back	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_back))
#define SLIM_TKOFF_DOM0M_blur	(SLIM_TKOFF_BASE_DOM0M0 + 47)
#define SLIM_TKNAM_DOM0M_blur	(SLIM_TKNAM_BASE_DOM0M0 + 47)
#define SLIM_TKLEN_DOM0M_blur	(4)
#define SLIM_TOKEN_DOM0M_blur	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_blur))
#define SLIM_TKOFF_DOM0M_captureEvents	(SLIM_TKOFF_BASE_DOM0M0 + 52)
#define SLIM_TKNAM_DOM0M_captureEvents	(SLIM_TKNAM_BASE_DOM0M0 + 52)
#define SLIM_TKLEN_DOM0M_captureEvents	(13)
#define SLIM_TOKEN_DOM0M_captureEvents	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_captureEvents))
#define SLIM_TKOFF_DOM0M_clearInterval	(SLIM_TKOFF_BASE_DOM0M0 + 66)
#define SLIM_TKNAM_DOM0M_clearInterval	(SLIM_TKNAM_BASE_DOM0M0 + 66)
#define SLIM_TKLEN_DOM0M_clearInterval	(13)
#define SLIM_TOKEN_DOM0M_clearInterval	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_clearInterval))
#define SLIM_TKOFF_DOM0M_clearTimeout	(SLIM_TKOFF_BASE_DOM0M0 + 80)
#define SLIM_TKNAM_DOM0M_clearTimeout	(SLIM_TKNAM_BASE_DOM0M0 + 80)
#define SLIM_TKLEN_DOM0M_clearTimeout	(12)
#define SLIM_TOKEN_DOM0M_clearTimeout	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_clearTimeout))
#define SLIM_TKOFF_DOM0M_close	(SLIM_TKOFF_BASE_DOM0M0 + 93)
#define SLIM_TKNAM_DOM0M_close	(SLIM_TKNAM_BASE_DOM0M0 + 93)
#define SLIM_TKLEN_DOM0M_close	(5)
#define SLIM_TOKEN_DOM0M_close	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_close))
#define SLIM_TKOFF_DOM0M_confirm	(SLIM_TKOFF_BASE_DOM0M0 + 99)
#define SLIM_TKNAM_DOM0M_confirm	(SLIM_TKNAM_BASE_DOM0M0 + 99)
#define SLIM_TKLEN_DOM0M_confirm	(7)
#define SLIM_TOKEN_DOM0M_confirm	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_confirm))
#define SLIM_TKOFF_DOM0M_detachEvent	(SLIM_TKOFF_BASE_DOM0M0 + 107)
#define SLIM_TKNAM_DOM0M_detachEvent	(SLIM_TKNAM_BASE_DOM0M0 + 107)
#define SLIM_TKLEN_DOM0M_detachEvent	(11)
#define SLIM_TOKEN_DOM0M_detachEvent	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_detachEvent))
#define SLIM_TKOFF_DOM0M_disableExternalCapture	(SLIM_TKOFF_BASE_DOM0M0 + 119)
#define SLIM_TKNAM_DOM0M_disableExternalCapture	(SLIM_TKNAM_BASE_DOM0M0 + 119)
#define SLIM_TKLEN_DOM0M_disableExternalCapture	(22)
#define SLIM_TOKEN_DOM0M_disableExternalCapture	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_disableExternalCapture))
#define SLIM_TKOFF_DOM0M_enableExternalCapture	(SLIM_TKOFF_BASE_DOM0M0 + 142)
#define SLIM_TKNAM_DOM0M_enableExternalCapture	(SLIM_TKNAM_BASE_DOM0M0 + 142)
#define SLIM_TKLEN_DOM0M_enableExternalCapture	(21)
#define SLIM_TOKEN_DOM0M_enableExternalCapture	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_enableExternalCapture))
#define SLIM_TKOFF_DOM0M_find	(SLIM_TKOFF_BASE_DOM0M0 + 164)
#define SLIM_TKNAM_DOM0M_find	(SLIM_TKNAM_BASE_DOM0M0 + 164)
#define SLIM_TKLEN_DOM0M_find	(4)
#define SLIM_TOKEN_DOM0M_find	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_find))
#define SLIM_TKOFF_DOM0M_focus	(SLIM_TKOFF_BASE_DOM0M0 + 169)
#define SLIM_TKNAM_DOM0M_focus	(SLIM_TKNAM_BASE_DOM0M0 + 169)
#define SLIM_TKLEN_DOM0M_focus	(5)
#define SLIM_TOKEN_DOM0M_focus	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_focus))
#define SLIM_TKOFF_DOM0M_forward	(SLIM_TKOFF_BASE_DOM0M0 + 175)
#define SLIM_TKNAM_DOM0M_forward	(SLIM_TKNAM_BASE_DOM0M0 + 175)
#define SLIM_TKLEN_DOM0M_forward	(7)
#define SLIM_TOKEN_DOM0M_forward	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_forward))
#define SLIM_TKOFF_DOM0M_genEnrollReq	(SLIM_TKOFF_BASE_DOM0M0 + 183)
#define SLIM_TKNAM_DOM0M_genEnrollReq	(SLIM_TKNAM_BASE_DOM0M0 + 183)
#define SLIM_TKLEN_DOM0M_genEnrollReq	(12)
#define SLIM_TOKEN_DOM0M_genEnrollReq	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_genEnrollReq))
#define SLIM_TKOFF_DOM0M_go	(SLIM_TKOFF_BASE_DOM0M0 + 196)
#define SLIM_TKNAM_DOM0M_go	(SLIM_TKNAM_BASE_DOM0M0 + 196)
#define SLIM_TKLEN_DOM0M_go	(2)
#define SLIM_TOKEN_DOM0M_go	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_go))
#define SLIM_TKOFF_DOM0M_handleEvent	(SLIM_TKOFF_BASE_DOM0M0 + 199)
#define SLIM_TKNAM_DOM0M_handleEvent	(SLIM_TKNAM_BASE_DOM0M0 + 199)
#define SLIM_TKLEN_DOM0M_handleEvent	(11)
#define SLIM_TOKEN_DOM0M_handleEvent	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_handleEvent))
#define SLIM_TKOFF_DOM0M_home	(SLIM_TKOFF_BASE_DOM0M0 + 211)
#define SLIM_TKNAM_DOM0M_home	(SLIM_TKNAM_BASE_DOM0M0 + 211)
#define SLIM_TKLEN_DOM0M_home	(4)
#define SLIM_TOKEN_DOM0M_home	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_home))
#define SLIM_TKOFF_DOM0M_javaEnabled	(SLIM_TKOFF_BASE_DOM0M0 + 216)
#define SLIM_TKNAM_DOM0M_javaEnabled	(SLIM_TKNAM_BASE_DOM0M0 + 216)
#define SLIM_TKLEN_DOM0M_javaEnabled	(11)
#define SLIM_TOKEN_DOM0M_javaEnabled	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_javaEnabled))
#define SLIM_TKOFF_DOM0M_keyGen	(SLIM_TKOFF_BASE_DOM0M0 + 228)
#define SLIM_TKNAM_DOM0M_keyGen	(SLIM_TKNAM_BASE_DOM0M0 + 228)
#define SLIM_TKLEN_DOM0M_keyGen	(6)
#define SLIM_TOKEN_DOM0M_keyGen	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_keyGen))
#define SLIM_TKOFF_DOM0M_moveBy	(SLIM_TKOFF_BASE_DOM0M0 + 235)
#define SLIM_TKNAM_DOM0M_moveBy	(SLIM_TKNAM_BASE_DOM0M0 + 235)
#define SLIM_TKLEN_DOM0M_moveBy	(6)
#define SLIM_TOKEN_DOM0M_moveBy	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_moveBy))
#define SLIM_TKOFF_DOM0M_moveTo	(SLIM_TKOFF_BASE_DOM0M0 + 242)
#define SLIM_TKNAM_DOM0M_moveTo	(SLIM_TKNAM_BASE_DOM0M0 + 242)
#define SLIM_TKLEN_DOM0M_moveTo	(6)
#define SLIM_TOKEN_DOM0M_moveTo	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_moveTo))
#define SLIM_TKOFF_DOM0M_open	(SLIM_TKOFF_BASE_DOM0M0 + 249)
#define SLIM_TKNAM_DOM0M_open	(SLIM_TKNAM_BASE_DOM0M0 + 249)
#define SLIM_TKLEN_DOM0M_open	(4)
#define SLIM_TOKEN_DOM0M_open	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_open))
#define SLIM_TKOFF_DOM0M_parseFromString	(SLIM_TKOFF_BASE_DOM0M0 + 254)
#define SLIM_TKNAM_DOM0M_parseFromString	(SLIM_TKNAM_BASE_DOM0M0 + 254)
#define SLIM_TKLEN_DOM0M_parseFromString	(15)
#define SLIM_TOKEN_DOM0M_parseFromString	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_parseFromString))
#define SLIM_TKOFF_DOM0M_preference	(SLIM_TKOFF_BASE_DOM0M0 + 270)
#define SLIM_TKNAM_DOM0M_preference	(SLIM_TKNAM_BASE_DOM0M0 + 270)
#define SLIM_TKLEN_DOM0M_preference	(10)
#define SLIM_TOKEN_DOM0M_preference	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_preference))
#define SLIM_TKOFF_DOM0M_print	(SLIM_TKOFF_BASE_DOM0M0 + 281)
#define SLIM_TKNAM_DOM0M_print	(SLIM_TKNAM_BASE_DOM0M0 + 281)
#define SLIM_TKLEN_DOM0M_print	(5)
#define SLIM_TOKEN_DOM0M_print	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_print))
#define SLIM_TKOFF_DOM0M_prompt	(SLIM_TKOFF_BASE_DOM0M0 + 287)
#define SLIM_TKNAM_DOM0M_prompt	(SLIM_TKNAM_BASE_DOM0M0 + 287)
#define SLIM_TKLEN_DOM0M_prompt	(6)
#define SLIM_TOKEN_DOM0M_prompt	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_prompt))
#define SLIM_TKOFF_DOM0M_random	(SLIM_TKOFF_BASE_DOM0M0 + 294)
#define SLIM_TKNAM_DOM0M_random	(SLIM_TKNAM_BASE_DOM0M0 + 294)
#define SLIM_TKLEN_DOM0M_random	(6)
#define SLIM_TOKEN_DOM0M_random	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_random))
#define SLIM_TKOFF_DOM0M_refresh	(SLIM_TKOFF_BASE_DOM0M0 + 301)
#define SLIM_TKNAM_DOM0M_refresh	(SLIM_TKNAM_BASE_DOM0M0 + 301)
#define SLIM_TKLEN_DOM0M_refresh	(7)
#define SLIM_TOKEN_DOM0M_refresh	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_refresh))
#define SLIM_TKOFF_DOM0M_releaseEvent	(SLIM_TKOFF_BASE_DOM0M0 + 309)
#define SLIM_TKNAM_DOM0M_releaseEvent	(SLIM_TKNAM_BASE_DOM0M0 + 309)
#define SLIM_TKLEN_DOM0M_releaseEvent	(12)
#define SLIM_TOKEN_DOM0M_releaseEvent	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_releaseEvent))
#define SLIM_TKOFF_DOM0M_reload	(SLIM_TKOFF_BASE_DOM0M0 + 322)
#define SLIM_TKNAM_DOM0M_reload	(SLIM_TKNAM_BASE_DOM0M0 + 322)
#define SLIM_TKLEN_DOM0M_reload	(6)
#define SLIM_TOKEN_DOM0M_reload	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_reload))
#define SLIM_TKOFF_DOM0M_removeEventListener	(SLIM_TKOFF_BASE_DOM0M0 + 329)
#define SLIM_TKNAM_DOM0M_removeEventListener	(SLIM_TKNAM_BASE_DOM0M0 + 329)
#define SLIM_TKLEN_DOM0M_removeEventListener	(19)
#define SLIM_TOKEN_DOM0M_removeEventListener	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_removeEventListener))
#define SLIM_TKOFF_DOM0M_replace	(SLIM_TKOFF_BASE_DOM0M0 + 349)
#define SLIM_TKNAM_DOM0M_replace	(SLIM_TKNAM_BASE_DOM0M0 + 349)
#define SLIM_TKLEN_DOM0M_replace	(7)
#define SLIM_TOKEN_DOM0M_replace	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_replace))
#define SLIM_TKOFF_DOM0M_resizeBy	(SLIM_TKOFF_BASE_DOM0M0 + 357)
#define SLIM_TKNAM_DOM0M_resizeBy	(SLIM_TKNAM_BASE_DOM0M0 + 357)
#define SLIM_TKLEN_DOM0M_resizeBy	(8)
#define SLIM_TOKEN_DOM0M_resizeBy	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_resizeBy))
#define SLIM_TKOFF_DOM0M_resizeTo	(SLIM_TKOFF_BASE_DOM0M0 + 366)
#define SLIM_TKNAM_DOM0M_resizeTo	(SLIM_TKNAM_BASE_DOM0M0 + 366)
#define SLIM_TKLEN_DOM0M_resizeTo	(8)
#define SLIM_TOKEN_DOM0M_resizeTo	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_resizeTo))
#define SLIM_TKOFF_DOM0M_routeEvent	(SLIM_TKOFF_BASE_DOM0M0 + 375)
#define SLIM_TKNAM_DOM0M_routeEvent	(SLIM_TKNAM_BASE_DOM0M0 + 375)
#define SLIM_TKLEN_DOM0M_routeEvent	(10)
#define SLIM_TOKEN_DOM0M_routeEvent	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_routeEvent))
#define SLIM_TKOFF_DOM0M_savePreferences	(SLIM_TKOFF_BASE_DOM0M0 + 386)
#define SLIM_TKNAM_DOM0M_savePreferences	(SLIM_TKNAM_BASE_DOM0M0 + 386)
#define SLIM_TKLEN_DOM0M_savePreferences	(15)
#define SLIM_TOKEN_DOM0M_savePreferences	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_savePreferences))
#define SLIM_TKOFF_DOM0M_scroll	(SLIM_TKOFF_BASE_DOM0M0 + 402)
#define SLIM_TKNAM_DOM0M_scroll	(SLIM_TKNAM_BASE_DOM0M0 + 402)
#define SLIM_TKLEN_DOM0M_scroll	(6)
#define SLIM_TOKEN_DOM0M_scroll	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_scroll))
#define SLIM_TKOFF_DOM0M_scrollBy	(SLIM_TKOFF_BASE_DOM0M0 + 409)
#define SLIM_TKNAM_DOM0M_scrollBy	(SLIM_TKNAM_BASE_DOM0M0 + 409)
#define SLIM_TKLEN_DOM0M_scrollBy	(8)
#define SLIM_TOKEN_DOM0M_scrollBy	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_scrollBy))
#define SLIM_TKOFF_DOM0M_scrollTo	(SLIM_TKOFF_BASE_DOM0M0 + 418)
#define SLIM_TKNAM_DOM0M_scrollTo	(SLIM_TKNAM_BASE_DOM0M0 + 418)
#define SLIM_TKLEN_DOM0M_scrollTo	(8)
#define SLIM_TOKEN_DOM0M_scrollTo	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_scrollTo))
#define SLIM_TKOFF_DOM0M_serializeToString	(SLIM_TKOFF_BASE_DOM0M0 + 427)
#define SLIM_TKNAM_DOM0M_serializeToString	(SLIM_TKNAM_BASE_DOM0M0 + 427)
#define SLIM_TKLEN_DOM0M_serializeToString	(17)
#define SLIM_TOKEN_DOM0M_serializeToString	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_serializeToString))
#define SLIM_TKOFF_DOM0M_setInterval	(SLIM_TKOFF_BASE_DOM0M0 + 445)
#define SLIM_TKNAM_DOM0M_setInterval	(SLIM_TKNAM_BASE_DOM0M0 + 445)
#define SLIM_TKLEN_DOM0M_setInterval	(11)
#define SLIM_TOKEN_DOM0M_setInterval	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_setInterval))
#define SLIM_TKOFF_DOM0M_setTimeout	(SLIM_TKOFF_BASE_DOM0M0 + 457)
#define SLIM_TKNAM_DOM0M_setTimeout	(SLIM_TKNAM_BASE_DOM0M0 + 457)
#define SLIM_TKLEN_DOM0M_setTimeout	(10)
#define SLIM_TOKEN_DOM0M_setTimeout	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_setTimeout))
#define SLIM_TKOFF_DOM0M_signText	(SLIM_TKOFF_BASE_DOM0M0 + 468)
#define SLIM_TKNAM_DOM0M_signText	(SLIM_TKNAM_BASE_DOM0M0 + 468)
#define SLIM_TKLEN_DOM0M_signText	(8)
#define SLIM_TOKEN_DOM0M_signText	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_signText))
#define SLIM_TKOFF_DOM0M_stop	(SLIM_TKOFF_BASE_DOM0M0 + 477)
#define SLIM_TKNAM_DOM0M_stop	(SLIM_TKNAM_BASE_DOM0M0 + 477)
#define SLIM_TKLEN_DOM0M_stop	(4)
#define SLIM_TOKEN_DOM0M_stop	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_stop))
#define SLIM_TKOFF_DOM0M_taintEnabled	(SLIM_TKOFF_BASE_DOM0M0 + 482)
#define SLIM_TKNAM_DOM0M_taintEnabled	(SLIM_TKNAM_BASE_DOM0M0 + 482)
#define SLIM_TKLEN_DOM0M_taintEnabled	(12)
#define SLIM_TOKEN_DOM0M_taintEnabled	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_taintEnabled))
#define SLIM_TKOFF_DOM0M_toString	(SLIM_TKOFF_BASE_DOM0M0 + 495)
#define SLIM_TKNAM_DOM0M_toString	(SLIM_TKNAM_BASE_DOM0M0 + 495)
#define SLIM_TKLEN_DOM0M_toString	(8)
#define SLIM_TOKEN_DOM0M_toString	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_toString))
#define SLIM_TKOFF_DOM0M_valueOf	(SLIM_TKOFF_BASE_DOM0M0 + 504)
#define SLIM_TKNAM_DOM0M_valueOf	(SLIM_TKNAM_BASE_DOM0M0 + 504)
#define SLIM_TKLEN_DOM0M_valueOf	(7)
#define SLIM_TOKEN_DOM0M_valueOf	(DOM0MethodInfo_GetItem(SLIM_TKID_DOM0M_valueOf))
#define SLIM_TKOFF_BASE_DOM0M1	(SLIM_TKOFF_BASE_DOM0M0 + 512)
#define SLIM_TKNAM_BASE_DOM0M1	(SLIM_TKNAM_BASE_DOM0M0 + SLIM_TKOFF_BASE_DOM0M1)
#define SLIM_TKLEN_TOTAL_DOM0M	SLIM_TKOFF_BASE_DOM0M1

extern SLIM_ROM slim_char cSlim_TokenName_DOM0M[SLIM_TKLEN_TOTAL_DOM0M];

extern SLIM_ROM TDOM0MethodInfo cSlim_Token_DOM0M[SLIM_TOKEN_DOM0M_TOKENS];
#define DOM0MethodInfo_GetItem(id)		((TDOM0MethodInfo *)&cSlim_Token_DOM0M[(id)])
#define DOM0MethodInfo_GetItemName(id)	((slim_char *)cSlim_TokenName_DOM0M + ((TToken *)&cSlim_Token_DOM0M[(id)])->fOffset)
#define DOM0MethodInfo_GetItemNameLen(id)	(((TToken *)&cSlim_Token_DOM0M[(id)])->fLength)

TDOM0MethodInfo *DOM0MethodInfo_CaseFindSS(slim_char *in_s, slim_int in_slen);

SLIM_END_C_LINKAGE
#endif
