/*
	dom1m.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_DOM1M_H
#define SLIM_TOKEN_DOM1M_H

#include <slim/basis/base.h>
#include <slim/basis/token.h>
#include <slim/private/token/dom1mid.h>

SLIM_BEGIN_C_LINKAGE

#include <slim/www/dom.h>

void TDOMModuleEntry_SetDOM1IFNameTable(TDOMModuleEntry *self);
void TDOMModuleEntry_SetDOM1MethodProcTable(TDOMModuleEntry *self);

struct TDOM1IFInfo_ {
    slim_int fNodeType;
    slim_int fBaseIFType;
    slim_int fChildren[3];
};
typedef struct TDOM1IFInfo_ TDOM1IFInfo;
extern SLIM_ROM TDOM1IFInfo gSlim_DOM1IFInfo[];
struct TDOM1MethodInfo_ {
    TToken fBase;	/* must be the first field */
    slim_int fArgs;
    slim_int fFlags[3];
};
typedef struct TDOM1MethodInfo_ TDOM1MethodInfo;
slim_bool TDOM1MethodAttrInfo_CheckIF(slim_int* in_flags, slim_int in_iftype);

#define SLIM_TKOFF_BASE_DOM1M0	(0)
#define SLIM_TKNAM_BASE_DOM1M0	((slim_char *)cSlim_TokenName_DOM1M)
#define SLIM_TKOFF_DOM1M_add	(SLIM_TKOFF_BASE_DOM1M0 + 0)
#define SLIM_TKNAM_DOM1M_add	(SLIM_TKNAM_BASE_DOM1M0 + 0)
#define SLIM_TKLEN_DOM1M_add	(3)
#define SLIM_TOKEN_DOM1M_add	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_add))
#define SLIM_TKOFF_DOM1M_addEventListener	(SLIM_TKOFF_BASE_DOM1M0 + 4)
#define SLIM_TKNAM_DOM1M_addEventListener	(SLIM_TKNAM_BASE_DOM1M0 + 4)
#define SLIM_TKLEN_DOM1M_addEventListener	(16)
#define SLIM_TOKEN_DOM1M_addEventListener	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_addEventListener))
#define SLIM_TKOFF_DOM1M_appendChild	(SLIM_TKOFF_BASE_DOM1M0 + 21)
#define SLIM_TKNAM_DOM1M_appendChild	(SLIM_TKNAM_BASE_DOM1M0 + 21)
#define SLIM_TKLEN_DOM1M_appendChild	(11)
#define SLIM_TOKEN_DOM1M_appendChild	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_appendChild))
#define SLIM_TKOFF_DOM1M_appendData	(SLIM_TKOFF_BASE_DOM1M0 + 33)
#define SLIM_TKNAM_DOM1M_appendData	(SLIM_TKNAM_BASE_DOM1M0 + 33)
#define SLIM_TKLEN_DOM1M_appendData	(10)
#define SLIM_TOKEN_DOM1M_appendData	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_appendData))
#define SLIM_TKOFF_DOM1M_attachEvent	(SLIM_TKOFF_BASE_DOM1M0 + 44)
#define SLIM_TKNAM_DOM1M_attachEvent	(SLIM_TKNAM_BASE_DOM1M0 + 44)
#define SLIM_TKLEN_DOM1M_attachEvent	(11)
#define SLIM_TOKEN_DOM1M_attachEvent	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_attachEvent))
#define SLIM_TKOFF_DOM1M_blur	(SLIM_TKOFF_BASE_DOM1M0 + 56)
#define SLIM_TKNAM_DOM1M_blur	(SLIM_TKNAM_BASE_DOM1M0 + 56)
#define SLIM_TKLEN_DOM1M_blur	(4)
#define SLIM_TOKEN_DOM1M_blur	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_blur))
#define SLIM_TKOFF_DOM1M_clear	(SLIM_TKOFF_BASE_DOM1M0 + 61)
#define SLIM_TKNAM_DOM1M_clear	(SLIM_TKNAM_BASE_DOM1M0 + 61)
#define SLIM_TKLEN_DOM1M_clear	(5)
#define SLIM_TOKEN_DOM1M_clear	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_clear))
#define SLIM_TKOFF_DOM1M_click	(SLIM_TKOFF_BASE_DOM1M0 + 67)
#define SLIM_TKNAM_DOM1M_click	(SLIM_TKNAM_BASE_DOM1M0 + 67)
#define SLIM_TKLEN_DOM1M_click	(5)
#define SLIM_TOKEN_DOM1M_click	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_click))
#define SLIM_TKOFF_DOM1M_cloneNode	(SLIM_TKOFF_BASE_DOM1M0 + 73)
#define SLIM_TKNAM_DOM1M_cloneNode	(SLIM_TKNAM_BASE_DOM1M0 + 73)
#define SLIM_TKLEN_DOM1M_cloneNode	(9)
#define SLIM_TOKEN_DOM1M_cloneNode	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_cloneNode))
#define SLIM_TKOFF_DOM1M_close	(SLIM_TKOFF_BASE_DOM1M0 + 83)
#define SLIM_TKNAM_DOM1M_close	(SLIM_TKNAM_BASE_DOM1M0 + 83)
#define SLIM_TKLEN_DOM1M_close	(5)
#define SLIM_TOKEN_DOM1M_close	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_close))
#define SLIM_TKOFF_DOM1M_contains	(SLIM_TKOFF_BASE_DOM1M0 + 89)
#define SLIM_TKNAM_DOM1M_contains	(SLIM_TKNAM_BASE_DOM1M0 + 89)
#define SLIM_TKLEN_DOM1M_contains	(8)
#define SLIM_TOKEN_DOM1M_contains	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_contains))
#define SLIM_TKOFF_DOM1M_createAttribute	(SLIM_TKOFF_BASE_DOM1M0 + 98)
#define SLIM_TKNAM_DOM1M_createAttribute	(SLIM_TKNAM_BASE_DOM1M0 + 98)
#define SLIM_TKLEN_DOM1M_createAttribute	(15)
#define SLIM_TOKEN_DOM1M_createAttribute	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createAttribute))
#define SLIM_TKOFF_DOM1M_createAttributeNS	(SLIM_TKOFF_BASE_DOM1M0 + 114)
#define SLIM_TKNAM_DOM1M_createAttributeNS	(SLIM_TKNAM_BASE_DOM1M0 + 114)
#define SLIM_TKLEN_DOM1M_createAttributeNS	(17)
#define SLIM_TOKEN_DOM1M_createAttributeNS	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createAttributeNS))
#define SLIM_TKOFF_DOM1M_createCDATASection	(SLIM_TKOFF_BASE_DOM1M0 + 132)
#define SLIM_TKNAM_DOM1M_createCDATASection	(SLIM_TKNAM_BASE_DOM1M0 + 132)
#define SLIM_TKLEN_DOM1M_createCDATASection	(18)
#define SLIM_TOKEN_DOM1M_createCDATASection	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createCDATASection))
#define SLIM_TKOFF_DOM1M_createCaption	(SLIM_TKOFF_BASE_DOM1M0 + 151)
#define SLIM_TKNAM_DOM1M_createCaption	(SLIM_TKNAM_BASE_DOM1M0 + 151)
#define SLIM_TKLEN_DOM1M_createCaption	(13)
#define SLIM_TOKEN_DOM1M_createCaption	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createCaption))
#define SLIM_TKOFF_DOM1M_createComment	(SLIM_TKOFF_BASE_DOM1M0 + 165)
#define SLIM_TKNAM_DOM1M_createComment	(SLIM_TKNAM_BASE_DOM1M0 + 165)
#define SLIM_TKLEN_DOM1M_createComment	(13)
#define SLIM_TOKEN_DOM1M_createComment	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createComment))
#define SLIM_TKOFF_DOM1M_createDocument	(SLIM_TKOFF_BASE_DOM1M0 + 179)
#define SLIM_TKNAM_DOM1M_createDocument	(SLIM_TKNAM_BASE_DOM1M0 + 179)
#define SLIM_TKLEN_DOM1M_createDocument	(14)
#define SLIM_TOKEN_DOM1M_createDocument	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createDocument))
#define SLIM_TKOFF_DOM1M_createDocumentFragment	(SLIM_TKOFF_BASE_DOM1M0 + 194)
#define SLIM_TKNAM_DOM1M_createDocumentFragment	(SLIM_TKNAM_BASE_DOM1M0 + 194)
#define SLIM_TKLEN_DOM1M_createDocumentFragment	(22)
#define SLIM_TOKEN_DOM1M_createDocumentFragment	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createDocumentFragment))
#define SLIM_TKOFF_DOM1M_createDocumentType	(SLIM_TKOFF_BASE_DOM1M0 + 217)
#define SLIM_TKNAM_DOM1M_createDocumentType	(SLIM_TKNAM_BASE_DOM1M0 + 217)
#define SLIM_TKLEN_DOM1M_createDocumentType	(18)
#define SLIM_TOKEN_DOM1M_createDocumentType	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createDocumentType))
#define SLIM_TKOFF_DOM1M_createElement	(SLIM_TKOFF_BASE_DOM1M0 + 236)
#define SLIM_TKNAM_DOM1M_createElement	(SLIM_TKNAM_BASE_DOM1M0 + 236)
#define SLIM_TKLEN_DOM1M_createElement	(13)
#define SLIM_TOKEN_DOM1M_createElement	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createElement))
#define SLIM_TKOFF_DOM1M_createElementNS	(SLIM_TKOFF_BASE_DOM1M0 + 250)
#define SLIM_TKNAM_DOM1M_createElementNS	(SLIM_TKNAM_BASE_DOM1M0 + 250)
#define SLIM_TKLEN_DOM1M_createElementNS	(15)
#define SLIM_TOKEN_DOM1M_createElementNS	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createElementNS))
#define SLIM_TKOFF_DOM1M_createEntityReference	(SLIM_TKOFF_BASE_DOM1M0 + 266)
#define SLIM_TKNAM_DOM1M_createEntityReference	(SLIM_TKNAM_BASE_DOM1M0 + 266)
#define SLIM_TKLEN_DOM1M_createEntityReference	(21)
#define SLIM_TOKEN_DOM1M_createEntityReference	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createEntityReference))
#define SLIM_TKOFF_DOM1M_createEvent	(SLIM_TKOFF_BASE_DOM1M0 + 288)
#define SLIM_TKNAM_DOM1M_createEvent	(SLIM_TKNAM_BASE_DOM1M0 + 288)
#define SLIM_TKLEN_DOM1M_createEvent	(11)
#define SLIM_TOKEN_DOM1M_createEvent	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createEvent))
#define SLIM_TKOFF_DOM1M_createProcessingInstruction	(SLIM_TKOFF_BASE_DOM1M0 + 300)
#define SLIM_TKNAM_DOM1M_createProcessingInstruction	(SLIM_TKNAM_BASE_DOM1M0 + 300)
#define SLIM_TKLEN_DOM1M_createProcessingInstruction	(27)
#define SLIM_TOKEN_DOM1M_createProcessingInstruction	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createProcessingInstruction))
#define SLIM_TKOFF_DOM1M_createTFoot	(SLIM_TKOFF_BASE_DOM1M0 + 328)
#define SLIM_TKNAM_DOM1M_createTFoot	(SLIM_TKNAM_BASE_DOM1M0 + 328)
#define SLIM_TKLEN_DOM1M_createTFoot	(11)
#define SLIM_TOKEN_DOM1M_createTFoot	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createTFoot))
#define SLIM_TKOFF_DOM1M_createTHead	(SLIM_TKOFF_BASE_DOM1M0 + 340)
#define SLIM_TKNAM_DOM1M_createTHead	(SLIM_TKNAM_BASE_DOM1M0 + 340)
#define SLIM_TKLEN_DOM1M_createTHead	(11)
#define SLIM_TOKEN_DOM1M_createTHead	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createTHead))
#define SLIM_TKOFF_DOM1M_createTextNode	(SLIM_TKOFF_BASE_DOM1M0 + 352)
#define SLIM_TKNAM_DOM1M_createTextNode	(SLIM_TKNAM_BASE_DOM1M0 + 352)
#define SLIM_TKLEN_DOM1M_createTextNode	(14)
#define SLIM_TOKEN_DOM1M_createTextNode	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_createTextNode))
#define SLIM_TKOFF_DOM1M_deleteCaption	(SLIM_TKOFF_BASE_DOM1M0 + 367)
#define SLIM_TKNAM_DOM1M_deleteCaption	(SLIM_TKNAM_BASE_DOM1M0 + 367)
#define SLIM_TKLEN_DOM1M_deleteCaption	(13)
#define SLIM_TOKEN_DOM1M_deleteCaption	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_deleteCaption))
#define SLIM_TKOFF_DOM1M_deleteCell	(SLIM_TKOFF_BASE_DOM1M0 + 381)
#define SLIM_TKNAM_DOM1M_deleteCell	(SLIM_TKNAM_BASE_DOM1M0 + 381)
#define SLIM_TKLEN_DOM1M_deleteCell	(10)
#define SLIM_TOKEN_DOM1M_deleteCell	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_deleteCell))
#define SLIM_TKOFF_DOM1M_deleteData	(SLIM_TKOFF_BASE_DOM1M0 + 392)
#define SLIM_TKNAM_DOM1M_deleteData	(SLIM_TKNAM_BASE_DOM1M0 + 392)
#define SLIM_TKLEN_DOM1M_deleteData	(10)
#define SLIM_TOKEN_DOM1M_deleteData	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_deleteData))
#define SLIM_TKOFF_DOM1M_deleteRow	(SLIM_TKOFF_BASE_DOM1M0 + 403)
#define SLIM_TKNAM_DOM1M_deleteRow	(SLIM_TKNAM_BASE_DOM1M0 + 403)
#define SLIM_TKLEN_DOM1M_deleteRow	(9)
#define SLIM_TOKEN_DOM1M_deleteRow	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_deleteRow))
#define SLIM_TKOFF_DOM1M_deleteTFoot	(SLIM_TKOFF_BASE_DOM1M0 + 413)
#define SLIM_TKNAM_DOM1M_deleteTFoot	(SLIM_TKNAM_BASE_DOM1M0 + 413)
#define SLIM_TKLEN_DOM1M_deleteTFoot	(11)
#define SLIM_TOKEN_DOM1M_deleteTFoot	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_deleteTFoot))
#define SLIM_TKOFF_DOM1M_deleteTHead	(SLIM_TKOFF_BASE_DOM1M0 + 425)
#define SLIM_TKNAM_DOM1M_deleteTHead	(SLIM_TKNAM_BASE_DOM1M0 + 425)
#define SLIM_TKLEN_DOM1M_deleteTHead	(11)
#define SLIM_TOKEN_DOM1M_deleteTHead	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_deleteTHead))
#define SLIM_TKOFF_DOM1M_detachEvent	(SLIM_TKOFF_BASE_DOM1M0 + 437)
#define SLIM_TKNAM_DOM1M_detachEvent	(SLIM_TKNAM_BASE_DOM1M0 + 437)
#define SLIM_TKLEN_DOM1M_detachEvent	(11)
#define SLIM_TOKEN_DOM1M_detachEvent	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_detachEvent))
#define SLIM_TKOFF_DOM1M_dispatchEvent	(SLIM_TKOFF_BASE_DOM1M0 + 449)
#define SLIM_TKNAM_DOM1M_dispatchEvent	(SLIM_TKNAM_BASE_DOM1M0 + 449)
#define SLIM_TKLEN_DOM1M_dispatchEvent	(13)
#define SLIM_TOKEN_DOM1M_dispatchEvent	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_dispatchEvent))
#define SLIM_TKOFF_DOM1M_focus	(SLIM_TKOFF_BASE_DOM1M0 + 463)
#define SLIM_TKNAM_DOM1M_focus	(SLIM_TKNAM_BASE_DOM1M0 + 463)
#define SLIM_TKLEN_DOM1M_focus	(5)
#define SLIM_TOKEN_DOM1M_focus	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_focus))
#define SLIM_TKOFF_DOM1M_getAdjacentText	(SLIM_TKOFF_BASE_DOM1M0 + 469)
#define SLIM_TKNAM_DOM1M_getAdjacentText	(SLIM_TKNAM_BASE_DOM1M0 + 469)
#define SLIM_TKLEN_DOM1M_getAdjacentText	(15)
#define SLIM_TOKEN_DOM1M_getAdjacentText	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_getAdjacentText))
#define SLIM_TKOFF_DOM1M_getAttribute	(SLIM_TKOFF_BASE_DOM1M0 + 485)
#define SLIM_TKNAM_DOM1M_getAttribute	(SLIM_TKNAM_BASE_DOM1M0 + 485)
#define SLIM_TKLEN_DOM1M_getAttribute	(12)
#define SLIM_TOKEN_DOM1M_getAttribute	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_getAttribute))
#define SLIM_TKOFF_DOM1M_getAttributeNS	(SLIM_TKOFF_BASE_DOM1M0 + 498)
#define SLIM_TKNAM_DOM1M_getAttributeNS	(SLIM_TKNAM_BASE_DOM1M0 + 498)
#define SLIM_TKLEN_DOM1M_getAttributeNS	(14)
#define SLIM_TOKEN_DOM1M_getAttributeNS	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_getAttributeNS))
#define SLIM_TKOFF_DOM1M_getAttributeNode	(SLIM_TKOFF_BASE_DOM1M0 + 513)
#define SLIM_TKNAM_DOM1M_getAttributeNode	(SLIM_TKNAM_BASE_DOM1M0 + 513)
#define SLIM_TKLEN_DOM1M_getAttributeNode	(16)
#define SLIM_TOKEN_DOM1M_getAttributeNode	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_getAttributeNode))
#define SLIM_TKOFF_DOM1M_getAttributeNodeNS	(SLIM_TKOFF_BASE_DOM1M0 + 530)
#define SLIM_TKNAM_DOM1M_getAttributeNodeNS	(SLIM_TKNAM_BASE_DOM1M0 + 530)
#define SLIM_TKLEN_DOM1M_getAttributeNodeNS	(18)
#define SLIM_TOKEN_DOM1M_getAttributeNodeNS	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_getAttributeNodeNS))
#define SLIM_TKOFF_DOM1M_getBoxObjectFor	(SLIM_TKOFF_BASE_DOM1M0 + 549)
#define SLIM_TKNAM_DOM1M_getBoxObjectFor	(SLIM_TKNAM_BASE_DOM1M0 + 549)
#define SLIM_TKLEN_DOM1M_getBoxObjectFor	(15)
#define SLIM_TOKEN_DOM1M_getBoxObjectFor	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_getBoxObjectFor))
#define SLIM_TKOFF_DOM1M_getElementById	(SLIM_TKOFF_BASE_DOM1M0 + 565)
#define SLIM_TKNAM_DOM1M_getElementById	(SLIM_TKNAM_BASE_DOM1M0 + 565)
#define SLIM_TKLEN_DOM1M_getElementById	(14)
#define SLIM_TOKEN_DOM1M_getElementById	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_getElementById))
#define SLIM_TKOFF_DOM1M_getElementsByName	(SLIM_TKOFF_BASE_DOM1M0 + 580)
#define SLIM_TKNAM_DOM1M_getElementsByName	(SLIM_TKNAM_BASE_DOM1M0 + 580)
#define SLIM_TKLEN_DOM1M_getElementsByName	(17)
#define SLIM_TOKEN_DOM1M_getElementsByName	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_getElementsByName))
#define SLIM_TKOFF_DOM1M_getElementsByTagName	(SLIM_TKOFF_BASE_DOM1M0 + 598)
#define SLIM_TKNAM_DOM1M_getElementsByTagName	(SLIM_TKNAM_BASE_DOM1M0 + 598)
#define SLIM_TKLEN_DOM1M_getElementsByTagName	(20)
#define SLIM_TOKEN_DOM1M_getElementsByTagName	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_getElementsByTagName))
#define SLIM_TKOFF_DOM1M_getElementsByTagNameNS	(SLIM_TKOFF_BASE_DOM1M0 + 619)
#define SLIM_TKNAM_DOM1M_getElementsByTagNameNS	(SLIM_TKNAM_BASE_DOM1M0 + 619)
#define SLIM_TKLEN_DOM1M_getElementsByTagNameNS	(22)
#define SLIM_TOKEN_DOM1M_getElementsByTagNameNS	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_getElementsByTagNameNS))
#define SLIM_TKOFF_DOM1M_getNamedItem	(SLIM_TKOFF_BASE_DOM1M0 + 642)
#define SLIM_TKNAM_DOM1M_getNamedItem	(SLIM_TKNAM_BASE_DOM1M0 + 642)
#define SLIM_TKLEN_DOM1M_getNamedItem	(12)
#define SLIM_TOKEN_DOM1M_getNamedItem	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_getNamedItem))
#define SLIM_TKOFF_DOM1M_getNamedItemNS	(SLIM_TKOFF_BASE_DOM1M0 + 655)
#define SLIM_TKNAM_DOM1M_getNamedItemNS	(SLIM_TKNAM_BASE_DOM1M0 + 655)
#define SLIM_TKLEN_DOM1M_getNamedItemNS	(14)
#define SLIM_TOKEN_DOM1M_getNamedItemNS	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_getNamedItemNS))
#define SLIM_TKOFF_DOM1M_hasAttribute	(SLIM_TKOFF_BASE_DOM1M0 + 670)
#define SLIM_TKNAM_DOM1M_hasAttribute	(SLIM_TKNAM_BASE_DOM1M0 + 670)
#define SLIM_TKLEN_DOM1M_hasAttribute	(12)
#define SLIM_TOKEN_DOM1M_hasAttribute	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_hasAttribute))
#define SLIM_TKOFF_DOM1M_hasAttributeNS	(SLIM_TKOFF_BASE_DOM1M0 + 683)
#define SLIM_TKNAM_DOM1M_hasAttributeNS	(SLIM_TKNAM_BASE_DOM1M0 + 683)
#define SLIM_TKLEN_DOM1M_hasAttributeNS	(14)
#define SLIM_TOKEN_DOM1M_hasAttributeNS	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_hasAttributeNS))
#define SLIM_TKOFF_DOM1M_hasAttributes	(SLIM_TKOFF_BASE_DOM1M0 + 698)
#define SLIM_TKNAM_DOM1M_hasAttributes	(SLIM_TKNAM_BASE_DOM1M0 + 698)
#define SLIM_TKLEN_DOM1M_hasAttributes	(13)
#define SLIM_TOKEN_DOM1M_hasAttributes	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_hasAttributes))
#define SLIM_TKOFF_DOM1M_hasChildNodes	(SLIM_TKOFF_BASE_DOM1M0 + 712)
#define SLIM_TKNAM_DOM1M_hasChildNodes	(SLIM_TKNAM_BASE_DOM1M0 + 712)
#define SLIM_TKLEN_DOM1M_hasChildNodes	(13)
#define SLIM_TOKEN_DOM1M_hasChildNodes	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_hasChildNodes))
#define SLIM_TKOFF_DOM1M_hasFeature	(SLIM_TKOFF_BASE_DOM1M0 + 726)
#define SLIM_TKNAM_DOM1M_hasFeature	(SLIM_TKNAM_BASE_DOM1M0 + 726)
#define SLIM_TKLEN_DOM1M_hasFeature	(10)
#define SLIM_TOKEN_DOM1M_hasFeature	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_hasFeature))
#define SLIM_TKOFF_DOM1M_importNode	(SLIM_TKOFF_BASE_DOM1M0 + 737)
#define SLIM_TKNAM_DOM1M_importNode	(SLIM_TKNAM_BASE_DOM1M0 + 737)
#define SLIM_TKLEN_DOM1M_importNode	(10)
#define SLIM_TOKEN_DOM1M_importNode	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_importNode))
#define SLIM_TKOFF_DOM1M_insertAdjacentElement	(SLIM_TKOFF_BASE_DOM1M0 + 748)
#define SLIM_TKNAM_DOM1M_insertAdjacentElement	(SLIM_TKNAM_BASE_DOM1M0 + 748)
#define SLIM_TKLEN_DOM1M_insertAdjacentElement	(21)
#define SLIM_TOKEN_DOM1M_insertAdjacentElement	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_insertAdjacentElement))
#define SLIM_TKOFF_DOM1M_insertAdjacentHTML	(SLIM_TKOFF_BASE_DOM1M0 + 770)
#define SLIM_TKNAM_DOM1M_insertAdjacentHTML	(SLIM_TKNAM_BASE_DOM1M0 + 770)
#define SLIM_TKLEN_DOM1M_insertAdjacentHTML	(18)
#define SLIM_TOKEN_DOM1M_insertAdjacentHTML	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_insertAdjacentHTML))
#define SLIM_TKOFF_DOM1M_insertAdjacentText	(SLIM_TKOFF_BASE_DOM1M0 + 789)
#define SLIM_TKNAM_DOM1M_insertAdjacentText	(SLIM_TKNAM_BASE_DOM1M0 + 789)
#define SLIM_TKLEN_DOM1M_insertAdjacentText	(18)
#define SLIM_TOKEN_DOM1M_insertAdjacentText	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_insertAdjacentText))
#define SLIM_TKOFF_DOM1M_insertBefore	(SLIM_TKOFF_BASE_DOM1M0 + 808)
#define SLIM_TKNAM_DOM1M_insertBefore	(SLIM_TKNAM_BASE_DOM1M0 + 808)
#define SLIM_TKLEN_DOM1M_insertBefore	(12)
#define SLIM_TOKEN_DOM1M_insertBefore	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_insertBefore))
#define SLIM_TKOFF_DOM1M_insertCell	(SLIM_TKOFF_BASE_DOM1M0 + 821)
#define SLIM_TKNAM_DOM1M_insertCell	(SLIM_TKNAM_BASE_DOM1M0 + 821)
#define SLIM_TKLEN_DOM1M_insertCell	(10)
#define SLIM_TOKEN_DOM1M_insertCell	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_insertCell))
#define SLIM_TKOFF_DOM1M_insertData	(SLIM_TKOFF_BASE_DOM1M0 + 832)
#define SLIM_TKNAM_DOM1M_insertData	(SLIM_TKNAM_BASE_DOM1M0 + 832)
#define SLIM_TKLEN_DOM1M_insertData	(10)
#define SLIM_TOKEN_DOM1M_insertData	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_insertData))
#define SLIM_TKOFF_DOM1M_insertRow	(SLIM_TKOFF_BASE_DOM1M0 + 843)
#define SLIM_TKNAM_DOM1M_insertRow	(SLIM_TKNAM_BASE_DOM1M0 + 843)
#define SLIM_TKLEN_DOM1M_insertRow	(9)
#define SLIM_TOKEN_DOM1M_insertRow	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_insertRow))
#define SLIM_TKOFF_DOM1M_isSupported	(SLIM_TKOFF_BASE_DOM1M0 + 853)
#define SLIM_TKNAM_DOM1M_isSupported	(SLIM_TKNAM_BASE_DOM1M0 + 853)
#define SLIM_TKLEN_DOM1M_isSupported	(11)
#define SLIM_TOKEN_DOM1M_isSupported	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_isSupported))
#define SLIM_TKOFF_DOM1M_item	(SLIM_TKOFF_BASE_DOM1M0 + 865)
#define SLIM_TKNAM_DOM1M_item	(SLIM_TKNAM_BASE_DOM1M0 + 865)
#define SLIM_TKLEN_DOM1M_item	(4)
#define SLIM_TOKEN_DOM1M_item	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_item))
#define SLIM_TKOFF_DOM1M_namedItem	(SLIM_TKOFF_BASE_DOM1M0 + 870)
#define SLIM_TKNAM_DOM1M_namedItem	(SLIM_TKNAM_BASE_DOM1M0 + 870)
#define SLIM_TKLEN_DOM1M_namedItem	(9)
#define SLIM_TOKEN_DOM1M_namedItem	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_namedItem))
#define SLIM_TKOFF_DOM1M_normalize	(SLIM_TKOFF_BASE_DOM1M0 + 880)
#define SLIM_TKNAM_DOM1M_normalize	(SLIM_TKNAM_BASE_DOM1M0 + 880)
#define SLIM_TKLEN_DOM1M_normalize	(9)
#define SLIM_TOKEN_DOM1M_normalize	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_normalize))
#define SLIM_TKOFF_DOM1M_open	(SLIM_TKOFF_BASE_DOM1M0 + 890)
#define SLIM_TKNAM_DOM1M_open	(SLIM_TKNAM_BASE_DOM1M0 + 890)
#define SLIM_TKLEN_DOM1M_open	(4)
#define SLIM_TOKEN_DOM1M_open	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_open))
#define SLIM_TKOFF_DOM1M_remove	(SLIM_TKOFF_BASE_DOM1M0 + 895)
#define SLIM_TKNAM_DOM1M_remove	(SLIM_TKNAM_BASE_DOM1M0 + 895)
#define SLIM_TKLEN_DOM1M_remove	(6)
#define SLIM_TOKEN_DOM1M_remove	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_remove))
#define SLIM_TKOFF_DOM1M_removeAttribute	(SLIM_TKOFF_BASE_DOM1M0 + 902)
#define SLIM_TKNAM_DOM1M_removeAttribute	(SLIM_TKNAM_BASE_DOM1M0 + 902)
#define SLIM_TKLEN_DOM1M_removeAttribute	(15)
#define SLIM_TOKEN_DOM1M_removeAttribute	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_removeAttribute))
#define SLIM_TKOFF_DOM1M_removeAttributeNS	(SLIM_TKOFF_BASE_DOM1M0 + 918)
#define SLIM_TKNAM_DOM1M_removeAttributeNS	(SLIM_TKNAM_BASE_DOM1M0 + 918)
#define SLIM_TKLEN_DOM1M_removeAttributeNS	(17)
#define SLIM_TOKEN_DOM1M_removeAttributeNS	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_removeAttributeNS))
#define SLIM_TKOFF_DOM1M_removeAttributeNode	(SLIM_TKOFF_BASE_DOM1M0 + 936)
#define SLIM_TKNAM_DOM1M_removeAttributeNode	(SLIM_TKNAM_BASE_DOM1M0 + 936)
#define SLIM_TKLEN_DOM1M_removeAttributeNode	(19)
#define SLIM_TOKEN_DOM1M_removeAttributeNode	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_removeAttributeNode))
#define SLIM_TKOFF_DOM1M_removeChild	(SLIM_TKOFF_BASE_DOM1M0 + 956)
#define SLIM_TKNAM_DOM1M_removeChild	(SLIM_TKNAM_BASE_DOM1M0 + 956)
#define SLIM_TKLEN_DOM1M_removeChild	(11)
#define SLIM_TOKEN_DOM1M_removeChild	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_removeChild))
#define SLIM_TKOFF_DOM1M_removeEventListener	(SLIM_TKOFF_BASE_DOM1M0 + 968)
#define SLIM_TKNAM_DOM1M_removeEventListener	(SLIM_TKNAM_BASE_DOM1M0 + 968)
#define SLIM_TKLEN_DOM1M_removeEventListener	(19)
#define SLIM_TOKEN_DOM1M_removeEventListener	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_removeEventListener))
#define SLIM_TKOFF_DOM1M_removeNamedItem	(SLIM_TKOFF_BASE_DOM1M0 + 988)
#define SLIM_TKNAM_DOM1M_removeNamedItem	(SLIM_TKNAM_BASE_DOM1M0 + 988)
#define SLIM_TKLEN_DOM1M_removeNamedItem	(15)
#define SLIM_TOKEN_DOM1M_removeNamedItem	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_removeNamedItem))
#define SLIM_TKOFF_DOM1M_removeNamedItemNS	(SLIM_TKOFF_BASE_DOM1M0 + 1004)
#define SLIM_TKNAM_DOM1M_removeNamedItemNS	(SLIM_TKNAM_BASE_DOM1M0 + 1004)
#define SLIM_TKLEN_DOM1M_removeNamedItemNS	(17)
#define SLIM_TOKEN_DOM1M_removeNamedItemNS	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_removeNamedItemNS))
#define SLIM_TKOFF_DOM1M_replaceAdjacentText	(SLIM_TKOFF_BASE_DOM1M0 + 1022)
#define SLIM_TKNAM_DOM1M_replaceAdjacentText	(SLIM_TKNAM_BASE_DOM1M0 + 1022)
#define SLIM_TKLEN_DOM1M_replaceAdjacentText	(19)
#define SLIM_TOKEN_DOM1M_replaceAdjacentText	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_replaceAdjacentText))
#define SLIM_TKOFF_DOM1M_replaceChild	(SLIM_TKOFF_BASE_DOM1M0 + 1042)
#define SLIM_TKNAM_DOM1M_replaceChild	(SLIM_TKNAM_BASE_DOM1M0 + 1042)
#define SLIM_TKLEN_DOM1M_replaceChild	(12)
#define SLIM_TOKEN_DOM1M_replaceChild	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_replaceChild))
#define SLIM_TKOFF_DOM1M_replaceData	(SLIM_TKOFF_BASE_DOM1M0 + 1055)
#define SLIM_TKNAM_DOM1M_replaceData	(SLIM_TKNAM_BASE_DOM1M0 + 1055)
#define SLIM_TKLEN_DOM1M_replaceData	(11)
#define SLIM_TOKEN_DOM1M_replaceData	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_replaceData))
#define SLIM_TKOFF_DOM1M_reset	(SLIM_TKOFF_BASE_DOM1M0 + 1067)
#define SLIM_TKNAM_DOM1M_reset	(SLIM_TKNAM_BASE_DOM1M0 + 1067)
#define SLIM_TKLEN_DOM1M_reset	(5)
#define SLIM_TOKEN_DOM1M_reset	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_reset))
#define SLIM_TKOFF_DOM1M_select	(SLIM_TKOFF_BASE_DOM1M0 + 1073)
#define SLIM_TKNAM_DOM1M_select	(SLIM_TKNAM_BASE_DOM1M0 + 1073)
#define SLIM_TKLEN_DOM1M_select	(6)
#define SLIM_TOKEN_DOM1M_select	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_select))
#define SLIM_TKOFF_DOM1M_setAttribute	(SLIM_TKOFF_BASE_DOM1M0 + 1080)
#define SLIM_TKNAM_DOM1M_setAttribute	(SLIM_TKNAM_BASE_DOM1M0 + 1080)
#define SLIM_TKLEN_DOM1M_setAttribute	(12)
#define SLIM_TOKEN_DOM1M_setAttribute	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_setAttribute))
#define SLIM_TKOFF_DOM1M_setAttributeNS	(SLIM_TKOFF_BASE_DOM1M0 + 1093)
#define SLIM_TKNAM_DOM1M_setAttributeNS	(SLIM_TKNAM_BASE_DOM1M0 + 1093)
#define SLIM_TKLEN_DOM1M_setAttributeNS	(14)
#define SLIM_TOKEN_DOM1M_setAttributeNS	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_setAttributeNS))
#define SLIM_TKOFF_DOM1M_setAttributeNode	(SLIM_TKOFF_BASE_DOM1M0 + 1108)
#define SLIM_TKNAM_DOM1M_setAttributeNode	(SLIM_TKNAM_BASE_DOM1M0 + 1108)
#define SLIM_TKLEN_DOM1M_setAttributeNode	(16)
#define SLIM_TOKEN_DOM1M_setAttributeNode	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_setAttributeNode))
#define SLIM_TKOFF_DOM1M_setAttributeNodeNS	(SLIM_TKOFF_BASE_DOM1M0 + 1125)
#define SLIM_TKNAM_DOM1M_setAttributeNodeNS	(SLIM_TKNAM_BASE_DOM1M0 + 1125)
#define SLIM_TKLEN_DOM1M_setAttributeNodeNS	(18)
#define SLIM_TOKEN_DOM1M_setAttributeNodeNS	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_setAttributeNodeNS))
#define SLIM_TKOFF_DOM1M_setNamedItem	(SLIM_TKOFF_BASE_DOM1M0 + 1144)
#define SLIM_TKNAM_DOM1M_setNamedItem	(SLIM_TKNAM_BASE_DOM1M0 + 1144)
#define SLIM_TKLEN_DOM1M_setNamedItem	(12)
#define SLIM_TOKEN_DOM1M_setNamedItem	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_setNamedItem))
#define SLIM_TKOFF_DOM1M_setNamedItemNS	(SLIM_TKOFF_BASE_DOM1M0 + 1157)
#define SLIM_TKNAM_DOM1M_setNamedItemNS	(SLIM_TKNAM_BASE_DOM1M0 + 1157)
#define SLIM_TKLEN_DOM1M_setNamedItemNS	(14)
#define SLIM_TOKEN_DOM1M_setNamedItemNS	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_setNamedItemNS))
#define SLIM_TKOFF_DOM1M_splitText	(SLIM_TKOFF_BASE_DOM1M0 + 1172)
#define SLIM_TKNAM_DOM1M_splitText	(SLIM_TKNAM_BASE_DOM1M0 + 1172)
#define SLIM_TKLEN_DOM1M_splitText	(9)
#define SLIM_TOKEN_DOM1M_splitText	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_splitText))
#define SLIM_TKOFF_DOM1M_submit	(SLIM_TKOFF_BASE_DOM1M0 + 1182)
#define SLIM_TKNAM_DOM1M_submit	(SLIM_TKNAM_BASE_DOM1M0 + 1182)
#define SLIM_TKLEN_DOM1M_submit	(6)
#define SLIM_TOKEN_DOM1M_submit	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_submit))
#define SLIM_TKOFF_DOM1M_substringData	(SLIM_TKOFF_BASE_DOM1M0 + 1189)
#define SLIM_TKNAM_DOM1M_substringData	(SLIM_TKNAM_BASE_DOM1M0 + 1189)
#define SLIM_TKLEN_DOM1M_substringData	(13)
#define SLIM_TOKEN_DOM1M_substringData	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_substringData))
#define SLIM_TKOFF_DOM1M_toString	(SLIM_TKOFF_BASE_DOM1M0 + 1203)
#define SLIM_TKNAM_DOM1M_toString	(SLIM_TKNAM_BASE_DOM1M0 + 1203)
#define SLIM_TKLEN_DOM1M_toString	(8)
#define SLIM_TOKEN_DOM1M_toString	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_toString))
#define SLIM_TKOFF_DOM1M_valueOf	(SLIM_TKOFF_BASE_DOM1M0 + 1212)
#define SLIM_TKNAM_DOM1M_valueOf	(SLIM_TKNAM_BASE_DOM1M0 + 1212)
#define SLIM_TKLEN_DOM1M_valueOf	(7)
#define SLIM_TOKEN_DOM1M_valueOf	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_valueOf))
#define SLIM_TKOFF_DOM1M_write	(SLIM_TKOFF_BASE_DOM1M0 + 1220)
#define SLIM_TKNAM_DOM1M_write	(SLIM_TKNAM_BASE_DOM1M0 + 1220)
#define SLIM_TKLEN_DOM1M_write	(5)
#define SLIM_TOKEN_DOM1M_write	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_write))
#define SLIM_TKOFF_DOM1M_writeln	(SLIM_TKOFF_BASE_DOM1M0 + 1226)
#define SLIM_TKNAM_DOM1M_writeln	(SLIM_TKNAM_BASE_DOM1M0 + 1226)
#define SLIM_TKLEN_DOM1M_writeln	(7)
#define SLIM_TOKEN_DOM1M_writeln	(DOM1MethodInfo_GetItem(SLIM_TKID_DOM1M_writeln))
#define SLIM_TKOFF_BASE_DOM1M1	(SLIM_TKOFF_BASE_DOM1M0 + 1234)
#define SLIM_TKNAM_BASE_DOM1M1	(SLIM_TKNAM_BASE_DOM1M0 + SLIM_TKOFF_BASE_DOM1M1)
#define SLIM_TKLEN_TOTAL_DOM1M	SLIM_TKOFF_BASE_DOM1M1

extern SLIM_ROM slim_char cSlim_TokenName_DOM1M[SLIM_TKLEN_TOTAL_DOM1M];

extern SLIM_ROM TDOM1MethodInfo cSlim_Token_DOM1M[SLIM_TOKEN_DOM1M_TOKENS];
#define DOM1MethodInfo_GetItem(id)		((TDOM1MethodInfo *)&cSlim_Token_DOM1M[(id)])
#define DOM1MethodInfo_GetItemName(id)	((slim_char *)cSlim_TokenName_DOM1M + ((TToken *)&cSlim_Token_DOM1M[(id)])->fOffset)
#define DOM1MethodInfo_GetItemNameLen(id)	(((TToken *)&cSlim_Token_DOM1M[(id)])->fLength)

TDOM1MethodInfo *DOM1MethodInfo_CaseFindSS(slim_char *in_s, slim_int in_slen);

SLIM_END_C_LINKAGE
#endif
