/*
	dom1a.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_DOM1A_H
#define SLIM_TOKEN_DOM1A_H

#include <slim/basis/base.h>
#include <slim/basis/token.h>
#include <slim/private/token/dom1aid.h>

SLIM_BEGIN_C_LINKAGE

#include <slim/www/dom.h>

void TDOMModuleEntry_SetDOM1AttrProcTable(TDOMModuleEntry *self);

struct TDOM1AttrInfo_ {
    TToken fBase;	/* must be the first field */
    slim_int fType;
    slim_int fAttrIFType;
    slim_int fFlags[3];
};
typedef struct TDOM1AttrInfo_ TDOM1AttrInfo;

#define SLIM_TKOFF_BASE_DOM1A0	(0)
#define SLIM_TKNAM_BASE_DOM1A0	((slim_char *)cSlim_TokenName_DOM1A)
#define SLIM_TKOFF_DOM1A_URL	(SLIM_TKOFF_BASE_DOM1A0 + 0)
#define SLIM_TKNAM_DOM1A_URL	(SLIM_TKNAM_BASE_DOM1A0 + 0)
#define SLIM_TKLEN_DOM1A_URL	(3)
#define SLIM_TOKEN_DOM1A_URL	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_URL))
#define SLIM_TKOFF_DOM1A_aLink	(SLIM_TKOFF_BASE_DOM1A0 + 4)
#define SLIM_TKNAM_DOM1A_aLink	(SLIM_TKNAM_BASE_DOM1A0 + 4)
#define SLIM_TKLEN_DOM1A_aLink	(5)
#define SLIM_TOKEN_DOM1A_aLink	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_aLink))
#define SLIM_TKOFF_DOM1A_abbr	(SLIM_TKOFF_BASE_DOM1A0 + 10)
#define SLIM_TKNAM_DOM1A_abbr	(SLIM_TKNAM_BASE_DOM1A0 + 10)
#define SLIM_TKLEN_DOM1A_abbr	(4)
#define SLIM_TOKEN_DOM1A_abbr	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_abbr))
#define SLIM_TKOFF_DOM1A_accept	(SLIM_TKOFF_BASE_DOM1A0 + 15)
#define SLIM_TKNAM_DOM1A_accept	(SLIM_TKNAM_BASE_DOM1A0 + 15)
#define SLIM_TKLEN_DOM1A_accept	(6)
#define SLIM_TOKEN_DOM1A_accept	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_accept))
#define SLIM_TKOFF_DOM1A_acceptCharset	(SLIM_TKOFF_BASE_DOM1A0 + 22)
#define SLIM_TKNAM_DOM1A_acceptCharset	(SLIM_TKNAM_BASE_DOM1A0 + 22)
#define SLIM_TKLEN_DOM1A_acceptCharset	(13)
#define SLIM_TOKEN_DOM1A_acceptCharset	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_acceptCharset))
#define SLIM_TKOFF_DOM1A_accessKey	(SLIM_TKOFF_BASE_DOM1A0 + 36)
#define SLIM_TKNAM_DOM1A_accessKey	(SLIM_TKNAM_BASE_DOM1A0 + 36)
#define SLIM_TKLEN_DOM1A_accessKey	(9)
#define SLIM_TOKEN_DOM1A_accessKey	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_accessKey))
#define SLIM_TKOFF_DOM1A_action	(SLIM_TKOFF_BASE_DOM1A0 + 46)
#define SLIM_TKNAM_DOM1A_action	(SLIM_TKNAM_BASE_DOM1A0 + 46)
#define SLIM_TKLEN_DOM1A_action	(6)
#define SLIM_TOKEN_DOM1A_action	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_action))
#define SLIM_TKOFF_DOM1A_align	(SLIM_TKOFF_BASE_DOM1A0 + 53)
#define SLIM_TKNAM_DOM1A_align	(SLIM_TKNAM_BASE_DOM1A0 + 53)
#define SLIM_TKLEN_DOM1A_align	(5)
#define SLIM_TOKEN_DOM1A_align	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_align))
#define SLIM_TKOFF_DOM1A_alinkColor	(SLIM_TKOFF_BASE_DOM1A0 + 59)
#define SLIM_TKNAM_DOM1A_alinkColor	(SLIM_TKNAM_BASE_DOM1A0 + 59)
#define SLIM_TKLEN_DOM1A_alinkColor	(10)
#define SLIM_TOKEN_DOM1A_alinkColor	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_alinkColor))
#define SLIM_TKOFF_DOM1A_all	(SLIM_TKOFF_BASE_DOM1A0 + 70)
#define SLIM_TKNAM_DOM1A_all	(SLIM_TKNAM_BASE_DOM1A0 + 70)
#define SLIM_TKLEN_DOM1A_all	(3)
#define SLIM_TOKEN_DOM1A_all	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_all))
#define SLIM_TKOFF_DOM1A_alt	(SLIM_TKOFF_BASE_DOM1A0 + 74)
#define SLIM_TKNAM_DOM1A_alt	(SLIM_TKNAM_BASE_DOM1A0 + 74)
#define SLIM_TKLEN_DOM1A_alt	(3)
#define SLIM_TOKEN_DOM1A_alt	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_alt))
#define SLIM_TKOFF_DOM1A_anchors	(SLIM_TKOFF_BASE_DOM1A0 + 78)
#define SLIM_TKNAM_DOM1A_anchors	(SLIM_TKNAM_BASE_DOM1A0 + 78)
#define SLIM_TKLEN_DOM1A_anchors	(7)
#define SLIM_TOKEN_DOM1A_anchors	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_anchors))
#define SLIM_TKOFF_DOM1A_applets	(SLIM_TKOFF_BASE_DOM1A0 + 86)
#define SLIM_TKNAM_DOM1A_applets	(SLIM_TKNAM_BASE_DOM1A0 + 86)
#define SLIM_TKLEN_DOM1A_applets	(7)
#define SLIM_TOKEN_DOM1A_applets	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_applets))
#define SLIM_TKOFF_DOM1A_archive	(SLIM_TKOFF_BASE_DOM1A0 + 94)
#define SLIM_TKNAM_DOM1A_archive	(SLIM_TKNAM_BASE_DOM1A0 + 94)
#define SLIM_TKLEN_DOM1A_archive	(7)
#define SLIM_TOKEN_DOM1A_archive	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_archive))
#define SLIM_TKOFF_DOM1A_areas	(SLIM_TKOFF_BASE_DOM1A0 + 102)
#define SLIM_TKNAM_DOM1A_areas	(SLIM_TKNAM_BASE_DOM1A0 + 102)
#define SLIM_TKLEN_DOM1A_areas	(5)
#define SLIM_TOKEN_DOM1A_areas	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_areas))
#define SLIM_TKOFF_DOM1A_attributes	(SLIM_TKOFF_BASE_DOM1A0 + 108)
#define SLIM_TKNAM_DOM1A_attributes	(SLIM_TKNAM_BASE_DOM1A0 + 108)
#define SLIM_TKLEN_DOM1A_attributes	(10)
#define SLIM_TOKEN_DOM1A_attributes	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_attributes))
#define SLIM_TKOFF_DOM1A_axis	(SLIM_TKOFF_BASE_DOM1A0 + 119)
#define SLIM_TKNAM_DOM1A_axis	(SLIM_TKNAM_BASE_DOM1A0 + 119)
#define SLIM_TKLEN_DOM1A_axis	(4)
#define SLIM_TOKEN_DOM1A_axis	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_axis))
#define SLIM_TKOFF_DOM1A_background	(SLIM_TKOFF_BASE_DOM1A0 + 124)
#define SLIM_TKNAM_DOM1A_background	(SLIM_TKNAM_BASE_DOM1A0 + 124)
#define SLIM_TKLEN_DOM1A_background	(10)
#define SLIM_TOKEN_DOM1A_background	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_background))
#define SLIM_TKOFF_DOM1A_bgColor	(SLIM_TKOFF_BASE_DOM1A0 + 135)
#define SLIM_TKNAM_DOM1A_bgColor	(SLIM_TKNAM_BASE_DOM1A0 + 135)
#define SLIM_TKLEN_DOM1A_bgColor	(7)
#define SLIM_TOKEN_DOM1A_bgColor	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_bgColor))
#define SLIM_TKOFF_DOM1A_body	(SLIM_TKOFF_BASE_DOM1A0 + 143)
#define SLIM_TKNAM_DOM1A_body	(SLIM_TKNAM_BASE_DOM1A0 + 143)
#define SLIM_TKLEN_DOM1A_body	(4)
#define SLIM_TOKEN_DOM1A_body	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_body))
#define SLIM_TKOFF_DOM1A_border	(SLIM_TKOFF_BASE_DOM1A0 + 148)
#define SLIM_TKNAM_DOM1A_border	(SLIM_TKNAM_BASE_DOM1A0 + 148)
#define SLIM_TKLEN_DOM1A_border	(6)
#define SLIM_TOKEN_DOM1A_border	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_border))
#define SLIM_TKOFF_DOM1A_caption	(SLIM_TKOFF_BASE_DOM1A0 + 155)
#define SLIM_TKNAM_DOM1A_caption	(SLIM_TKNAM_BASE_DOM1A0 + 155)
#define SLIM_TKLEN_DOM1A_caption	(7)
#define SLIM_TOKEN_DOM1A_caption	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_caption))
#define SLIM_TKOFF_DOM1A_cellIndex	(SLIM_TKOFF_BASE_DOM1A0 + 163)
#define SLIM_TKNAM_DOM1A_cellIndex	(SLIM_TKNAM_BASE_DOM1A0 + 163)
#define SLIM_TKLEN_DOM1A_cellIndex	(9)
#define SLIM_TOKEN_DOM1A_cellIndex	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_cellIndex))
#define SLIM_TKOFF_DOM1A_cellPadding	(SLIM_TKOFF_BASE_DOM1A0 + 173)
#define SLIM_TKNAM_DOM1A_cellPadding	(SLIM_TKNAM_BASE_DOM1A0 + 173)
#define SLIM_TKLEN_DOM1A_cellPadding	(11)
#define SLIM_TOKEN_DOM1A_cellPadding	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_cellPadding))
#define SLIM_TKOFF_DOM1A_cellSpacing	(SLIM_TKOFF_BASE_DOM1A0 + 185)
#define SLIM_TKNAM_DOM1A_cellSpacing	(SLIM_TKNAM_BASE_DOM1A0 + 185)
#define SLIM_TKLEN_DOM1A_cellSpacing	(11)
#define SLIM_TOKEN_DOM1A_cellSpacing	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_cellSpacing))
#define SLIM_TKOFF_DOM1A_cells	(SLIM_TKOFF_BASE_DOM1A0 + 197)
#define SLIM_TKNAM_DOM1A_cells	(SLIM_TKNAM_BASE_DOM1A0 + 197)
#define SLIM_TKLEN_DOM1A_cells	(5)
#define SLIM_TOKEN_DOM1A_cells	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_cells))
#define SLIM_TKOFF_DOM1A_ch	(SLIM_TKOFF_BASE_DOM1A0 + 203)
#define SLIM_TKNAM_DOM1A_ch	(SLIM_TKNAM_BASE_DOM1A0 + 203)
#define SLIM_TKLEN_DOM1A_ch	(2)
#define SLIM_TOKEN_DOM1A_ch	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_ch))
#define SLIM_TKOFF_DOM1A_chOff	(SLIM_TKOFF_BASE_DOM1A0 + 206)
#define SLIM_TKNAM_DOM1A_chOff	(SLIM_TKNAM_BASE_DOM1A0 + 206)
#define SLIM_TKLEN_DOM1A_chOff	(5)
#define SLIM_TOKEN_DOM1A_chOff	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_chOff))
#define SLIM_TKOFF_DOM1A_characterSet	(SLIM_TKOFF_BASE_DOM1A0 + 212)
#define SLIM_TKNAM_DOM1A_characterSet	(SLIM_TKNAM_BASE_DOM1A0 + 212)
#define SLIM_TKLEN_DOM1A_characterSet	(12)
#define SLIM_TOKEN_DOM1A_characterSet	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_characterSet))
#define SLIM_TKOFF_DOM1A_charset	(SLIM_TKOFF_BASE_DOM1A0 + 225)
#define SLIM_TKNAM_DOM1A_charset	(SLIM_TKNAM_BASE_DOM1A0 + 225)
#define SLIM_TKLEN_DOM1A_charset	(7)
#define SLIM_TOKEN_DOM1A_charset	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_charset))
#define SLIM_TKOFF_DOM1A_checked	(SLIM_TKOFF_BASE_DOM1A0 + 233)
#define SLIM_TKNAM_DOM1A_checked	(SLIM_TKNAM_BASE_DOM1A0 + 233)
#define SLIM_TKLEN_DOM1A_checked	(7)
#define SLIM_TOKEN_DOM1A_checked	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_checked))
#define SLIM_TKOFF_DOM1A_childNodes	(SLIM_TKOFF_BASE_DOM1A0 + 241)
#define SLIM_TKNAM_DOM1A_childNodes	(SLIM_TKNAM_BASE_DOM1A0 + 241)
#define SLIM_TKLEN_DOM1A_childNodes	(10)
#define SLIM_TOKEN_DOM1A_childNodes	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_childNodes))
#define SLIM_TKOFF_DOM1A_children	(SLIM_TKOFF_BASE_DOM1A0 + 252)
#define SLIM_TKNAM_DOM1A_children	(SLIM_TKNAM_BASE_DOM1A0 + 252)
#define SLIM_TKLEN_DOM1A_children	(8)
#define SLIM_TOKEN_DOM1A_children	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_children))
#define SLIM_TKOFF_DOM1A_cite	(SLIM_TKOFF_BASE_DOM1A0 + 261)
#define SLIM_TKNAM_DOM1A_cite	(SLIM_TKNAM_BASE_DOM1A0 + 261)
#define SLIM_TKLEN_DOM1A_cite	(4)
#define SLIM_TOKEN_DOM1A_cite	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_cite))
#define SLIM_TKOFF_DOM1A_className	(SLIM_TKOFF_BASE_DOM1A0 + 266)
#define SLIM_TKNAM_DOM1A_className	(SLIM_TKNAM_BASE_DOM1A0 + 266)
#define SLIM_TKLEN_DOM1A_className	(9)
#define SLIM_TOKEN_DOM1A_className	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_className))
#define SLIM_TKOFF_DOM1A_clear	(SLIM_TKOFF_BASE_DOM1A0 + 276)
#define SLIM_TKNAM_DOM1A_clear	(SLIM_TKNAM_BASE_DOM1A0 + 276)
#define SLIM_TKLEN_DOM1A_clear	(5)
#define SLIM_TOKEN_DOM1A_clear	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_clear))
#define SLIM_TKOFF_DOM1A_clientHeight	(SLIM_TKOFF_BASE_DOM1A0 + 282)
#define SLIM_TKNAM_DOM1A_clientHeight	(SLIM_TKNAM_BASE_DOM1A0 + 282)
#define SLIM_TKLEN_DOM1A_clientHeight	(12)
#define SLIM_TOKEN_DOM1A_clientHeight	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_clientHeight))
#define SLIM_TKOFF_DOM1A_clientWidth	(SLIM_TKOFF_BASE_DOM1A0 + 295)
#define SLIM_TKNAM_DOM1A_clientWidth	(SLIM_TKNAM_BASE_DOM1A0 + 295)
#define SLIM_TKLEN_DOM1A_clientWidth	(11)
#define SLIM_TOKEN_DOM1A_clientWidth	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_clientWidth))
#define SLIM_TKOFF_DOM1A_code	(SLIM_TKOFF_BASE_DOM1A0 + 307)
#define SLIM_TKNAM_DOM1A_code	(SLIM_TKNAM_BASE_DOM1A0 + 307)
#define SLIM_TKLEN_DOM1A_code	(4)
#define SLIM_TOKEN_DOM1A_code	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_code))
#define SLIM_TKOFF_DOM1A_codeBase	(SLIM_TKOFF_BASE_DOM1A0 + 312)
#define SLIM_TKNAM_DOM1A_codeBase	(SLIM_TKNAM_BASE_DOM1A0 + 312)
#define SLIM_TKLEN_DOM1A_codeBase	(8)
#define SLIM_TOKEN_DOM1A_codeBase	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_codeBase))
#define SLIM_TKOFF_DOM1A_codeType	(SLIM_TKOFF_BASE_DOM1A0 + 321)
#define SLIM_TKNAM_DOM1A_codeType	(SLIM_TKNAM_BASE_DOM1A0 + 321)
#define SLIM_TKLEN_DOM1A_codeType	(8)
#define SLIM_TOKEN_DOM1A_codeType	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_codeType))
#define SLIM_TKOFF_DOM1A_colSpan	(SLIM_TKOFF_BASE_DOM1A0 + 330)
#define SLIM_TKNAM_DOM1A_colSpan	(SLIM_TKNAM_BASE_DOM1A0 + 330)
#define SLIM_TKLEN_DOM1A_colSpan	(7)
#define SLIM_TOKEN_DOM1A_colSpan	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_colSpan))
#define SLIM_TKOFF_DOM1A_color	(SLIM_TKOFF_BASE_DOM1A0 + 338)
#define SLIM_TKNAM_DOM1A_color	(SLIM_TKNAM_BASE_DOM1A0 + 338)
#define SLIM_TKLEN_DOM1A_color	(5)
#define SLIM_TOKEN_DOM1A_color	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_color))
#define SLIM_TKOFF_DOM1A_cols	(SLIM_TKOFF_BASE_DOM1A0 + 344)
#define SLIM_TKNAM_DOM1A_cols	(SLIM_TKNAM_BASE_DOM1A0 + 344)
#define SLIM_TKLEN_DOM1A_cols	(4)
#define SLIM_TOKEN_DOM1A_cols	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_cols))
#define SLIM_TKOFF_DOM1A_compact	(SLIM_TKOFF_BASE_DOM1A0 + 349)
#define SLIM_TKNAM_DOM1A_compact	(SLIM_TKNAM_BASE_DOM1A0 + 349)
#define SLIM_TKLEN_DOM1A_compact	(7)
#define SLIM_TOKEN_DOM1A_compact	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_compact))
#define SLIM_TKOFF_DOM1A_compatMode	(SLIM_TKOFF_BASE_DOM1A0 + 357)
#define SLIM_TKNAM_DOM1A_compatMode	(SLIM_TKNAM_BASE_DOM1A0 + 357)
#define SLIM_TKLEN_DOM1A_compatMode	(10)
#define SLIM_TOKEN_DOM1A_compatMode	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_compatMode))
#define SLIM_TKOFF_DOM1A_complete	(SLIM_TKOFF_BASE_DOM1A0 + 368)
#define SLIM_TKNAM_DOM1A_complete	(SLIM_TKNAM_BASE_DOM1A0 + 368)
#define SLIM_TKLEN_DOM1A_complete	(8)
#define SLIM_TOKEN_DOM1A_complete	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_complete))
#define SLIM_TKOFF_DOM1A_content	(SLIM_TKOFF_BASE_DOM1A0 + 377)
#define SLIM_TKNAM_DOM1A_content	(SLIM_TKNAM_BASE_DOM1A0 + 377)
#define SLIM_TKLEN_DOM1A_content	(7)
#define SLIM_TOKEN_DOM1A_content	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_content))
#define SLIM_TKOFF_DOM1A_contentDocument	(SLIM_TKOFF_BASE_DOM1A0 + 385)
#define SLIM_TKNAM_DOM1A_contentDocument	(SLIM_TKNAM_BASE_DOM1A0 + 385)
#define SLIM_TKLEN_DOM1A_contentDocument	(15)
#define SLIM_TOKEN_DOM1A_contentDocument	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_contentDocument))
#define SLIM_TKOFF_DOM1A_contentWindow	(SLIM_TKOFF_BASE_DOM1A0 + 401)
#define SLIM_TKNAM_DOM1A_contentWindow	(SLIM_TKNAM_BASE_DOM1A0 + 401)
#define SLIM_TKLEN_DOM1A_contentWindow	(13)
#define SLIM_TOKEN_DOM1A_contentWindow	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_contentWindow))
#define SLIM_TKOFF_DOM1A_cookie	(SLIM_TKOFF_BASE_DOM1A0 + 415)
#define SLIM_TKNAM_DOM1A_cookie	(SLIM_TKNAM_BASE_DOM1A0 + 415)
#define SLIM_TKLEN_DOM1A_cookie	(6)
#define SLIM_TOKEN_DOM1A_cookie	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_cookie))
#define SLIM_TKOFF_DOM1A_coords	(SLIM_TKOFF_BASE_DOM1A0 + 422)
#define SLIM_TKNAM_DOM1A_coords	(SLIM_TKNAM_BASE_DOM1A0 + 422)
#define SLIM_TKLEN_DOM1A_coords	(6)
#define SLIM_TOKEN_DOM1A_coords	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_coords))
#define SLIM_TKOFF_DOM1A_currentStyle	(SLIM_TKOFF_BASE_DOM1A0 + 429)
#define SLIM_TKNAM_DOM1A_currentStyle	(SLIM_TKNAM_BASE_DOM1A0 + 429)
#define SLIM_TKLEN_DOM1A_currentStyle	(12)
#define SLIM_TOKEN_DOM1A_currentStyle	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_currentStyle))
#define SLIM_TKOFF_DOM1A_data	(SLIM_TKOFF_BASE_DOM1A0 + 442)
#define SLIM_TKNAM_DOM1A_data	(SLIM_TKNAM_BASE_DOM1A0 + 442)
#define SLIM_TKLEN_DOM1A_data	(4)
#define SLIM_TOKEN_DOM1A_data	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_data))
#define SLIM_TKOFF_DOM1A_dateTime	(SLIM_TKOFF_BASE_DOM1A0 + 447)
#define SLIM_TKNAM_DOM1A_dateTime	(SLIM_TKNAM_BASE_DOM1A0 + 447)
#define SLIM_TKLEN_DOM1A_dateTime	(8)
#define SLIM_TOKEN_DOM1A_dateTime	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_dateTime))
#define SLIM_TKOFF_DOM1A_declare	(SLIM_TKOFF_BASE_DOM1A0 + 456)
#define SLIM_TKNAM_DOM1A_declare	(SLIM_TKNAM_BASE_DOM1A0 + 456)
#define SLIM_TKLEN_DOM1A_declare	(7)
#define SLIM_TOKEN_DOM1A_declare	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_declare))
#define SLIM_TKOFF_DOM1A_defaultChecked	(SLIM_TKOFF_BASE_DOM1A0 + 464)
#define SLIM_TKNAM_DOM1A_defaultChecked	(SLIM_TKNAM_BASE_DOM1A0 + 464)
#define SLIM_TKLEN_DOM1A_defaultChecked	(14)
#define SLIM_TOKEN_DOM1A_defaultChecked	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_defaultChecked))
#define SLIM_TKOFF_DOM1A_defaultSelected	(SLIM_TKOFF_BASE_DOM1A0 + 479)
#define SLIM_TKNAM_DOM1A_defaultSelected	(SLIM_TKNAM_BASE_DOM1A0 + 479)
#define SLIM_TKLEN_DOM1A_defaultSelected	(15)
#define SLIM_TOKEN_DOM1A_defaultSelected	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_defaultSelected))
#define SLIM_TKOFF_DOM1A_defaultValue	(SLIM_TKOFF_BASE_DOM1A0 + 495)
#define SLIM_TKNAM_DOM1A_defaultValue	(SLIM_TKNAM_BASE_DOM1A0 + 495)
#define SLIM_TKLEN_DOM1A_defaultValue	(12)
#define SLIM_TOKEN_DOM1A_defaultValue	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_defaultValue))
#define SLIM_TKOFF_DOM1A_defer	(SLIM_TKOFF_BASE_DOM1A0 + 508)
#define SLIM_TKNAM_DOM1A_defer	(SLIM_TKNAM_BASE_DOM1A0 + 508)
#define SLIM_TKLEN_DOM1A_defer	(5)
#define SLIM_TOKEN_DOM1A_defer	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_defer))
#define SLIM_TKOFF_DOM1A_dir	(SLIM_TKOFF_BASE_DOM1A0 + 514)
#define SLIM_TKNAM_DOM1A_dir	(SLIM_TKNAM_BASE_DOM1A0 + 514)
#define SLIM_TKLEN_DOM1A_dir	(3)
#define SLIM_TOKEN_DOM1A_dir	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_dir))
#define SLIM_TKOFF_DOM1A_disabled	(SLIM_TKOFF_BASE_DOM1A0 + 518)
#define SLIM_TKNAM_DOM1A_disabled	(SLIM_TKNAM_BASE_DOM1A0 + 518)
#define SLIM_TKLEN_DOM1A_disabled	(8)
#define SLIM_TOKEN_DOM1A_disabled	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_disabled))
#define SLIM_TKOFF_DOM1A_doctype	(SLIM_TKOFF_BASE_DOM1A0 + 527)
#define SLIM_TKNAM_DOM1A_doctype	(SLIM_TKNAM_BASE_DOM1A0 + 527)
#define SLIM_TKLEN_DOM1A_doctype	(7)
#define SLIM_TOKEN_DOM1A_doctype	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_doctype))
#define SLIM_TKOFF_DOM1A_document	(SLIM_TKOFF_BASE_DOM1A0 + 535)
#define SLIM_TKNAM_DOM1A_document	(SLIM_TKNAM_BASE_DOM1A0 + 535)
#define SLIM_TKLEN_DOM1A_document	(8)
#define SLIM_TOKEN_DOM1A_document	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_document))
#define SLIM_TKOFF_DOM1A_documentElement	(SLIM_TKOFF_BASE_DOM1A0 + 544)
#define SLIM_TKNAM_DOM1A_documentElement	(SLIM_TKNAM_BASE_DOM1A0 + 544)
#define SLIM_TKLEN_DOM1A_documentElement	(15)
#define SLIM_TOKEN_DOM1A_documentElement	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_documentElement))
#define SLIM_TKOFF_DOM1A_domain	(SLIM_TKOFF_BASE_DOM1A0 + 560)
#define SLIM_TKNAM_DOM1A_domain	(SLIM_TKNAM_BASE_DOM1A0 + 560)
#define SLIM_TKLEN_DOM1A_domain	(6)
#define SLIM_TOKEN_DOM1A_domain	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_domain))
#define SLIM_TKOFF_DOM1A_elements	(SLIM_TKOFF_BASE_DOM1A0 + 567)
#define SLIM_TKNAM_DOM1A_elements	(SLIM_TKNAM_BASE_DOM1A0 + 567)
#define SLIM_TKLEN_DOM1A_elements	(8)
#define SLIM_TOKEN_DOM1A_elements	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_elements))
#define SLIM_TKOFF_DOM1A_embeds	(SLIM_TKOFF_BASE_DOM1A0 + 576)
#define SLIM_TKNAM_DOM1A_embeds	(SLIM_TKNAM_BASE_DOM1A0 + 576)
#define SLIM_TKLEN_DOM1A_embeds	(6)
#define SLIM_TOKEN_DOM1A_embeds	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_embeds))
#define SLIM_TKOFF_DOM1A_enctype	(SLIM_TKOFF_BASE_DOM1A0 + 583)
#define SLIM_TKNAM_DOM1A_enctype	(SLIM_TKNAM_BASE_DOM1A0 + 583)
#define SLIM_TKLEN_DOM1A_enctype	(7)
#define SLIM_TOKEN_DOM1A_enctype	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_enctype))
#define SLIM_TKOFF_DOM1A_entities	(SLIM_TKOFF_BASE_DOM1A0 + 591)
#define SLIM_TKNAM_DOM1A_entities	(SLIM_TKNAM_BASE_DOM1A0 + 591)
#define SLIM_TKLEN_DOM1A_entities	(8)
#define SLIM_TOKEN_DOM1A_entities	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_entities))
#define SLIM_TKOFF_DOM1A_event	(SLIM_TKOFF_BASE_DOM1A0 + 600)
#define SLIM_TKNAM_DOM1A_event	(SLIM_TKNAM_BASE_DOM1A0 + 600)
#define SLIM_TKLEN_DOM1A_event	(5)
#define SLIM_TOKEN_DOM1A_event	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_event))
#define SLIM_TKOFF_DOM1A_face	(SLIM_TKOFF_BASE_DOM1A0 + 606)
#define SLIM_TKNAM_DOM1A_face	(SLIM_TKNAM_BASE_DOM1A0 + 606)
#define SLIM_TKLEN_DOM1A_face	(4)
#define SLIM_TOKEN_DOM1A_face	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_face))
#define SLIM_TKOFF_DOM1A_fgColor	(SLIM_TKOFF_BASE_DOM1A0 + 611)
#define SLIM_TKNAM_DOM1A_fgColor	(SLIM_TKNAM_BASE_DOM1A0 + 611)
#define SLIM_TKLEN_DOM1A_fgColor	(7)
#define SLIM_TOKEN_DOM1A_fgColor	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_fgColor))
#define SLIM_TKOFF_DOM1A_firstChild	(SLIM_TKOFF_BASE_DOM1A0 + 619)
#define SLIM_TKNAM_DOM1A_firstChild	(SLIM_TKNAM_BASE_DOM1A0 + 619)
#define SLIM_TKLEN_DOM1A_firstChild	(10)
#define SLIM_TOKEN_DOM1A_firstChild	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_firstChild))
#define SLIM_TKOFF_DOM1A_form	(SLIM_TKOFF_BASE_DOM1A0 + 630)
#define SLIM_TKNAM_DOM1A_form	(SLIM_TKNAM_BASE_DOM1A0 + 630)
#define SLIM_TKLEN_DOM1A_form	(4)
#define SLIM_TOKEN_DOM1A_form	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_form))
#define SLIM_TKOFF_DOM1A_forms	(SLIM_TKOFF_BASE_DOM1A0 + 635)
#define SLIM_TKNAM_DOM1A_forms	(SLIM_TKNAM_BASE_DOM1A0 + 635)
#define SLIM_TKLEN_DOM1A_forms	(5)
#define SLIM_TOKEN_DOM1A_forms	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_forms))
#define SLIM_TKOFF_DOM1A_frame	(SLIM_TKOFF_BASE_DOM1A0 + 641)
#define SLIM_TKNAM_DOM1A_frame	(SLIM_TKNAM_BASE_DOM1A0 + 641)
#define SLIM_TKLEN_DOM1A_frame	(5)
#define SLIM_TOKEN_DOM1A_frame	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_frame))
#define SLIM_TKOFF_DOM1A_frameBorder	(SLIM_TKOFF_BASE_DOM1A0 + 647)
#define SLIM_TKNAM_DOM1A_frameBorder	(SLIM_TKNAM_BASE_DOM1A0 + 647)
#define SLIM_TKLEN_DOM1A_frameBorder	(11)
#define SLIM_TOKEN_DOM1A_frameBorder	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_frameBorder))
#define SLIM_TKOFF_DOM1A_hash	(SLIM_TKOFF_BASE_DOM1A0 + 659)
#define SLIM_TKNAM_DOM1A_hash	(SLIM_TKNAM_BASE_DOM1A0 + 659)
#define SLIM_TKLEN_DOM1A_hash	(4)
#define SLIM_TOKEN_DOM1A_hash	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_hash))
#define SLIM_TKOFF_DOM1A_headers	(SLIM_TKOFF_BASE_DOM1A0 + 664)
#define SLIM_TKNAM_DOM1A_headers	(SLIM_TKNAM_BASE_DOM1A0 + 664)
#define SLIM_TKLEN_DOM1A_headers	(7)
#define SLIM_TOKEN_DOM1A_headers	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_headers))
#define SLIM_TKOFF_DOM1A_height	(SLIM_TKOFF_BASE_DOM1A0 + 672)
#define SLIM_TKNAM_DOM1A_height	(SLIM_TKNAM_BASE_DOM1A0 + 672)
#define SLIM_TKLEN_DOM1A_height	(6)
#define SLIM_TOKEN_DOM1A_height	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_height))
#define SLIM_TKOFF_DOM1A_host	(SLIM_TKOFF_BASE_DOM1A0 + 679)
#define SLIM_TKNAM_DOM1A_host	(SLIM_TKNAM_BASE_DOM1A0 + 679)
#define SLIM_TKLEN_DOM1A_host	(4)
#define SLIM_TOKEN_DOM1A_host	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_host))
#define SLIM_TKOFF_DOM1A_hostname	(SLIM_TKOFF_BASE_DOM1A0 + 684)
#define SLIM_TKNAM_DOM1A_hostname	(SLIM_TKNAM_BASE_DOM1A0 + 684)
#define SLIM_TKLEN_DOM1A_hostname	(8)
#define SLIM_TOKEN_DOM1A_hostname	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_hostname))
#define SLIM_TKOFF_DOM1A_href	(SLIM_TKOFF_BASE_DOM1A0 + 693)
#define SLIM_TKNAM_DOM1A_href	(SLIM_TKNAM_BASE_DOM1A0 + 693)
#define SLIM_TKLEN_DOM1A_href	(4)
#define SLIM_TOKEN_DOM1A_href	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_href))
#define SLIM_TKOFF_DOM1A_hreflang	(SLIM_TKOFF_BASE_DOM1A0 + 698)
#define SLIM_TKNAM_DOM1A_hreflang	(SLIM_TKNAM_BASE_DOM1A0 + 698)
#define SLIM_TKLEN_DOM1A_hreflang	(8)
#define SLIM_TOKEN_DOM1A_hreflang	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_hreflang))
#define SLIM_TKOFF_DOM1A_hspace	(SLIM_TKOFF_BASE_DOM1A0 + 707)
#define SLIM_TKNAM_DOM1A_hspace	(SLIM_TKNAM_BASE_DOM1A0 + 707)
#define SLIM_TKLEN_DOM1A_hspace	(6)
#define SLIM_TOKEN_DOM1A_hspace	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_hspace))
#define SLIM_TKOFF_DOM1A_htmlFor	(SLIM_TKOFF_BASE_DOM1A0 + 714)
#define SLIM_TKNAM_DOM1A_htmlFor	(SLIM_TKNAM_BASE_DOM1A0 + 714)
#define SLIM_TKLEN_DOM1A_htmlFor	(7)
#define SLIM_TOKEN_DOM1A_htmlFor	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_htmlFor))
#define SLIM_TKOFF_DOM1A_httpEquiv	(SLIM_TKOFF_BASE_DOM1A0 + 722)
#define SLIM_TKNAM_DOM1A_httpEquiv	(SLIM_TKNAM_BASE_DOM1A0 + 722)
#define SLIM_TKLEN_DOM1A_httpEquiv	(9)
#define SLIM_TOKEN_DOM1A_httpEquiv	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_httpEquiv))
#define SLIM_TKOFF_DOM1A_id	(SLIM_TKOFF_BASE_DOM1A0 + 732)
#define SLIM_TKNAM_DOM1A_id	(SLIM_TKNAM_BASE_DOM1A0 + 732)
#define SLIM_TKLEN_DOM1A_id	(2)
#define SLIM_TOKEN_DOM1A_id	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_id))
#define SLIM_TKOFF_DOM1A_images	(SLIM_TKOFF_BASE_DOM1A0 + 735)
#define SLIM_TKNAM_DOM1A_images	(SLIM_TKNAM_BASE_DOM1A0 + 735)
#define SLIM_TKLEN_DOM1A_images	(6)
#define SLIM_TOKEN_DOM1A_images	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_images))
#define SLIM_TKOFF_DOM1A_implementation	(SLIM_TKOFF_BASE_DOM1A0 + 742)
#define SLIM_TKNAM_DOM1A_implementation	(SLIM_TKNAM_BASE_DOM1A0 + 742)
#define SLIM_TKLEN_DOM1A_implementation	(14)
#define SLIM_TOKEN_DOM1A_implementation	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_implementation))
#define SLIM_TKOFF_DOM1A_index	(SLIM_TKOFF_BASE_DOM1A0 + 757)
#define SLIM_TKNAM_DOM1A_index	(SLIM_TKNAM_BASE_DOM1A0 + 757)
#define SLIM_TKLEN_DOM1A_index	(5)
#define SLIM_TOKEN_DOM1A_index	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_index))
#define SLIM_TKOFF_DOM1A_innerHTML	(SLIM_TKOFF_BASE_DOM1A0 + 763)
#define SLIM_TKNAM_DOM1A_innerHTML	(SLIM_TKNAM_BASE_DOM1A0 + 763)
#define SLIM_TKLEN_DOM1A_innerHTML	(9)
#define SLIM_TOKEN_DOM1A_innerHTML	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_innerHTML))
#define SLIM_TKOFF_DOM1A_innerText	(SLIM_TKOFF_BASE_DOM1A0 + 773)
#define SLIM_TKNAM_DOM1A_innerText	(SLIM_TKNAM_BASE_DOM1A0 + 773)
#define SLIM_TKLEN_DOM1A_innerText	(9)
#define SLIM_TOKEN_DOM1A_innerText	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_innerText))
#define SLIM_TKOFF_DOM1A_internalSubset	(SLIM_TKOFF_BASE_DOM1A0 + 783)
#define SLIM_TKNAM_DOM1A_internalSubset	(SLIM_TKNAM_BASE_DOM1A0 + 783)
#define SLIM_TKLEN_DOM1A_internalSubset	(14)
#define SLIM_TOKEN_DOM1A_internalSubset	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_internalSubset))
#define SLIM_TKOFF_DOM1A_isMap	(SLIM_TKOFF_BASE_DOM1A0 + 798)
#define SLIM_TKNAM_DOM1A_isMap	(SLIM_TKNAM_BASE_DOM1A0 + 798)
#define SLIM_TKLEN_DOM1A_isMap	(5)
#define SLIM_TOKEN_DOM1A_isMap	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_isMap))
#define SLIM_TKOFF_DOM1A_label	(SLIM_TKOFF_BASE_DOM1A0 + 804)
#define SLIM_TKNAM_DOM1A_label	(SLIM_TKNAM_BASE_DOM1A0 + 804)
#define SLIM_TKLEN_DOM1A_label	(5)
#define SLIM_TOKEN_DOM1A_label	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_label))
#define SLIM_TKOFF_DOM1A_lang	(SLIM_TKOFF_BASE_DOM1A0 + 810)
#define SLIM_TKNAM_DOM1A_lang	(SLIM_TKNAM_BASE_DOM1A0 + 810)
#define SLIM_TKLEN_DOM1A_lang	(4)
#define SLIM_TOKEN_DOM1A_lang	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_lang))
#define SLIM_TKOFF_DOM1A_lastChild	(SLIM_TKOFF_BASE_DOM1A0 + 815)
#define SLIM_TKNAM_DOM1A_lastChild	(SLIM_TKNAM_BASE_DOM1A0 + 815)
#define SLIM_TKLEN_DOM1A_lastChild	(9)
#define SLIM_TOKEN_DOM1A_lastChild	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_lastChild))
#define SLIM_TKOFF_DOM1A_lastModified	(SLIM_TKOFF_BASE_DOM1A0 + 825)
#define SLIM_TKNAM_DOM1A_lastModified	(SLIM_TKNAM_BASE_DOM1A0 + 825)
#define SLIM_TKLEN_DOM1A_lastModified	(12)
#define SLIM_TOKEN_DOM1A_lastModified	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_lastModified))
#define SLIM_TKOFF_DOM1A_length	(SLIM_TKOFF_BASE_DOM1A0 + 838)
#define SLIM_TKNAM_DOM1A_length	(SLIM_TKNAM_BASE_DOM1A0 + 838)
#define SLIM_TKLEN_DOM1A_length	(6)
#define SLIM_TOKEN_DOM1A_length	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_length))
#define SLIM_TKOFF_DOM1A_link	(SLIM_TKOFF_BASE_DOM1A0 + 845)
#define SLIM_TKNAM_DOM1A_link	(SLIM_TKNAM_BASE_DOM1A0 + 845)
#define SLIM_TKLEN_DOM1A_link	(4)
#define SLIM_TOKEN_DOM1A_link	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_link))
#define SLIM_TKOFF_DOM1A_linkColor	(SLIM_TKOFF_BASE_DOM1A0 + 850)
#define SLIM_TKNAM_DOM1A_linkColor	(SLIM_TKNAM_BASE_DOM1A0 + 850)
#define SLIM_TKLEN_DOM1A_linkColor	(9)
#define SLIM_TOKEN_DOM1A_linkColor	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_linkColor))
#define SLIM_TKOFF_DOM1A_links	(SLIM_TKOFF_BASE_DOM1A0 + 860)
#define SLIM_TKNAM_DOM1A_links	(SLIM_TKNAM_BASE_DOM1A0 + 860)
#define SLIM_TKLEN_DOM1A_links	(5)
#define SLIM_TOKEN_DOM1A_links	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_links))
#define SLIM_TKOFF_DOM1A_localName	(SLIM_TKOFF_BASE_DOM1A0 + 866)
#define SLIM_TKNAM_DOM1A_localName	(SLIM_TKNAM_BASE_DOM1A0 + 866)
#define SLIM_TKLEN_DOM1A_localName	(9)
#define SLIM_TOKEN_DOM1A_localName	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_localName))
#define SLIM_TKOFF_DOM1A_location	(SLIM_TKOFF_BASE_DOM1A0 + 876)
#define SLIM_TKNAM_DOM1A_location	(SLIM_TKNAM_BASE_DOM1A0 + 876)
#define SLIM_TKLEN_DOM1A_location	(8)
#define SLIM_TOKEN_DOM1A_location	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_location))
#define SLIM_TKOFF_DOM1A_longDesc	(SLIM_TKOFF_BASE_DOM1A0 + 885)
#define SLIM_TKNAM_DOM1A_longDesc	(SLIM_TKNAM_BASE_DOM1A0 + 885)
#define SLIM_TKLEN_DOM1A_longDesc	(8)
#define SLIM_TOKEN_DOM1A_longDesc	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_longDesc))
#define SLIM_TKOFF_DOM1A_lowsrc	(SLIM_TKOFF_BASE_DOM1A0 + 894)
#define SLIM_TKNAM_DOM1A_lowsrc	(SLIM_TKNAM_BASE_DOM1A0 + 894)
#define SLIM_TKLEN_DOM1A_lowsrc	(6)
#define SLIM_TOKEN_DOM1A_lowsrc	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_lowsrc))
#define SLIM_TKOFF_DOM1A_marginHeight	(SLIM_TKOFF_BASE_DOM1A0 + 901)
#define SLIM_TKNAM_DOM1A_marginHeight	(SLIM_TKNAM_BASE_DOM1A0 + 901)
#define SLIM_TKLEN_DOM1A_marginHeight	(12)
#define SLIM_TOKEN_DOM1A_marginHeight	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_marginHeight))
#define SLIM_TKOFF_DOM1A_marginWidth	(SLIM_TKOFF_BASE_DOM1A0 + 914)
#define SLIM_TKNAM_DOM1A_marginWidth	(SLIM_TKNAM_BASE_DOM1A0 + 914)
#define SLIM_TKLEN_DOM1A_marginWidth	(11)
#define SLIM_TOKEN_DOM1A_marginWidth	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_marginWidth))
#define SLIM_TKOFF_DOM1A_maxLength	(SLIM_TKOFF_BASE_DOM1A0 + 926)
#define SLIM_TKNAM_DOM1A_maxLength	(SLIM_TKNAM_BASE_DOM1A0 + 926)
#define SLIM_TKLEN_DOM1A_maxLength	(9)
#define SLIM_TOKEN_DOM1A_maxLength	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_maxLength))
#define SLIM_TKOFF_DOM1A_media	(SLIM_TKOFF_BASE_DOM1A0 + 936)
#define SLIM_TKNAM_DOM1A_media	(SLIM_TKNAM_BASE_DOM1A0 + 936)
#define SLIM_TKLEN_DOM1A_media	(5)
#define SLIM_TOKEN_DOM1A_media	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_media))
#define SLIM_TKOFF_DOM1A_method	(SLIM_TKOFF_BASE_DOM1A0 + 942)
#define SLIM_TKNAM_DOM1A_method	(SLIM_TKNAM_BASE_DOM1A0 + 942)
#define SLIM_TKLEN_DOM1A_method	(6)
#define SLIM_TOKEN_DOM1A_method	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_method))
#define SLIM_TKOFF_DOM1A_multiple	(SLIM_TKOFF_BASE_DOM1A0 + 949)
#define SLIM_TKNAM_DOM1A_multiple	(SLIM_TKNAM_BASE_DOM1A0 + 949)
#define SLIM_TKLEN_DOM1A_multiple	(8)
#define SLIM_TOKEN_DOM1A_multiple	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_multiple))
#define SLIM_TKOFF_DOM1A_name	(SLIM_TKOFF_BASE_DOM1A0 + 958)
#define SLIM_TKNAM_DOM1A_name	(SLIM_TKNAM_BASE_DOM1A0 + 958)
#define SLIM_TKLEN_DOM1A_name	(4)
#define SLIM_TOKEN_DOM1A_name	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_name))
#define SLIM_TKOFF_DOM1A_namespaceURI	(SLIM_TKOFF_BASE_DOM1A0 + 963)
#define SLIM_TKNAM_DOM1A_namespaceURI	(SLIM_TKNAM_BASE_DOM1A0 + 963)
#define SLIM_TKLEN_DOM1A_namespaceURI	(12)
#define SLIM_TOKEN_DOM1A_namespaceURI	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_namespaceURI))
#define SLIM_TKOFF_DOM1A_nextSibling	(SLIM_TKOFF_BASE_DOM1A0 + 976)
#define SLIM_TKNAM_DOM1A_nextSibling	(SLIM_TKNAM_BASE_DOM1A0 + 976)
#define SLIM_TKLEN_DOM1A_nextSibling	(11)
#define SLIM_TOKEN_DOM1A_nextSibling	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_nextSibling))
#define SLIM_TKOFF_DOM1A_noHref	(SLIM_TKOFF_BASE_DOM1A0 + 988)
#define SLIM_TKNAM_DOM1A_noHref	(SLIM_TKNAM_BASE_DOM1A0 + 988)
#define SLIM_TKLEN_DOM1A_noHref	(6)
#define SLIM_TOKEN_DOM1A_noHref	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_noHref))
#define SLIM_TKOFF_DOM1A_noResize	(SLIM_TKOFF_BASE_DOM1A0 + 995)
#define SLIM_TKNAM_DOM1A_noResize	(SLIM_TKNAM_BASE_DOM1A0 + 995)
#define SLIM_TKLEN_DOM1A_noResize	(8)
#define SLIM_TOKEN_DOM1A_noResize	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_noResize))
#define SLIM_TKOFF_DOM1A_noShade	(SLIM_TKOFF_BASE_DOM1A0 + 1004)
#define SLIM_TKNAM_DOM1A_noShade	(SLIM_TKNAM_BASE_DOM1A0 + 1004)
#define SLIM_TKLEN_DOM1A_noShade	(7)
#define SLIM_TOKEN_DOM1A_noShade	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_noShade))
#define SLIM_TKOFF_DOM1A_noWrap	(SLIM_TKOFF_BASE_DOM1A0 + 1012)
#define SLIM_TKNAM_DOM1A_noWrap	(SLIM_TKNAM_BASE_DOM1A0 + 1012)
#define SLIM_TKLEN_DOM1A_noWrap	(6)
#define SLIM_TOKEN_DOM1A_noWrap	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_noWrap))
#define SLIM_TKOFF_DOM1A_nodeName	(SLIM_TKOFF_BASE_DOM1A0 + 1019)
#define SLIM_TKNAM_DOM1A_nodeName	(SLIM_TKNAM_BASE_DOM1A0 + 1019)
#define SLIM_TKLEN_DOM1A_nodeName	(8)
#define SLIM_TOKEN_DOM1A_nodeName	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_nodeName))
#define SLIM_TKOFF_DOM1A_nodeType	(SLIM_TKOFF_BASE_DOM1A0 + 1028)
#define SLIM_TKNAM_DOM1A_nodeType	(SLIM_TKNAM_BASE_DOM1A0 + 1028)
#define SLIM_TKLEN_DOM1A_nodeType	(8)
#define SLIM_TOKEN_DOM1A_nodeType	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_nodeType))
#define SLIM_TKOFF_DOM1A_nodeValue	(SLIM_TKOFF_BASE_DOM1A0 + 1037)
#define SLIM_TKNAM_DOM1A_nodeValue	(SLIM_TKNAM_BASE_DOM1A0 + 1037)
#define SLIM_TKLEN_DOM1A_nodeValue	(9)
#define SLIM_TOKEN_DOM1A_nodeValue	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_nodeValue))
#define SLIM_TKOFF_DOM1A_notationName	(SLIM_TKOFF_BASE_DOM1A0 + 1047)
#define SLIM_TKNAM_DOM1A_notationName	(SLIM_TKNAM_BASE_DOM1A0 + 1047)
#define SLIM_TKLEN_DOM1A_notationName	(12)
#define SLIM_TOKEN_DOM1A_notationName	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_notationName))
#define SLIM_TKOFF_DOM1A_notations	(SLIM_TKOFF_BASE_DOM1A0 + 1060)
#define SLIM_TKNAM_DOM1A_notations	(SLIM_TKNAM_BASE_DOM1A0 + 1060)
#define SLIM_TKLEN_DOM1A_notations	(9)
#define SLIM_TOKEN_DOM1A_notations	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_notations))
#define SLIM_TKOFF_DOM1A_object	(SLIM_TKOFF_BASE_DOM1A0 + 1070)
#define SLIM_TKNAM_DOM1A_object	(SLIM_TKNAM_BASE_DOM1A0 + 1070)
#define SLIM_TKLEN_DOM1A_object	(6)
#define SLIM_TOKEN_DOM1A_object	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_object))
#define SLIM_TKOFF_DOM1A_offsetHeight	(SLIM_TKOFF_BASE_DOM1A0 + 1077)
#define SLIM_TKNAM_DOM1A_offsetHeight	(SLIM_TKNAM_BASE_DOM1A0 + 1077)
#define SLIM_TKLEN_DOM1A_offsetHeight	(12)
#define SLIM_TOKEN_DOM1A_offsetHeight	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_offsetHeight))
#define SLIM_TKOFF_DOM1A_offsetLeft	(SLIM_TKOFF_BASE_DOM1A0 + 1090)
#define SLIM_TKNAM_DOM1A_offsetLeft	(SLIM_TKNAM_BASE_DOM1A0 + 1090)
#define SLIM_TKLEN_DOM1A_offsetLeft	(10)
#define SLIM_TOKEN_DOM1A_offsetLeft	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_offsetLeft))
#define SLIM_TKOFF_DOM1A_offsetParent	(SLIM_TKOFF_BASE_DOM1A0 + 1101)
#define SLIM_TKNAM_DOM1A_offsetParent	(SLIM_TKNAM_BASE_DOM1A0 + 1101)
#define SLIM_TKLEN_DOM1A_offsetParent	(12)
#define SLIM_TOKEN_DOM1A_offsetParent	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_offsetParent))
#define SLIM_TKOFF_DOM1A_offsetTop	(SLIM_TKOFF_BASE_DOM1A0 + 1114)
#define SLIM_TKNAM_DOM1A_offsetTop	(SLIM_TKNAM_BASE_DOM1A0 + 1114)
#define SLIM_TKLEN_DOM1A_offsetTop	(9)
#define SLIM_TOKEN_DOM1A_offsetTop	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_offsetTop))
#define SLIM_TKOFF_DOM1A_offsetWidth	(SLIM_TKOFF_BASE_DOM1A0 + 1124)
#define SLIM_TKNAM_DOM1A_offsetWidth	(SLIM_TKNAM_BASE_DOM1A0 + 1124)
#define SLIM_TKLEN_DOM1A_offsetWidth	(11)
#define SLIM_TOKEN_DOM1A_offsetWidth	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_offsetWidth))
#define SLIM_TKOFF_DOM1A_onblur	(SLIM_TKOFF_BASE_DOM1A0 + 1136)
#define SLIM_TKNAM_DOM1A_onblur	(SLIM_TKNAM_BASE_DOM1A0 + 1136)
#define SLIM_TKLEN_DOM1A_onblur	(6)
#define SLIM_TOKEN_DOM1A_onblur	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onblur))
#define SLIM_TKOFF_DOM1A_onchange	(SLIM_TKOFF_BASE_DOM1A0 + 1143)
#define SLIM_TKNAM_DOM1A_onchange	(SLIM_TKNAM_BASE_DOM1A0 + 1143)
#define SLIM_TKLEN_DOM1A_onchange	(8)
#define SLIM_TOKEN_DOM1A_onchange	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onchange))
#define SLIM_TKOFF_DOM1A_onclick	(SLIM_TKOFF_BASE_DOM1A0 + 1152)
#define SLIM_TKNAM_DOM1A_onclick	(SLIM_TKNAM_BASE_DOM1A0 + 1152)
#define SLIM_TKLEN_DOM1A_onclick	(7)
#define SLIM_TOKEN_DOM1A_onclick	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onclick))
#define SLIM_TKOFF_DOM1A_oncontextmenu	(SLIM_TKOFF_BASE_DOM1A0 + 1160)
#define SLIM_TKNAM_DOM1A_oncontextmenu	(SLIM_TKNAM_BASE_DOM1A0 + 1160)
#define SLIM_TKLEN_DOM1A_oncontextmenu	(13)
#define SLIM_TOKEN_DOM1A_oncontextmenu	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_oncontextmenu))
#define SLIM_TKOFF_DOM1A_ondblclick	(SLIM_TKOFF_BASE_DOM1A0 + 1174)
#define SLIM_TKNAM_DOM1A_ondblclick	(SLIM_TKNAM_BASE_DOM1A0 + 1174)
#define SLIM_TKLEN_DOM1A_ondblclick	(10)
#define SLIM_TOKEN_DOM1A_ondblclick	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_ondblclick))
#define SLIM_TKOFF_DOM1A_onfocus	(SLIM_TKOFF_BASE_DOM1A0 + 1185)
#define SLIM_TKNAM_DOM1A_onfocus	(SLIM_TKNAM_BASE_DOM1A0 + 1185)
#define SLIM_TKLEN_DOM1A_onfocus	(7)
#define SLIM_TOKEN_DOM1A_onfocus	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onfocus))
#define SLIM_TKOFF_DOM1A_onkeydown	(SLIM_TKOFF_BASE_DOM1A0 + 1193)
#define SLIM_TKNAM_DOM1A_onkeydown	(SLIM_TKNAM_BASE_DOM1A0 + 1193)
#define SLIM_TKLEN_DOM1A_onkeydown	(9)
#define SLIM_TOKEN_DOM1A_onkeydown	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onkeydown))
#define SLIM_TKOFF_DOM1A_onkeypress	(SLIM_TKOFF_BASE_DOM1A0 + 1203)
#define SLIM_TKNAM_DOM1A_onkeypress	(SLIM_TKNAM_BASE_DOM1A0 + 1203)
#define SLIM_TKLEN_DOM1A_onkeypress	(10)
#define SLIM_TOKEN_DOM1A_onkeypress	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onkeypress))
#define SLIM_TKOFF_DOM1A_onkeyup	(SLIM_TKOFF_BASE_DOM1A0 + 1214)
#define SLIM_TKNAM_DOM1A_onkeyup	(SLIM_TKNAM_BASE_DOM1A0 + 1214)
#define SLIM_TKLEN_DOM1A_onkeyup	(7)
#define SLIM_TOKEN_DOM1A_onkeyup	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onkeyup))
#define SLIM_TKOFF_DOM1A_onload	(SLIM_TKOFF_BASE_DOM1A0 + 1222)
#define SLIM_TKNAM_DOM1A_onload	(SLIM_TKNAM_BASE_DOM1A0 + 1222)
#define SLIM_TKLEN_DOM1A_onload	(6)
#define SLIM_TOKEN_DOM1A_onload	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onload))
#define SLIM_TKOFF_DOM1A_onmousedown	(SLIM_TKOFF_BASE_DOM1A0 + 1229)
#define SLIM_TKNAM_DOM1A_onmousedown	(SLIM_TKNAM_BASE_DOM1A0 + 1229)
#define SLIM_TKLEN_DOM1A_onmousedown	(11)
#define SLIM_TOKEN_DOM1A_onmousedown	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onmousedown))
#define SLIM_TKOFF_DOM1A_onmousemove	(SLIM_TKOFF_BASE_DOM1A0 + 1241)
#define SLIM_TKNAM_DOM1A_onmousemove	(SLIM_TKNAM_BASE_DOM1A0 + 1241)
#define SLIM_TKLEN_DOM1A_onmousemove	(11)
#define SLIM_TOKEN_DOM1A_onmousemove	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onmousemove))
#define SLIM_TKOFF_DOM1A_onmouseout	(SLIM_TKOFF_BASE_DOM1A0 + 1253)
#define SLIM_TKNAM_DOM1A_onmouseout	(SLIM_TKNAM_BASE_DOM1A0 + 1253)
#define SLIM_TKLEN_DOM1A_onmouseout	(10)
#define SLIM_TOKEN_DOM1A_onmouseout	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onmouseout))
#define SLIM_TKOFF_DOM1A_onmouseover	(SLIM_TKOFF_BASE_DOM1A0 + 1264)
#define SLIM_TKNAM_DOM1A_onmouseover	(SLIM_TKNAM_BASE_DOM1A0 + 1264)
#define SLIM_TKLEN_DOM1A_onmouseover	(11)
#define SLIM_TOKEN_DOM1A_onmouseover	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onmouseover))
#define SLIM_TKOFF_DOM1A_onmouseup	(SLIM_TKOFF_BASE_DOM1A0 + 1276)
#define SLIM_TKNAM_DOM1A_onmouseup	(SLIM_TKNAM_BASE_DOM1A0 + 1276)
#define SLIM_TKLEN_DOM1A_onmouseup	(9)
#define SLIM_TOKEN_DOM1A_onmouseup	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onmouseup))
#define SLIM_TKOFF_DOM1A_onmousewheel	(SLIM_TKOFF_BASE_DOM1A0 + 1286)
#define SLIM_TKNAM_DOM1A_onmousewheel	(SLIM_TKNAM_BASE_DOM1A0 + 1286)
#define SLIM_TKLEN_DOM1A_onmousewheel	(12)
#define SLIM_TOKEN_DOM1A_onmousewheel	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onmousewheel))
#define SLIM_TKOFF_DOM1A_onreset	(SLIM_TKOFF_BASE_DOM1A0 + 1299)
#define SLIM_TKNAM_DOM1A_onreset	(SLIM_TKNAM_BASE_DOM1A0 + 1299)
#define SLIM_TKLEN_DOM1A_onreset	(7)
#define SLIM_TOKEN_DOM1A_onreset	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onreset))
#define SLIM_TKOFF_DOM1A_onselect	(SLIM_TKOFF_BASE_DOM1A0 + 1307)
#define SLIM_TKNAM_DOM1A_onselect	(SLIM_TKNAM_BASE_DOM1A0 + 1307)
#define SLIM_TKLEN_DOM1A_onselect	(8)
#define SLIM_TOKEN_DOM1A_onselect	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onselect))
#define SLIM_TKOFF_DOM1A_onsubmit	(SLIM_TKOFF_BASE_DOM1A0 + 1316)
#define SLIM_TKNAM_DOM1A_onsubmit	(SLIM_TKNAM_BASE_DOM1A0 + 1316)
#define SLIM_TKLEN_DOM1A_onsubmit	(8)
#define SLIM_TOKEN_DOM1A_onsubmit	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onsubmit))
#define SLIM_TKOFF_DOM1A_onunload	(SLIM_TKOFF_BASE_DOM1A0 + 1325)
#define SLIM_TKNAM_DOM1A_onunload	(SLIM_TKNAM_BASE_DOM1A0 + 1325)
#define SLIM_TKLEN_DOM1A_onunload	(8)
#define SLIM_TOKEN_DOM1A_onunload	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_onunload))
#define SLIM_TKOFF_DOM1A_options	(SLIM_TKOFF_BASE_DOM1A0 + 1334)
#define SLIM_TKNAM_DOM1A_options	(SLIM_TKNAM_BASE_DOM1A0 + 1334)
#define SLIM_TKLEN_DOM1A_options	(7)
#define SLIM_TOKEN_DOM1A_options	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_options))
#define SLIM_TKOFF_DOM1A_outerHTML	(SLIM_TKOFF_BASE_DOM1A0 + 1342)
#define SLIM_TKNAM_DOM1A_outerHTML	(SLIM_TKNAM_BASE_DOM1A0 + 1342)
#define SLIM_TKLEN_DOM1A_outerHTML	(9)
#define SLIM_TOKEN_DOM1A_outerHTML	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_outerHTML))
#define SLIM_TKOFF_DOM1A_outerText	(SLIM_TKOFF_BASE_DOM1A0 + 1352)
#define SLIM_TKNAM_DOM1A_outerText	(SLIM_TKNAM_BASE_DOM1A0 + 1352)
#define SLIM_TKLEN_DOM1A_outerText	(9)
#define SLIM_TOKEN_DOM1A_outerText	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_outerText))
#define SLIM_TKOFF_DOM1A_ownerDocument	(SLIM_TKOFF_BASE_DOM1A0 + 1362)
#define SLIM_TKNAM_DOM1A_ownerDocument	(SLIM_TKNAM_BASE_DOM1A0 + 1362)
#define SLIM_TKLEN_DOM1A_ownerDocument	(13)
#define SLIM_TOKEN_DOM1A_ownerDocument	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_ownerDocument))
#define SLIM_TKOFF_DOM1A_ownerElement	(SLIM_TKOFF_BASE_DOM1A0 + 1376)
#define SLIM_TKNAM_DOM1A_ownerElement	(SLIM_TKNAM_BASE_DOM1A0 + 1376)
#define SLIM_TKLEN_DOM1A_ownerElement	(12)
#define SLIM_TOKEN_DOM1A_ownerElement	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_ownerElement))
#define SLIM_TKOFF_DOM1A_parentElement	(SLIM_TKOFF_BASE_DOM1A0 + 1389)
#define SLIM_TKNAM_DOM1A_parentElement	(SLIM_TKNAM_BASE_DOM1A0 + 1389)
#define SLIM_TKLEN_DOM1A_parentElement	(13)
#define SLIM_TOKEN_DOM1A_parentElement	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_parentElement))
#define SLIM_TKOFF_DOM1A_parentNode	(SLIM_TKOFF_BASE_DOM1A0 + 1403)
#define SLIM_TKNAM_DOM1A_parentNode	(SLIM_TKNAM_BASE_DOM1A0 + 1403)
#define SLIM_TKLEN_DOM1A_parentNode	(10)
#define SLIM_TOKEN_DOM1A_parentNode	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_parentNode))
#define SLIM_TKOFF_DOM1A_pathname	(SLIM_TKOFF_BASE_DOM1A0 + 1414)
#define SLIM_TKNAM_DOM1A_pathname	(SLIM_TKNAM_BASE_DOM1A0 + 1414)
#define SLIM_TKLEN_DOM1A_pathname	(8)
#define SLIM_TOKEN_DOM1A_pathname	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_pathname))
#define SLIM_TKOFF_DOM1A_plugins	(SLIM_TKOFF_BASE_DOM1A0 + 1423)
#define SLIM_TKNAM_DOM1A_plugins	(SLIM_TKNAM_BASE_DOM1A0 + 1423)
#define SLIM_TKLEN_DOM1A_plugins	(7)
#define SLIM_TOKEN_DOM1A_plugins	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_plugins))
#define SLIM_TKOFF_DOM1A_port	(SLIM_TKOFF_BASE_DOM1A0 + 1431)
#define SLIM_TKNAM_DOM1A_port	(SLIM_TKNAM_BASE_DOM1A0 + 1431)
#define SLIM_TKLEN_DOM1A_port	(4)
#define SLIM_TOKEN_DOM1A_port	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_port))
#define SLIM_TKOFF_DOM1A_prefix	(SLIM_TKOFF_BASE_DOM1A0 + 1436)
#define SLIM_TKNAM_DOM1A_prefix	(SLIM_TKNAM_BASE_DOM1A0 + 1436)
#define SLIM_TKLEN_DOM1A_prefix	(6)
#define SLIM_TOKEN_DOM1A_prefix	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_prefix))
#define SLIM_TKOFF_DOM1A_previousSibling	(SLIM_TKOFF_BASE_DOM1A0 + 1443)
#define SLIM_TKNAM_DOM1A_previousSibling	(SLIM_TKNAM_BASE_DOM1A0 + 1443)
#define SLIM_TKLEN_DOM1A_previousSibling	(15)
#define SLIM_TOKEN_DOM1A_previousSibling	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_previousSibling))
#define SLIM_TKOFF_DOM1A_profile	(SLIM_TKOFF_BASE_DOM1A0 + 1459)
#define SLIM_TKNAM_DOM1A_profile	(SLIM_TKNAM_BASE_DOM1A0 + 1459)
#define SLIM_TKLEN_DOM1A_profile	(7)
#define SLIM_TOKEN_DOM1A_profile	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_profile))
#define SLIM_TKOFF_DOM1A_prompt	(SLIM_TKOFF_BASE_DOM1A0 + 1467)
#define SLIM_TKNAM_DOM1A_prompt	(SLIM_TKNAM_BASE_DOM1A0 + 1467)
#define SLIM_TKLEN_DOM1A_prompt	(6)
#define SLIM_TOKEN_DOM1A_prompt	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_prompt))
#define SLIM_TKOFF_DOM1A_protocol	(SLIM_TKOFF_BASE_DOM1A0 + 1474)
#define SLIM_TKNAM_DOM1A_protocol	(SLIM_TKNAM_BASE_DOM1A0 + 1474)
#define SLIM_TKLEN_DOM1A_protocol	(8)
#define SLIM_TOKEN_DOM1A_protocol	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_protocol))
#define SLIM_TKOFF_DOM1A_publicId	(SLIM_TKOFF_BASE_DOM1A0 + 1483)
#define SLIM_TKNAM_DOM1A_publicId	(SLIM_TKNAM_BASE_DOM1A0 + 1483)
#define SLIM_TKLEN_DOM1A_publicId	(8)
#define SLIM_TOKEN_DOM1A_publicId	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_publicId))
#define SLIM_TKOFF_DOM1A_readOnly	(SLIM_TKOFF_BASE_DOM1A0 + 1492)
#define SLIM_TKNAM_DOM1A_readOnly	(SLIM_TKNAM_BASE_DOM1A0 + 1492)
#define SLIM_TKLEN_DOM1A_readOnly	(8)
#define SLIM_TOKEN_DOM1A_readOnly	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_readOnly))
#define SLIM_TKOFF_DOM1A_referrer	(SLIM_TKOFF_BASE_DOM1A0 + 1501)
#define SLIM_TKNAM_DOM1A_referrer	(SLIM_TKNAM_BASE_DOM1A0 + 1501)
#define SLIM_TKLEN_DOM1A_referrer	(8)
#define SLIM_TOKEN_DOM1A_referrer	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_referrer))
#define SLIM_TKOFF_DOM1A_rel	(SLIM_TKOFF_BASE_DOM1A0 + 1510)
#define SLIM_TKNAM_DOM1A_rel	(SLIM_TKNAM_BASE_DOM1A0 + 1510)
#define SLIM_TKLEN_DOM1A_rel	(3)
#define SLIM_TOKEN_DOM1A_rel	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_rel))
#define SLIM_TKOFF_DOM1A_rev	(SLIM_TKOFF_BASE_DOM1A0 + 1514)
#define SLIM_TKNAM_DOM1A_rev	(SLIM_TKNAM_BASE_DOM1A0 + 1514)
#define SLIM_TKLEN_DOM1A_rev	(3)
#define SLIM_TOKEN_DOM1A_rev	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_rev))
#define SLIM_TKOFF_DOM1A_rowIndex	(SLIM_TKOFF_BASE_DOM1A0 + 1518)
#define SLIM_TKNAM_DOM1A_rowIndex	(SLIM_TKNAM_BASE_DOM1A0 + 1518)
#define SLIM_TKLEN_DOM1A_rowIndex	(8)
#define SLIM_TOKEN_DOM1A_rowIndex	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_rowIndex))
#define SLIM_TKOFF_DOM1A_rowSpan	(SLIM_TKOFF_BASE_DOM1A0 + 1527)
#define SLIM_TKNAM_DOM1A_rowSpan	(SLIM_TKNAM_BASE_DOM1A0 + 1527)
#define SLIM_TKLEN_DOM1A_rowSpan	(7)
#define SLIM_TOKEN_DOM1A_rowSpan	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_rowSpan))
#define SLIM_TKOFF_DOM1A_rows	(SLIM_TKOFF_BASE_DOM1A0 + 1535)
#define SLIM_TKNAM_DOM1A_rows	(SLIM_TKNAM_BASE_DOM1A0 + 1535)
#define SLIM_TKLEN_DOM1A_rows	(4)
#define SLIM_TOKEN_DOM1A_rows	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_rows))
#define SLIM_TKOFF_DOM1A_rules	(SLIM_TKOFF_BASE_DOM1A0 + 1540)
#define SLIM_TKNAM_DOM1A_rules	(SLIM_TKNAM_BASE_DOM1A0 + 1540)
#define SLIM_TKLEN_DOM1A_rules	(5)
#define SLIM_TOKEN_DOM1A_rules	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_rules))
#define SLIM_TKOFF_DOM1A_scheme	(SLIM_TKOFF_BASE_DOM1A0 + 1546)
#define SLIM_TKNAM_DOM1A_scheme	(SLIM_TKNAM_BASE_DOM1A0 + 1546)
#define SLIM_TKLEN_DOM1A_scheme	(6)
#define SLIM_TOKEN_DOM1A_scheme	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_scheme))
#define SLIM_TKOFF_DOM1A_scope	(SLIM_TKOFF_BASE_DOM1A0 + 1553)
#define SLIM_TKNAM_DOM1A_scope	(SLIM_TKNAM_BASE_DOM1A0 + 1553)
#define SLIM_TKLEN_DOM1A_scope	(5)
#define SLIM_TOKEN_DOM1A_scope	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_scope))
#define SLIM_TKOFF_DOM1A_scrollHeight	(SLIM_TKOFF_BASE_DOM1A0 + 1559)
#define SLIM_TKNAM_DOM1A_scrollHeight	(SLIM_TKNAM_BASE_DOM1A0 + 1559)
#define SLIM_TKLEN_DOM1A_scrollHeight	(12)
#define SLIM_TOKEN_DOM1A_scrollHeight	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_scrollHeight))
#define SLIM_TKOFF_DOM1A_scrollLeft	(SLIM_TKOFF_BASE_DOM1A0 + 1572)
#define SLIM_TKNAM_DOM1A_scrollLeft	(SLIM_TKNAM_BASE_DOM1A0 + 1572)
#define SLIM_TKLEN_DOM1A_scrollLeft	(10)
#define SLIM_TOKEN_DOM1A_scrollLeft	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_scrollLeft))
#define SLIM_TKOFF_DOM1A_scrollTop	(SLIM_TKOFF_BASE_DOM1A0 + 1583)
#define SLIM_TKNAM_DOM1A_scrollTop	(SLIM_TKNAM_BASE_DOM1A0 + 1583)
#define SLIM_TKLEN_DOM1A_scrollTop	(9)
#define SLIM_TOKEN_DOM1A_scrollTop	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_scrollTop))
#define SLIM_TKOFF_DOM1A_scrollWidth	(SLIM_TKOFF_BASE_DOM1A0 + 1593)
#define SLIM_TKNAM_DOM1A_scrollWidth	(SLIM_TKNAM_BASE_DOM1A0 + 1593)
#define SLIM_TKLEN_DOM1A_scrollWidth	(11)
#define SLIM_TOKEN_DOM1A_scrollWidth	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_scrollWidth))
#define SLIM_TKOFF_DOM1A_scrolling	(SLIM_TKOFF_BASE_DOM1A0 + 1605)
#define SLIM_TKNAM_DOM1A_scrolling	(SLIM_TKNAM_BASE_DOM1A0 + 1605)
#define SLIM_TKLEN_DOM1A_scrolling	(9)
#define SLIM_TOKEN_DOM1A_scrolling	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_scrolling))
#define SLIM_TKOFF_DOM1A_search	(SLIM_TKOFF_BASE_DOM1A0 + 1615)
#define SLIM_TKNAM_DOM1A_search	(SLIM_TKNAM_BASE_DOM1A0 + 1615)
#define SLIM_TKLEN_DOM1A_search	(6)
#define SLIM_TOKEN_DOM1A_search	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_search))
#define SLIM_TKOFF_DOM1A_sectionRowIndex	(SLIM_TKOFF_BASE_DOM1A0 + 1622)
#define SLIM_TKNAM_DOM1A_sectionRowIndex	(SLIM_TKNAM_BASE_DOM1A0 + 1622)
#define SLIM_TKLEN_DOM1A_sectionRowIndex	(15)
#define SLIM_TOKEN_DOM1A_sectionRowIndex	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_sectionRowIndex))
#define SLIM_TKOFF_DOM1A_selected	(SLIM_TKOFF_BASE_DOM1A0 + 1638)
#define SLIM_TKNAM_DOM1A_selected	(SLIM_TKNAM_BASE_DOM1A0 + 1638)
#define SLIM_TKLEN_DOM1A_selected	(8)
#define SLIM_TOKEN_DOM1A_selected	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_selected))
#define SLIM_TKOFF_DOM1A_selectedIndex	(SLIM_TKOFF_BASE_DOM1A0 + 1647)
#define SLIM_TKNAM_DOM1A_selectedIndex	(SLIM_TKNAM_BASE_DOM1A0 + 1647)
#define SLIM_TKLEN_DOM1A_selectedIndex	(13)
#define SLIM_TOKEN_DOM1A_selectedIndex	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_selectedIndex))
#define SLIM_TKOFF_DOM1A_shape	(SLIM_TKOFF_BASE_DOM1A0 + 1661)
#define SLIM_TKNAM_DOM1A_shape	(SLIM_TKNAM_BASE_DOM1A0 + 1661)
#define SLIM_TKLEN_DOM1A_shape	(5)
#define SLIM_TOKEN_DOM1A_shape	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_shape))
#define SLIM_TKOFF_DOM1A_size	(SLIM_TKOFF_BASE_DOM1A0 + 1667)
#define SLIM_TKNAM_DOM1A_size	(SLIM_TKNAM_BASE_DOM1A0 + 1667)
#define SLIM_TKLEN_DOM1A_size	(4)
#define SLIM_TOKEN_DOM1A_size	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_size))
#define SLIM_TKOFF_DOM1A_span	(SLIM_TKOFF_BASE_DOM1A0 + 1672)
#define SLIM_TKNAM_DOM1A_span	(SLIM_TKNAM_BASE_DOM1A0 + 1672)
#define SLIM_TKLEN_DOM1A_span	(4)
#define SLIM_TOKEN_DOM1A_span	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_span))
#define SLIM_TKOFF_DOM1A_specified	(SLIM_TKOFF_BASE_DOM1A0 + 1677)
#define SLIM_TKNAM_DOM1A_specified	(SLIM_TKNAM_BASE_DOM1A0 + 1677)
#define SLIM_TKLEN_DOM1A_specified	(9)
#define SLIM_TOKEN_DOM1A_specified	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_specified))
#define SLIM_TKOFF_DOM1A_src	(SLIM_TKOFF_BASE_DOM1A0 + 1687)
#define SLIM_TKNAM_DOM1A_src	(SLIM_TKNAM_BASE_DOM1A0 + 1687)
#define SLIM_TKLEN_DOM1A_src	(3)
#define SLIM_TOKEN_DOM1A_src	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_src))
#define SLIM_TKOFF_DOM1A_standby	(SLIM_TKOFF_BASE_DOM1A0 + 1691)
#define SLIM_TKNAM_DOM1A_standby	(SLIM_TKNAM_BASE_DOM1A0 + 1691)
#define SLIM_TKLEN_DOM1A_standby	(7)
#define SLIM_TOKEN_DOM1A_standby	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_standby))
#define SLIM_TKOFF_DOM1A_start	(SLIM_TKOFF_BASE_DOM1A0 + 1699)
#define SLIM_TKNAM_DOM1A_start	(SLIM_TKNAM_BASE_DOM1A0 + 1699)
#define SLIM_TKLEN_DOM1A_start	(5)
#define SLIM_TOKEN_DOM1A_start	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_start))
#define SLIM_TKOFF_DOM1A_style	(SLIM_TKOFF_BASE_DOM1A0 + 1705)
#define SLIM_TKNAM_DOM1A_style	(SLIM_TKNAM_BASE_DOM1A0 + 1705)
#define SLIM_TKLEN_DOM1A_style	(5)
#define SLIM_TOKEN_DOM1A_style	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_style))
#define SLIM_TKOFF_DOM1A_styleSheets	(SLIM_TKOFF_BASE_DOM1A0 + 1711)
#define SLIM_TKNAM_DOM1A_styleSheets	(SLIM_TKNAM_BASE_DOM1A0 + 1711)
#define SLIM_TKLEN_DOM1A_styleSheets	(11)
#define SLIM_TOKEN_DOM1A_styleSheets	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_styleSheets))
#define SLIM_TKOFF_DOM1A_summary	(SLIM_TKOFF_BASE_DOM1A0 + 1723)
#define SLIM_TKNAM_DOM1A_summary	(SLIM_TKNAM_BASE_DOM1A0 + 1723)
#define SLIM_TKLEN_DOM1A_summary	(7)
#define SLIM_TOKEN_DOM1A_summary	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_summary))
#define SLIM_TKOFF_DOM1A_systemId	(SLIM_TKOFF_BASE_DOM1A0 + 1731)
#define SLIM_TKNAM_DOM1A_systemId	(SLIM_TKNAM_BASE_DOM1A0 + 1731)
#define SLIM_TKLEN_DOM1A_systemId	(8)
#define SLIM_TOKEN_DOM1A_systemId	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_systemId))
#define SLIM_TKOFF_DOM1A_tBodies	(SLIM_TKOFF_BASE_DOM1A0 + 1740)
#define SLIM_TKNAM_DOM1A_tBodies	(SLIM_TKNAM_BASE_DOM1A0 + 1740)
#define SLIM_TKLEN_DOM1A_tBodies	(7)
#define SLIM_TOKEN_DOM1A_tBodies	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_tBodies))
#define SLIM_TKOFF_DOM1A_tFoot	(SLIM_TKOFF_BASE_DOM1A0 + 1748)
#define SLIM_TKNAM_DOM1A_tFoot	(SLIM_TKNAM_BASE_DOM1A0 + 1748)
#define SLIM_TKLEN_DOM1A_tFoot	(5)
#define SLIM_TOKEN_DOM1A_tFoot	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_tFoot))
#define SLIM_TKOFF_DOM1A_tHead	(SLIM_TKOFF_BASE_DOM1A0 + 1754)
#define SLIM_TKNAM_DOM1A_tHead	(SLIM_TKNAM_BASE_DOM1A0 + 1754)
#define SLIM_TKLEN_DOM1A_tHead	(5)
#define SLIM_TOKEN_DOM1A_tHead	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_tHead))
#define SLIM_TKOFF_DOM1A_tabIndex	(SLIM_TKOFF_BASE_DOM1A0 + 1760)
#define SLIM_TKNAM_DOM1A_tabIndex	(SLIM_TKNAM_BASE_DOM1A0 + 1760)
#define SLIM_TKLEN_DOM1A_tabIndex	(8)
#define SLIM_TOKEN_DOM1A_tabIndex	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_tabIndex))
#define SLIM_TKOFF_DOM1A_tagName	(SLIM_TKOFF_BASE_DOM1A0 + 1769)
#define SLIM_TKNAM_DOM1A_tagName	(SLIM_TKNAM_BASE_DOM1A0 + 1769)
#define SLIM_TKLEN_DOM1A_tagName	(7)
#define SLIM_TOKEN_DOM1A_tagName	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_tagName))
#define SLIM_TKOFF_DOM1A_target	(SLIM_TKOFF_BASE_DOM1A0 + 1777)
#define SLIM_TKNAM_DOM1A_target	(SLIM_TKNAM_BASE_DOM1A0 + 1777)
#define SLIM_TKLEN_DOM1A_target	(6)
#define SLIM_TOKEN_DOM1A_target	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_target))
#define SLIM_TKOFF_DOM1A_text	(SLIM_TKOFF_BASE_DOM1A0 + 1784)
#define SLIM_TKNAM_DOM1A_text	(SLIM_TKNAM_BASE_DOM1A0 + 1784)
#define SLIM_TKLEN_DOM1A_text	(4)
#define SLIM_TOKEN_DOM1A_text	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_text))
#define SLIM_TKOFF_DOM1A_textContent	(SLIM_TKOFF_BASE_DOM1A0 + 1789)
#define SLIM_TKNAM_DOM1A_textContent	(SLIM_TKNAM_BASE_DOM1A0 + 1789)
#define SLIM_TKLEN_DOM1A_textContent	(11)
#define SLIM_TOKEN_DOM1A_textContent	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_textContent))
#define SLIM_TKOFF_DOM1A_title	(SLIM_TKOFF_BASE_DOM1A0 + 1801)
#define SLIM_TKNAM_DOM1A_title	(SLIM_TKNAM_BASE_DOM1A0 + 1801)
#define SLIM_TKLEN_DOM1A_title	(5)
#define SLIM_TOKEN_DOM1A_title	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_title))
#define SLIM_TKOFF_DOM1A_type	(SLIM_TKOFF_BASE_DOM1A0 + 1807)
#define SLIM_TKNAM_DOM1A_type	(SLIM_TKNAM_BASE_DOM1A0 + 1807)
#define SLIM_TKLEN_DOM1A_type	(4)
#define SLIM_TOKEN_DOM1A_type	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_type))
#define SLIM_TKOFF_DOM1A_useMap	(SLIM_TKOFF_BASE_DOM1A0 + 1812)
#define SLIM_TKNAM_DOM1A_useMap	(SLIM_TKNAM_BASE_DOM1A0 + 1812)
#define SLIM_TKLEN_DOM1A_useMap	(6)
#define SLIM_TOKEN_DOM1A_useMap	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_useMap))
#define SLIM_TKOFF_DOM1A_vAlign	(SLIM_TKOFF_BASE_DOM1A0 + 1819)
#define SLIM_TKNAM_DOM1A_vAlign	(SLIM_TKNAM_BASE_DOM1A0 + 1819)
#define SLIM_TKLEN_DOM1A_vAlign	(6)
#define SLIM_TOKEN_DOM1A_vAlign	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_vAlign))
#define SLIM_TKOFF_DOM1A_vLink	(SLIM_TKOFF_BASE_DOM1A0 + 1826)
#define SLIM_TKNAM_DOM1A_vLink	(SLIM_TKNAM_BASE_DOM1A0 + 1826)
#define SLIM_TKLEN_DOM1A_vLink	(5)
#define SLIM_TOKEN_DOM1A_vLink	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_vLink))
#define SLIM_TKOFF_DOM1A_value	(SLIM_TKOFF_BASE_DOM1A0 + 1832)
#define SLIM_TKNAM_DOM1A_value	(SLIM_TKNAM_BASE_DOM1A0 + 1832)
#define SLIM_TKLEN_DOM1A_value	(5)
#define SLIM_TOKEN_DOM1A_value	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_value))
#define SLIM_TKOFF_DOM1A_valueType	(SLIM_TKOFF_BASE_DOM1A0 + 1838)
#define SLIM_TKNAM_DOM1A_valueType	(SLIM_TKNAM_BASE_DOM1A0 + 1838)
#define SLIM_TKLEN_DOM1A_valueType	(9)
#define SLIM_TOKEN_DOM1A_valueType	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_valueType))
#define SLIM_TKOFF_DOM1A_version	(SLIM_TKOFF_BASE_DOM1A0 + 1848)
#define SLIM_TKNAM_DOM1A_version	(SLIM_TKNAM_BASE_DOM1A0 + 1848)
#define SLIM_TKLEN_DOM1A_version	(7)
#define SLIM_TOKEN_DOM1A_version	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_version))
#define SLIM_TKOFF_DOM1A_vlinkColor	(SLIM_TKOFF_BASE_DOM1A0 + 1856)
#define SLIM_TKNAM_DOM1A_vlinkColor	(SLIM_TKNAM_BASE_DOM1A0 + 1856)
#define SLIM_TKLEN_DOM1A_vlinkColor	(10)
#define SLIM_TOKEN_DOM1A_vlinkColor	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_vlinkColor))
#define SLIM_TKOFF_DOM1A_vspace	(SLIM_TKOFF_BASE_DOM1A0 + 1867)
#define SLIM_TKNAM_DOM1A_vspace	(SLIM_TKNAM_BASE_DOM1A0 + 1867)
#define SLIM_TKLEN_DOM1A_vspace	(6)
#define SLIM_TOKEN_DOM1A_vspace	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_vspace))
#define SLIM_TKOFF_DOM1A_width	(SLIM_TKOFF_BASE_DOM1A0 + 1874)
#define SLIM_TKNAM_DOM1A_width	(SLIM_TKNAM_BASE_DOM1A0 + 1874)
#define SLIM_TKLEN_DOM1A_width	(5)
#define SLIM_TOKEN_DOM1A_width	(DOM1AttrInfo_GetItem(SLIM_TKID_DOM1A_width))
#define SLIM_TKOFF_BASE_DOM1A1	(SLIM_TKOFF_BASE_DOM1A0 + 1880)
#define SLIM_TKNAM_BASE_DOM1A1	(SLIM_TKNAM_BASE_DOM1A0 + SLIM_TKOFF_BASE_DOM1A1)
#define SLIM_TKLEN_TOTAL_DOM1A	SLIM_TKOFF_BASE_DOM1A1

extern SLIM_ROM slim_char cSlim_TokenName_DOM1A[SLIM_TKLEN_TOTAL_DOM1A];

extern SLIM_ROM TDOM1AttrInfo cSlim_Token_DOM1A[SLIM_TOKEN_DOM1A_TOKENS];
#define DOM1AttrInfo_GetItem(id)		((TDOM1AttrInfo *)&cSlim_Token_DOM1A[(id)])
#define DOM1AttrInfo_GetItemName(id)	((slim_char *)cSlim_TokenName_DOM1A + ((TToken *)&cSlim_Token_DOM1A[(id)])->fOffset)
#define DOM1AttrInfo_GetItemNameLen(id)	(((TToken *)&cSlim_Token_DOM1A[(id)])->fLength)

TDOM1AttrInfo *DOM1AttrInfo_CaseFindSS(slim_char *in_s, slim_int in_slen);

SLIM_END_C_LINKAGE
#endif
