/*
	dom2aid.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/private/token/dom2aid.h 6     06/07/26 22:21 Endoh $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_DOM2AID_H
#define SLIM_TOKEN_DOM2AID_H


SLIM_BEGIN_C_LINKAGE

enum {
	SLIM_TKID_DOM2A_azimuth = 0,
	SLIM_TKID_DOM2A_background,
	SLIM_TKID_DOM2A_backgroundAttachment,
	SLIM_TKID_DOM2A_backgroundColor,
	SLIM_TKID_DOM2A_backgroundImage,
	SLIM_TKID_DOM2A_backgroundPosition,
	SLIM_TKID_DOM2A_backgroundRepeat,
	SLIM_TKID_DOM2A_border,
	SLIM_TKID_DOM2A_borderBottom,
	SLIM_TKID_DOM2A_borderBottomColor,
	SLIM_TKID_DOM2A_borderBottomStyle,
	SLIM_TKID_DOM2A_borderBottomWidth,
	SLIM_TKID_DOM2A_borderCollapse,
	SLIM_TKID_DOM2A_borderColor,
	SLIM_TKID_DOM2A_borderLeft,
	SLIM_TKID_DOM2A_borderLeftColor,
	SLIM_TKID_DOM2A_borderLeftStyle,
	SLIM_TKID_DOM2A_borderLeftWidth,
	SLIM_TKID_DOM2A_borderRight,
	SLIM_TKID_DOM2A_borderRightColor,
	SLIM_TKID_DOM2A_borderRightStyle,
	SLIM_TKID_DOM2A_borderRightWidth,
	SLIM_TKID_DOM2A_borderSpacing,
	SLIM_TKID_DOM2A_borderStyle,
	SLIM_TKID_DOM2A_borderTop,
	SLIM_TKID_DOM2A_borderTopColor,
	SLIM_TKID_DOM2A_borderTopStyle,
	SLIM_TKID_DOM2A_borderTopWidth,
	SLIM_TKID_DOM2A_borderWidth,
	SLIM_TKID_DOM2A_bottom,
	SLIM_TKID_DOM2A_captionSide,
	SLIM_TKID_DOM2A_clear,
	SLIM_TKID_DOM2A_clip,
	SLIM_TKID_DOM2A_color,
	SLIM_TKID_DOM2A_content,
	SLIM_TKID_DOM2A_counterIncrement,
	SLIM_TKID_DOM2A_counterReset,
	SLIM_TKID_DOM2A_cssFloat,
	SLIM_TKID_DOM2A_cue,
	SLIM_TKID_DOM2A_cueAfter,
	SLIM_TKID_DOM2A_cueBefore,
	SLIM_TKID_DOM2A_cursor,
	SLIM_TKID_DOM2A_direction,
	SLIM_TKID_DOM2A_disabled,
	SLIM_TKID_DOM2A_display,
	SLIM_TKID_DOM2A_elevation,
	SLIM_TKID_DOM2A_emptyCells,
	SLIM_TKID_DOM2A_font,
	SLIM_TKID_DOM2A_fontFamily,
	SLIM_TKID_DOM2A_fontSize,
	SLIM_TKID_DOM2A_fontSizeAdjust,
	SLIM_TKID_DOM2A_fontStretch,
	SLIM_TKID_DOM2A_fontStyle,
	SLIM_TKID_DOM2A_fontVariant,
	SLIM_TKID_DOM2A_fontWeight,
	SLIM_TKID_DOM2A_height,
	SLIM_TKID_DOM2A_href,
	SLIM_TKID_DOM2A_left,
	SLIM_TKID_DOM2A_length,
	SLIM_TKID_DOM2A_letterSpacing,
	SLIM_TKID_DOM2A_lineHeight,
	SLIM_TKID_DOM2A_listStyle,
	SLIM_TKID_DOM2A_listStyleImage,
	SLIM_TKID_DOM2A_listStylePosition,
	SLIM_TKID_DOM2A_listStyleType,
	SLIM_TKID_DOM2A_margin,
	SLIM_TKID_DOM2A_marginBottom,
	SLIM_TKID_DOM2A_marginLeft,
	SLIM_TKID_DOM2A_marginRight,
	SLIM_TKID_DOM2A_marginTop,
	SLIM_TKID_DOM2A_markerOffset,
	SLIM_TKID_DOM2A_marks,
	SLIM_TKID_DOM2A_maxHeight,
	SLIM_TKID_DOM2A_maxWidth,
	SLIM_TKID_DOM2A_media,
	SLIM_TKID_DOM2A_mediaText,
	SLIM_TKID_DOM2A_minHeight,
	SLIM_TKID_DOM2A_minWidth,
	SLIM_TKID_DOM2A_orphans,
	SLIM_TKID_DOM2A_outline,
	SLIM_TKID_DOM2A_outlineColor,
	SLIM_TKID_DOM2A_outlineStyle,
	SLIM_TKID_DOM2A_outlineWidth,
	SLIM_TKID_DOM2A_overflow,
	SLIM_TKID_DOM2A_ownerNode,
	SLIM_TKID_DOM2A_padding,
	SLIM_TKID_DOM2A_paddingBottom,
	SLIM_TKID_DOM2A_paddingLeft,
	SLIM_TKID_DOM2A_paddingRight,
	SLIM_TKID_DOM2A_paddingTop,
	SLIM_TKID_DOM2A_page,
	SLIM_TKID_DOM2A_pageBreakAfter,
	SLIM_TKID_DOM2A_pageBreakBefore,
	SLIM_TKID_DOM2A_pageBreakInside,
	SLIM_TKID_DOM2A_parentStyleSheet,
	SLIM_TKID_DOM2A_pause,
	SLIM_TKID_DOM2A_pauseAfter,
	SLIM_TKID_DOM2A_pauseBefore,
	SLIM_TKID_DOM2A_pitch,
	SLIM_TKID_DOM2A_pitchRange,
	SLIM_TKID_DOM2A_playDuring,
	SLIM_TKID_DOM2A_position,
	SLIM_TKID_DOM2A_quotes,
	SLIM_TKID_DOM2A_richness,
	SLIM_TKID_DOM2A_right,
	SLIM_TKID_DOM2A_size,
	SLIM_TKID_DOM2A_speak,
	SLIM_TKID_DOM2A_speakHeader,
	SLIM_TKID_DOM2A_speakNumeral,
	SLIM_TKID_DOM2A_speakPunctuation,
	SLIM_TKID_DOM2A_speechRate,
	SLIM_TKID_DOM2A_stress,
	SLIM_TKID_DOM2A_styleFloat,
	SLIM_TKID_DOM2A_tableLayout,
	SLIM_TKID_DOM2A_textAlign,
	SLIM_TKID_DOM2A_textDecoration,
	SLIM_TKID_DOM2A_textIndent,
	SLIM_TKID_DOM2A_textShadow,
	SLIM_TKID_DOM2A_textTransform,
	SLIM_TKID_DOM2A_title,
	SLIM_TKID_DOM2A_top,
	SLIM_TKID_DOM2A_type,
	SLIM_TKID_DOM2A_unicodeBidi,
	SLIM_TKID_DOM2A_verticalAlign,
	SLIM_TKID_DOM2A_visibility,
	SLIM_TKID_DOM2A_voiceFamily,
	SLIM_TKID_DOM2A_volume,
	SLIM_TKID_DOM2A_whiteSpace,
	SLIM_TKID_DOM2A_widows,
	SLIM_TKID_DOM2A_width,
	SLIM_TKID_DOM2A_wordSpacing,
	SLIM_TKID_DOM2A_zIndex,
	SLIM_TKID_DOM2A_ENUMS
};

#define SLIM_TOKEN_DOM2A_TOKENS SLIM_TKID_DOM2A_ENUMS
#define SLIM_TOKEN_DOM2A_ENUMS SLIM_TKID_DOM2A_ENUMS


SLIM_END_C_LINKAGE
#endif
