/*
	dom2a.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/private/token/dom2a.h 25    06/07/26 22:21 Endoh $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_DOM2A_H
#define SLIM_TOKEN_DOM2A_H

#include <slim/basis/base.h>
#include <slim/basis/token.h>
#include <slim/private/token/dom2aid.h>

SLIM_BEGIN_C_LINKAGE

#include <slim/www/dom.h>

void TDOMModuleEntry_SetDOM2AttrProcTable(TDOMModuleEntry *self);

struct TDOM2AttrInfo_ {
    TToken fBase;	/* must be the first field */
    slim_int fType;
    slim_int fAttrIFType;
    slim_int fFlags[1];
};
typedef struct TDOM2AttrInfo_ TDOM2AttrInfo;

#define SLIM_TKOFF_BASE_DOM2A0	(0)
#define SLIM_TKNAM_BASE_DOM2A0	((slim_char *)cSlim_TokenName_DOM2A)
#define SLIM_TKOFF_DOM2A_azimuth	(SLIM_TKOFF_BASE_DOM2A0 + 0)
#define SLIM_TKNAM_DOM2A_azimuth	(SLIM_TKNAM_BASE_DOM2A0 + 0)
#define SLIM_TKLEN_DOM2A_azimuth	(7)
#define SLIM_TOKEN_DOM2A_azimuth	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_azimuth))
#define SLIM_TKOFF_DOM2A_background	(SLIM_TKOFF_BASE_DOM2A0 + 8)
#define SLIM_TKNAM_DOM2A_background	(SLIM_TKNAM_BASE_DOM2A0 + 8)
#define SLIM_TKLEN_DOM2A_background	(10)
#define SLIM_TOKEN_DOM2A_background	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_background))
#define SLIM_TKOFF_DOM2A_backgroundAttachment	(SLIM_TKOFF_BASE_DOM2A0 + 19)
#define SLIM_TKNAM_DOM2A_backgroundAttachment	(SLIM_TKNAM_BASE_DOM2A0 + 19)
#define SLIM_TKLEN_DOM2A_backgroundAttachment	(20)
#define SLIM_TOKEN_DOM2A_backgroundAttachment	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_backgroundAttachment))
#define SLIM_TKOFF_DOM2A_backgroundColor	(SLIM_TKOFF_BASE_DOM2A0 + 40)
#define SLIM_TKNAM_DOM2A_backgroundColor	(SLIM_TKNAM_BASE_DOM2A0 + 40)
#define SLIM_TKLEN_DOM2A_backgroundColor	(15)
#define SLIM_TOKEN_DOM2A_backgroundColor	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_backgroundColor))
#define SLIM_TKOFF_DOM2A_backgroundImage	(SLIM_TKOFF_BASE_DOM2A0 + 56)
#define SLIM_TKNAM_DOM2A_backgroundImage	(SLIM_TKNAM_BASE_DOM2A0 + 56)
#define SLIM_TKLEN_DOM2A_backgroundImage	(15)
#define SLIM_TOKEN_DOM2A_backgroundImage	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_backgroundImage))
#define SLIM_TKOFF_DOM2A_backgroundPosition	(SLIM_TKOFF_BASE_DOM2A0 + 72)
#define SLIM_TKNAM_DOM2A_backgroundPosition	(SLIM_TKNAM_BASE_DOM2A0 + 72)
#define SLIM_TKLEN_DOM2A_backgroundPosition	(18)
#define SLIM_TOKEN_DOM2A_backgroundPosition	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_backgroundPosition))
#define SLIM_TKOFF_DOM2A_backgroundRepeat	(SLIM_TKOFF_BASE_DOM2A0 + 91)
#define SLIM_TKNAM_DOM2A_backgroundRepeat	(SLIM_TKNAM_BASE_DOM2A0 + 91)
#define SLIM_TKLEN_DOM2A_backgroundRepeat	(16)
#define SLIM_TOKEN_DOM2A_backgroundRepeat	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_backgroundRepeat))
#define SLIM_TKOFF_DOM2A_border	(SLIM_TKOFF_BASE_DOM2A0 + 108)
#define SLIM_TKNAM_DOM2A_border	(SLIM_TKNAM_BASE_DOM2A0 + 108)
#define SLIM_TKLEN_DOM2A_border	(6)
#define SLIM_TOKEN_DOM2A_border	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_border))
#define SLIM_TKOFF_DOM2A_borderBottom	(SLIM_TKOFF_BASE_DOM2A0 + 115)
#define SLIM_TKNAM_DOM2A_borderBottom	(SLIM_TKNAM_BASE_DOM2A0 + 115)
#define SLIM_TKLEN_DOM2A_borderBottom	(12)
#define SLIM_TOKEN_DOM2A_borderBottom	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderBottom))
#define SLIM_TKOFF_DOM2A_borderBottomColor	(SLIM_TKOFF_BASE_DOM2A0 + 128)
#define SLIM_TKNAM_DOM2A_borderBottomColor	(SLIM_TKNAM_BASE_DOM2A0 + 128)
#define SLIM_TKLEN_DOM2A_borderBottomColor	(17)
#define SLIM_TOKEN_DOM2A_borderBottomColor	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderBottomColor))
#define SLIM_TKOFF_DOM2A_borderBottomStyle	(SLIM_TKOFF_BASE_DOM2A0 + 146)
#define SLIM_TKNAM_DOM2A_borderBottomStyle	(SLIM_TKNAM_BASE_DOM2A0 + 146)
#define SLIM_TKLEN_DOM2A_borderBottomStyle	(17)
#define SLIM_TOKEN_DOM2A_borderBottomStyle	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderBottomStyle))
#define SLIM_TKOFF_DOM2A_borderBottomWidth	(SLIM_TKOFF_BASE_DOM2A0 + 164)
#define SLIM_TKNAM_DOM2A_borderBottomWidth	(SLIM_TKNAM_BASE_DOM2A0 + 164)
#define SLIM_TKLEN_DOM2A_borderBottomWidth	(17)
#define SLIM_TOKEN_DOM2A_borderBottomWidth	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderBottomWidth))
#define SLIM_TKOFF_DOM2A_borderCollapse	(SLIM_TKOFF_BASE_DOM2A0 + 182)
#define SLIM_TKNAM_DOM2A_borderCollapse	(SLIM_TKNAM_BASE_DOM2A0 + 182)
#define SLIM_TKLEN_DOM2A_borderCollapse	(14)
#define SLIM_TOKEN_DOM2A_borderCollapse	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderCollapse))
#define SLIM_TKOFF_DOM2A_borderColor	(SLIM_TKOFF_BASE_DOM2A0 + 197)
#define SLIM_TKNAM_DOM2A_borderColor	(SLIM_TKNAM_BASE_DOM2A0 + 197)
#define SLIM_TKLEN_DOM2A_borderColor	(11)
#define SLIM_TOKEN_DOM2A_borderColor	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderColor))
#define SLIM_TKOFF_DOM2A_borderLeft	(SLIM_TKOFF_BASE_DOM2A0 + 209)
#define SLIM_TKNAM_DOM2A_borderLeft	(SLIM_TKNAM_BASE_DOM2A0 + 209)
#define SLIM_TKLEN_DOM2A_borderLeft	(10)
#define SLIM_TOKEN_DOM2A_borderLeft	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderLeft))
#define SLIM_TKOFF_DOM2A_borderLeftColor	(SLIM_TKOFF_BASE_DOM2A0 + 220)
#define SLIM_TKNAM_DOM2A_borderLeftColor	(SLIM_TKNAM_BASE_DOM2A0 + 220)
#define SLIM_TKLEN_DOM2A_borderLeftColor	(15)
#define SLIM_TOKEN_DOM2A_borderLeftColor	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderLeftColor))
#define SLIM_TKOFF_DOM2A_borderLeftStyle	(SLIM_TKOFF_BASE_DOM2A0 + 236)
#define SLIM_TKNAM_DOM2A_borderLeftStyle	(SLIM_TKNAM_BASE_DOM2A0 + 236)
#define SLIM_TKLEN_DOM2A_borderLeftStyle	(15)
#define SLIM_TOKEN_DOM2A_borderLeftStyle	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderLeftStyle))
#define SLIM_TKOFF_DOM2A_borderLeftWidth	(SLIM_TKOFF_BASE_DOM2A0 + 252)
#define SLIM_TKNAM_DOM2A_borderLeftWidth	(SLIM_TKNAM_BASE_DOM2A0 + 252)
#define SLIM_TKLEN_DOM2A_borderLeftWidth	(15)
#define SLIM_TOKEN_DOM2A_borderLeftWidth	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderLeftWidth))
#define SLIM_TKOFF_DOM2A_borderRight	(SLIM_TKOFF_BASE_DOM2A0 + 268)
#define SLIM_TKNAM_DOM2A_borderRight	(SLIM_TKNAM_BASE_DOM2A0 + 268)
#define SLIM_TKLEN_DOM2A_borderRight	(11)
#define SLIM_TOKEN_DOM2A_borderRight	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderRight))
#define SLIM_TKOFF_DOM2A_borderRightColor	(SLIM_TKOFF_BASE_DOM2A0 + 280)
#define SLIM_TKNAM_DOM2A_borderRightColor	(SLIM_TKNAM_BASE_DOM2A0 + 280)
#define SLIM_TKLEN_DOM2A_borderRightColor	(16)
#define SLIM_TOKEN_DOM2A_borderRightColor	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderRightColor))
#define SLIM_TKOFF_DOM2A_borderRightStyle	(SLIM_TKOFF_BASE_DOM2A0 + 297)
#define SLIM_TKNAM_DOM2A_borderRightStyle	(SLIM_TKNAM_BASE_DOM2A0 + 297)
#define SLIM_TKLEN_DOM2A_borderRightStyle	(16)
#define SLIM_TOKEN_DOM2A_borderRightStyle	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderRightStyle))
#define SLIM_TKOFF_DOM2A_borderRightWidth	(SLIM_TKOFF_BASE_DOM2A0 + 314)
#define SLIM_TKNAM_DOM2A_borderRightWidth	(SLIM_TKNAM_BASE_DOM2A0 + 314)
#define SLIM_TKLEN_DOM2A_borderRightWidth	(16)
#define SLIM_TOKEN_DOM2A_borderRightWidth	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderRightWidth))
#define SLIM_TKOFF_DOM2A_borderSpacing	(SLIM_TKOFF_BASE_DOM2A0 + 331)
#define SLIM_TKNAM_DOM2A_borderSpacing	(SLIM_TKNAM_BASE_DOM2A0 + 331)
#define SLIM_TKLEN_DOM2A_borderSpacing	(13)
#define SLIM_TOKEN_DOM2A_borderSpacing	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderSpacing))
#define SLIM_TKOFF_DOM2A_borderStyle	(SLIM_TKOFF_BASE_DOM2A0 + 345)
#define SLIM_TKNAM_DOM2A_borderStyle	(SLIM_TKNAM_BASE_DOM2A0 + 345)
#define SLIM_TKLEN_DOM2A_borderStyle	(11)
#define SLIM_TOKEN_DOM2A_borderStyle	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderStyle))
#define SLIM_TKOFF_DOM2A_borderTop	(SLIM_TKOFF_BASE_DOM2A0 + 357)
#define SLIM_TKNAM_DOM2A_borderTop	(SLIM_TKNAM_BASE_DOM2A0 + 357)
#define SLIM_TKLEN_DOM2A_borderTop	(9)
#define SLIM_TOKEN_DOM2A_borderTop	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderTop))
#define SLIM_TKOFF_DOM2A_borderTopColor	(SLIM_TKOFF_BASE_DOM2A0 + 367)
#define SLIM_TKNAM_DOM2A_borderTopColor	(SLIM_TKNAM_BASE_DOM2A0 + 367)
#define SLIM_TKLEN_DOM2A_borderTopColor	(14)
#define SLIM_TOKEN_DOM2A_borderTopColor	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderTopColor))
#define SLIM_TKOFF_DOM2A_borderTopStyle	(SLIM_TKOFF_BASE_DOM2A0 + 382)
#define SLIM_TKNAM_DOM2A_borderTopStyle	(SLIM_TKNAM_BASE_DOM2A0 + 382)
#define SLIM_TKLEN_DOM2A_borderTopStyle	(14)
#define SLIM_TOKEN_DOM2A_borderTopStyle	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderTopStyle))
#define SLIM_TKOFF_DOM2A_borderTopWidth	(SLIM_TKOFF_BASE_DOM2A0 + 397)
#define SLIM_TKNAM_DOM2A_borderTopWidth	(SLIM_TKNAM_BASE_DOM2A0 + 397)
#define SLIM_TKLEN_DOM2A_borderTopWidth	(14)
#define SLIM_TOKEN_DOM2A_borderTopWidth	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderTopWidth))
#define SLIM_TKOFF_DOM2A_borderWidth	(SLIM_TKOFF_BASE_DOM2A0 + 412)
#define SLIM_TKNAM_DOM2A_borderWidth	(SLIM_TKNAM_BASE_DOM2A0 + 412)
#define SLIM_TKLEN_DOM2A_borderWidth	(11)
#define SLIM_TOKEN_DOM2A_borderWidth	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_borderWidth))
#define SLIM_TKOFF_DOM2A_bottom	(SLIM_TKOFF_BASE_DOM2A0 + 424)
#define SLIM_TKNAM_DOM2A_bottom	(SLIM_TKNAM_BASE_DOM2A0 + 424)
#define SLIM_TKLEN_DOM2A_bottom	(6)
#define SLIM_TOKEN_DOM2A_bottom	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_bottom))
#define SLIM_TKOFF_DOM2A_captionSide	(SLIM_TKOFF_BASE_DOM2A0 + 431)
#define SLIM_TKNAM_DOM2A_captionSide	(SLIM_TKNAM_BASE_DOM2A0 + 431)
#define SLIM_TKLEN_DOM2A_captionSide	(11)
#define SLIM_TOKEN_DOM2A_captionSide	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_captionSide))
#define SLIM_TKOFF_DOM2A_clear	(SLIM_TKOFF_BASE_DOM2A0 + 443)
#define SLIM_TKNAM_DOM2A_clear	(SLIM_TKNAM_BASE_DOM2A0 + 443)
#define SLIM_TKLEN_DOM2A_clear	(5)
#define SLIM_TOKEN_DOM2A_clear	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_clear))
#define SLIM_TKOFF_DOM2A_clip	(SLIM_TKOFF_BASE_DOM2A0 + 449)
#define SLIM_TKNAM_DOM2A_clip	(SLIM_TKNAM_BASE_DOM2A0 + 449)
#define SLIM_TKLEN_DOM2A_clip	(4)
#define SLIM_TOKEN_DOM2A_clip	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_clip))
#define SLIM_TKOFF_DOM2A_color	(SLIM_TKOFF_BASE_DOM2A0 + 454)
#define SLIM_TKNAM_DOM2A_color	(SLIM_TKNAM_BASE_DOM2A0 + 454)
#define SLIM_TKLEN_DOM2A_color	(5)
#define SLIM_TOKEN_DOM2A_color	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_color))
#define SLIM_TKOFF_DOM2A_content	(SLIM_TKOFF_BASE_DOM2A0 + 460)
#define SLIM_TKNAM_DOM2A_content	(SLIM_TKNAM_BASE_DOM2A0 + 460)
#define SLIM_TKLEN_DOM2A_content	(7)
#define SLIM_TOKEN_DOM2A_content	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_content))
#define SLIM_TKOFF_DOM2A_counterIncrement	(SLIM_TKOFF_BASE_DOM2A0 + 468)
#define SLIM_TKNAM_DOM2A_counterIncrement	(SLIM_TKNAM_BASE_DOM2A0 + 468)
#define SLIM_TKLEN_DOM2A_counterIncrement	(16)
#define SLIM_TOKEN_DOM2A_counterIncrement	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_counterIncrement))
#define SLIM_TKOFF_DOM2A_counterReset	(SLIM_TKOFF_BASE_DOM2A0 + 485)
#define SLIM_TKNAM_DOM2A_counterReset	(SLIM_TKNAM_BASE_DOM2A0 + 485)
#define SLIM_TKLEN_DOM2A_counterReset	(12)
#define SLIM_TOKEN_DOM2A_counterReset	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_counterReset))
#define SLIM_TKOFF_DOM2A_cssFloat	(SLIM_TKOFF_BASE_DOM2A0 + 498)
#define SLIM_TKNAM_DOM2A_cssFloat	(SLIM_TKNAM_BASE_DOM2A0 + 498)
#define SLIM_TKLEN_DOM2A_cssFloat	(8)
#define SLIM_TOKEN_DOM2A_cssFloat	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_cssFloat))
#define SLIM_TKOFF_DOM2A_cue	(SLIM_TKOFF_BASE_DOM2A0 + 507)
#define SLIM_TKNAM_DOM2A_cue	(SLIM_TKNAM_BASE_DOM2A0 + 507)
#define SLIM_TKLEN_DOM2A_cue	(3)
#define SLIM_TOKEN_DOM2A_cue	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_cue))
#define SLIM_TKOFF_DOM2A_cueAfter	(SLIM_TKOFF_BASE_DOM2A0 + 511)
#define SLIM_TKNAM_DOM2A_cueAfter	(SLIM_TKNAM_BASE_DOM2A0 + 511)
#define SLIM_TKLEN_DOM2A_cueAfter	(8)
#define SLIM_TOKEN_DOM2A_cueAfter	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_cueAfter))
#define SLIM_TKOFF_DOM2A_cueBefore	(SLIM_TKOFF_BASE_DOM2A0 + 520)
#define SLIM_TKNAM_DOM2A_cueBefore	(SLIM_TKNAM_BASE_DOM2A0 + 520)
#define SLIM_TKLEN_DOM2A_cueBefore	(9)
#define SLIM_TOKEN_DOM2A_cueBefore	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_cueBefore))
#define SLIM_TKOFF_DOM2A_cursor	(SLIM_TKOFF_BASE_DOM2A0 + 530)
#define SLIM_TKNAM_DOM2A_cursor	(SLIM_TKNAM_BASE_DOM2A0 + 530)
#define SLIM_TKLEN_DOM2A_cursor	(6)
#define SLIM_TOKEN_DOM2A_cursor	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_cursor))
#define SLIM_TKOFF_DOM2A_direction	(SLIM_TKOFF_BASE_DOM2A0 + 537)
#define SLIM_TKNAM_DOM2A_direction	(SLIM_TKNAM_BASE_DOM2A0 + 537)
#define SLIM_TKLEN_DOM2A_direction	(9)
#define SLIM_TOKEN_DOM2A_direction	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_direction))
#define SLIM_TKOFF_DOM2A_disabled	(SLIM_TKOFF_BASE_DOM2A0 + 547)
#define SLIM_TKNAM_DOM2A_disabled	(SLIM_TKNAM_BASE_DOM2A0 + 547)
#define SLIM_TKLEN_DOM2A_disabled	(8)
#define SLIM_TOKEN_DOM2A_disabled	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_disabled))
#define SLIM_TKOFF_DOM2A_display	(SLIM_TKOFF_BASE_DOM2A0 + 556)
#define SLIM_TKNAM_DOM2A_display	(SLIM_TKNAM_BASE_DOM2A0 + 556)
#define SLIM_TKLEN_DOM2A_display	(7)
#define SLIM_TOKEN_DOM2A_display	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_display))
#define SLIM_TKOFF_DOM2A_elevation	(SLIM_TKOFF_BASE_DOM2A0 + 564)
#define SLIM_TKNAM_DOM2A_elevation	(SLIM_TKNAM_BASE_DOM2A0 + 564)
#define SLIM_TKLEN_DOM2A_elevation	(9)
#define SLIM_TOKEN_DOM2A_elevation	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_elevation))
#define SLIM_TKOFF_DOM2A_emptyCells	(SLIM_TKOFF_BASE_DOM2A0 + 574)
#define SLIM_TKNAM_DOM2A_emptyCells	(SLIM_TKNAM_BASE_DOM2A0 + 574)
#define SLIM_TKLEN_DOM2A_emptyCells	(10)
#define SLIM_TOKEN_DOM2A_emptyCells	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_emptyCells))
#define SLIM_TKOFF_DOM2A_font	(SLIM_TKOFF_BASE_DOM2A0 + 585)
#define SLIM_TKNAM_DOM2A_font	(SLIM_TKNAM_BASE_DOM2A0 + 585)
#define SLIM_TKLEN_DOM2A_font	(4)
#define SLIM_TOKEN_DOM2A_font	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_font))
#define SLIM_TKOFF_DOM2A_fontFamily	(SLIM_TKOFF_BASE_DOM2A0 + 590)
#define SLIM_TKNAM_DOM2A_fontFamily	(SLIM_TKNAM_BASE_DOM2A0 + 590)
#define SLIM_TKLEN_DOM2A_fontFamily	(10)
#define SLIM_TOKEN_DOM2A_fontFamily	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_fontFamily))
#define SLIM_TKOFF_DOM2A_fontSize	(SLIM_TKOFF_BASE_DOM2A0 + 601)
#define SLIM_TKNAM_DOM2A_fontSize	(SLIM_TKNAM_BASE_DOM2A0 + 601)
#define SLIM_TKLEN_DOM2A_fontSize	(8)
#define SLIM_TOKEN_DOM2A_fontSize	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_fontSize))
#define SLIM_TKOFF_DOM2A_fontSizeAdjust	(SLIM_TKOFF_BASE_DOM2A0 + 610)
#define SLIM_TKNAM_DOM2A_fontSizeAdjust	(SLIM_TKNAM_BASE_DOM2A0 + 610)
#define SLIM_TKLEN_DOM2A_fontSizeAdjust	(14)
#define SLIM_TOKEN_DOM2A_fontSizeAdjust	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_fontSizeAdjust))
#define SLIM_TKOFF_DOM2A_fontStretch	(SLIM_TKOFF_BASE_DOM2A0 + 625)
#define SLIM_TKNAM_DOM2A_fontStretch	(SLIM_TKNAM_BASE_DOM2A0 + 625)
#define SLIM_TKLEN_DOM2A_fontStretch	(11)
#define SLIM_TOKEN_DOM2A_fontStretch	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_fontStretch))
#define SLIM_TKOFF_DOM2A_fontStyle	(SLIM_TKOFF_BASE_DOM2A0 + 637)
#define SLIM_TKNAM_DOM2A_fontStyle	(SLIM_TKNAM_BASE_DOM2A0 + 637)
#define SLIM_TKLEN_DOM2A_fontStyle	(9)
#define SLIM_TOKEN_DOM2A_fontStyle	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_fontStyle))
#define SLIM_TKOFF_DOM2A_fontVariant	(SLIM_TKOFF_BASE_DOM2A0 + 647)
#define SLIM_TKNAM_DOM2A_fontVariant	(SLIM_TKNAM_BASE_DOM2A0 + 647)
#define SLIM_TKLEN_DOM2A_fontVariant	(11)
#define SLIM_TOKEN_DOM2A_fontVariant	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_fontVariant))
#define SLIM_TKOFF_DOM2A_fontWeight	(SLIM_TKOFF_BASE_DOM2A0 + 659)
#define SLIM_TKNAM_DOM2A_fontWeight	(SLIM_TKNAM_BASE_DOM2A0 + 659)
#define SLIM_TKLEN_DOM2A_fontWeight	(10)
#define SLIM_TOKEN_DOM2A_fontWeight	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_fontWeight))
#define SLIM_TKOFF_DOM2A_height	(SLIM_TKOFF_BASE_DOM2A0 + 670)
#define SLIM_TKNAM_DOM2A_height	(SLIM_TKNAM_BASE_DOM2A0 + 670)
#define SLIM_TKLEN_DOM2A_height	(6)
#define SLIM_TOKEN_DOM2A_height	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_height))
#define SLIM_TKOFF_DOM2A_href	(SLIM_TKOFF_BASE_DOM2A0 + 677)
#define SLIM_TKNAM_DOM2A_href	(SLIM_TKNAM_BASE_DOM2A0 + 677)
#define SLIM_TKLEN_DOM2A_href	(4)
#define SLIM_TOKEN_DOM2A_href	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_href))
#define SLIM_TKOFF_DOM2A_left	(SLIM_TKOFF_BASE_DOM2A0 + 682)
#define SLIM_TKNAM_DOM2A_left	(SLIM_TKNAM_BASE_DOM2A0 + 682)
#define SLIM_TKLEN_DOM2A_left	(4)
#define SLIM_TOKEN_DOM2A_left	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_left))
#define SLIM_TKOFF_DOM2A_length	(SLIM_TKOFF_BASE_DOM2A0 + 687)
#define SLIM_TKNAM_DOM2A_length	(SLIM_TKNAM_BASE_DOM2A0 + 687)
#define SLIM_TKLEN_DOM2A_length	(6)
#define SLIM_TOKEN_DOM2A_length	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_length))
#define SLIM_TKOFF_DOM2A_letterSpacing	(SLIM_TKOFF_BASE_DOM2A0 + 694)
#define SLIM_TKNAM_DOM2A_letterSpacing	(SLIM_TKNAM_BASE_DOM2A0 + 694)
#define SLIM_TKLEN_DOM2A_letterSpacing	(13)
#define SLIM_TOKEN_DOM2A_letterSpacing	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_letterSpacing))
#define SLIM_TKOFF_DOM2A_lineHeight	(SLIM_TKOFF_BASE_DOM2A0 + 708)
#define SLIM_TKNAM_DOM2A_lineHeight	(SLIM_TKNAM_BASE_DOM2A0 + 708)
#define SLIM_TKLEN_DOM2A_lineHeight	(10)
#define SLIM_TOKEN_DOM2A_lineHeight	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_lineHeight))
#define SLIM_TKOFF_DOM2A_listStyle	(SLIM_TKOFF_BASE_DOM2A0 + 719)
#define SLIM_TKNAM_DOM2A_listStyle	(SLIM_TKNAM_BASE_DOM2A0 + 719)
#define SLIM_TKLEN_DOM2A_listStyle	(9)
#define SLIM_TOKEN_DOM2A_listStyle	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_listStyle))
#define SLIM_TKOFF_DOM2A_listStyleImage	(SLIM_TKOFF_BASE_DOM2A0 + 729)
#define SLIM_TKNAM_DOM2A_listStyleImage	(SLIM_TKNAM_BASE_DOM2A0 + 729)
#define SLIM_TKLEN_DOM2A_listStyleImage	(14)
#define SLIM_TOKEN_DOM2A_listStyleImage	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_listStyleImage))
#define SLIM_TKOFF_DOM2A_listStylePosition	(SLIM_TKOFF_BASE_DOM2A0 + 744)
#define SLIM_TKNAM_DOM2A_listStylePosition	(SLIM_TKNAM_BASE_DOM2A0 + 744)
#define SLIM_TKLEN_DOM2A_listStylePosition	(17)
#define SLIM_TOKEN_DOM2A_listStylePosition	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_listStylePosition))
#define SLIM_TKOFF_DOM2A_listStyleType	(SLIM_TKOFF_BASE_DOM2A0 + 762)
#define SLIM_TKNAM_DOM2A_listStyleType	(SLIM_TKNAM_BASE_DOM2A0 + 762)
#define SLIM_TKLEN_DOM2A_listStyleType	(13)
#define SLIM_TOKEN_DOM2A_listStyleType	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_listStyleType))
#define SLIM_TKOFF_DOM2A_margin	(SLIM_TKOFF_BASE_DOM2A0 + 776)
#define SLIM_TKNAM_DOM2A_margin	(SLIM_TKNAM_BASE_DOM2A0 + 776)
#define SLIM_TKLEN_DOM2A_margin	(6)
#define SLIM_TOKEN_DOM2A_margin	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_margin))
#define SLIM_TKOFF_DOM2A_marginBottom	(SLIM_TKOFF_BASE_DOM2A0 + 783)
#define SLIM_TKNAM_DOM2A_marginBottom	(SLIM_TKNAM_BASE_DOM2A0 + 783)
#define SLIM_TKLEN_DOM2A_marginBottom	(12)
#define SLIM_TOKEN_DOM2A_marginBottom	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_marginBottom))
#define SLIM_TKOFF_DOM2A_marginLeft	(SLIM_TKOFF_BASE_DOM2A0 + 796)
#define SLIM_TKNAM_DOM2A_marginLeft	(SLIM_TKNAM_BASE_DOM2A0 + 796)
#define SLIM_TKLEN_DOM2A_marginLeft	(10)
#define SLIM_TOKEN_DOM2A_marginLeft	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_marginLeft))
#define SLIM_TKOFF_DOM2A_marginRight	(SLIM_TKOFF_BASE_DOM2A0 + 807)
#define SLIM_TKNAM_DOM2A_marginRight	(SLIM_TKNAM_BASE_DOM2A0 + 807)
#define SLIM_TKLEN_DOM2A_marginRight	(11)
#define SLIM_TOKEN_DOM2A_marginRight	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_marginRight))
#define SLIM_TKOFF_DOM2A_marginTop	(SLIM_TKOFF_BASE_DOM2A0 + 819)
#define SLIM_TKNAM_DOM2A_marginTop	(SLIM_TKNAM_BASE_DOM2A0 + 819)
#define SLIM_TKLEN_DOM2A_marginTop	(9)
#define SLIM_TOKEN_DOM2A_marginTop	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_marginTop))
#define SLIM_TKOFF_DOM2A_markerOffset	(SLIM_TKOFF_BASE_DOM2A0 + 829)
#define SLIM_TKNAM_DOM2A_markerOffset	(SLIM_TKNAM_BASE_DOM2A0 + 829)
#define SLIM_TKLEN_DOM2A_markerOffset	(12)
#define SLIM_TOKEN_DOM2A_markerOffset	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_markerOffset))
#define SLIM_TKOFF_DOM2A_marks	(SLIM_TKOFF_BASE_DOM2A0 + 842)
#define SLIM_TKNAM_DOM2A_marks	(SLIM_TKNAM_BASE_DOM2A0 + 842)
#define SLIM_TKLEN_DOM2A_marks	(5)
#define SLIM_TOKEN_DOM2A_marks	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_marks))
#define SLIM_TKOFF_DOM2A_maxHeight	(SLIM_TKOFF_BASE_DOM2A0 + 848)
#define SLIM_TKNAM_DOM2A_maxHeight	(SLIM_TKNAM_BASE_DOM2A0 + 848)
#define SLIM_TKLEN_DOM2A_maxHeight	(9)
#define SLIM_TOKEN_DOM2A_maxHeight	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_maxHeight))
#define SLIM_TKOFF_DOM2A_maxWidth	(SLIM_TKOFF_BASE_DOM2A0 + 858)
#define SLIM_TKNAM_DOM2A_maxWidth	(SLIM_TKNAM_BASE_DOM2A0 + 858)
#define SLIM_TKLEN_DOM2A_maxWidth	(8)
#define SLIM_TOKEN_DOM2A_maxWidth	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_maxWidth))
#define SLIM_TKOFF_DOM2A_media	(SLIM_TKOFF_BASE_DOM2A0 + 867)
#define SLIM_TKNAM_DOM2A_media	(SLIM_TKNAM_BASE_DOM2A0 + 867)
#define SLIM_TKLEN_DOM2A_media	(5)
#define SLIM_TOKEN_DOM2A_media	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_media))
#define SLIM_TKOFF_DOM2A_mediaText	(SLIM_TKOFF_BASE_DOM2A0 + 873)
#define SLIM_TKNAM_DOM2A_mediaText	(SLIM_TKNAM_BASE_DOM2A0 + 873)
#define SLIM_TKLEN_DOM2A_mediaText	(9)
#define SLIM_TOKEN_DOM2A_mediaText	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_mediaText))
#define SLIM_TKOFF_DOM2A_minHeight	(SLIM_TKOFF_BASE_DOM2A0 + 883)
#define SLIM_TKNAM_DOM2A_minHeight	(SLIM_TKNAM_BASE_DOM2A0 + 883)
#define SLIM_TKLEN_DOM2A_minHeight	(9)
#define SLIM_TOKEN_DOM2A_minHeight	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_minHeight))
#define SLIM_TKOFF_DOM2A_minWidth	(SLIM_TKOFF_BASE_DOM2A0 + 893)
#define SLIM_TKNAM_DOM2A_minWidth	(SLIM_TKNAM_BASE_DOM2A0 + 893)
#define SLIM_TKLEN_DOM2A_minWidth	(8)
#define SLIM_TOKEN_DOM2A_minWidth	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_minWidth))
#define SLIM_TKOFF_DOM2A_orphans	(SLIM_TKOFF_BASE_DOM2A0 + 902)
#define SLIM_TKNAM_DOM2A_orphans	(SLIM_TKNAM_BASE_DOM2A0 + 902)
#define SLIM_TKLEN_DOM2A_orphans	(7)
#define SLIM_TOKEN_DOM2A_orphans	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_orphans))
#define SLIM_TKOFF_DOM2A_outline	(SLIM_TKOFF_BASE_DOM2A0 + 910)
#define SLIM_TKNAM_DOM2A_outline	(SLIM_TKNAM_BASE_DOM2A0 + 910)
#define SLIM_TKLEN_DOM2A_outline	(7)
#define SLIM_TOKEN_DOM2A_outline	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_outline))
#define SLIM_TKOFF_DOM2A_outlineColor	(SLIM_TKOFF_BASE_DOM2A0 + 918)
#define SLIM_TKNAM_DOM2A_outlineColor	(SLIM_TKNAM_BASE_DOM2A0 + 918)
#define SLIM_TKLEN_DOM2A_outlineColor	(12)
#define SLIM_TOKEN_DOM2A_outlineColor	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_outlineColor))
#define SLIM_TKOFF_DOM2A_outlineStyle	(SLIM_TKOFF_BASE_DOM2A0 + 931)
#define SLIM_TKNAM_DOM2A_outlineStyle	(SLIM_TKNAM_BASE_DOM2A0 + 931)
#define SLIM_TKLEN_DOM2A_outlineStyle	(12)
#define SLIM_TOKEN_DOM2A_outlineStyle	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_outlineStyle))
#define SLIM_TKOFF_DOM2A_outlineWidth	(SLIM_TKOFF_BASE_DOM2A0 + 944)
#define SLIM_TKNAM_DOM2A_outlineWidth	(SLIM_TKNAM_BASE_DOM2A0 + 944)
#define SLIM_TKLEN_DOM2A_outlineWidth	(12)
#define SLIM_TOKEN_DOM2A_outlineWidth	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_outlineWidth))
#define SLIM_TKOFF_DOM2A_overflow	(SLIM_TKOFF_BASE_DOM2A0 + 957)
#define SLIM_TKNAM_DOM2A_overflow	(SLIM_TKNAM_BASE_DOM2A0 + 957)
#define SLIM_TKLEN_DOM2A_overflow	(8)
#define SLIM_TOKEN_DOM2A_overflow	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_overflow))
#define SLIM_TKOFF_DOM2A_ownerNode	(SLIM_TKOFF_BASE_DOM2A0 + 966)
#define SLIM_TKNAM_DOM2A_ownerNode	(SLIM_TKNAM_BASE_DOM2A0 + 966)
#define SLIM_TKLEN_DOM2A_ownerNode	(9)
#define SLIM_TOKEN_DOM2A_ownerNode	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_ownerNode))
#define SLIM_TKOFF_DOM2A_padding	(SLIM_TKOFF_BASE_DOM2A0 + 976)
#define SLIM_TKNAM_DOM2A_padding	(SLIM_TKNAM_BASE_DOM2A0 + 976)
#define SLIM_TKLEN_DOM2A_padding	(7)
#define SLIM_TOKEN_DOM2A_padding	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_padding))
#define SLIM_TKOFF_DOM2A_paddingBottom	(SLIM_TKOFF_BASE_DOM2A0 + 984)
#define SLIM_TKNAM_DOM2A_paddingBottom	(SLIM_TKNAM_BASE_DOM2A0 + 984)
#define SLIM_TKLEN_DOM2A_paddingBottom	(13)
#define SLIM_TOKEN_DOM2A_paddingBottom	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_paddingBottom))
#define SLIM_TKOFF_DOM2A_paddingLeft	(SLIM_TKOFF_BASE_DOM2A0 + 998)
#define SLIM_TKNAM_DOM2A_paddingLeft	(SLIM_TKNAM_BASE_DOM2A0 + 998)
#define SLIM_TKLEN_DOM2A_paddingLeft	(11)
#define SLIM_TOKEN_DOM2A_paddingLeft	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_paddingLeft))
#define SLIM_TKOFF_DOM2A_paddingRight	(SLIM_TKOFF_BASE_DOM2A0 + 1010)
#define SLIM_TKNAM_DOM2A_paddingRight	(SLIM_TKNAM_BASE_DOM2A0 + 1010)
#define SLIM_TKLEN_DOM2A_paddingRight	(12)
#define SLIM_TOKEN_DOM2A_paddingRight	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_paddingRight))
#define SLIM_TKOFF_DOM2A_paddingTop	(SLIM_TKOFF_BASE_DOM2A0 + 1023)
#define SLIM_TKNAM_DOM2A_paddingTop	(SLIM_TKNAM_BASE_DOM2A0 + 1023)
#define SLIM_TKLEN_DOM2A_paddingTop	(10)
#define SLIM_TOKEN_DOM2A_paddingTop	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_paddingTop))
#define SLIM_TKOFF_DOM2A_page	(SLIM_TKOFF_BASE_DOM2A0 + 1034)
#define SLIM_TKNAM_DOM2A_page	(SLIM_TKNAM_BASE_DOM2A0 + 1034)
#define SLIM_TKLEN_DOM2A_page	(4)
#define SLIM_TOKEN_DOM2A_page	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_page))
#define SLIM_TKOFF_DOM2A_pageBreakAfter	(SLIM_TKOFF_BASE_DOM2A0 + 1039)
#define SLIM_TKNAM_DOM2A_pageBreakAfter	(SLIM_TKNAM_BASE_DOM2A0 + 1039)
#define SLIM_TKLEN_DOM2A_pageBreakAfter	(14)
#define SLIM_TOKEN_DOM2A_pageBreakAfter	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_pageBreakAfter))
#define SLIM_TKOFF_DOM2A_pageBreakBefore	(SLIM_TKOFF_BASE_DOM2A0 + 1054)
#define SLIM_TKNAM_DOM2A_pageBreakBefore	(SLIM_TKNAM_BASE_DOM2A0 + 1054)
#define SLIM_TKLEN_DOM2A_pageBreakBefore	(15)
#define SLIM_TOKEN_DOM2A_pageBreakBefore	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_pageBreakBefore))
#define SLIM_TKOFF_DOM2A_pageBreakInside	(SLIM_TKOFF_BASE_DOM2A0 + 1070)
#define SLIM_TKNAM_DOM2A_pageBreakInside	(SLIM_TKNAM_BASE_DOM2A0 + 1070)
#define SLIM_TKLEN_DOM2A_pageBreakInside	(15)
#define SLIM_TOKEN_DOM2A_pageBreakInside	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_pageBreakInside))
#define SLIM_TKOFF_DOM2A_parentStyleSheet	(SLIM_TKOFF_BASE_DOM2A0 + 1086)
#define SLIM_TKNAM_DOM2A_parentStyleSheet	(SLIM_TKNAM_BASE_DOM2A0 + 1086)
#define SLIM_TKLEN_DOM2A_parentStyleSheet	(16)
#define SLIM_TOKEN_DOM2A_parentStyleSheet	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_parentStyleSheet))
#define SLIM_TKOFF_DOM2A_pause	(SLIM_TKOFF_BASE_DOM2A0 + 1103)
#define SLIM_TKNAM_DOM2A_pause	(SLIM_TKNAM_BASE_DOM2A0 + 1103)
#define SLIM_TKLEN_DOM2A_pause	(5)
#define SLIM_TOKEN_DOM2A_pause	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_pause))
#define SLIM_TKOFF_DOM2A_pauseAfter	(SLIM_TKOFF_BASE_DOM2A0 + 1109)
#define SLIM_TKNAM_DOM2A_pauseAfter	(SLIM_TKNAM_BASE_DOM2A0 + 1109)
#define SLIM_TKLEN_DOM2A_pauseAfter	(10)
#define SLIM_TOKEN_DOM2A_pauseAfter	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_pauseAfter))
#define SLIM_TKOFF_DOM2A_pauseBefore	(SLIM_TKOFF_BASE_DOM2A0 + 1120)
#define SLIM_TKNAM_DOM2A_pauseBefore	(SLIM_TKNAM_BASE_DOM2A0 + 1120)
#define SLIM_TKLEN_DOM2A_pauseBefore	(11)
#define SLIM_TOKEN_DOM2A_pauseBefore	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_pauseBefore))
#define SLIM_TKOFF_DOM2A_pitch	(SLIM_TKOFF_BASE_DOM2A0 + 1132)
#define SLIM_TKNAM_DOM2A_pitch	(SLIM_TKNAM_BASE_DOM2A0 + 1132)
#define SLIM_TKLEN_DOM2A_pitch	(5)
#define SLIM_TOKEN_DOM2A_pitch	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_pitch))
#define SLIM_TKOFF_DOM2A_pitchRange	(SLIM_TKOFF_BASE_DOM2A0 + 1138)
#define SLIM_TKNAM_DOM2A_pitchRange	(SLIM_TKNAM_BASE_DOM2A0 + 1138)
#define SLIM_TKLEN_DOM2A_pitchRange	(10)
#define SLIM_TOKEN_DOM2A_pitchRange	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_pitchRange))
#define SLIM_TKOFF_DOM2A_playDuring	(SLIM_TKOFF_BASE_DOM2A0 + 1149)
#define SLIM_TKNAM_DOM2A_playDuring	(SLIM_TKNAM_BASE_DOM2A0 + 1149)
#define SLIM_TKLEN_DOM2A_playDuring	(10)
#define SLIM_TOKEN_DOM2A_playDuring	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_playDuring))
#define SLIM_TKOFF_DOM2A_position	(SLIM_TKOFF_BASE_DOM2A0 + 1160)
#define SLIM_TKNAM_DOM2A_position	(SLIM_TKNAM_BASE_DOM2A0 + 1160)
#define SLIM_TKLEN_DOM2A_position	(8)
#define SLIM_TOKEN_DOM2A_position	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_position))
#define SLIM_TKOFF_DOM2A_quotes	(SLIM_TKOFF_BASE_DOM2A0 + 1169)
#define SLIM_TKNAM_DOM2A_quotes	(SLIM_TKNAM_BASE_DOM2A0 + 1169)
#define SLIM_TKLEN_DOM2A_quotes	(6)
#define SLIM_TOKEN_DOM2A_quotes	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_quotes))
#define SLIM_TKOFF_DOM2A_richness	(SLIM_TKOFF_BASE_DOM2A0 + 1176)
#define SLIM_TKNAM_DOM2A_richness	(SLIM_TKNAM_BASE_DOM2A0 + 1176)
#define SLIM_TKLEN_DOM2A_richness	(8)
#define SLIM_TOKEN_DOM2A_richness	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_richness))
#define SLIM_TKOFF_DOM2A_right	(SLIM_TKOFF_BASE_DOM2A0 + 1185)
#define SLIM_TKNAM_DOM2A_right	(SLIM_TKNAM_BASE_DOM2A0 + 1185)
#define SLIM_TKLEN_DOM2A_right	(5)
#define SLIM_TOKEN_DOM2A_right	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_right))
#define SLIM_TKOFF_DOM2A_size	(SLIM_TKOFF_BASE_DOM2A0 + 1191)
#define SLIM_TKNAM_DOM2A_size	(SLIM_TKNAM_BASE_DOM2A0 + 1191)
#define SLIM_TKLEN_DOM2A_size	(4)
#define SLIM_TOKEN_DOM2A_size	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_size))
#define SLIM_TKOFF_DOM2A_speak	(SLIM_TKOFF_BASE_DOM2A0 + 1196)
#define SLIM_TKNAM_DOM2A_speak	(SLIM_TKNAM_BASE_DOM2A0 + 1196)
#define SLIM_TKLEN_DOM2A_speak	(5)
#define SLIM_TOKEN_DOM2A_speak	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_speak))
#define SLIM_TKOFF_DOM2A_speakHeader	(SLIM_TKOFF_BASE_DOM2A0 + 1202)
#define SLIM_TKNAM_DOM2A_speakHeader	(SLIM_TKNAM_BASE_DOM2A0 + 1202)
#define SLIM_TKLEN_DOM2A_speakHeader	(11)
#define SLIM_TOKEN_DOM2A_speakHeader	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_speakHeader))
#define SLIM_TKOFF_DOM2A_speakNumeral	(SLIM_TKOFF_BASE_DOM2A0 + 1214)
#define SLIM_TKNAM_DOM2A_speakNumeral	(SLIM_TKNAM_BASE_DOM2A0 + 1214)
#define SLIM_TKLEN_DOM2A_speakNumeral	(12)
#define SLIM_TOKEN_DOM2A_speakNumeral	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_speakNumeral))
#define SLIM_TKOFF_DOM2A_speakPunctuation	(SLIM_TKOFF_BASE_DOM2A0 + 1227)
#define SLIM_TKNAM_DOM2A_speakPunctuation	(SLIM_TKNAM_BASE_DOM2A0 + 1227)
#define SLIM_TKLEN_DOM2A_speakPunctuation	(16)
#define SLIM_TOKEN_DOM2A_speakPunctuation	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_speakPunctuation))
#define SLIM_TKOFF_DOM2A_speechRate	(SLIM_TKOFF_BASE_DOM2A0 + 1244)
#define SLIM_TKNAM_DOM2A_speechRate	(SLIM_TKNAM_BASE_DOM2A0 + 1244)
#define SLIM_TKLEN_DOM2A_speechRate	(10)
#define SLIM_TOKEN_DOM2A_speechRate	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_speechRate))
#define SLIM_TKOFF_DOM2A_stress	(SLIM_TKOFF_BASE_DOM2A0 + 1255)
#define SLIM_TKNAM_DOM2A_stress	(SLIM_TKNAM_BASE_DOM2A0 + 1255)
#define SLIM_TKLEN_DOM2A_stress	(6)
#define SLIM_TOKEN_DOM2A_stress	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_stress))
#define SLIM_TKOFF_DOM2A_styleFloat	(SLIM_TKOFF_BASE_DOM2A0 + 1262)
#define SLIM_TKNAM_DOM2A_styleFloat	(SLIM_TKNAM_BASE_DOM2A0 + 1262)
#define SLIM_TKLEN_DOM2A_styleFloat	(10)
#define SLIM_TOKEN_DOM2A_styleFloat	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_styleFloat))
#define SLIM_TKOFF_DOM2A_tableLayout	(SLIM_TKOFF_BASE_DOM2A0 + 1273)
#define SLIM_TKNAM_DOM2A_tableLayout	(SLIM_TKNAM_BASE_DOM2A0 + 1273)
#define SLIM_TKLEN_DOM2A_tableLayout	(11)
#define SLIM_TOKEN_DOM2A_tableLayout	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_tableLayout))
#define SLIM_TKOFF_DOM2A_textAlign	(SLIM_TKOFF_BASE_DOM2A0 + 1285)
#define SLIM_TKNAM_DOM2A_textAlign	(SLIM_TKNAM_BASE_DOM2A0 + 1285)
#define SLIM_TKLEN_DOM2A_textAlign	(9)
#define SLIM_TOKEN_DOM2A_textAlign	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_textAlign))
#define SLIM_TKOFF_DOM2A_textDecoration	(SLIM_TKOFF_BASE_DOM2A0 + 1295)
#define SLIM_TKNAM_DOM2A_textDecoration	(SLIM_TKNAM_BASE_DOM2A0 + 1295)
#define SLIM_TKLEN_DOM2A_textDecoration	(14)
#define SLIM_TOKEN_DOM2A_textDecoration	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_textDecoration))
#define SLIM_TKOFF_DOM2A_textIndent	(SLIM_TKOFF_BASE_DOM2A0 + 1310)
#define SLIM_TKNAM_DOM2A_textIndent	(SLIM_TKNAM_BASE_DOM2A0 + 1310)
#define SLIM_TKLEN_DOM2A_textIndent	(10)
#define SLIM_TOKEN_DOM2A_textIndent	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_textIndent))
#define SLIM_TKOFF_DOM2A_textShadow	(SLIM_TKOFF_BASE_DOM2A0 + 1321)
#define SLIM_TKNAM_DOM2A_textShadow	(SLIM_TKNAM_BASE_DOM2A0 + 1321)
#define SLIM_TKLEN_DOM2A_textShadow	(10)
#define SLIM_TOKEN_DOM2A_textShadow	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_textShadow))
#define SLIM_TKOFF_DOM2A_textTransform	(SLIM_TKOFF_BASE_DOM2A0 + 1332)
#define SLIM_TKNAM_DOM2A_textTransform	(SLIM_TKNAM_BASE_DOM2A0 + 1332)
#define SLIM_TKLEN_DOM2A_textTransform	(13)
#define SLIM_TOKEN_DOM2A_textTransform	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_textTransform))
#define SLIM_TKOFF_DOM2A_title	(SLIM_TKOFF_BASE_DOM2A0 + 1346)
#define SLIM_TKNAM_DOM2A_title	(SLIM_TKNAM_BASE_DOM2A0 + 1346)
#define SLIM_TKLEN_DOM2A_title	(5)
#define SLIM_TOKEN_DOM2A_title	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_title))
#define SLIM_TKOFF_DOM2A_top	(SLIM_TKOFF_BASE_DOM2A0 + 1352)
#define SLIM_TKNAM_DOM2A_top	(SLIM_TKNAM_BASE_DOM2A0 + 1352)
#define SLIM_TKLEN_DOM2A_top	(3)
#define SLIM_TOKEN_DOM2A_top	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_top))
#define SLIM_TKOFF_DOM2A_type	(SLIM_TKOFF_BASE_DOM2A0 + 1356)
#define SLIM_TKNAM_DOM2A_type	(SLIM_TKNAM_BASE_DOM2A0 + 1356)
#define SLIM_TKLEN_DOM2A_type	(4)
#define SLIM_TOKEN_DOM2A_type	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_type))
#define SLIM_TKOFF_DOM2A_unicodeBidi	(SLIM_TKOFF_BASE_DOM2A0 + 1361)
#define SLIM_TKNAM_DOM2A_unicodeBidi	(SLIM_TKNAM_BASE_DOM2A0 + 1361)
#define SLIM_TKLEN_DOM2A_unicodeBidi	(11)
#define SLIM_TOKEN_DOM2A_unicodeBidi	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_unicodeBidi))
#define SLIM_TKOFF_DOM2A_verticalAlign	(SLIM_TKOFF_BASE_DOM2A0 + 1373)
#define SLIM_TKNAM_DOM2A_verticalAlign	(SLIM_TKNAM_BASE_DOM2A0 + 1373)
#define SLIM_TKLEN_DOM2A_verticalAlign	(13)
#define SLIM_TOKEN_DOM2A_verticalAlign	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_verticalAlign))
#define SLIM_TKOFF_DOM2A_visibility	(SLIM_TKOFF_BASE_DOM2A0 + 1387)
#define SLIM_TKNAM_DOM2A_visibility	(SLIM_TKNAM_BASE_DOM2A0 + 1387)
#define SLIM_TKLEN_DOM2A_visibility	(10)
#define SLIM_TOKEN_DOM2A_visibility	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_visibility))
#define SLIM_TKOFF_DOM2A_voiceFamily	(SLIM_TKOFF_BASE_DOM2A0 + 1398)
#define SLIM_TKNAM_DOM2A_voiceFamily	(SLIM_TKNAM_BASE_DOM2A0 + 1398)
#define SLIM_TKLEN_DOM2A_voiceFamily	(11)
#define SLIM_TOKEN_DOM2A_voiceFamily	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_voiceFamily))
#define SLIM_TKOFF_DOM2A_volume	(SLIM_TKOFF_BASE_DOM2A0 + 1410)
#define SLIM_TKNAM_DOM2A_volume	(SLIM_TKNAM_BASE_DOM2A0 + 1410)
#define SLIM_TKLEN_DOM2A_volume	(6)
#define SLIM_TOKEN_DOM2A_volume	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_volume))
#define SLIM_TKOFF_DOM2A_whiteSpace	(SLIM_TKOFF_BASE_DOM2A0 + 1417)
#define SLIM_TKNAM_DOM2A_whiteSpace	(SLIM_TKNAM_BASE_DOM2A0 + 1417)
#define SLIM_TKLEN_DOM2A_whiteSpace	(10)
#define SLIM_TOKEN_DOM2A_whiteSpace	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_whiteSpace))
#define SLIM_TKOFF_DOM2A_widows	(SLIM_TKOFF_BASE_DOM2A0 + 1428)
#define SLIM_TKNAM_DOM2A_widows	(SLIM_TKNAM_BASE_DOM2A0 + 1428)
#define SLIM_TKLEN_DOM2A_widows	(6)
#define SLIM_TOKEN_DOM2A_widows	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_widows))
#define SLIM_TKOFF_DOM2A_width	(SLIM_TKOFF_BASE_DOM2A0 + 1435)
#define SLIM_TKNAM_DOM2A_width	(SLIM_TKNAM_BASE_DOM2A0 + 1435)
#define SLIM_TKLEN_DOM2A_width	(5)
#define SLIM_TOKEN_DOM2A_width	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_width))
#define SLIM_TKOFF_DOM2A_wordSpacing	(SLIM_TKOFF_BASE_DOM2A0 + 1441)
#define SLIM_TKNAM_DOM2A_wordSpacing	(SLIM_TKNAM_BASE_DOM2A0 + 1441)
#define SLIM_TKLEN_DOM2A_wordSpacing	(11)
#define SLIM_TOKEN_DOM2A_wordSpacing	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_wordSpacing))
#define SLIM_TKOFF_DOM2A_zIndex	(SLIM_TKOFF_BASE_DOM2A0 + 1453)
#define SLIM_TKNAM_DOM2A_zIndex	(SLIM_TKNAM_BASE_DOM2A0 + 1453)
#define SLIM_TKLEN_DOM2A_zIndex	(6)
#define SLIM_TOKEN_DOM2A_zIndex	(DOM2AttrInfo_GetItem(SLIM_TKID_DOM2A_zIndex))
#define SLIM_TKOFF_BASE_DOM2A1	(SLIM_TKOFF_BASE_DOM2A0 + 1460)
#define SLIM_TKNAM_BASE_DOM2A1	(SLIM_TKNAM_BASE_DOM2A0 + SLIM_TKOFF_BASE_DOM2A1)
#define SLIM_TKLEN_TOTAL_DOM2A	SLIM_TKOFF_BASE_DOM2A1

extern SLIM_ROM slim_char cSlim_TokenName_DOM2A[SLIM_TKLEN_TOTAL_DOM2A];

extern SLIM_ROM TDOM2AttrInfo cSlim_Token_DOM2A[SLIM_TOKEN_DOM2A_TOKENS];
#define DOM2AttrInfo_GetItem(id)		((TDOM2AttrInfo *)&cSlim_Token_DOM2A[(id)])
#define DOM2AttrInfo_GetItemName(id)	((slim_char *)cSlim_TokenName_DOM2A + ((TToken *)&cSlim_Token_DOM2A[(id)])->fOffset)
#define DOM2AttrInfo_GetItemNameLen(id)	(((TToken *)&cSlim_Token_DOM2A[(id)])->fLength)

TDOM2AttrInfo *DOM2AttrInfo_CaseFindSS(slim_char *in_s, slim_int in_slen);

SLIM_END_C_LINKAGE
#endif
