/*
	domcid.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/private/token/domcid.h 4     05/12/28 12:08 Someya $ */

/* DO NOT EDIT! This file is generated automatically. */

#ifndef SLIM_TOKEN_DOMCID_H
#define SLIM_TOKEN_DOMCID_H


SLIM_BEGIN_C_LINKAGE

enum {
	SLIM_TKID_DOMC_ELEMENT_NODE = 0,
	SLIM_TKID_DOMC_ATTRIBUTE_NODE,
	SLIM_TKID_DOMC_TEXT_NODE,
	SLIM_TKID_DOMC_CDATA_SECTION_NODE,
	SLIM_TKID_DOMC_ENTITY_REFERENCE_NODE,
	SLIM_TKID_DOMC_ENTITY_NODE,
	SLIM_TKID_DOMC_PROCESSING_INSTRUCTION_NODE,
	SLIM_TKID_DOMC_COMMENT_NODE,
	SLIM_TKID_DOMC_DOCUMENT_NODE,
	SLIM_TKID_DOMC_DOCUMENT_TYPE_NODE,
	SLIM_TKID_DOMC_DOCUMENT_FRAGMENT_NODE,
	SLIM_TKID_DOMC_NOTATION_NODE,
	SLIM_TKID_DOMC_ENUMS
};

#define SLIM_TOKEN_DOMC_TOKENS SLIM_TKID_DOMC_ENUMS
#define SLIM_TOKEN_DOMC_ENUMS SLIM_TKID_DOMC_ENUMS


SLIM_END_C_LINKAGE
#endif
