/*
	domc.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/private/token/domc.h 18    05/12/28 12:08 Someya $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_DOMC_H
#define SLIM_TOKEN_DOMC_H

#include <slim/basis/base.h>
#include <slim/basis/token.h>
#include <slim/private/token/domcid.h>

SLIM_BEGIN_C_LINKAGE

#include <slim/www/dom.h>

#define SLIM_DOM_C_Node_ELEMENT_NODE 1
#define SLIM_DOM_C_Node_ATTRIBUTE_NODE 2
#define SLIM_DOM_C_Node_TEXT_NODE 3
#define SLIM_DOM_C_Node_CDATA_SECTION_NODE 4
#define SLIM_DOM_C_Node_ENTITY_REFERENCE_NODE 5
#define SLIM_DOM_C_Node_ENTITY_NODE 6
#define SLIM_DOM_C_Node_PROCESSING_INSTRUCTION_NODE 7
#define SLIM_DOM_C_Node_COMMENT_NODE 8
#define SLIM_DOM_C_Node_DOCUMENT_NODE 9
#define SLIM_DOM_C_Node_DOCUMENT_TYPE_NODE 10
#define SLIM_DOM_C_Node_DOCUMENT_FRAGMENT_NODE 11
#define SLIM_DOM_C_Node_NOTATION_NODE 12

struct TDOMConstInfo_ {
    TToken fBase;	/* must be the first field */
    slim_int fType;
    slim_int fValue;
};
typedef struct TDOMConstInfo_ TDOMConstInfo;
#define SLIM_DOM_EXCEPTION_INDEX_SIZE_ERR 1
#define SLIM_DOM_EXCEPTION_DOMSTRING_SIZE_ERR 2
#define SLIM_DOM_EXCEPTION_HIERARCHY_REQUEST_ERR 3
#define SLIM_DOM_EXCEPTION_WRONG_DOCUMENT_ERR 4
#define SLIM_DOM_EXCEPTION_INVALID_CHARACTER_ERR 5
#define SLIM_DOM_EXCEPTION_NO_DATA_ALLOWED_ERR 6
#define SLIM_DOM_EXCEPTION_NO_MODIFICATION_ALLOWED_ERR 7
#define SLIM_DOM_EXCEPTION_NOT_FOUND_ERR 8
#define SLIM_DOM_EXCEPTION_NOT_SUPPORTED_ERR 9
#define SLIM_DOM_EXCEPTION_INUSE_ATTRIBUTE_ERR 10
#define SLIM_DOM_EXCEPTION_INVALID_STATE_ERR 11
#define SLIM_DOM_EXCEPTION_SYNTAX_ERR 12
#define SLIM_DOM_EXCEPTION_INVALID_MODIFICATION_ERR 13
#define SLIM_DOM_EXCEPTION_NAMESPACE_ERR 14
#define SLIM_DOM_EXCEPTION_INVALID_ACCESS_ERR 15

#define SLIM_TKOFF_BASE_DOMC0	(0)
#define SLIM_TKNAM_BASE_DOMC0	((slim_char *)cSlim_TokenName_DOMC)
#define SLIM_TKOFF_DOMC_ELEMENT_NODE	(SLIM_TKOFF_BASE_DOMC0 + 0)
#define SLIM_TKNAM_DOMC_ELEMENT_NODE	(SLIM_TKNAM_BASE_DOMC0 + 0)
#define SLIM_TKLEN_DOMC_ELEMENT_NODE	(12)
#define SLIM_TOKEN_DOMC_ELEMENT_NODE	(DOMConstInfo_GetItem(SLIM_TKID_DOMC_ELEMENT_NODE))
#define SLIM_TKOFF_DOMC_ATTRIBUTE_NODE	(SLIM_TKOFF_BASE_DOMC0 + 13)
#define SLIM_TKNAM_DOMC_ATTRIBUTE_NODE	(SLIM_TKNAM_BASE_DOMC0 + 13)
#define SLIM_TKLEN_DOMC_ATTRIBUTE_NODE	(14)
#define SLIM_TOKEN_DOMC_ATTRIBUTE_NODE	(DOMConstInfo_GetItem(SLIM_TKID_DOMC_ATTRIBUTE_NODE))
#define SLIM_TKOFF_DOMC_TEXT_NODE	(SLIM_TKOFF_BASE_DOMC0 + 28)
#define SLIM_TKNAM_DOMC_TEXT_NODE	(SLIM_TKNAM_BASE_DOMC0 + 28)
#define SLIM_TKLEN_DOMC_TEXT_NODE	(9)
#define SLIM_TOKEN_DOMC_TEXT_NODE	(DOMConstInfo_GetItem(SLIM_TKID_DOMC_TEXT_NODE))
#define SLIM_TKOFF_DOMC_CDATA_SECTION_NODE	(SLIM_TKOFF_BASE_DOMC0 + 38)
#define SLIM_TKNAM_DOMC_CDATA_SECTION_NODE	(SLIM_TKNAM_BASE_DOMC0 + 38)
#define SLIM_TKLEN_DOMC_CDATA_SECTION_NODE	(18)
#define SLIM_TOKEN_DOMC_CDATA_SECTION_NODE	(DOMConstInfo_GetItem(SLIM_TKID_DOMC_CDATA_SECTION_NODE))
#define SLIM_TKOFF_DOMC_ENTITY_REFERENCE_NODE	(SLIM_TKOFF_BASE_DOMC0 + 57)
#define SLIM_TKNAM_DOMC_ENTITY_REFERENCE_NODE	(SLIM_TKNAM_BASE_DOMC0 + 57)
#define SLIM_TKLEN_DOMC_ENTITY_REFERENCE_NODE	(21)
#define SLIM_TOKEN_DOMC_ENTITY_REFERENCE_NODE	(DOMConstInfo_GetItem(SLIM_TKID_DOMC_ENTITY_REFERENCE_NODE))
#define SLIM_TKOFF_DOMC_ENTITY_NODE	(SLIM_TKOFF_BASE_DOMC0 + 79)
#define SLIM_TKNAM_DOMC_ENTITY_NODE	(SLIM_TKNAM_BASE_DOMC0 + 79)
#define SLIM_TKLEN_DOMC_ENTITY_NODE	(11)
#define SLIM_TOKEN_DOMC_ENTITY_NODE	(DOMConstInfo_GetItem(SLIM_TKID_DOMC_ENTITY_NODE))
#define SLIM_TKOFF_DOMC_PROCESSING_INSTRUCTION_NODE	(SLIM_TKOFF_BASE_DOMC0 + 91)
#define SLIM_TKNAM_DOMC_PROCESSING_INSTRUCTION_NODE	(SLIM_TKNAM_BASE_DOMC0 + 91)
#define SLIM_TKLEN_DOMC_PROCESSING_INSTRUCTION_NODE	(27)
#define SLIM_TOKEN_DOMC_PROCESSING_INSTRUCTION_NODE	(DOMConstInfo_GetItem(SLIM_TKID_DOMC_PROCESSING_INSTRUCTION_NODE))
#define SLIM_TKOFF_DOMC_COMMENT_NODE	(SLIM_TKOFF_BASE_DOMC0 + 119)
#define SLIM_TKNAM_DOMC_COMMENT_NODE	(SLIM_TKNAM_BASE_DOMC0 + 119)
#define SLIM_TKLEN_DOMC_COMMENT_NODE	(12)
#define SLIM_TOKEN_DOMC_COMMENT_NODE	(DOMConstInfo_GetItem(SLIM_TKID_DOMC_COMMENT_NODE))
#define SLIM_TKOFF_DOMC_DOCUMENT_NODE	(SLIM_TKOFF_BASE_DOMC0 + 132)
#define SLIM_TKNAM_DOMC_DOCUMENT_NODE	(SLIM_TKNAM_BASE_DOMC0 + 132)
#define SLIM_TKLEN_DOMC_DOCUMENT_NODE	(13)
#define SLIM_TOKEN_DOMC_DOCUMENT_NODE	(DOMConstInfo_GetItem(SLIM_TKID_DOMC_DOCUMENT_NODE))
#define SLIM_TKOFF_DOMC_DOCUMENT_TYPE_NODE	(SLIM_TKOFF_BASE_DOMC0 + 146)
#define SLIM_TKNAM_DOMC_DOCUMENT_TYPE_NODE	(SLIM_TKNAM_BASE_DOMC0 + 146)
#define SLIM_TKLEN_DOMC_DOCUMENT_TYPE_NODE	(18)
#define SLIM_TOKEN_DOMC_DOCUMENT_TYPE_NODE	(DOMConstInfo_GetItem(SLIM_TKID_DOMC_DOCUMENT_TYPE_NODE))
#define SLIM_TKOFF_DOMC_DOCUMENT_FRAGMENT_NODE	(SLIM_TKOFF_BASE_DOMC0 + 165)
#define SLIM_TKNAM_DOMC_DOCUMENT_FRAGMENT_NODE	(SLIM_TKNAM_BASE_DOMC0 + 165)
#define SLIM_TKLEN_DOMC_DOCUMENT_FRAGMENT_NODE	(22)
#define SLIM_TOKEN_DOMC_DOCUMENT_FRAGMENT_NODE	(DOMConstInfo_GetItem(SLIM_TKID_DOMC_DOCUMENT_FRAGMENT_NODE))
#define SLIM_TKOFF_DOMC_NOTATION_NODE	(SLIM_TKOFF_BASE_DOMC0 + 188)
#define SLIM_TKNAM_DOMC_NOTATION_NODE	(SLIM_TKNAM_BASE_DOMC0 + 188)
#define SLIM_TKLEN_DOMC_NOTATION_NODE	(13)
#define SLIM_TOKEN_DOMC_NOTATION_NODE	(DOMConstInfo_GetItem(SLIM_TKID_DOMC_NOTATION_NODE))
#define SLIM_TKOFF_BASE_DOMC1	(SLIM_TKOFF_BASE_DOMC0 + 202)
#define SLIM_TKNAM_BASE_DOMC1	(SLIM_TKNAM_BASE_DOMC0 + SLIM_TKOFF_BASE_DOMC1)
#define SLIM_TKLEN_TOTAL_DOMC	SLIM_TKOFF_BASE_DOMC1

extern SLIM_ROM slim_char cSlim_TokenName_DOMC[SLIM_TKLEN_TOTAL_DOMC];

extern SLIM_ROM TDOMConstInfo cSlim_Token_DOMC[SLIM_TOKEN_DOMC_TOKENS];
#define DOMConstInfo_GetItem(id)		((TDOMConstInfo *)&cSlim_Token_DOMC[(id)])
#define DOMConstInfo_GetItemName(id)	((slim_char *)cSlim_TokenName_DOMC + ((TToken *)&cSlim_Token_DOMC[(id)])->fOffset)
#define DOMConstInfo_GetItemNameLen(id)	(((TToken *)&cSlim_Token_DOMC[(id)])->fLength)

TDOMConstInfo *DOMConstInfo_CaseFindSS(slim_char *in_s, slim_int in_slen);

SLIM_END_C_LINKAGE
#endif
