/*
	hpstrid.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/private/token/hpstrid.h 4     05/12/28 12:08 Someya $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_HPSTRID_H
#define SLIM_TOKEN_HPSTRID_H


SLIM_BEGIN_C_LINKAGE

enum {
	SLIM_TKID_HPSTR_http_ = 0,
	SLIM_TKID_HPSTR_https_,
	SLIM_TKID_HPSTR_OPTIONS,
	SLIM_TKID_HPSTR_GET,
	SLIM_TKID_HPSTR_HEAD,
	SLIM_TKID_HPSTR_POST,
	SLIM_TKID_HPSTR_PUT,
	SLIM_TKID_HPSTR_DELETE,
	SLIM_TKID_HPSTR_TRACE,
	SLIM_TKID_HPSTR_CONNECT,
	SLIM_TKID_HPSTR_HTTP_0_9,
	SLIM_TKID_HPSTR_HTTP_1_0,
	SLIM_TKID_HPSTR_HTTP_1_1,
	SLIM_TKID_HPSTR_timeout_,
	SLIM_TKID_HPSTR_max_,
	SLIM_TKID_HPSTR_maxreq_,
	SLIM_TKID_HPSTR_bytes_,
	SLIM_TKID_HPSTR_bytes,
	SLIM_TKID_HPSTR_close,
	SLIM_TKID_HPSTR_Keep_Alive,
	SLIM_TKID_HPSTR_no_cache,
	SLIM_TKID_HPSTR_Basic,
	SLIM_TKID_HPSTR_Digest,
	SLIM_TKID_HPSTR_chunked,
	SLIM_TKID_HPSTR_realm_,
	SLIM_TKID_HPSTR_nonce_,
	SLIM_TKID_HPSTR_algorithm_,
	SLIM_TKID_HPSTR_opaque_,
	SLIM_TKID_HPSTR_qop_,
	SLIM_TKID_HPSTR_domain_,
	SLIM_TKID_HPSTR_stale_,
	SLIM_TKID_HPSTR_cnonce_,
	SLIM_TKID_HPSTR_nc_,
	SLIM_TKID_HPSTR_uri_,
	SLIM_TKID_HPSTR_nextnonce_,
	SLIM_TKID_HPSTR_rspauth_,
	SLIM_TKID_HPSTR_true,
	SLIM_TKID_HPSTR_com,
	SLIM_TKID_HPSTR_net,
	SLIM_TKID_HPSTR_org,
	SLIM_TKID_HPSTR_info,
	SLIM_TKID_HPSTR_biz,
	SLIM_TKID_HPSTR_gov,
	SLIM_TKID_HPSTR_edu,
	SLIM_TKID_HPSTR_int,
	SLIM_TKID_HPSTR_mil,
	SLIM_TKID_HPSTR_coop,
	SLIM_TKID_HPSTR_aero,
	SLIM_TKID_HPSTR_museum,
	SLIM_TKID_HPSTR_name,
	SLIM_TKID_HPSTR_pro,
	SLIM_TKID_HPSTR_ai,
	SLIM_TKID_HPSTR_au,
	SLIM_TKID_HPSTR_bd,
	SLIM_TKID_HPSTR_bh,
	SLIM_TKID_HPSTR_ck,
	SLIM_TKID_HPSTR_eg,
	SLIM_TKID_HPSTR_et,
	SLIM_TKID_HPSTR_fk,
	SLIM_TKID_HPSTR_il,
	SLIM_TKID_HPSTR_in,
	SLIM_TKID_HPSTR_kh,
	SLIM_TKID_HPSTR_kr,
	SLIM_TKID_HPSTR_mk,
	SLIM_TKID_HPSTR_mt,
	SLIM_TKID_HPSTR_na,
	SLIM_TKID_HPSTR_np,
	SLIM_TKID_HPSTR_nz,
	SLIM_TKID_HPSTR_pg,
	SLIM_TKID_HPSTR_pk,
	SLIM_TKID_HPSTR_qa,
	SLIM_TKID_HPSTR_sa,
	SLIM_TKID_HPSTR_sb,
	SLIM_TKID_HPSTR_sg,
	SLIM_TKID_HPSTR_sv,
	SLIM_TKID_HPSTR_ua,
	SLIM_TKID_HPSTR_ug,
	SLIM_TKID_HPSTR_uk,
	SLIM_TKID_HPSTR_uy,
	SLIM_TKID_HPSTR_vn,
	SLIM_TKID_HPSTR_za,
	SLIM_TKID_HPSTR_zw,
	SLIM_TKID_HPSTR_ENUMS
};

#define SLIM_TOKEN_HPSTR_TOKENS SLIM_TKID_HPSTR_ENUMS
#define SLIM_TOKEN_HPSTR_ENUMS SLIM_TKID_HPSTR_ENUMS


SLIM_END_C_LINKAGE
#endif
