/*
	htatid.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/private/token/htatid.h 8     06/07/11 22:03 Yamabuti $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_HTATID_H
#define SLIM_TOKEN_HTATID_H


SLIM_BEGIN_C_LINKAGE

enum {
	SLIM_TKID_HTAT_abbr = 0,
	SLIM_TKID_HTAT_accept_charset,
	SLIM_TKID_HTAT_accept,
	SLIM_TKID_HTAT_accesskey,
	SLIM_TKID_HTAT_action,
	SLIM_TKID_HTAT_align,
	SLIM_TKID_HTAT_alink,
	SLIM_TKID_HTAT_alt,
	SLIM_TKID_HTAT_archive,
	SLIM_TKID_HTAT_axis,
	SLIM_TKID_HTAT_background,
	SLIM_TKID_HTAT_balance,
	SLIM_TKID_HTAT_bgcolor,
	SLIM_TKID_HTAT_bgproperties,
	SLIM_TKID_HTAT_border,
	SLIM_TKID_HTAT_bordercolor,
	SLIM_TKID_HTAT_bottommargin,
	SLIM_TKID_HTAT_cellpadding,
	SLIM_TKID_HTAT_cellspacing,
	SLIM_TKID_HTAT_char,
	SLIM_TKID_HTAT_charoff,
	SLIM_TKID_HTAT_charset,
	SLIM_TKID_HTAT_checked,
	SLIM_TKID_HTAT_cite,
	SLIM_TKID_HTAT_class,
	SLIM_TKID_HTAT_classid,
	SLIM_TKID_HTAT_clear,
	SLIM_TKID_HTAT_code,
	SLIM_TKID_HTAT_codebase,
	SLIM_TKID_HTAT_codetype,
	SLIM_TKID_HTAT_color,
	SLIM_TKID_HTAT_cols,
	SLIM_TKID_HTAT_colspan,
	SLIM_TKID_HTAT_compact,
	SLIM_TKID_HTAT_content,
	SLIM_TKID_HTAT_coords,
	SLIM_TKID_HTAT_data,
	SLIM_TKID_HTAT_datetime,
	SLIM_TKID_HTAT_declare,
	SLIM_TKID_HTAT_defer,
	SLIM_TKID_HTAT_dir,
	SLIM_TKID_HTAT_disabled,
	SLIM_TKID_HTAT_enctype,
	SLIM_TKID_HTAT_face,
	SLIM_TKID_HTAT_for,
	SLIM_TKID_HTAT_frame,
	SLIM_TKID_HTAT_frameborder,
	SLIM_TKID_HTAT_headers,
	SLIM_TKID_HTAT_height,
	SLIM_TKID_HTAT_hidden,
	SLIM_TKID_HTAT_href,
	SLIM_TKID_HTAT_hreflang,
	SLIM_TKID_HTAT_hspace,
	SLIM_TKID_HTAT_http_equiv,
	SLIM_TKID_HTAT_id,
	SLIM_TKID_HTAT_ismap,
	SLIM_TKID_HTAT_label,
	SLIM_TKID_HTAT_lang,
	SLIM_TKID_HTAT_language,
	SLIM_TKID_HTAT_leftmargin,
	SLIM_TKID_HTAT_link,
	SLIM_TKID_HTAT_longdesc,
	SLIM_TKID_HTAT_lowsrc,
	SLIM_TKID_HTAT_marginheight,
	SLIM_TKID_HTAT_marginwidth,
	SLIM_TKID_HTAT_maxlength,
	SLIM_TKID_HTAT_media,
	SLIM_TKID_HTAT_method,
	SLIM_TKID_HTAT_multiple,
	SLIM_TKID_HTAT_name,
	SLIM_TKID_HTAT_nohref,
	SLIM_TKID_HTAT_noresize,
	SLIM_TKID_HTAT_noshade,
	SLIM_TKID_HTAT_nowrap,
	SLIM_TKID_HTAT_object,
	SLIM_TKID_HTAT_onabort,
	SLIM_TKID_HTAT_onblur,
	SLIM_TKID_HTAT_onchange,
	SLIM_TKID_HTAT_onclick,
	SLIM_TKID_HTAT_oncontextmenu,
	SLIM_TKID_HTAT_ondblclick,
	SLIM_TKID_HTAT_onerror,
	SLIM_TKID_HTAT_onfocus,
	SLIM_TKID_HTAT_onkeydown,
	SLIM_TKID_HTAT_onkeypress,
	SLIM_TKID_HTAT_onkeyup,
	SLIM_TKID_HTAT_onload,
	SLIM_TKID_HTAT_onmousedown,
	SLIM_TKID_HTAT_onmousemove,
	SLIM_TKID_HTAT_onmouseout,
	SLIM_TKID_HTAT_onmouseover,
	SLIM_TKID_HTAT_onmouseup,
	SLIM_TKID_HTAT_onmousewheel,
	SLIM_TKID_HTAT_onreset,
	SLIM_TKID_HTAT_onselect,
	SLIM_TKID_HTAT_onsubmit,
	SLIM_TKID_HTAT_onunload,
	SLIM_TKID_HTAT_profile,
	SLIM_TKID_HTAT_prompt,
	SLIM_TKID_HTAT_readonly,
	SLIM_TKID_HTAT_rel,
	SLIM_TKID_HTAT_rev,
	SLIM_TKID_HTAT_rightmargin,
	SLIM_TKID_HTAT_rows,
	SLIM_TKID_HTAT_rowspan,
	SLIM_TKID_HTAT_rules,
	SLIM_TKID_HTAT_scheme,
	SLIM_TKID_HTAT_scope,
	SLIM_TKID_HTAT_scroll,
	SLIM_TKID_HTAT_scrolling,
	SLIM_TKID_HTAT_selected,
	SLIM_TKID_HTAT_shape,
	SLIM_TKID_HTAT_size,
	SLIM_TKID_HTAT_span,
	SLIM_TKID_HTAT_src,
	SLIM_TKID_HTAT_standby,
	SLIM_TKID_HTAT_start,
	SLIM_TKID_HTAT_style,
	SLIM_TKID_HTAT_summary,
	SLIM_TKID_HTAT_tabbable,
	SLIM_TKID_HTAT_tabindex,
	SLIM_TKID_HTAT_target,
	SLIM_TKID_HTAT_text,
	SLIM_TKID_HTAT_title,
	SLIM_TKID_HTAT_topmargin,
	SLIM_TKID_HTAT_type,
	SLIM_TKID_HTAT_usemap,
	SLIM_TKID_HTAT_valign,
	SLIM_TKID_HTAT_value,
	SLIM_TKID_HTAT_valuetype,
	SLIM_TKID_HTAT_version,
	SLIM_TKID_HTAT_vlink,
	SLIM_TKID_HTAT_volume,
	SLIM_TKID_HTAT_vspace,
	SLIM_TKID_HTAT_width,
	SLIM_TKID_HTAT_wrap,
	SLIM_TKID_HTAT_behavior,
	SLIM_TKID_HTAT_direction,
	SLIM_TKID_HTAT_loop,
	SLIM_TKID_HTAT_scrollamount,
	SLIM_TKID_HTAT_scrolldelay,
	SLIM_TKID_HTAT_xmlns,
	SLIM_TKID_HTAT_jad,
	SLIM_TKID_HTAT_datasrc,
	SLIM_TKID_HTAT_datafld,
	SLIM_TKID_HTAT_dataformatas,
	SLIM_TKID_HTAT_datapagesize,
	SLIM_TKID_HTAT_ENUMS
};

#define SLIM_TOKEN_HTAT_TOKENS SLIM_TKID_HTAT_ENUMS
#define SLIM_TOKEN_HTAT_ENUMS SLIM_TKID_HTAT_ENUMS


SLIM_END_C_LINKAGE
#endif
