/*
	htclid.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/private/token/htclid.h 4     05/12/28 12:08 Someya $ */

/* DO NOT EDIT! This file is generated automatically. */

#ifndef SLIM_TOKEN_HTCLID_H
#define SLIM_TOKEN_HTCLID_H


SLIM_BEGIN_C_LINKAGE

enum {
	SLIM_TKID_HTCL_aliceblue = 0,
	SLIM_TKID_HTCL_antiquewhite,
	SLIM_TKID_HTCL_aqua,
	SLIM_TKID_HTCL_aquamarine,
	SLIM_TKID_HTCL_azure,
	SLIM_TKID_HTCL_beige,
	SLIM_TKID_HTCL_bisque,
	SLIM_TKID_HTCL_black,
	SLIM_TKID_HTCL_blanchedalmond,
	SLIM_TKID_HTCL_blue,
	SLIM_TKID_HTCL_blueviolet,
	SLIM_TKID_HTCL_brown,
	SLIM_TKID_HTCL_burlywood,
	SLIM_TKID_HTCL_cadetblue,
	SLIM_TKID_HTCL_chartreuse,
	SLIM_TKID_HTCL_chocolate,
	SLIM_TKID_HTCL_coral,
	SLIM_TKID_HTCL_cornflower,
	SLIM_TKID_HTCL_cornflowerblue,
	SLIM_TKID_HTCL_cornsilk,
	SLIM_TKID_HTCL_crimson,
	SLIM_TKID_HTCL_cyan,
	SLIM_TKID_HTCL_darkblue,
	SLIM_TKID_HTCL_darkcyan,
	SLIM_TKID_HTCL_darkgoldenrod,
	SLIM_TKID_HTCL_darkgray,
	SLIM_TKID_HTCL_darkgreen,
	SLIM_TKID_HTCL_darkkhaki,
	SLIM_TKID_HTCL_darkmagenta,
	SLIM_TKID_HTCL_darkolivegreen,
	SLIM_TKID_HTCL_darkorange,
	SLIM_TKID_HTCL_darkorchid,
	SLIM_TKID_HTCL_darkred,
	SLIM_TKID_HTCL_darksalmon,
	SLIM_TKID_HTCL_darkseagreen,
	SLIM_TKID_HTCL_darkslateblue,
	SLIM_TKID_HTCL_darkslategray,
	SLIM_TKID_HTCL_darkturquoise,
	SLIM_TKID_HTCL_darkviolet,
	SLIM_TKID_HTCL_deeppink,
	SLIM_TKID_HTCL_deepskyblue,
	SLIM_TKID_HTCL_dimgray,
	SLIM_TKID_HTCL_dodgerblue,
	SLIM_TKID_HTCL_firebrick,
	SLIM_TKID_HTCL_floralwhite,
	SLIM_TKID_HTCL_forestgreen,
	SLIM_TKID_HTCL_fuchsia,
	SLIM_TKID_HTCL_gainsboro,
	SLIM_TKID_HTCL_ghostwhite,
	SLIM_TKID_HTCL_gold,
	SLIM_TKID_HTCL_goldenrod,
	SLIM_TKID_HTCL_gray,
	SLIM_TKID_HTCL_green,
	SLIM_TKID_HTCL_greenyellow,
	SLIM_TKID_HTCL_honeydew,
	SLIM_TKID_HTCL_hotpink,
	SLIM_TKID_HTCL_indianred,
	SLIM_TKID_HTCL_indigo,
	SLIM_TKID_HTCL_ivory,
	SLIM_TKID_HTCL_khaki,
	SLIM_TKID_HTCL_lavender,
	SLIM_TKID_HTCL_lavenderblush,
	SLIM_TKID_HTCL_lawngreen,
	SLIM_TKID_HTCL_lemonchiffon,
	SLIM_TKID_HTCL_lightblue,
	SLIM_TKID_HTCL_lightcoral,
	SLIM_TKID_HTCL_lightcyan,
	SLIM_TKID_HTCL_lightgoldenrodyellow,
	SLIM_TKID_HTCL_lightgray,
	SLIM_TKID_HTCL_lightgreen,
	SLIM_TKID_HTCL_lightgrey,
	SLIM_TKID_HTCL_lightpink,
	SLIM_TKID_HTCL_lightsalmon,
	SLIM_TKID_HTCL_lightseagreen,
	SLIM_TKID_HTCL_lightskyblue,
	SLIM_TKID_HTCL_lightslategray,
	SLIM_TKID_HTCL_lightsteelblue,
	SLIM_TKID_HTCL_lightyellow,
	SLIM_TKID_HTCL_lime,
	SLIM_TKID_HTCL_limegreen,
	SLIM_TKID_HTCL_linen,
	SLIM_TKID_HTCL_magenta,
	SLIM_TKID_HTCL_maroon,
	SLIM_TKID_HTCL_mediumaquamarine,
	SLIM_TKID_HTCL_mediumblue,
	SLIM_TKID_HTCL_mediumorchid,
	SLIM_TKID_HTCL_mediumpurple,
	SLIM_TKID_HTCL_mediumseagreen,
	SLIM_TKID_HTCL_mediumslateblue,
	SLIM_TKID_HTCL_mediumspringgreen,
	SLIM_TKID_HTCL_mediumturquoise,
	SLIM_TKID_HTCL_mediumvioletred,
	SLIM_TKID_HTCL_midnightblue,
	SLIM_TKID_HTCL_mintcream,
	SLIM_TKID_HTCL_mistyrose,
	SLIM_TKID_HTCL_moccasin,
	SLIM_TKID_HTCL_navajowhite,
	SLIM_TKID_HTCL_navy,
	SLIM_TKID_HTCL_oldlace,
	SLIM_TKID_HTCL_olive,
	SLIM_TKID_HTCL_olivedrab,
	SLIM_TKID_HTCL_orange,
	SLIM_TKID_HTCL_orangered,
	SLIM_TKID_HTCL_orchid,
	SLIM_TKID_HTCL_palegoldenrod,
	SLIM_TKID_HTCL_palegreen,
	SLIM_TKID_HTCL_paleturquoise,
	SLIM_TKID_HTCL_palevioletred,
	SLIM_TKID_HTCL_papayawhip,
	SLIM_TKID_HTCL_peachpuff,
	SLIM_TKID_HTCL_peru,
	SLIM_TKID_HTCL_pink,
	SLIM_TKID_HTCL_plum,
	SLIM_TKID_HTCL_powderblue,
	SLIM_TKID_HTCL_purple,
	SLIM_TKID_HTCL_red,
	SLIM_TKID_HTCL_rosybrown,
	SLIM_TKID_HTCL_royalblue,
	SLIM_TKID_HTCL_saddlebrown,
	SLIM_TKID_HTCL_salmon,
	SLIM_TKID_HTCL_sandybrown,
	SLIM_TKID_HTCL_seagreen,
	SLIM_TKID_HTCL_seashell,
	SLIM_TKID_HTCL_sienna,
	SLIM_TKID_HTCL_silver,
	SLIM_TKID_HTCL_skyblue,
	SLIM_TKID_HTCL_slateblue,
	SLIM_TKID_HTCL_slategray,
	SLIM_TKID_HTCL_snow,
	SLIM_TKID_HTCL_springgreen,
	SLIM_TKID_HTCL_steelblue,
	SLIM_TKID_HTCL_tan,
	SLIM_TKID_HTCL_teal,
	SLIM_TKID_HTCL_thistle,
	SLIM_TKID_HTCL_tomato,
	SLIM_TKID_HTCL_turquoise,
	SLIM_TKID_HTCL_violet,
	SLIM_TKID_HTCL_wheat,
	SLIM_TKID_HTCL_white,
	SLIM_TKID_HTCL_whitesmoke,
	SLIM_TKID_HTCL_yellow,
	SLIM_TKID_HTCL_yellowgreen,
	SLIM_TKID_HTCL_ENUMS
};

#define SLIM_TOKEN_HTCL_TOKENS SLIM_TKID_HTCL_ENUMS
#define SLIM_TOKEN_HTCL_ENUMS SLIM_TKID_HTCL_ENUMS


SLIM_END_C_LINKAGE
#endif
