/*
	mime.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_MIME_H
#define SLIM_TOKEN_MIME_H

#include <slim/basis/base.h>
#include <slim/basis/token.h>
#include <slim/token/mimeid.h>

SLIM_BEGIN_C_LINKAGE

struct TMIMEInfo_ {
	TToken fBase;	/* must be the first field */
	slim_int fFlag;
};
typedef struct TMIMEInfo_ TMIMEInfo;

#define SLIM_MIMEINFO_FLAG_TEXT			0x00000001
#define SLIM_MIMEINFO_FLAG_IMAGE		0x00000002
#define SLIM_MIMEINFO_FLAG_XML			0x00000004
#define SLIM_MIMEINFO_FLAG_HTML			0x00000008
#define SLIM_MIMEINFO_FLAG_WML			0x00000010
#define SLIM_MIMEINFO_FLAG_DRM			0x00000020
#define SLIM_MIMEINFO_FLAG_MULTIPART	0x00000040
#define SLIM_MIMEINFO_FLAG_DEFAULT		0x00000080

#define SLIM_TKOFF_BASE_MIME0	(0)
#define SLIM_TKNAM_BASE_MIME0	((slim_char *)cSlim_TokenName_MIME)
#define SLIM_TKOFF_MIME____	(SLIM_TKOFF_BASE_MIME0 + 0)
#define SLIM_TKNAM_MIME____	(SLIM_TKNAM_BASE_MIME0 + 0)
#define SLIM_TKLEN_MIME____	(3)
#define SLIM_TOKEN_MIME____	(MIMEInfo_GetItem(SLIM_TKID_MIME____))
#define SLIM_TKOFF_MIME_text__	(SLIM_TKOFF_BASE_MIME0 + 4)
#define SLIM_TKNAM_MIME_text__	(SLIM_TKNAM_BASE_MIME0 + 4)
#define SLIM_TKLEN_MIME_text__	(6)
#define SLIM_TOKEN_MIME_text__	(MIMEInfo_GetItem(SLIM_TKID_MIME_text__))
#define SLIM_TKOFF_MIME_application__	(SLIM_TKOFF_BASE_MIME0 + 11)
#define SLIM_TKNAM_MIME_application__	(SLIM_TKNAM_BASE_MIME0 + 11)
#define SLIM_TKLEN_MIME_application__	(13)
#define SLIM_TOKEN_MIME_application__	(MIMEInfo_GetItem(SLIM_TKID_MIME_application__))
#define SLIM_TKOFF_MIME_image__	(SLIM_TKOFF_BASE_MIME0 + 25)
#define SLIM_TKNAM_MIME_image__	(SLIM_TKNAM_BASE_MIME0 + 25)
#define SLIM_TKLEN_MIME_image__	(7)
#define SLIM_TOKEN_MIME_image__	(MIMEInfo_GetItem(SLIM_TKID_MIME_image__))
#define SLIM_TKOFF_MIME_audio__	(SLIM_TKOFF_BASE_MIME0 + 33)
#define SLIM_TKNAM_MIME_audio__	(SLIM_TKNAM_BASE_MIME0 + 33)
#define SLIM_TKLEN_MIME_audio__	(7)
#define SLIM_TOKEN_MIME_audio__	(MIMEInfo_GetItem(SLIM_TKID_MIME_audio__))
#define SLIM_TKOFF_MIME_video__	(SLIM_TKOFF_BASE_MIME0 + 41)
#define SLIM_TKNAM_MIME_video__	(SLIM_TKNAM_BASE_MIME0 + 41)
#define SLIM_TKLEN_MIME_video__	(7)
#define SLIM_TOKEN_MIME_video__	(MIMEInfo_GetItem(SLIM_TKID_MIME_video__))
#define SLIM_TKOFF_MIME_model__	(SLIM_TKOFF_BASE_MIME0 + 49)
#define SLIM_TKNAM_MIME_model__	(SLIM_TKNAM_BASE_MIME0 + 49)
#define SLIM_TKLEN_MIME_model__	(7)
#define SLIM_TOKEN_MIME_model__	(MIMEInfo_GetItem(SLIM_TKID_MIME_model__))
#define SLIM_TKOFF_MIME_message__	(SLIM_TKOFF_BASE_MIME0 + 57)
#define SLIM_TKNAM_MIME_message__	(SLIM_TKNAM_BASE_MIME0 + 57)
#define SLIM_TKLEN_MIME_message__	(9)
#define SLIM_TOKEN_MIME_message__	(MIMEInfo_GetItem(SLIM_TKID_MIME_message__))
#define SLIM_TKOFF_MIME_multipart__	(SLIM_TKOFF_BASE_MIME0 + 67)
#define SLIM_TKNAM_MIME_multipart__	(SLIM_TKNAM_BASE_MIME0 + 67)
#define SLIM_TKLEN_MIME_multipart__	(11)
#define SLIM_TOKEN_MIME_multipart__	(MIMEInfo_GetItem(SLIM_TKID_MIME_multipart__))
#define SLIM_TKOFF_MIME_x_world__	(SLIM_TKOFF_BASE_MIME0 + 79)
#define SLIM_TKNAM_MIME_x_world__	(SLIM_TKNAM_BASE_MIME0 + 79)
#define SLIM_TKLEN_MIME_x_world__	(9)
#define SLIM_TOKEN_MIME_x_world__	(MIMEInfo_GetItem(SLIM_TKID_MIME_x_world__))
#define SLIM_TKOFF_MIME_text_html	(SLIM_TKOFF_BASE_MIME0 + 89)
#define SLIM_TKNAM_MIME_text_html	(SLIM_TKNAM_BASE_MIME0 + 89)
#define SLIM_TKLEN_MIME_text_html	(9)
#define SLIM_TOKEN_MIME_text_html	(MIMEInfo_GetItem(SLIM_TKID_MIME_text_html))
#define SLIM_TKOFF_MIME_application_xhtml_xml	(SLIM_TKOFF_BASE_MIME0 + 99)
#define SLIM_TKNAM_MIME_application_xhtml_xml	(SLIM_TKNAM_BASE_MIME0 + 99)
#define SLIM_TKLEN_MIME_application_xhtml_xml	(21)
#define SLIM_TOKEN_MIME_application_xhtml_xml	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_xhtml_xml))
#define SLIM_TKOFF_MIME_text_plain	(SLIM_TKOFF_BASE_MIME0 + 121)
#define SLIM_TKNAM_MIME_text_plain	(SLIM_TKNAM_BASE_MIME0 + 121)
#define SLIM_TKLEN_MIME_text_plain	(10)
#define SLIM_TOKEN_MIME_text_plain	(MIMEInfo_GetItem(SLIM_TKID_MIME_text_plain))
#define SLIM_TKOFF_MIME_text_xml	(SLIM_TKOFF_BASE_MIME0 + 132)
#define SLIM_TKNAM_MIME_text_xml	(SLIM_TKNAM_BASE_MIME0 + 132)
#define SLIM_TKLEN_MIME_text_xml	(8)
#define SLIM_TOKEN_MIME_text_xml	(MIMEInfo_GetItem(SLIM_TKID_MIME_text_xml))
#define SLIM_TKOFF_MIME_application_xml	(SLIM_TKOFF_BASE_MIME0 + 141)
#define SLIM_TKNAM_MIME_application_xml	(SLIM_TKNAM_BASE_MIME0 + 141)
#define SLIM_TKLEN_MIME_application_xml	(15)
#define SLIM_TOKEN_MIME_application_xml	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_xml))
#define SLIM_TKOFF_MIME_image_gif	(SLIM_TKOFF_BASE_MIME0 + 157)
#define SLIM_TKNAM_MIME_image_gif	(SLIM_TKNAM_BASE_MIME0 + 157)
#define SLIM_TKLEN_MIME_image_gif	(9)
#define SLIM_TOKEN_MIME_image_gif	(MIMEInfo_GetItem(SLIM_TKID_MIME_image_gif))
#define SLIM_TKOFF_MIME_image_jpeg	(SLIM_TKOFF_BASE_MIME0 + 167)
#define SLIM_TKNAM_MIME_image_jpeg	(SLIM_TKNAM_BASE_MIME0 + 167)
#define SLIM_TKLEN_MIME_image_jpeg	(10)
#define SLIM_TOKEN_MIME_image_jpeg	(MIMEInfo_GetItem(SLIM_TKID_MIME_image_jpeg))
#define SLIM_TKOFF_MIME_image_pjpeg	(SLIM_TKOFF_BASE_MIME0 + 178)
#define SLIM_TKNAM_MIME_image_pjpeg	(SLIM_TKNAM_BASE_MIME0 + 178)
#define SLIM_TKLEN_MIME_image_pjpeg	(11)
#define SLIM_TOKEN_MIME_image_pjpeg	(MIMEInfo_GetItem(SLIM_TKID_MIME_image_pjpeg))
#define SLIM_TKOFF_MIME_image_png	(SLIM_TKOFF_BASE_MIME0 + 190)
#define SLIM_TKNAM_MIME_image_png	(SLIM_TKNAM_BASE_MIME0 + 190)
#define SLIM_TKLEN_MIME_image_png	(9)
#define SLIM_TOKEN_MIME_image_png	(MIMEInfo_GetItem(SLIM_TKID_MIME_image_png))
#define SLIM_TKOFF_MIME_image_bmp	(SLIM_TKOFF_BASE_MIME0 + 200)
#define SLIM_TKNAM_MIME_image_bmp	(SLIM_TKNAM_BASE_MIME0 + 200)
#define SLIM_TKLEN_MIME_image_bmp	(9)
#define SLIM_TOKEN_MIME_image_bmp	(MIMEInfo_GetItem(SLIM_TKID_MIME_image_bmp))
#define SLIM_TKOFF_MIME_video_x_mng	(SLIM_TKOFF_BASE_MIME0 + 210)
#define SLIM_TKNAM_MIME_video_x_mng	(SLIM_TKNAM_BASE_MIME0 + 210)
#define SLIM_TKLEN_MIME_video_x_mng	(11)
#define SLIM_TOKEN_MIME_video_x_mng	(MIMEInfo_GetItem(SLIM_TKID_MIME_video_x_mng))
#define SLIM_TKOFF_MIME_text_css	(SLIM_TKOFF_BASE_MIME0 + 222)
#define SLIM_TKNAM_MIME_text_css	(SLIM_TKNAM_BASE_MIME0 + 222)
#define SLIM_TKLEN_MIME_text_css	(8)
#define SLIM_TOKEN_MIME_text_css	(MIMEInfo_GetItem(SLIM_TKID_MIME_text_css))
#define SLIM_TKOFF_MIME_text_javascript	(SLIM_TKOFF_BASE_MIME0 + 231)
#define SLIM_TKNAM_MIME_text_javascript	(SLIM_TKNAM_BASE_MIME0 + 231)
#define SLIM_TKLEN_MIME_text_javascript	(15)
#define SLIM_TOKEN_MIME_text_javascript	(MIMEInfo_GetItem(SLIM_TKID_MIME_text_javascript))
#define SLIM_TKOFF_MIME_application_x_javascript	(SLIM_TKOFF_BASE_MIME0 + 247)
#define SLIM_TKNAM_MIME_application_x_javascript	(SLIM_TKNAM_BASE_MIME0 + 247)
#define SLIM_TKLEN_MIME_application_x_javascript	(24)
#define SLIM_TOKEN_MIME_application_x_javascript	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_javascript))
#define SLIM_TKOFF_MIME_application_smil	(SLIM_TKOFF_BASE_MIME0 + 272)
#define SLIM_TKNAM_MIME_application_smil	(SLIM_TKNAM_BASE_MIME0 + 272)
#define SLIM_TKLEN_MIME_application_smil	(16)
#define SLIM_TOKEN_MIME_application_smil	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_smil))
#define SLIM_TKOFF_MIME_message_rfc822	(SLIM_TKOFF_BASE_MIME0 + 289)
#define SLIM_TKNAM_MIME_message_rfc822	(SLIM_TKNAM_BASE_MIME0 + 289)
#define SLIM_TKLEN_MIME_message_rfc822	(14)
#define SLIM_TOKEN_MIME_message_rfc822	(MIMEInfo_GetItem(SLIM_TKID_MIME_message_rfc822))
#define SLIM_TKOFF_MIME_multipart_mixed	(SLIM_TKOFF_BASE_MIME0 + 304)
#define SLIM_TKNAM_MIME_multipart_mixed	(SLIM_TKNAM_BASE_MIME0 + 304)
#define SLIM_TKLEN_MIME_multipart_mixed	(15)
#define SLIM_TOKEN_MIME_multipart_mixed	(MIMEInfo_GetItem(SLIM_TKID_MIME_multipart_mixed))
#define SLIM_TKOFF_MIME_multipart_related	(SLIM_TKOFF_BASE_MIME0 + 320)
#define SLIM_TKNAM_MIME_multipart_related	(SLIM_TKNAM_BASE_MIME0 + 320)
#define SLIM_TKLEN_MIME_multipart_related	(17)
#define SLIM_TOKEN_MIME_multipart_related	(MIMEInfo_GetItem(SLIM_TKID_MIME_multipart_related))
#define SLIM_TKOFF_MIME_multipart_alternative	(SLIM_TKOFF_BASE_MIME0 + 338)
#define SLIM_TKNAM_MIME_multipart_alternative	(SLIM_TKNAM_BASE_MIME0 + 338)
#define SLIM_TKLEN_MIME_multipart_alternative	(21)
#define SLIM_TOKEN_MIME_multipart_alternative	(MIMEInfo_GetItem(SLIM_TKID_MIME_multipart_alternative))
#define SLIM_TKOFF_MIME_multipart_byteranges	(SLIM_TKOFF_BASE_MIME0 + 360)
#define SLIM_TKNAM_MIME_multipart_byteranges	(SLIM_TKNAM_BASE_MIME0 + 360)
#define SLIM_TKLEN_MIME_multipart_byteranges	(20)
#define SLIM_TOKEN_MIME_multipart_byteranges	(MIMEInfo_GetItem(SLIM_TKID_MIME_multipart_byteranges))
#define SLIM_TKOFF_MIME_application_rdf_xml	(SLIM_TKOFF_BASE_MIME0 + 381)
#define SLIM_TKNAM_MIME_application_rdf_xml	(SLIM_TKNAM_BASE_MIME0 + 381)
#define SLIM_TKLEN_MIME_application_rdf_xml	(19)
#define SLIM_TOKEN_MIME_application_rdf_xml	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_rdf_xml))
#define SLIM_TKOFF_MIME_application_rss_xml	(SLIM_TKOFF_BASE_MIME0 + 401)
#define SLIM_TKNAM_MIME_application_rss_xml	(SLIM_TKNAM_BASE_MIME0 + 401)
#define SLIM_TKLEN_MIME_application_rss_xml	(19)
#define SLIM_TOKEN_MIME_application_rss_xml	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_rss_xml))
#define SLIM_TKOFF_MIME_application_atom_xml	(SLIM_TKOFF_BASE_MIME0 + 421)
#define SLIM_TKNAM_MIME_application_atom_xml	(SLIM_TKNAM_BASE_MIME0 + 421)
#define SLIM_TKLEN_MIME_application_atom_xml	(20)
#define SLIM_TOKEN_MIME_application_atom_xml	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_atom_xml))
#define SLIM_TKOFF_MIME_application_opml_xml	(SLIM_TKOFF_BASE_MIME0 + 442)
#define SLIM_TKNAM_MIME_application_opml_xml	(SLIM_TKNAM_BASE_MIME0 + 442)
#define SLIM_TKLEN_MIME_application_opml_xml	(20)
#define SLIM_TOKEN_MIME_application_opml_xml	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_opml_xml))
#define SLIM_TKOFF_MIME_application_x_netcdf	(SLIM_TKOFF_BASE_MIME0 + 463)
#define SLIM_TKNAM_MIME_application_x_netcdf	(SLIM_TKNAM_BASE_MIME0 + 463)
#define SLIM_TKLEN_MIME_application_x_netcdf	(20)
#define SLIM_TOKEN_MIME_application_x_netcdf	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_netcdf))
#define SLIM_TKOFF_MIME_application_x_xbel	(SLIM_TKOFF_BASE_MIME0 + 484)
#define SLIM_TKNAM_MIME_application_x_xbel	(SLIM_TKNAM_BASE_MIME0 + 484)
#define SLIM_TKLEN_MIME_application_x_xbel	(18)
#define SLIM_TOKEN_MIME_application_x_xbel	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_xbel))
#define SLIM_TKOFF_MIME_application_x_url	(SLIM_TKOFF_BASE_MIME0 + 503)
#define SLIM_TKNAM_MIME_application_x_url	(SLIM_TKNAM_BASE_MIME0 + 503)
#define SLIM_TKLEN_MIME_application_x_url	(17)
#define SLIM_TOKEN_MIME_application_x_url	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_url))
#define SLIM_TKOFF_MIME_text_vnd_wap_wml	(SLIM_TKOFF_BASE_MIME0 + 521)
#define SLIM_TKNAM_MIME_text_vnd_wap_wml	(SLIM_TKNAM_BASE_MIME0 + 521)
#define SLIM_TKLEN_MIME_text_vnd_wap_wml	(16)
#define SLIM_TOKEN_MIME_text_vnd_wap_wml	(MIMEInfo_GetItem(SLIM_TKID_MIME_text_vnd_wap_wml))
#define SLIM_TKOFF_MIME_image_vnd_wap_wbmp	(SLIM_TKOFF_BASE_MIME0 + 538)
#define SLIM_TKNAM_MIME_image_vnd_wap_wbmp	(SLIM_TKNAM_BASE_MIME0 + 538)
#define SLIM_TKLEN_MIME_image_vnd_wap_wbmp	(18)
#define SLIM_TOKEN_MIME_image_vnd_wap_wbmp	(MIMEInfo_GetItem(SLIM_TKID_MIME_image_vnd_wap_wbmp))
#define SLIM_TKOFF_MIME_text_vnd_wap_wmlscript	(SLIM_TKOFF_BASE_MIME0 + 557)
#define SLIM_TKNAM_MIME_text_vnd_wap_wmlscript	(SLIM_TKNAM_BASE_MIME0 + 557)
#define SLIM_TKLEN_MIME_text_vnd_wap_wmlscript	(22)
#define SLIM_TOKEN_MIME_text_vnd_wap_wmlscript	(MIMEInfo_GetItem(SLIM_TKID_MIME_text_vnd_wap_wmlscript))
#define SLIM_TKOFF_MIME_application_vnd_wap_xhtml_xml	(SLIM_TKOFF_BASE_MIME0 + 580)
#define SLIM_TKNAM_MIME_application_vnd_wap_xhtml_xml	(SLIM_TKNAM_BASE_MIME0 + 580)
#define SLIM_TKLEN_MIME_application_vnd_wap_xhtml_xml	(29)
#define SLIM_TOKEN_MIME_application_vnd_wap_xhtml_xml	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_vnd_wap_xhtml_xml))
#define SLIM_TKOFF_MIME_application_vnd_wap_wbxml	(SLIM_TKOFF_BASE_MIME0 + 610)
#define SLIM_TKNAM_MIME_application_vnd_wap_wbxml	(SLIM_TKNAM_BASE_MIME0 + 610)
#define SLIM_TKLEN_MIME_application_vnd_wap_wbxml	(25)
#define SLIM_TOKEN_MIME_application_vnd_wap_wbxml	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_vnd_wap_wbxml))
#define SLIM_TKOFF_MIME_application_vnd_wap_wmlc	(SLIM_TKOFF_BASE_MIME0 + 636)
#define SLIM_TKNAM_MIME_application_vnd_wap_wmlc	(SLIM_TKNAM_BASE_MIME0 + 636)
#define SLIM_TKLEN_MIME_application_vnd_wap_wmlc	(24)
#define SLIM_TOKEN_MIME_application_vnd_wap_wmlc	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_vnd_wap_wmlc))
#define SLIM_TKOFF_MIME_application_vnd_wap_wmlsc	(SLIM_TKOFF_BASE_MIME0 + 661)
#define SLIM_TKNAM_MIME_application_vnd_wap_wmlsc	(SLIM_TKNAM_BASE_MIME0 + 661)
#define SLIM_TKLEN_MIME_application_vnd_wap_wmlsc	(25)
#define SLIM_TOKEN_MIME_application_vnd_wap_wmlsc	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_vnd_wap_wmlsc))
#define SLIM_TKOFF_MIME_application_vnd_wap_wmlscriptc	(SLIM_TKOFF_BASE_MIME0 + 687)
#define SLIM_TKNAM_MIME_application_vnd_wap_wmlscriptc	(SLIM_TKNAM_BASE_MIME0 + 687)
#define SLIM_TKLEN_MIME_application_vnd_wap_wmlscriptc	(30)
#define SLIM_TOKEN_MIME_application_vnd_wap_wmlscriptc	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_vnd_wap_wmlscriptc))
#define SLIM_TKOFF_MIME_image_svg_xml	(SLIM_TKOFF_BASE_MIME0 + 718)
#define SLIM_TKNAM_MIME_image_svg_xml	(SLIM_TKNAM_BASE_MIME0 + 718)
#define SLIM_TKLEN_MIME_image_svg_xml	(13)
#define SLIM_TOKEN_MIME_image_svg_xml	(MIMEInfo_GetItem(SLIM_TKID_MIME_image_svg_xml))
#define SLIM_TKOFF_MIME_application_pdf	(SLIM_TKOFF_BASE_MIME0 + 732)
#define SLIM_TKNAM_MIME_application_pdf	(SLIM_TKNAM_BASE_MIME0 + 732)
#define SLIM_TKLEN_MIME_application_pdf	(15)
#define SLIM_TOKEN_MIME_application_pdf	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_pdf))
#define SLIM_TKOFF_MIME_application_x_shockwave_flash	(SLIM_TKOFF_BASE_MIME0 + 748)
#define SLIM_TKNAM_MIME_application_x_shockwave_flash	(SLIM_TKNAM_BASE_MIME0 + 748)
#define SLIM_TKLEN_MIME_application_x_shockwave_flash	(29)
#define SLIM_TOKEN_MIME_application_x_shockwave_flash	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_shockwave_flash))
#define SLIM_TKOFF_MIME_application_futuresplash	(SLIM_TKOFF_BASE_MIME0 + 778)
#define SLIM_TKNAM_MIME_application_futuresplash	(SLIM_TKNAM_BASE_MIME0 + 778)
#define SLIM_TKLEN_MIME_application_futuresplash	(24)
#define SLIM_TOKEN_MIME_application_futuresplash	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_futuresplash))
#define SLIM_TKOFF_MIME_application_x_director	(SLIM_TKOFF_BASE_MIME0 + 803)
#define SLIM_TKNAM_MIME_application_x_director	(SLIM_TKNAM_BASE_MIME0 + 803)
#define SLIM_TKLEN_MIME_application_x_director	(22)
#define SLIM_TOKEN_MIME_application_x_director	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_director))
#define SLIM_TKOFF_MIME_audio_x_pn_realaudio	(SLIM_TKOFF_BASE_MIME0 + 826)
#define SLIM_TKNAM_MIME_audio_x_pn_realaudio	(SLIM_TKNAM_BASE_MIME0 + 826)
#define SLIM_TKLEN_MIME_audio_x_pn_realaudio	(20)
#define SLIM_TOKEN_MIME_audio_x_pn_realaudio	(MIMEInfo_GetItem(SLIM_TKID_MIME_audio_x_pn_realaudio))
#define SLIM_TKOFF_MIME_application_x_java	(SLIM_TKOFF_BASE_MIME0 + 847)
#define SLIM_TKNAM_MIME_application_x_java	(SLIM_TKNAM_BASE_MIME0 + 847)
#define SLIM_TKLEN_MIME_application_x_java	(18)
#define SLIM_TOKEN_MIME_application_x_java	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_java))
#define SLIM_TKOFF_MIME_audio_midi	(SLIM_TKOFF_BASE_MIME0 + 866)
#define SLIM_TKNAM_MIME_audio_midi	(SLIM_TKNAM_BASE_MIME0 + 866)
#define SLIM_TKLEN_MIME_audio_midi	(10)
#define SLIM_TOKEN_MIME_audio_midi	(MIMEInfo_GetItem(SLIM_TKID_MIME_audio_midi))
#define SLIM_TKOFF_MIME_audio_x_wav	(SLIM_TKOFF_BASE_MIME0 + 877)
#define SLIM_TKNAM_MIME_audio_x_wav	(SLIM_TKNAM_BASE_MIME0 + 877)
#define SLIM_TKLEN_MIME_audio_x_wav	(11)
#define SLIM_TOKEN_MIME_audio_x_wav	(MIMEInfo_GetItem(SLIM_TKID_MIME_audio_x_wav))
#define SLIM_TKOFF_MIME_audio_x_aiff	(SLIM_TKOFF_BASE_MIME0 + 889)
#define SLIM_TKNAM_MIME_audio_x_aiff	(SLIM_TKNAM_BASE_MIME0 + 889)
#define SLIM_TKLEN_MIME_audio_x_aiff	(12)
#define SLIM_TOKEN_MIME_audio_x_aiff	(MIMEInfo_GetItem(SLIM_TKID_MIME_audio_x_aiff))
#define SLIM_TKOFF_MIME_audio_basic	(SLIM_TKOFF_BASE_MIME0 + 902)
#define SLIM_TKNAM_MIME_audio_basic	(SLIM_TKNAM_BASE_MIME0 + 902)
#define SLIM_TKLEN_MIME_audio_basic	(11)
#define SLIM_TOKEN_MIME_audio_basic	(MIMEInfo_GetItem(SLIM_TKID_MIME_audio_basic))
#define SLIM_TKOFF_MIME_video_mpeg	(SLIM_TKOFF_BASE_MIME0 + 914)
#define SLIM_TKNAM_MIME_video_mpeg	(SLIM_TKNAM_BASE_MIME0 + 914)
#define SLIM_TKLEN_MIME_video_mpeg	(10)
#define SLIM_TOKEN_MIME_video_mpeg	(MIMEInfo_GetItem(SLIM_TKID_MIME_video_mpeg))
#define SLIM_TKOFF_MIME_audio_mpeg	(SLIM_TKOFF_BASE_MIME0 + 925)
#define SLIM_TKNAM_MIME_audio_mpeg	(SLIM_TKNAM_BASE_MIME0 + 925)
#define SLIM_TKLEN_MIME_audio_mpeg	(10)
#define SLIM_TOKEN_MIME_audio_mpeg	(MIMEInfo_GetItem(SLIM_TKID_MIME_audio_mpeg))
#define SLIM_TKOFF_MIME_application_vnd_oma_drm_message	(SLIM_TKOFF_BASE_MIME0 + 936)
#define SLIM_TKNAM_MIME_application_vnd_oma_drm_message	(SLIM_TKNAM_BASE_MIME0 + 936)
#define SLIM_TKLEN_MIME_application_vnd_oma_drm_message	(31)
#define SLIM_TOKEN_MIME_application_vnd_oma_drm_message	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_vnd_oma_drm_message))
#define SLIM_TKOFF_MIME_application_vnd_oma_drm_rights_xml	(SLIM_TKOFF_BASE_MIME0 + 968)
#define SLIM_TKNAM_MIME_application_vnd_oma_drm_rights_xml	(SLIM_TKNAM_BASE_MIME0 + 968)
#define SLIM_TKLEN_MIME_application_vnd_oma_drm_rights_xml	(34)
#define SLIM_TOKEN_MIME_application_vnd_oma_drm_rights_xml	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_vnd_oma_drm_rights_xml))
#define SLIM_TKOFF_MIME_application_vnd_oma_drm_rights_wbxml	(SLIM_TKOFF_BASE_MIME0 + 1003)
#define SLIM_TKNAM_MIME_application_vnd_oma_drm_rights_wbxml	(SLIM_TKNAM_BASE_MIME0 + 1003)
#define SLIM_TKLEN_MIME_application_vnd_oma_drm_rights_wbxml	(36)
#define SLIM_TOKEN_MIME_application_vnd_oma_drm_rights_wbxml	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_vnd_oma_drm_rights_wbxml))
#define SLIM_TKOFF_MIME_application_vnd_oma_drm_content	(SLIM_TKOFF_BASE_MIME0 + 1040)
#define SLIM_TKNAM_MIME_application_vnd_oma_drm_content	(SLIM_TKNAM_BASE_MIME0 + 1040)
#define SLIM_TKLEN_MIME_application_vnd_oma_drm_content	(31)
#define SLIM_TOKEN_MIME_application_vnd_oma_drm_content	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_vnd_oma_drm_content))
#define SLIM_TKOFF_MIME_application_x_www_form_urlencoded	(SLIM_TKOFF_BASE_MIME0 + 1072)
#define SLIM_TKNAM_MIME_application_x_www_form_urlencoded	(SLIM_TKNAM_BASE_MIME0 + 1072)
#define SLIM_TKLEN_MIME_application_x_www_form_urlencoded	(33)
#define SLIM_TOKEN_MIME_application_x_www_form_urlencoded	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_www_form_urlencoded))
#define SLIM_TKOFF_MIME_multipart_form_data	(SLIM_TKOFF_BASE_MIME0 + 1106)
#define SLIM_TKNAM_MIME_multipart_form_data	(SLIM_TKNAM_BASE_MIME0 + 1106)
#define SLIM_TKLEN_MIME_multipart_form_data	(19)
#define SLIM_TOKEN_MIME_multipart_form_data	(MIMEInfo_GetItem(SLIM_TKID_MIME_multipart_form_data))
#define SLIM_TKOFF_MIME_application_octet_stream	(SLIM_TKOFF_BASE_MIME0 + 1126)
#define SLIM_TKNAM_MIME_application_octet_stream	(SLIM_TKNAM_BASE_MIME0 + 1126)
#define SLIM_TKLEN_MIME_application_octet_stream	(24)
#define SLIM_TOKEN_MIME_application_octet_stream	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_octet_stream))
#define SLIM_TKOFF_MIME_application_x_gzip	(SLIM_TKOFF_BASE_MIME0 + 1151)
#define SLIM_TKNAM_MIME_application_x_gzip	(SLIM_TKNAM_BASE_MIME0 + 1151)
#define SLIM_TKLEN_MIME_application_x_gzip	(18)
#define SLIM_TOKEN_MIME_application_x_gzip	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_gzip))
#define SLIM_TKOFF_MIME_application_x_tar	(SLIM_TKOFF_BASE_MIME0 + 1170)
#define SLIM_TKNAM_MIME_application_x_tar	(SLIM_TKNAM_BASE_MIME0 + 1170)
#define SLIM_TKLEN_MIME_application_x_tar	(17)
#define SLIM_TOKEN_MIME_application_x_tar	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_tar))
#define SLIM_TKOFF_MIME_application_zip	(SLIM_TKOFF_BASE_MIME0 + 1188)
#define SLIM_TKNAM_MIME_application_zip	(SLIM_TKNAM_BASE_MIME0 + 1188)
#define SLIM_TKLEN_MIME_application_zip	(15)
#define SLIM_TOKEN_MIME_application_zip	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_zip))
#define SLIM_TKOFF_MIME_video_x_msvideo	(SLIM_TKOFF_BASE_MIME0 + 1204)
#define SLIM_TKNAM_MIME_video_x_msvideo	(SLIM_TKNAM_BASE_MIME0 + 1204)
#define SLIM_TKLEN_MIME_video_x_msvideo	(15)
#define SLIM_TOKEN_MIME_video_x_msvideo	(MIMEInfo_GetItem(SLIM_TKID_MIME_video_x_msvideo))
#define SLIM_TKOFF_MIME_video_quicktime	(SLIM_TKOFF_BASE_MIME0 + 1220)
#define SLIM_TKNAM_MIME_video_quicktime	(SLIM_TKNAM_BASE_MIME0 + 1220)
#define SLIM_TKLEN_MIME_video_quicktime	(15)
#define SLIM_TOKEN_MIME_video_quicktime	(MIMEInfo_GetItem(SLIM_TKID_MIME_video_quicktime))
#define SLIM_TKOFF_MIME_video_3gpp	(SLIM_TKOFF_BASE_MIME0 + 1236)
#define SLIM_TKNAM_MIME_video_3gpp	(SLIM_TKNAM_BASE_MIME0 + 1236)
#define SLIM_TKLEN_MIME_video_3gpp	(10)
#define SLIM_TOKEN_MIME_video_3gpp	(MIMEInfo_GetItem(SLIM_TKID_MIME_video_3gpp))
#define SLIM_TKOFF_MIME_video_3gpp2	(SLIM_TKOFF_BASE_MIME0 + 1247)
#define SLIM_TKNAM_MIME_video_3gpp2	(SLIM_TKNAM_BASE_MIME0 + 1247)
#define SLIM_TKLEN_MIME_video_3gpp2	(11)
#define SLIM_TOKEN_MIME_video_3gpp2	(MIMEInfo_GetItem(SLIM_TKID_MIME_video_3gpp2))
#define SLIM_TKOFF_MIME_audio_3gpp	(SLIM_TKOFF_BASE_MIME0 + 1259)
#define SLIM_TKNAM_MIME_audio_3gpp	(SLIM_TKNAM_BASE_MIME0 + 1259)
#define SLIM_TKLEN_MIME_audio_3gpp	(10)
#define SLIM_TOKEN_MIME_audio_3gpp	(MIMEInfo_GetItem(SLIM_TKID_MIME_audio_3gpp))
#define SLIM_TKOFF_MIME_audio_3gpp2	(SLIM_TKOFF_BASE_MIME0 + 1270)
#define SLIM_TKNAM_MIME_audio_3gpp2	(SLIM_TKNAM_BASE_MIME0 + 1270)
#define SLIM_TKLEN_MIME_audio_3gpp2	(11)
#define SLIM_TOKEN_MIME_audio_3gpp2	(MIMEInfo_GetItem(SLIM_TKID_MIME_audio_3gpp2))
#define SLIM_TKOFF_MIME_video_x_ms_wmv	(SLIM_TKOFF_BASE_MIME0 + 1282)
#define SLIM_TKNAM_MIME_video_x_ms_wmv	(SLIM_TKNAM_BASE_MIME0 + 1282)
#define SLIM_TKLEN_MIME_video_x_ms_wmv	(14)
#define SLIM_TOKEN_MIME_video_x_ms_wmv	(MIMEInfo_GetItem(SLIM_TKID_MIME_video_x_ms_wmv))
#define SLIM_TKOFF_MIME_video_x_ms_asf	(SLIM_TKOFF_BASE_MIME0 + 1297)
#define SLIM_TKNAM_MIME_video_x_ms_asf	(SLIM_TKNAM_BASE_MIME0 + 1297)
#define SLIM_TKLEN_MIME_video_x_ms_asf	(14)
#define SLIM_TOKEN_MIME_video_x_ms_asf	(MIMEInfo_GetItem(SLIM_TKID_MIME_video_x_ms_asf))
#define SLIM_TKOFF_MIME_video_x_ms_asx	(SLIM_TKOFF_BASE_MIME0 + 1312)
#define SLIM_TKNAM_MIME_video_x_ms_asx	(SLIM_TKNAM_BASE_MIME0 + 1312)
#define SLIM_TKLEN_MIME_video_x_ms_asx	(14)
#define SLIM_TOKEN_MIME_video_x_ms_asx	(MIMEInfo_GetItem(SLIM_TKID_MIME_video_x_ms_asx))
#define SLIM_TKOFF_MIME_video_x_ms_wvx	(SLIM_TKOFF_BASE_MIME0 + 1327)
#define SLIM_TKNAM_MIME_video_x_ms_wvx	(SLIM_TKNAM_BASE_MIME0 + 1327)
#define SLIM_TKLEN_MIME_video_x_ms_wvx	(14)
#define SLIM_TOKEN_MIME_video_x_ms_wvx	(MIMEInfo_GetItem(SLIM_TKID_MIME_video_x_ms_wvx))
#define SLIM_TKOFF_MIME_video_x_ms_wm	(SLIM_TKOFF_BASE_MIME0 + 1342)
#define SLIM_TKNAM_MIME_video_x_ms_wm	(SLIM_TKNAM_BASE_MIME0 + 1342)
#define SLIM_TKLEN_MIME_video_x_ms_wm	(13)
#define SLIM_TOKEN_MIME_video_x_ms_wm	(MIMEInfo_GetItem(SLIM_TKID_MIME_video_x_ms_wm))
#define SLIM_TKOFF_MIME_audio_x_ms_wma	(SLIM_TKOFF_BASE_MIME0 + 1356)
#define SLIM_TKNAM_MIME_audio_x_ms_wma	(SLIM_TKNAM_BASE_MIME0 + 1356)
#define SLIM_TKLEN_MIME_audio_x_ms_wma	(14)
#define SLIM_TOKEN_MIME_audio_x_ms_wma	(MIMEInfo_GetItem(SLIM_TKID_MIME_audio_x_ms_wma))
#define SLIM_TKOFF_MIME_audio_x_ms_wax	(SLIM_TKOFF_BASE_MIME0 + 1371)
#define SLIM_TKNAM_MIME_audio_x_ms_wax	(SLIM_TKNAM_BASE_MIME0 + 1371)
#define SLIM_TKLEN_MIME_audio_x_ms_wax	(14)
#define SLIM_TOKEN_MIME_audio_x_ms_wax	(MIMEInfo_GetItem(SLIM_TKID_MIME_audio_x_ms_wax))
#define SLIM_TKOFF_MIME_audio_x_gsm	(SLIM_TKOFF_BASE_MIME0 + 1386)
#define SLIM_TKNAM_MIME_audio_x_gsm	(SLIM_TKNAM_BASE_MIME0 + 1386)
#define SLIM_TKLEN_MIME_audio_x_gsm	(11)
#define SLIM_TOKEN_MIME_audio_x_gsm	(MIMEInfo_GetItem(SLIM_TKID_MIME_audio_x_gsm))
#define SLIM_TKOFF_MIME_text_xsl	(SLIM_TKOFF_BASE_MIME0 + 1398)
#define SLIM_TKNAM_MIME_text_xsl	(SLIM_TKNAM_BASE_MIME0 + 1398)
#define SLIM_TKLEN_MIME_text_xsl	(8)
#define SLIM_TOKEN_MIME_text_xsl	(MIMEInfo_GetItem(SLIM_TKID_MIME_text_xsl))
#define SLIM_TKOFF_MIME_image_tiff	(SLIM_TKOFF_BASE_MIME0 + 1407)
#define SLIM_TKNAM_MIME_image_tiff	(SLIM_TKNAM_BASE_MIME0 + 1407)
#define SLIM_TKLEN_MIME_image_tiff	(10)
#define SLIM_TOKEN_MIME_image_tiff	(MIMEInfo_GetItem(SLIM_TKID_MIME_image_tiff))
#define SLIM_TKOFF_MIME_image_x_icon	(SLIM_TKOFF_BASE_MIME0 + 1418)
#define SLIM_TKNAM_MIME_image_x_icon	(SLIM_TKNAM_BASE_MIME0 + 1418)
#define SLIM_TKLEN_MIME_image_x_icon	(12)
#define SLIM_TOKEN_MIME_image_x_icon	(MIMEInfo_GetItem(SLIM_TKID_MIME_image_x_icon))
#define SLIM_TKOFF_MIME_image_x_xpixmap	(SLIM_TKOFF_BASE_MIME0 + 1431)
#define SLIM_TKNAM_MIME_image_x_xpixmap	(SLIM_TKNAM_BASE_MIME0 + 1431)
#define SLIM_TKLEN_MIME_image_x_xpixmap	(15)
#define SLIM_TOKEN_MIME_image_x_xpixmap	(MIMEInfo_GetItem(SLIM_TKID_MIME_image_x_xpixmap))
#define SLIM_TKOFF_MIME_image_x_xbitmap	(SLIM_TKOFF_BASE_MIME0 + 1447)
#define SLIM_TKNAM_MIME_image_x_xbitmap	(SLIM_TKNAM_BASE_MIME0 + 1447)
#define SLIM_TKLEN_MIME_image_x_xbitmap	(15)
#define SLIM_TOKEN_MIME_image_x_xbitmap	(MIMEInfo_GetItem(SLIM_TKID_MIME_image_x_xbitmap))
#define SLIM_TKOFF_MIME_model_vrml	(SLIM_TKOFF_BASE_MIME0 + 1463)
#define SLIM_TKNAM_MIME_model_vrml	(SLIM_TKNAM_BASE_MIME0 + 1463)
#define SLIM_TKLEN_MIME_model_vrml	(10)
#define SLIM_TOKEN_MIME_model_vrml	(MIMEInfo_GetItem(SLIM_TKID_MIME_model_vrml))
#define SLIM_TKOFF_MIME_x_world_x_vrml	(SLIM_TKOFF_BASE_MIME0 + 1474)
#define SLIM_TKNAM_MIME_x_world_x_vrml	(SLIM_TKNAM_BASE_MIME0 + 1474)
#define SLIM_TKLEN_MIME_x_world_x_vrml	(14)
#define SLIM_TOKEN_MIME_x_world_x_vrml	(MIMEInfo_GetItem(SLIM_TKID_MIME_x_world_x_vrml))
#define SLIM_TKOFF_MIME_application_x_binary_javascript	(SLIM_TKOFF_BASE_MIME0 + 1489)
#define SLIM_TKNAM_MIME_application_x_binary_javascript	(SLIM_TKNAM_BASE_MIME0 + 1489)
#define SLIM_TKLEN_MIME_application_x_binary_javascript	(31)
#define SLIM_TOKEN_MIME_application_x_binary_javascript	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_binary_javascript))
#define SLIM_TKOFF_MIME_application_word	(SLIM_TKOFF_BASE_MIME0 + 1521)
#define SLIM_TKNAM_MIME_application_word	(SLIM_TKNAM_BASE_MIME0 + 1521)
#define SLIM_TKLEN_MIME_application_word	(16)
#define SLIM_TOKEN_MIME_application_word	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_word))
#define SLIM_TKOFF_MIME_application_x_word	(SLIM_TKOFF_BASE_MIME0 + 1538)
#define SLIM_TKNAM_MIME_application_x_word	(SLIM_TKNAM_BASE_MIME0 + 1538)
#define SLIM_TKLEN_MIME_application_x_word	(18)
#define SLIM_TOKEN_MIME_application_x_word	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_word))
#define SLIM_TKOFF_MIME_application_msword	(SLIM_TKOFF_BASE_MIME0 + 1557)
#define SLIM_TKNAM_MIME_application_msword	(SLIM_TKNAM_BASE_MIME0 + 1557)
#define SLIM_TKLEN_MIME_application_msword	(18)
#define SLIM_TOKEN_MIME_application_msword	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_msword))
#define SLIM_TKOFF_MIME_application_x_msword	(SLIM_TKOFF_BASE_MIME0 + 1576)
#define SLIM_TKNAM_MIME_application_x_msword	(SLIM_TKNAM_BASE_MIME0 + 1576)
#define SLIM_TKLEN_MIME_application_x_msword	(20)
#define SLIM_TOKEN_MIME_application_x_msword	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_msword))
#define SLIM_TKOFF_MIME_application_vnd_ms_word	(SLIM_TKOFF_BASE_MIME0 + 1597)
#define SLIM_TKNAM_MIME_application_vnd_ms_word	(SLIM_TKNAM_BASE_MIME0 + 1597)
#define SLIM_TKLEN_MIME_application_vnd_ms_word	(23)
#define SLIM_TOKEN_MIME_application_vnd_ms_word	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_vnd_ms_word))
#define SLIM_TKOFF_MIME_application_excel	(SLIM_TKOFF_BASE_MIME0 + 1621)
#define SLIM_TKNAM_MIME_application_excel	(SLIM_TKNAM_BASE_MIME0 + 1621)
#define SLIM_TKLEN_MIME_application_excel	(17)
#define SLIM_TOKEN_MIME_application_excel	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_excel))
#define SLIM_TKOFF_MIME_application_x_excel	(SLIM_TKOFF_BASE_MIME0 + 1639)
#define SLIM_TKNAM_MIME_application_x_excel	(SLIM_TKNAM_BASE_MIME0 + 1639)
#define SLIM_TKLEN_MIME_application_x_excel	(19)
#define SLIM_TOKEN_MIME_application_x_excel	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_excel))
#define SLIM_TKOFF_MIME_application_msexcel	(SLIM_TKOFF_BASE_MIME0 + 1659)
#define SLIM_TKNAM_MIME_application_msexcel	(SLIM_TKNAM_BASE_MIME0 + 1659)
#define SLIM_TKLEN_MIME_application_msexcel	(19)
#define SLIM_TOKEN_MIME_application_msexcel	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_msexcel))
#define SLIM_TKOFF_MIME_application_x_msexcel	(SLIM_TKOFF_BASE_MIME0 + 1679)
#define SLIM_TKNAM_MIME_application_x_msexcel	(SLIM_TKNAM_BASE_MIME0 + 1679)
#define SLIM_TKLEN_MIME_application_x_msexcel	(21)
#define SLIM_TOKEN_MIME_application_x_msexcel	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_msexcel))
#define SLIM_TKOFF_MIME_application_vnd_ms_excel	(SLIM_TKOFF_BASE_MIME0 + 1701)
#define SLIM_TKNAM_MIME_application_vnd_ms_excel	(SLIM_TKNAM_BASE_MIME0 + 1701)
#define SLIM_TKLEN_MIME_application_vnd_ms_excel	(24)
#define SLIM_TOKEN_MIME_application_vnd_ms_excel	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_vnd_ms_excel))
#define SLIM_TKOFF_MIME_text_csv	(SLIM_TKOFF_BASE_MIME0 + 1726)
#define SLIM_TKNAM_MIME_text_csv	(SLIM_TKNAM_BASE_MIME0 + 1726)
#define SLIM_TKLEN_MIME_text_csv	(8)
#define SLIM_TOKEN_MIME_text_csv	(MIMEInfo_GetItem(SLIM_TKID_MIME_text_csv))
#define SLIM_TKOFF_MIME_text_comma_separated_values	(SLIM_TKOFF_BASE_MIME0 + 1735)
#define SLIM_TKNAM_MIME_text_comma_separated_values	(SLIM_TKNAM_BASE_MIME0 + 1735)
#define SLIM_TKLEN_MIME_text_comma_separated_values	(27)
#define SLIM_TOKEN_MIME_text_comma_separated_values	(MIMEInfo_GetItem(SLIM_TKID_MIME_text_comma_separated_values))
#define SLIM_TKOFF_MIME_application_powerpoint	(SLIM_TKOFF_BASE_MIME0 + 1763)
#define SLIM_TKNAM_MIME_application_powerpoint	(SLIM_TKNAM_BASE_MIME0 + 1763)
#define SLIM_TKLEN_MIME_application_powerpoint	(22)
#define SLIM_TOKEN_MIME_application_powerpoint	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_powerpoint))
#define SLIM_TKOFF_MIME_application_x_powerpoint	(SLIM_TKOFF_BASE_MIME0 + 1786)
#define SLIM_TKNAM_MIME_application_x_powerpoint	(SLIM_TKNAM_BASE_MIME0 + 1786)
#define SLIM_TKLEN_MIME_application_x_powerpoint	(24)
#define SLIM_TOKEN_MIME_application_x_powerpoint	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_powerpoint))
#define SLIM_TKOFF_MIME_application_mspowerpoint	(SLIM_TKOFF_BASE_MIME0 + 1811)
#define SLIM_TKNAM_MIME_application_mspowerpoint	(SLIM_TKNAM_BASE_MIME0 + 1811)
#define SLIM_TKLEN_MIME_application_mspowerpoint	(24)
#define SLIM_TOKEN_MIME_application_mspowerpoint	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_mspowerpoint))
#define SLIM_TKOFF_MIME_application_x_mspowerpoint	(SLIM_TKOFF_BASE_MIME0 + 1836)
#define SLIM_TKNAM_MIME_application_x_mspowerpoint	(SLIM_TKNAM_BASE_MIME0 + 1836)
#define SLIM_TKLEN_MIME_application_x_mspowerpoint	(26)
#define SLIM_TOKEN_MIME_application_x_mspowerpoint	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_x_mspowerpoint))
#define SLIM_TKOFF_MIME_application_vnd_ms_powerpoint	(SLIM_TKOFF_BASE_MIME0 + 1863)
#define SLIM_TKNAM_MIME_application_vnd_ms_powerpoint	(SLIM_TKNAM_BASE_MIME0 + 1863)
#define SLIM_TKLEN_MIME_application_vnd_ms_powerpoint	(29)
#define SLIM_TOKEN_MIME_application_vnd_ms_powerpoint	(MIMEInfo_GetItem(SLIM_TKID_MIME_application_vnd_ms_powerpoint))
#define SLIM_TKOFF_BASE_MIME1	(SLIM_TKOFF_BASE_MIME0 + 1893)
#define SLIM_TKNAM_BASE_MIME1	(SLIM_TKNAM_BASE_MIME0 + SLIM_TKOFF_BASE_MIME1)
#define SLIM_TKLEN_TOTAL_MIME	SLIM_TKOFF_BASE_MIME1

extern SLIM_ROM slim_char cSlim_TokenName_MIME[SLIM_TKLEN_TOTAL_MIME];

extern SLIM_ROM TMIMEInfo cSlim_Token_MIME[SLIM_TOKEN_MIME_TOKENS];
#define MIMEInfo_GetItem(id)		((TMIMEInfo *)&cSlim_Token_MIME[(id)])
#define MIMEInfo_GetItemName(id)	((slim_char *)cSlim_TokenName_MIME + ((TToken *)&cSlim_Token_MIME[(id)])->fOffset)
#define MIMEInfo_GetItemNameLen(id)	(((TToken *)&cSlim_Token_MIME[(id)])->fLength)

TMIMEInfo *MIMEInfo_FindSS(slim_char *in_s, slim_int in_slen);

SLIM_END_C_LINKAGE
#endif
