/*
	pictp.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/private/token/pictp.h 16    05/12/28 12:08 Someya $ */

/* DO NOT EDIT! This file is generated automatically. */

#ifndef SLIM_TOKEN_PICTP_H
#define SLIM_TOKEN_PICTP_H

#include <slim/basis/base.h>
#include <slim/basis/token.h>
#include <slim/private/token/pictpid.h>

SLIM_BEGIN_C_LINKAGE

typedef struct TPictpInfo_ TPictpInfo;
struct TPictpInfo_ {
	TToken fBase;	/* must be the first field */
	slim_int fMIMEType;
	slim_int fOffset;
	slim_int fSize;
};

extern SLIM_ROM slim_byte cSlim_PictpDataTable[];

#define SLIM_TKOFF_BASE_PICTP0	(0)
#define SLIM_TKNAM_BASE_PICTP0	((slim_char *)cSlim_TokenName_PICTP)
#define SLIM_TKOFF_PICTP_core_action_back	(SLIM_TKOFF_BASE_PICTP0 + 0)
#define SLIM_TKNAM_PICTP_core_action_back	(SLIM_TKNAM_BASE_PICTP0 + 0)
#define SLIM_TKLEN_PICTP_core_action_back	(16)
#define SLIM_TOKEN_PICTP_core_action_back	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_action_back))
#define SLIM_TKOFF_PICTP_core_action_clear	(SLIM_TKOFF_BASE_PICTP0 + 17)
#define SLIM_TKNAM_PICTP_core_action_clear	(SLIM_TKNAM_BASE_PICTP0 + 17)
#define SLIM_TKLEN_PICTP_core_action_clear	(17)
#define SLIM_TOKEN_PICTP_core_action_clear	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_action_clear))
#define SLIM_TKOFF_PICTP_core_action_find	(SLIM_TKOFF_BASE_PICTP0 + 35)
#define SLIM_TKNAM_PICTP_core_action_find	(SLIM_TKNAM_BASE_PICTP0 + 35)
#define SLIM_TKLEN_PICTP_core_action_find	(16)
#define SLIM_TOKEN_PICTP_core_action_find	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_action_find))
#define SLIM_TKOFF_PICTP_core_action_makePhoneCall	(SLIM_TKOFF_BASE_PICTP0 + 52)
#define SLIM_TKNAM_PICTP_core_action_makePhoneCall	(SLIM_TKNAM_BASE_PICTP0 + 52)
#define SLIM_TKLEN_PICTP_core_action_makePhoneCall	(25)
#define SLIM_TOKEN_PICTP_core_action_makePhoneCall	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_action_makePhoneCall))
#define SLIM_TKOFF_PICTP_core_action_next	(SLIM_TKOFF_BASE_PICTP0 + 78)
#define SLIM_TKNAM_PICTP_core_action_next	(SLIM_TKNAM_BASE_PICTP0 + 78)
#define SLIM_TKLEN_PICTP_core_action_next	(16)
#define SLIM_TOKEN_PICTP_core_action_next	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_action_next))
#define SLIM_TKOFF_PICTP_core_action_nextItem	(SLIM_TKOFF_BASE_PICTP0 + 95)
#define SLIM_TKNAM_PICTP_core_action_nextItem	(SLIM_TKNAM_BASE_PICTP0 + 95)
#define SLIM_TKLEN_PICTP_core_action_nextItem	(20)
#define SLIM_TOKEN_PICTP_core_action_nextItem	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_action_nextItem))
#define SLIM_TKOFF_PICTP_core_action_password	(SLIM_TKOFF_BASE_PICTP0 + 116)
#define SLIM_TKNAM_PICTP_core_action_password	(SLIM_TKNAM_BASE_PICTP0 + 116)
#define SLIM_TKLEN_PICTP_core_action_password	(20)
#define SLIM_TOKEN_PICTP_core_action_password	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_action_password))
#define SLIM_TKOFF_PICTP_core_action_stop	(SLIM_TKOFF_BASE_PICTP0 + 137)
#define SLIM_TKNAM_PICTP_core_action_stop	(SLIM_TKNAM_BASE_PICTP0 + 137)
#define SLIM_TKLEN_PICTP_core_action_stop	(16)
#define SLIM_TOKEN_PICTP_core_action_stop	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_action_stop))
#define SLIM_TKOFF_PICTP_core_action_top	(SLIM_TKOFF_BASE_PICTP0 + 154)
#define SLIM_TKNAM_PICTP_core_action_top	(SLIM_TKNAM_BASE_PICTP0 + 154)
#define SLIM_TKLEN_PICTP_core_action_top	(15)
#define SLIM_TOKEN_PICTP_core_action_top	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_action_top))
#define SLIM_TKOFF_PICTP_core_action_userAuthentication	(SLIM_TKOFF_BASE_PICTP0 + 170)
#define SLIM_TKNAM_PICTP_core_action_userAuthentication	(SLIM_TKNAM_BASE_PICTP0 + 170)
#define SLIM_TKLEN_PICTP_core_action_userAuthentication	(30)
#define SLIM_TOKEN_PICTP_core_action_userAuthentication	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_action_userAuthentication))
#define SLIM_TKOFF_PICTP_core_arrow_down	(SLIM_TKOFF_BASE_PICTP0 + 201)
#define SLIM_TKNAM_PICTP_core_arrow_down	(SLIM_TKNAM_BASE_PICTP0 + 201)
#define SLIM_TKLEN_PICTP_core_arrow_down	(15)
#define SLIM_TOKEN_PICTP_core_arrow_down	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_arrow_down))
#define SLIM_TKOFF_PICTP_core_arrow_fingerDown	(SLIM_TKOFF_BASE_PICTP0 + 217)
#define SLIM_TKNAM_PICTP_core_arrow_fingerDown	(SLIM_TKNAM_BASE_PICTP0 + 217)
#define SLIM_TKLEN_PICTP_core_arrow_fingerDown	(21)
#define SLIM_TOKEN_PICTP_core_arrow_fingerDown	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_arrow_fingerDown))
#define SLIM_TKOFF_PICTP_core_arrow_fingerLeft	(SLIM_TKOFF_BASE_PICTP0 + 239)
#define SLIM_TKNAM_PICTP_core_arrow_fingerLeft	(SLIM_TKNAM_BASE_PICTP0 + 239)
#define SLIM_TKLEN_PICTP_core_arrow_fingerLeft	(21)
#define SLIM_TOKEN_PICTP_core_arrow_fingerLeft	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_arrow_fingerLeft))
#define SLIM_TKOFF_PICTP_core_arrow_fingerRight	(SLIM_TKOFF_BASE_PICTP0 + 261)
#define SLIM_TKNAM_PICTP_core_arrow_fingerRight	(SLIM_TKNAM_BASE_PICTP0 + 261)
#define SLIM_TKLEN_PICTP_core_arrow_fingerRight	(22)
#define SLIM_TOKEN_PICTP_core_arrow_fingerRight	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_arrow_fingerRight))
#define SLIM_TKOFF_PICTP_core_arrow_fingerUp	(SLIM_TKOFF_BASE_PICTP0 + 284)
#define SLIM_TKNAM_PICTP_core_arrow_fingerUp	(SLIM_TKNAM_BASE_PICTP0 + 284)
#define SLIM_TKLEN_PICTP_core_arrow_fingerUp	(19)
#define SLIM_TOKEN_PICTP_core_arrow_fingerUp	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_arrow_fingerUp))
#define SLIM_TKOFF_PICTP_core_arrow_left	(SLIM_TKOFF_BASE_PICTP0 + 304)
#define SLIM_TKNAM_PICTP_core_arrow_left	(SLIM_TKNAM_BASE_PICTP0 + 304)
#define SLIM_TKLEN_PICTP_core_arrow_left	(15)
#define SLIM_TOKEN_PICTP_core_arrow_left	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_arrow_left))
#define SLIM_TKOFF_PICTP_core_arrow_lowerLeft	(SLIM_TKOFF_BASE_PICTP0 + 320)
#define SLIM_TKNAM_PICTP_core_arrow_lowerLeft	(SLIM_TKNAM_BASE_PICTP0 + 320)
#define SLIM_TKLEN_PICTP_core_arrow_lowerLeft	(20)
#define SLIM_TOKEN_PICTP_core_arrow_lowerLeft	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_arrow_lowerLeft))
#define SLIM_TKOFF_PICTP_core_arrow_lowerRight	(SLIM_TKOFF_BASE_PICTP0 + 341)
#define SLIM_TKNAM_PICTP_core_arrow_lowerRight	(SLIM_TKNAM_BASE_PICTP0 + 341)
#define SLIM_TKLEN_PICTP_core_arrow_lowerRight	(21)
#define SLIM_TOKEN_PICTP_core_arrow_lowerRight	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_arrow_lowerRight))
#define SLIM_TKOFF_PICTP_core_arrow_right	(SLIM_TKOFF_BASE_PICTP0 + 363)
#define SLIM_TKNAM_PICTP_core_arrow_right	(SLIM_TKNAM_BASE_PICTP0 + 363)
#define SLIM_TKLEN_PICTP_core_arrow_right	(16)
#define SLIM_TOKEN_PICTP_core_arrow_right	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_arrow_right))
#define SLIM_TKOFF_PICTP_core_arrow_up	(SLIM_TKOFF_BASE_PICTP0 + 380)
#define SLIM_TKNAM_PICTP_core_arrow_up	(SLIM_TKNAM_BASE_PICTP0 + 380)
#define SLIM_TKLEN_PICTP_core_arrow_up	(13)
#define SLIM_TOKEN_PICTP_core_arrow_up	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_arrow_up))
#define SLIM_TKOFF_PICTP_core_arrow_upperLeft	(SLIM_TKOFF_BASE_PICTP0 + 394)
#define SLIM_TKNAM_PICTP_core_arrow_upperLeft	(SLIM_TKNAM_BASE_PICTP0 + 394)
#define SLIM_TKLEN_PICTP_core_arrow_upperLeft	(20)
#define SLIM_TOKEN_PICTP_core_arrow_upperLeft	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_arrow_upperLeft))
#define SLIM_TKOFF_PICTP_core_arrow_upperRight	(SLIM_TKOFF_BASE_PICTP0 + 415)
#define SLIM_TKNAM_PICTP_core_arrow_upperRight	(SLIM_TKNAM_BASE_PICTP0 + 415)
#define SLIM_TKLEN_PICTP_core_arrow_upperRight	(21)
#define SLIM_TOKEN_PICTP_core_arrow_upperRight	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_arrow_upperRight))
#define SLIM_TKOFF_PICTP_core_button_0	(SLIM_TKOFF_BASE_PICTP0 + 437)
#define SLIM_TKNAM_PICTP_core_button_0	(SLIM_TKNAM_BASE_PICTP0 + 437)
#define SLIM_TKLEN_PICTP_core_button_0	(13)
#define SLIM_TOKEN_PICTP_core_button_0	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_button_0))
#define SLIM_TKOFF_PICTP_core_button_1	(SLIM_TKOFF_BASE_PICTP0 + 451)
#define SLIM_TKNAM_PICTP_core_button_1	(SLIM_TKNAM_BASE_PICTP0 + 451)
#define SLIM_TKLEN_PICTP_core_button_1	(13)
#define SLIM_TOKEN_PICTP_core_button_1	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_button_1))
#define SLIM_TKOFF_PICTP_core_button_2	(SLIM_TKOFF_BASE_PICTP0 + 465)
#define SLIM_TKNAM_PICTP_core_button_2	(SLIM_TKNAM_BASE_PICTP0 + 465)
#define SLIM_TKLEN_PICTP_core_button_2	(13)
#define SLIM_TOKEN_PICTP_core_button_2	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_button_2))
#define SLIM_TKOFF_PICTP_core_button_3	(SLIM_TKOFF_BASE_PICTP0 + 479)
#define SLIM_TKNAM_PICTP_core_button_3	(SLIM_TKNAM_BASE_PICTP0 + 479)
#define SLIM_TKLEN_PICTP_core_button_3	(13)
#define SLIM_TOKEN_PICTP_core_button_3	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_button_3))
#define SLIM_TKOFF_PICTP_core_button_4	(SLIM_TKOFF_BASE_PICTP0 + 493)
#define SLIM_TKNAM_PICTP_core_button_4	(SLIM_TKNAM_BASE_PICTP0 + 493)
#define SLIM_TKLEN_PICTP_core_button_4	(13)
#define SLIM_TOKEN_PICTP_core_button_4	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_button_4))
#define SLIM_TKOFF_PICTP_core_button_5	(SLIM_TKOFF_BASE_PICTP0 + 507)
#define SLIM_TKNAM_PICTP_core_button_5	(SLIM_TKNAM_BASE_PICTP0 + 507)
#define SLIM_TKLEN_PICTP_core_button_5	(13)
#define SLIM_TOKEN_PICTP_core_button_5	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_button_5))
#define SLIM_TKOFF_PICTP_core_button_6	(SLIM_TKOFF_BASE_PICTP0 + 521)
#define SLIM_TKNAM_PICTP_core_button_6	(SLIM_TKNAM_BASE_PICTP0 + 521)
#define SLIM_TKLEN_PICTP_core_button_6	(13)
#define SLIM_TOKEN_PICTP_core_button_6	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_button_6))
#define SLIM_TKOFF_PICTP_core_button_7	(SLIM_TKOFF_BASE_PICTP0 + 535)
#define SLIM_TKNAM_PICTP_core_button_7	(SLIM_TKNAM_BASE_PICTP0 + 535)
#define SLIM_TKLEN_PICTP_core_button_7	(13)
#define SLIM_TOKEN_PICTP_core_button_7	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_button_7))
#define SLIM_TKOFF_PICTP_core_button_8	(SLIM_TKOFF_BASE_PICTP0 + 549)
#define SLIM_TKNAM_PICTP_core_button_8	(SLIM_TKNAM_BASE_PICTP0 + 549)
#define SLIM_TKLEN_PICTP_core_button_8	(13)
#define SLIM_TOKEN_PICTP_core_button_8	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_button_8))
#define SLIM_TKOFF_PICTP_core_button_9	(SLIM_TKOFF_BASE_PICTP0 + 563)
#define SLIM_TKNAM_PICTP_core_button_9	(SLIM_TKNAM_BASE_PICTP0 + 563)
#define SLIM_TKLEN_PICTP_core_button_9	(13)
#define SLIM_TOKEN_PICTP_core_button_9	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_button_9))
#define SLIM_TKOFF_PICTP_core_info_charged	(SLIM_TKOFF_BASE_PICTP0 + 577)
#define SLIM_TKNAM_PICTP_core_info_charged	(SLIM_TKNAM_BASE_PICTP0 + 577)
#define SLIM_TKLEN_PICTP_core_info_charged	(17)
#define SLIM_TOKEN_PICTP_core_info_charged	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_info_charged))
#define SLIM_TKOFF_PICTP_core_info_freeofcharge	(SLIM_TKOFF_BASE_PICTP0 + 595)
#define SLIM_TKNAM_PICTP_core_info_freeofcharge	(SLIM_TKNAM_BASE_PICTP0 + 595)
#define SLIM_TKLEN_PICTP_core_info_freeofcharge	(22)
#define SLIM_TOKEN_PICTP_core_info_freeofcharge	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_info_freeofcharge))
#define SLIM_TKOFF_PICTP_core_info_new	(SLIM_TKOFF_BASE_PICTP0 + 618)
#define SLIM_TKNAM_PICTP_core_info_new	(SLIM_TKNAM_BASE_PICTP0 + 618)
#define SLIM_TKLEN_PICTP_core_info_new	(13)
#define SLIM_TOKEN_PICTP_core_info_new	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_info_new))
#define SLIM_TKOFF_PICTP_core_info_notice	(SLIM_TKOFF_BASE_PICTP0 + 632)
#define SLIM_TKNAM_PICTP_core_info_notice	(SLIM_TKNAM_BASE_PICTP0 + 632)
#define SLIM_TKLEN_PICTP_core_info_notice	(16)
#define SLIM_TOKEN_PICTP_core_info_notice	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_info_notice))
#define SLIM_TKOFF_PICTP_core_info_position	(SLIM_TKOFF_BASE_PICTP0 + 649)
#define SLIM_TKNAM_PICTP_core_info_position	(SLIM_TKNAM_BASE_PICTP0 + 649)
#define SLIM_TKLEN_PICTP_core_info_position	(18)
#define SLIM_TOKEN_PICTP_core_info_position	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_info_position))
#define SLIM_TKOFF_PICTP_core_info_reserved	(SLIM_TKOFF_BASE_PICTP0 + 668)
#define SLIM_TKNAM_PICTP_core_info_reserved	(SLIM_TKNAM_BASE_PICTP0 + 668)
#define SLIM_TKLEN_PICTP_core_info_reserved	(18)
#define SLIM_TOKEN_PICTP_core_info_reserved	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_info_reserved))
#define SLIM_TKOFF_PICTP_core_info_sharpdial	(SLIM_TKOFF_BASE_PICTP0 + 687)
#define SLIM_TKNAM_PICTP_core_info_sharpdial	(SLIM_TKNAM_BASE_PICTP0 + 687)
#define SLIM_TKLEN_PICTP_core_info_sharpdial	(19)
#define SLIM_TOKEN_PICTP_core_info_sharpdial	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_info_sharpdial))
#define SLIM_TKOFF_PICTP_core_info_speechinfo	(SLIM_TKOFF_BASE_PICTP0 + 707)
#define SLIM_TKNAM_PICTP_core_info_speechinfo	(SLIM_TKNAM_BASE_PICTP0 + 707)
#define SLIM_TKLEN_PICTP_core_info_speechinfo	(20)
#define SLIM_TOKEN_PICTP_core_info_speechinfo	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_info_speechinfo))
#define SLIM_TKOFF_PICTP_core_info_tollfree	(SLIM_TKOFF_BASE_PICTP0 + 728)
#define SLIM_TKNAM_PICTP_core_info_tollfree	(SLIM_TKNAM_BASE_PICTP0 + 728)
#define SLIM_TKLEN_PICTP_core_info_tollfree	(18)
#define SLIM_TOKEN_PICTP_core_info_tollfree	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_info_tollfree))
#define SLIM_TKOFF_PICTP_core_media_book	(SLIM_TKOFF_BASE_PICTP0 + 747)
#define SLIM_TKNAM_PICTP_core_media_book	(SLIM_TKNAM_BASE_PICTP0 + 747)
#define SLIM_TKLEN_PICTP_core_media_book	(15)
#define SLIM_TOKEN_PICTP_core_media_book	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_media_book))
#define SLIM_TKOFF_PICTP_core_media_cd	(SLIM_TKOFF_BASE_PICTP0 + 763)
#define SLIM_TKNAM_PICTP_core_media_cd	(SLIM_TKNAM_BASE_PICTP0 + 763)
#define SLIM_TKLEN_PICTP_core_media_cd	(13)
#define SLIM_TOKEN_PICTP_core_media_cd	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_media_cd))
#define SLIM_TKOFF_PICTP_core_media_dvd	(SLIM_TKOFF_BASE_PICTP0 + 777)
#define SLIM_TKNAM_PICTP_core_media_dvd	(SLIM_TKNAM_BASE_PICTP0 + 777)
#define SLIM_TKLEN_PICTP_core_media_dvd	(14)
#define SLIM_TOKEN_PICTP_core_media_dvd	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_media_dvd))
#define SLIM_TKOFF_PICTP_core_media_game	(SLIM_TKOFF_BASE_PICTP0 + 792)
#define SLIM_TKNAM_PICTP_core_media_game	(SLIM_TKNAM_BASE_PICTP0 + 792)
#define SLIM_TKLEN_PICTP_core_media_game	(15)
#define SLIM_TOKEN_PICTP_core_media_game	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_media_game))
#define SLIM_TKOFF_PICTP_core_media_radio	(SLIM_TKOFF_BASE_PICTP0 + 808)
#define SLIM_TKNAM_PICTP_core_media_radio	(SLIM_TKNAM_BASE_PICTP0 + 808)
#define SLIM_TKLEN_PICTP_core_media_radio	(16)
#define SLIM_TOKEN_PICTP_core_media_radio	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_media_radio))
#define SLIM_TKOFF_PICTP_core_media_tv	(SLIM_TKOFF_BASE_PICTP0 + 825)
#define SLIM_TKNAM_PICTP_core_media_tv	(SLIM_TKNAM_BASE_PICTP0 + 825)
#define SLIM_TKLEN_PICTP_core_media_tv	(13)
#define SLIM_TOKEN_PICTP_core_media_tv	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_media_tv))
#define SLIM_TKOFF_PICTP_core_media_video	(SLIM_TKOFF_BASE_PICTP0 + 839)
#define SLIM_TKNAM_PICTP_core_media_video	(SLIM_TKNAM_BASE_PICTP0 + 839)
#define SLIM_TKLEN_PICTP_core_media_video	(16)
#define SLIM_TOKEN_PICTP_core_media_video	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_media_video))
#define SLIM_TKOFF_PICTP_core_message_attachment	(SLIM_TKOFF_BASE_PICTP0 + 856)
#define SLIM_TKNAM_PICTP_core_message_attachment	(SLIM_TKNAM_BASE_PICTP0 + 856)
#define SLIM_TKLEN_PICTP_core_message_attachment	(23)
#define SLIM_TOKEN_PICTP_core_message_attachment	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_message_attachment))
#define SLIM_TKOFF_PICTP_core_message_document	(SLIM_TKOFF_BASE_PICTP0 + 880)
#define SLIM_TKNAM_PICTP_core_message_document	(SLIM_TKNAM_BASE_PICTP0 + 880)
#define SLIM_TKLEN_PICTP_core_message_document	(21)
#define SLIM_TOKEN_PICTP_core_message_document	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_message_document))
#define SLIM_TKOFF_PICTP_core_message_folder	(SLIM_TKOFF_BASE_PICTP0 + 902)
#define SLIM_TKNAM_PICTP_core_message_folder	(SLIM_TKNAM_BASE_PICTP0 + 902)
#define SLIM_TKLEN_PICTP_core_message_folder	(19)
#define SLIM_TOKEN_PICTP_core_message_folder	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_message_folder))
#define SLIM_TKOFF_PICTP_core_message_inbox	(SLIM_TKOFF_BASE_PICTP0 + 922)
#define SLIM_TKNAM_PICTP_core_message_inbox	(SLIM_TKNAM_BASE_PICTP0 + 922)
#define SLIM_TKLEN_PICTP_core_message_inbox	(18)
#define SLIM_TOKEN_PICTP_core_message_inbox	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_message_inbox))
#define SLIM_TKOFF_PICTP_core_message_message	(SLIM_TKOFF_BASE_PICTP0 + 941)
#define SLIM_TKNAM_PICTP_core_message_message	(SLIM_TKNAM_BASE_PICTP0 + 941)
#define SLIM_TKLEN_PICTP_core_message_message	(20)
#define SLIM_TOKEN_PICTP_core_message_message	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_message_message))
#define SLIM_TKOFF_PICTP_core_message_outbox	(SLIM_TKOFF_BASE_PICTP0 + 962)
#define SLIM_TKNAM_PICTP_core_message_outbox	(SLIM_TKNAM_BASE_PICTP0 + 962)
#define SLIM_TKLEN_PICTP_core_message_outbox	(19)
#define SLIM_TOKEN_PICTP_core_message_outbox	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_message_outbox))
#define SLIM_TKOFF_PICTP_core_message_receive	(SLIM_TKOFF_BASE_PICTP0 + 982)
#define SLIM_TKNAM_PICTP_core_message_receive	(SLIM_TKNAM_BASE_PICTP0 + 982)
#define SLIM_TKLEN_PICTP_core_message_receive	(20)
#define SLIM_TOKEN_PICTP_core_message_receive	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_message_receive))
#define SLIM_TKOFF_PICTP_core_message_send	(SLIM_TKOFF_BASE_PICTP0 + 1003)
#define SLIM_TKNAM_PICTP_core_message_send	(SLIM_TKNAM_BASE_PICTP0 + 1003)
#define SLIM_TKLEN_PICTP_core_message_send	(17)
#define SLIM_TOKEN_PICTP_core_message_send	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_message_send))
#define SLIM_TKOFF_PICTP_core_state_beginner	(SLIM_TKOFF_BASE_PICTP0 + 1021)
#define SLIM_TKNAM_PICTP_core_state_beginner	(SLIM_TKNAM_BASE_PICTP0 + 1021)
#define SLIM_TKLEN_PICTP_core_state_beginner	(19)
#define SLIM_TOKEN_PICTP_core_state_beginner	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_state_beginner))
#define SLIM_TKOFF_PICTP_core_state_copyright	(SLIM_TKOFF_BASE_PICTP0 + 1041)
#define SLIM_TKNAM_PICTP_core_state_copyright	(SLIM_TKNAM_BASE_PICTP0 + 1041)
#define SLIM_TKLEN_PICTP_core_state_copyright	(20)
#define SLIM_TOKEN_PICTP_core_state_copyright	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_state_copyright))
#define SLIM_TKOFF_PICTP_core_state_insecure	(SLIM_TKOFF_BASE_PICTP0 + 1062)
#define SLIM_TKNAM_PICTP_core_state_insecure	(SLIM_TKNAM_BASE_PICTP0 + 1062)
#define SLIM_TKLEN_PICTP_core_state_insecure	(19)
#define SLIM_TOKEN_PICTP_core_state_insecure	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_state_insecure))
#define SLIM_TKOFF_PICTP_core_state_secure	(SLIM_TKOFF_BASE_PICTP0 + 1082)
#define SLIM_TKNAM_PICTP_core_state_secure	(SLIM_TKNAM_BASE_PICTP0 + 1082)
#define SLIM_TKLEN_PICTP_core_state_secure	(17)
#define SLIM_TOKEN_PICTP_core_state_secure	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_state_secure))
#define SLIM_TKOFF_PICTP_core_state_trademark	(SLIM_TKOFF_BASE_PICTP0 + 1100)
#define SLIM_TKNAM_PICTP_core_state_trademark	(SLIM_TKNAM_BASE_PICTP0 + 1100)
#define SLIM_TKLEN_PICTP_core_state_trademark	(20)
#define SLIM_TOKEN_PICTP_core_state_trademark	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_state_trademark))
#define SLIM_TKOFF_PICTP_core_state_underConstruction	(SLIM_TKOFF_BASE_PICTP0 + 1121)
#define SLIM_TKNAM_PICTP_core_state_underConstruction	(SLIM_TKNAM_BASE_PICTP0 + 1121)
#define SLIM_TKLEN_PICTP_core_state_underConstruction	(28)
#define SLIM_TOKEN_PICTP_core_state_underConstruction	(PictpInfo_GetItem(SLIM_TKID_PICTP_core_state_underConstruction))
#define SLIM_TKOFF_BASE_PICTP1	(SLIM_TKOFF_BASE_PICTP0 + 1150)
#define SLIM_TKNAM_BASE_PICTP1	(SLIM_TKNAM_BASE_PICTP0 + SLIM_TKOFF_BASE_PICTP1)
#define SLIM_TKLEN_TOTAL_PICTP	SLIM_TKOFF_BASE_PICTP1

extern SLIM_ROM slim_char cSlim_TokenName_PICTP[SLIM_TKLEN_TOTAL_PICTP];

extern SLIM_ROM TPictpInfo cSlim_Token_PICTP[SLIM_TOKEN_PICTP_TOKENS];
#define PictpInfo_GetItem(id)		((TPictpInfo *)&cSlim_Token_PICTP[(id)])
#define PictpInfo_GetItemName(id)	((slim_char *)cSlim_TokenName_PICTP + ((TToken *)&cSlim_Token_PICTP[(id)])->fOffset)
#define PictpInfo_GetItemNameLen(id)	(((TToken *)&cSlim_Token_PICTP[(id)])->fLength)

TPictpInfo *PictpInfo_CaseFindSS(slim_char *in_s, slim_int in_slen);

SLIM_END_C_LINKAGE
#endif
