/*
	rmnumid.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/private/token/rmnumid.h 2     05/12/28 12:08 Someya $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_RMNUMID_H
#define SLIM_TOKEN_RMNUMID_H


SLIM_BEGIN_C_LINKAGE

enum {
	SLIM_TKID_RMNUM_i = 0,
	SLIM_TKID_RMNUM_ii,
	SLIM_TKID_RMNUM_iii,
	SLIM_TKID_RMNUM_iv,
	SLIM_TKID_RMNUM_v,
	SLIM_TKID_RMNUM_vi,
	SLIM_TKID_RMNUM_vii,
	SLIM_TKID_RMNUM_viii,
	SLIM_TKID_RMNUM_ix,
	SLIM_TKID_RMNUM_x,
	SLIM_TKID_RMNUM_xx,
	SLIM_TKID_RMNUM_xxx,
	SLIM_TKID_RMNUM_xl,
	SLIM_TKID_RMNUM_l,
	SLIM_TKID_RMNUM_lx,
	SLIM_TKID_RMNUM_lxx,
	SLIM_TKID_RMNUM_lxxx,
	SLIM_TKID_RMNUM_xc,
	SLIM_TKID_RMNUM_c,
	SLIM_TKID_RMNUM_cc,
	SLIM_TKID_RMNUM_ccc,
	SLIM_TKID_RMNUM_cd,
	SLIM_TKID_RMNUM_d,
	SLIM_TKID_RMNUM_dc,
	SLIM_TKID_RMNUM_dcc,
	SLIM_TKID_RMNUM_dccc,
	SLIM_TKID_RMNUM_cm,
	SLIM_TKID_RMNUM_I,
	SLIM_TKID_RMNUM_II,
	SLIM_TKID_RMNUM_III,
	SLIM_TKID_RMNUM_IV,
	SLIM_TKID_RMNUM_V,
	SLIM_TKID_RMNUM_VI,
	SLIM_TKID_RMNUM_VII,
	SLIM_TKID_RMNUM_VIII,
	SLIM_TKID_RMNUM_IX,
	SLIM_TKID_RMNUM_X,
	SLIM_TKID_RMNUM_XX,
	SLIM_TKID_RMNUM_XXX,
	SLIM_TKID_RMNUM_XL,
	SLIM_TKID_RMNUM_L,
	SLIM_TKID_RMNUM_LX,
	SLIM_TKID_RMNUM_LXX,
	SLIM_TKID_RMNUM_LXXX,
	SLIM_TKID_RMNUM_XC,
	SLIM_TKID_RMNUM_C,
	SLIM_TKID_RMNUM_CC,
	SLIM_TKID_RMNUM_CCC,
	SLIM_TKID_RMNUM_CD,
	SLIM_TKID_RMNUM_D,
	SLIM_TKID_RMNUM_DC,
	SLIM_TKID_RMNUM_DCC,
	SLIM_TKID_RMNUM_DCCC,
	SLIM_TKID_RMNUM_CM,
	SLIM_TKID_RMNUM_ENUMS
};

#define SLIM_TOKEN_RMNUM_TOKENS SLIM_TKID_RMNUM_ENUMS
#define SLIM_TOKEN_RMNUM_ENUMS SLIM_TKID_RMNUM_ENUMS


SLIM_END_C_LINKAGE
#endif
