/*
	timefid.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/private/token/timefid.h 2     05/12/28 12:08 Someya $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_TIMEFID_H
#define SLIM_TOKEN_TIMEFID_H


SLIM_BEGIN_C_LINKAGE

enum {
	SLIM_TKID_TIMEF_SUNDAY = 0,
	SLIM_TKID_TIMEF_MONDAY,
	SLIM_TKID_TIMEF_TUESDAY,
	SLIM_TKID_TIMEF_WEDNESDAY,
	SLIM_TKID_TIMEF_THURSDAY,
	SLIM_TKID_TIMEF_FRIDAY,
	SLIM_TKID_TIMEF_SATURDAY,
	SLIM_TKID_TIMEF_DECEMBER,
	SLIM_TKID_TIMEF_NOVEMBER,
	SLIM_TKID_TIMEF_OCTOBER,
	SLIM_TKID_TIMEF_SEPTEMBER,
	SLIM_TKID_TIMEF_AUGUST,
	SLIM_TKID_TIMEF_JULY,
	SLIM_TKID_TIMEF_JUNE,
	SLIM_TKID_TIMEF_MAY,
	SLIM_TKID_TIMEF_APRIL,
	SLIM_TKID_TIMEF_MARCH,
	SLIM_TKID_TIMEF_FEBRUARY,
	SLIM_TKID_TIMEF_JANUARY,
	SLIM_TKID_TIMEF_GMT,
	SLIM_TKID_TIMEF_UT,
	SLIM_TKID_TIMEF_UTC,
	SLIM_TKID_TIMEF_EST,
	SLIM_TKID_TIMEF_EDT,
	SLIM_TKID_TIMEF_CST,
	SLIM_TKID_TIMEF_CDT,
	SLIM_TKID_TIMEF_MST,
	SLIM_TKID_TIMEF_MDT,
	SLIM_TKID_TIMEF_PST,
	SLIM_TKID_TIMEF_PDT,
	SLIM_TKID_TIMEF_JST,
	SLIM_TKID_TIMEF_AM,
	SLIM_TKID_TIMEF_A_M_,
	SLIM_TKID_TIMEF_PM,
	SLIM_TKID_TIMEF_P_M_,
	SLIM_TKID_TIMEF_BC,
	SLIM_TKID_TIMEF_B_C_,
	SLIM_TKID_TIMEF_AD,
	SLIM_TKID_TIMEF_A_D_,
	SLIM_TKID_TIMEF_ENUMS
};

#define SLIM_TOKEN_TIMEF_TOKENS SLIM_TKID_TIMEF_ENUMS
#define SLIM_TOKEN_TIMEF_ENUMS SLIM_TKID_TIMEF_ENUMS


SLIM_END_C_LINKAGE
#endif
