/*
	a1oid.h
	Copyright(c) 1996-2006 ACCESS CO., LTD.
	All rights are reserved by ACCESS CO., LTD., whether the whole or
	part of the source code including any modifications.
*/

/* $Header: /SpinningWheel/slim/slim/private/ssl/a1oid.h 6     06/03/07 18:16 Nagamati $ */

/* DO NOT EDIT! This file is generated automagically. */

#ifndef SLIM_TOKEN_A1OID_H
#define SLIM_TOKEN_A1OID_H

#include <slim/basis/base.h>
#include <slim/basis/token.h>
#include <slim/ssl/a1oidid.h>

SLIM_BEGIN_C_LINKAGE

struct TASN1OIDInfo_ {
	TToken fBase;	/* must be the first field */
	slim_int fSchemaID;
};
typedef struct TASN1OIDInfo_ TASN1OIDInfo;

#define SLIM_TKOFF_BASE_A1OID0	(0)
#define SLIM_TKNAM_BASE_A1OID0	((slim_char *)cSlim_TokenName_A1OID)
#define SLIM_TKOFF_A1OID_id_at_name	(SLIM_TKOFF_BASE_A1OID0 + 0)
#define SLIM_TKNAM_A1OID_id_at_name	(SLIM_TKNAM_BASE_A1OID0 + 0)
#define SLIM_TKLEN_A1OID_id_at_name	(3)
#define SLIM_TOKEN_A1OID_id_at_name	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_at_name))
#define SLIM_TKOFF_A1OID_id_at_surname	(SLIM_TKOFF_BASE_A1OID0 + 3)
#define SLIM_TKNAM_A1OID_id_at_surname	(SLIM_TKNAM_BASE_A1OID0 + 3)
#define SLIM_TKLEN_A1OID_id_at_surname	(3)
#define SLIM_TOKEN_A1OID_id_at_surname	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_at_surname))
#define SLIM_TKOFF_A1OID_id_at_givenName	(SLIM_TKOFF_BASE_A1OID0 + 6)
#define SLIM_TKNAM_A1OID_id_at_givenName	(SLIM_TKNAM_BASE_A1OID0 + 6)
#define SLIM_TKLEN_A1OID_id_at_givenName	(3)
#define SLIM_TOKEN_A1OID_id_at_givenName	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_at_givenName))
#define SLIM_TKOFF_A1OID_id_at_initials	(SLIM_TKOFF_BASE_A1OID0 + 9)
#define SLIM_TKNAM_A1OID_id_at_initials	(SLIM_TKNAM_BASE_A1OID0 + 9)
#define SLIM_TKLEN_A1OID_id_at_initials	(3)
#define SLIM_TOKEN_A1OID_id_at_initials	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_at_initials))
#define SLIM_TKOFF_A1OID_id_at_generationQualifier	(SLIM_TKOFF_BASE_A1OID0 + 12)
#define SLIM_TKNAM_A1OID_id_at_generationQualifier	(SLIM_TKNAM_BASE_A1OID0 + 12)
#define SLIM_TKLEN_A1OID_id_at_generationQualifier	(3)
#define SLIM_TOKEN_A1OID_id_at_generationQualifier	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_at_generationQualifier))
#define SLIM_TKOFF_A1OID_id_at_commonName	(SLIM_TKOFF_BASE_A1OID0 + 15)
#define SLIM_TKNAM_A1OID_id_at_commonName	(SLIM_TKNAM_BASE_A1OID0 + 15)
#define SLIM_TKLEN_A1OID_id_at_commonName	(3)
#define SLIM_TOKEN_A1OID_id_at_commonName	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_at_commonName))
#define SLIM_TKOFF_A1OID_id_at_localityName	(SLIM_TKOFF_BASE_A1OID0 + 18)
#define SLIM_TKNAM_A1OID_id_at_localityName	(SLIM_TKNAM_BASE_A1OID0 + 18)
#define SLIM_TKLEN_A1OID_id_at_localityName	(3)
#define SLIM_TOKEN_A1OID_id_at_localityName	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_at_localityName))
#define SLIM_TKOFF_A1OID_id_at_stateOrProvinceName	(SLIM_TKOFF_BASE_A1OID0 + 21)
#define SLIM_TKNAM_A1OID_id_at_stateOrProvinceName	(SLIM_TKNAM_BASE_A1OID0 + 21)
#define SLIM_TKLEN_A1OID_id_at_stateOrProvinceName	(3)
#define SLIM_TOKEN_A1OID_id_at_stateOrProvinceName	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_at_stateOrProvinceName))
#define SLIM_TKOFF_A1OID_id_at_orgName	(SLIM_TKOFF_BASE_A1OID0 + 24)
#define SLIM_TKNAM_A1OID_id_at_orgName	(SLIM_TKNAM_BASE_A1OID0 + 24)
#define SLIM_TKLEN_A1OID_id_at_orgName	(3)
#define SLIM_TOKEN_A1OID_id_at_orgName	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_at_orgName))
#define SLIM_TKOFF_A1OID_id_at_orgUnitName	(SLIM_TKOFF_BASE_A1OID0 + 27)
#define SLIM_TKNAM_A1OID_id_at_orgUnitName	(SLIM_TKNAM_BASE_A1OID0 + 27)
#define SLIM_TKLEN_A1OID_id_at_orgUnitName	(3)
#define SLIM_TOKEN_A1OID_id_at_orgUnitName	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_at_orgUnitName))
#define SLIM_TKOFF_A1OID_id_at_title	(SLIM_TKOFF_BASE_A1OID0 + 30)
#define SLIM_TKNAM_A1OID_id_at_title	(SLIM_TKNAM_BASE_A1OID0 + 30)
#define SLIM_TKLEN_A1OID_id_at_title	(3)
#define SLIM_TOKEN_A1OID_id_at_title	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_at_title))
#define SLIM_TKOFF_A1OID_id_at_dnQualifier	(SLIM_TKOFF_BASE_A1OID0 + 33)
#define SLIM_TKNAM_A1OID_id_at_dnQualifier	(SLIM_TKNAM_BASE_A1OID0 + 33)
#define SLIM_TKLEN_A1OID_id_at_dnQualifier	(3)
#define SLIM_TOKEN_A1OID_id_at_dnQualifier	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_at_dnQualifier))
#define SLIM_TKOFF_A1OID_id_at_countryName	(SLIM_TKOFF_BASE_A1OID0 + 36)
#define SLIM_TKNAM_A1OID_id_at_countryName	(SLIM_TKNAM_BASE_A1OID0 + 36)
#define SLIM_TKLEN_A1OID_id_at_countryName	(3)
#define SLIM_TOKEN_A1OID_id_at_countryName	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_at_countryName))
#define SLIM_TKOFF_A1OID_id_at_serialNumber	(SLIM_TKOFF_BASE_A1OID0 + 39)
#define SLIM_TKNAM_A1OID_id_at_serialNumber	(SLIM_TKNAM_BASE_A1OID0 + 39)
#define SLIM_TKLEN_A1OID_id_at_serialNumber	(3)
#define SLIM_TOKEN_A1OID_id_at_serialNumber	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_at_serialNumber))
#define SLIM_TKOFF_A1OID_id_at_pseudonym	(SLIM_TKOFF_BASE_A1OID0 + 42)
#define SLIM_TKNAM_A1OID_id_at_pseudonym	(SLIM_TKNAM_BASE_A1OID0 + 42)
#define SLIM_TKLEN_A1OID_id_at_pseudonym	(3)
#define SLIM_TOKEN_A1OID_id_at_pseudonym	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_at_pseudonym))
#define SLIM_TKOFF_A1OID_id_domainComponent	(SLIM_TKOFF_BASE_A1OID0 + 45)
#define SLIM_TKNAM_A1OID_id_domainComponent	(SLIM_TKNAM_BASE_A1OID0 + 45)
#define SLIM_TKLEN_A1OID_id_domainComponent	(10)
#define SLIM_TOKEN_A1OID_id_domainComponent	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_domainComponent))
#define SLIM_TKOFF_A1OID_id_ce_subjectDirectoryAttributes	(SLIM_TKOFF_BASE_A1OID0 + 55)
#define SLIM_TKNAM_A1OID_id_ce_subjectDirectoryAttributes	(SLIM_TKNAM_BASE_A1OID0 + 55)
#define SLIM_TKLEN_A1OID_id_ce_subjectDirectoryAttributes	(3)
#define SLIM_TOKEN_A1OID_id_ce_subjectDirectoryAttributes	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_subjectDirectoryAttributes))
#define SLIM_TKOFF_A1OID_id_ce_subjectKeyIdentifier	(SLIM_TKOFF_BASE_A1OID0 + 58)
#define SLIM_TKNAM_A1OID_id_ce_subjectKeyIdentifier	(SLIM_TKNAM_BASE_A1OID0 + 58)
#define SLIM_TKLEN_A1OID_id_ce_subjectKeyIdentifier	(3)
#define SLIM_TOKEN_A1OID_id_ce_subjectKeyIdentifier	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_subjectKeyIdentifier))
#define SLIM_TKOFF_A1OID_id_ce_keyUsage	(SLIM_TKOFF_BASE_A1OID0 + 61)
#define SLIM_TKNAM_A1OID_id_ce_keyUsage	(SLIM_TKNAM_BASE_A1OID0 + 61)
#define SLIM_TKLEN_A1OID_id_ce_keyUsage	(3)
#define SLIM_TOKEN_A1OID_id_ce_keyUsage	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_keyUsage))
#define SLIM_TKOFF_A1OID_id_ce_privateKeyUsagePeriod	(SLIM_TKOFF_BASE_A1OID0 + 64)
#define SLIM_TKNAM_A1OID_id_ce_privateKeyUsagePeriod	(SLIM_TKNAM_BASE_A1OID0 + 64)
#define SLIM_TKLEN_A1OID_id_ce_privateKeyUsagePeriod	(3)
#define SLIM_TOKEN_A1OID_id_ce_privateKeyUsagePeriod	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_privateKeyUsagePeriod))
#define SLIM_TKOFF_A1OID_id_ce_subjectAltName	(SLIM_TKOFF_BASE_A1OID0 + 67)
#define SLIM_TKNAM_A1OID_id_ce_subjectAltName	(SLIM_TKNAM_BASE_A1OID0 + 67)
#define SLIM_TKLEN_A1OID_id_ce_subjectAltName	(3)
#define SLIM_TOKEN_A1OID_id_ce_subjectAltName	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_subjectAltName))
#define SLIM_TKOFF_A1OID_id_ce_issuerAltName	(SLIM_TKOFF_BASE_A1OID0 + 70)
#define SLIM_TKNAM_A1OID_id_ce_issuerAltName	(SLIM_TKNAM_BASE_A1OID0 + 70)
#define SLIM_TKLEN_A1OID_id_ce_issuerAltName	(3)
#define SLIM_TOKEN_A1OID_id_ce_issuerAltName	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_issuerAltName))
#define SLIM_TKOFF_A1OID_id_ce_basicConstraints	(SLIM_TKOFF_BASE_A1OID0 + 73)
#define SLIM_TKNAM_A1OID_id_ce_basicConstraints	(SLIM_TKNAM_BASE_A1OID0 + 73)
#define SLIM_TKLEN_A1OID_id_ce_basicConstraints	(3)
#define SLIM_TOKEN_A1OID_id_ce_basicConstraints	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_basicConstraints))
#define SLIM_TKOFF_A1OID_id_ce_cRLNumber	(SLIM_TKOFF_BASE_A1OID0 + 76)
#define SLIM_TKNAM_A1OID_id_ce_cRLNumber	(SLIM_TKNAM_BASE_A1OID0 + 76)
#define SLIM_TKLEN_A1OID_id_ce_cRLNumber	(3)
#define SLIM_TOKEN_A1OID_id_ce_cRLNumber	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_cRLNumber))
#define SLIM_TKOFF_A1OID_id_ce_cRLReason	(SLIM_TKOFF_BASE_A1OID0 + 79)
#define SLIM_TKNAM_A1OID_id_ce_cRLReason	(SLIM_TKNAM_BASE_A1OID0 + 79)
#define SLIM_TKLEN_A1OID_id_ce_cRLReason	(3)
#define SLIM_TOKEN_A1OID_id_ce_cRLReason	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_cRLReason))
#define SLIM_TKOFF_A1OID_id_ce_invalidityDate	(SLIM_TKOFF_BASE_A1OID0 + 82)
#define SLIM_TKNAM_A1OID_id_ce_invalidityDate	(SLIM_TKNAM_BASE_A1OID0 + 82)
#define SLIM_TKLEN_A1OID_id_ce_invalidityDate	(3)
#define SLIM_TOKEN_A1OID_id_ce_invalidityDate	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_invalidityDate))
#define SLIM_TKOFF_A1OID_id_ce_deltaCRLIndicator	(SLIM_TKOFF_BASE_A1OID0 + 85)
#define SLIM_TKNAM_A1OID_id_ce_deltaCRLIndicator	(SLIM_TKNAM_BASE_A1OID0 + 85)
#define SLIM_TKLEN_A1OID_id_ce_deltaCRLIndicator	(3)
#define SLIM_TOKEN_A1OID_id_ce_deltaCRLIndicator	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_deltaCRLIndicator))
#define SLIM_TKOFF_A1OID_id_ce_issuingDistributionPoint	(SLIM_TKOFF_BASE_A1OID0 + 88)
#define SLIM_TKNAM_A1OID_id_ce_issuingDistributionPoint	(SLIM_TKNAM_BASE_A1OID0 + 88)
#define SLIM_TKLEN_A1OID_id_ce_issuingDistributionPoint	(3)
#define SLIM_TOKEN_A1OID_id_ce_issuingDistributionPoint	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_issuingDistributionPoint))
#define SLIM_TKOFF_A1OID_id_ce_certificateIssuer	(SLIM_TKOFF_BASE_A1OID0 + 91)
#define SLIM_TKNAM_A1OID_id_ce_certificateIssuer	(SLIM_TKNAM_BASE_A1OID0 + 91)
#define SLIM_TKLEN_A1OID_id_ce_certificateIssuer	(3)
#define SLIM_TOKEN_A1OID_id_ce_certificateIssuer	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_certificateIssuer))
#define SLIM_TKOFF_A1OID_id_ce_nameConstraints	(SLIM_TKOFF_BASE_A1OID0 + 94)
#define SLIM_TKNAM_A1OID_id_ce_nameConstraints	(SLIM_TKNAM_BASE_A1OID0 + 94)
#define SLIM_TKLEN_A1OID_id_ce_nameConstraints	(3)
#define SLIM_TOKEN_A1OID_id_ce_nameConstraints	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_nameConstraints))
#define SLIM_TKOFF_A1OID_id_ce_cRLDistributionPoints	(SLIM_TKOFF_BASE_A1OID0 + 97)
#define SLIM_TKNAM_A1OID_id_ce_cRLDistributionPoints	(SLIM_TKNAM_BASE_A1OID0 + 97)
#define SLIM_TKLEN_A1OID_id_ce_cRLDistributionPoints	(3)
#define SLIM_TOKEN_A1OID_id_ce_cRLDistributionPoints	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_cRLDistributionPoints))
#define SLIM_TKOFF_A1OID_id_ce_certificatePolicies	(SLIM_TKOFF_BASE_A1OID0 + 100)
#define SLIM_TKNAM_A1OID_id_ce_certificatePolicies	(SLIM_TKNAM_BASE_A1OID0 + 100)
#define SLIM_TKLEN_A1OID_id_ce_certificatePolicies	(3)
#define SLIM_TOKEN_A1OID_id_ce_certificatePolicies	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_certificatePolicies))
#define SLIM_TKOFF_A1OID_id_ce_policyMappings	(SLIM_TKOFF_BASE_A1OID0 + 103)
#define SLIM_TKNAM_A1OID_id_ce_policyMappings	(SLIM_TKNAM_BASE_A1OID0 + 103)
#define SLIM_TKLEN_A1OID_id_ce_policyMappings	(3)
#define SLIM_TOKEN_A1OID_id_ce_policyMappings	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_policyMappings))
#define SLIM_TKOFF_A1OID_id_ce_authorityKeyIdentifier	(SLIM_TKOFF_BASE_A1OID0 + 106)
#define SLIM_TKNAM_A1OID_id_ce_authorityKeyIdentifier	(SLIM_TKNAM_BASE_A1OID0 + 106)
#define SLIM_TKLEN_A1OID_id_ce_authorityKeyIdentifier	(3)
#define SLIM_TOKEN_A1OID_id_ce_authorityKeyIdentifier	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_authorityKeyIdentifier))
#define SLIM_TKOFF_A1OID_id_ce_policyConstraints	(SLIM_TKOFF_BASE_A1OID0 + 109)
#define SLIM_TKNAM_A1OID_id_ce_policyConstraints	(SLIM_TKNAM_BASE_A1OID0 + 109)
#define SLIM_TKLEN_A1OID_id_ce_policyConstraints	(3)
#define SLIM_TOKEN_A1OID_id_ce_policyConstraints	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_policyConstraints))
#define SLIM_TKOFF_A1OID_id_ce_extKeyUsage	(SLIM_TKOFF_BASE_A1OID0 + 112)
#define SLIM_TKNAM_A1OID_id_ce_extKeyUsage	(SLIM_TKNAM_BASE_A1OID0 + 112)
#define SLIM_TKLEN_A1OID_id_ce_extKeyUsage	(3)
#define SLIM_TOKEN_A1OID_id_ce_extKeyUsage	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_extKeyUsage))
#define SLIM_TKOFF_A1OID_id_ce_freshestCRL	(SLIM_TKOFF_BASE_A1OID0 + 115)
#define SLIM_TKNAM_A1OID_id_ce_freshestCRL	(SLIM_TKNAM_BASE_A1OID0 + 115)
#define SLIM_TKLEN_A1OID_id_ce_freshestCRL	(3)
#define SLIM_TOKEN_A1OID_id_ce_freshestCRL	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_freshestCRL))
#define SLIM_TKOFF_A1OID_id_ce_inhibitAnyPolicy	(SLIM_TKOFF_BASE_A1OID0 + 118)
#define SLIM_TKNAM_A1OID_id_ce_inhibitAnyPolicy	(SLIM_TKNAM_BASE_A1OID0 + 118)
#define SLIM_TKLEN_A1OID_id_ce_inhibitAnyPolicy	(3)
#define SLIM_TOKEN_A1OID_id_ce_inhibitAnyPolicy	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ce_inhibitAnyPolicy))
#define SLIM_TKOFF_A1OID_id_pe_authorityInfoAccess	(SLIM_TKOFF_BASE_A1OID0 + 121)
#define SLIM_TKNAM_A1OID_id_pe_authorityInfoAccess	(SLIM_TKNAM_BASE_A1OID0 + 121)
#define SLIM_TKLEN_A1OID_id_pe_authorityInfoAccess	(8)
#define SLIM_TOKEN_A1OID_id_pe_authorityInfoAccess	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_pe_authorityInfoAccess))
#define SLIM_TKOFF_A1OID_id_pe_subjectInfoAccess	(SLIM_TKOFF_BASE_A1OID0 + 129)
#define SLIM_TKNAM_A1OID_id_pe_subjectInfoAccess	(SLIM_TKNAM_BASE_A1OID0 + 129)
#define SLIM_TKLEN_A1OID_id_pe_subjectInfoAccess	(8)
#define SLIM_TOKEN_A1OID_id_pe_subjectInfoAccess	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_pe_subjectInfoAccess))
#define SLIM_TKOFF_A1OID_id_ad_ocsp	(SLIM_TKOFF_BASE_A1OID0 + 137)
#define SLIM_TKNAM_A1OID_id_ad_ocsp	(SLIM_TKNAM_BASE_A1OID0 + 137)
#define SLIM_TKLEN_A1OID_id_ad_ocsp	(8)
#define SLIM_TOKEN_A1OID_id_ad_ocsp	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ad_ocsp))
#define SLIM_TKOFF_A1OID_id_ad_caIssuers	(SLIM_TKOFF_BASE_A1OID0 + 145)
#define SLIM_TKNAM_A1OID_id_ad_caIssuers	(SLIM_TKNAM_BASE_A1OID0 + 145)
#define SLIM_TKLEN_A1OID_id_ad_caIssuers	(8)
#define SLIM_TOKEN_A1OID_id_ad_caIssuers	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ad_caIssuers))
#define SLIM_TKOFF_A1OID_id_ad_timeStamping	(SLIM_TKOFF_BASE_A1OID0 + 153)
#define SLIM_TKNAM_A1OID_id_ad_timeStamping	(SLIM_TKNAM_BASE_A1OID0 + 153)
#define SLIM_TKLEN_A1OID_id_ad_timeStamping	(8)
#define SLIM_TOKEN_A1OID_id_ad_timeStamping	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ad_timeStamping))
#define SLIM_TKOFF_A1OID_id_ad_caRepository	(SLIM_TKOFF_BASE_A1OID0 + 161)
#define SLIM_TKNAM_A1OID_id_ad_caRepository	(SLIM_TKNAM_BASE_A1OID0 + 161)
#define SLIM_TKLEN_A1OID_id_ad_caRepository	(8)
#define SLIM_TOKEN_A1OID_id_ad_caRepository	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_ad_caRepository))
#define SLIM_TKOFF_A1OID_rsaEncryption	(SLIM_TKOFF_BASE_A1OID0 + 169)
#define SLIM_TKNAM_A1OID_rsaEncryption	(SLIM_TKNAM_BASE_A1OID0 + 169)
#define SLIM_TKLEN_A1OID_rsaEncryption	(9)
#define SLIM_TOKEN_A1OID_rsaEncryption	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_rsaEncryption))
#define SLIM_TKOFF_A1OID_md2WithRSAEncryption	(SLIM_TKOFF_BASE_A1OID0 + 178)
#define SLIM_TKNAM_A1OID_md2WithRSAEncryption	(SLIM_TKNAM_BASE_A1OID0 + 178)
#define SLIM_TKLEN_A1OID_md2WithRSAEncryption	(9)
#define SLIM_TOKEN_A1OID_md2WithRSAEncryption	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_md2WithRSAEncryption))
#define SLIM_TKOFF_A1OID_md5WithRSAEncryption	(SLIM_TKOFF_BASE_A1OID0 + 187)
#define SLIM_TKNAM_A1OID_md5WithRSAEncryption	(SLIM_TKNAM_BASE_A1OID0 + 187)
#define SLIM_TKLEN_A1OID_md5WithRSAEncryption	(9)
#define SLIM_TOKEN_A1OID_md5WithRSAEncryption	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_md5WithRSAEncryption))
#define SLIM_TKOFF_A1OID_sha1WithRSAEncryption	(SLIM_TKOFF_BASE_A1OID0 + 196)
#define SLIM_TKNAM_A1OID_sha1WithRSAEncryption	(SLIM_TKNAM_BASE_A1OID0 + 196)
#define SLIM_TKLEN_A1OID_sha1WithRSAEncryption	(9)
#define SLIM_TOKEN_A1OID_sha1WithRSAEncryption	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_sha1WithRSAEncryption))
#define SLIM_TKOFF_A1OID_id_sha1	(SLIM_TKOFF_BASE_A1OID0 + 205)
#define SLIM_TKNAM_A1OID_id_sha1	(SLIM_TKNAM_BASE_A1OID0 + 205)
#define SLIM_TKLEN_A1OID_id_sha1	(5)
#define SLIM_TOKEN_A1OID_id_sha1	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_sha1))
#define SLIM_TKOFF_A1OID_id_md2	(SLIM_TKOFF_BASE_A1OID0 + 210)
#define SLIM_TKNAM_A1OID_id_md2	(SLIM_TKNAM_BASE_A1OID0 + 210)
#define SLIM_TKLEN_A1OID_id_md2	(8)
#define SLIM_TOKEN_A1OID_id_md2	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_md2))
#define SLIM_TKOFF_A1OID_id_md5	(SLIM_TKOFF_BASE_A1OID0 + 218)
#define SLIM_TKNAM_A1OID_id_md5	(SLIM_TKNAM_BASE_A1OID0 + 218)
#define SLIM_TKLEN_A1OID_id_md5	(8)
#define SLIM_TOKEN_A1OID_id_md5	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_id_md5))
#define SLIM_TKOFF_A1OID_pkcs_9_1_at_emailAddress	(SLIM_TKOFF_BASE_A1OID0 + 226)
#define SLIM_TKNAM_A1OID_pkcs_9_1_at_emailAddress	(SLIM_TKNAM_BASE_A1OID0 + 226)
#define SLIM_TKLEN_A1OID_pkcs_9_1_at_emailAddress	(9)
#define SLIM_TOKEN_A1OID_pkcs_9_1_at_emailAddress	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pkcs_9_1_at_emailAddress))
#define SLIM_TKOFF_A1OID_pkcs_9_3_at_contentType	(SLIM_TKOFF_BASE_A1OID0 + 235)
#define SLIM_TKNAM_A1OID_pkcs_9_3_at_contentType	(SLIM_TKNAM_BASE_A1OID0 + 235)
#define SLIM_TKLEN_A1OID_pkcs_9_3_at_contentType	(9)
#define SLIM_TOKEN_A1OID_pkcs_9_3_at_contentType	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pkcs_9_3_at_contentType))
#define SLIM_TKOFF_A1OID_pkcs_9_4_at_messageDigest	(SLIM_TKOFF_BASE_A1OID0 + 244)
#define SLIM_TKNAM_A1OID_pkcs_9_4_at_messageDigest	(SLIM_TKNAM_BASE_A1OID0 + 244)
#define SLIM_TKLEN_A1OID_pkcs_9_4_at_messageDigest	(9)
#define SLIM_TOKEN_A1OID_pkcs_9_4_at_messageDigest	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pkcs_9_4_at_messageDigest))
#define SLIM_TKOFF_A1OID_pkcs_9_5_at_signingTime	(SLIM_TKOFF_BASE_A1OID0 + 253)
#define SLIM_TKNAM_A1OID_pkcs_9_5_at_signingTime	(SLIM_TKNAM_BASE_A1OID0 + 253)
#define SLIM_TKLEN_A1OID_pkcs_9_5_at_signingTime	(9)
#define SLIM_TOKEN_A1OID_pkcs_9_5_at_signingTime	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pkcs_9_5_at_signingTime))
#define SLIM_TKOFF_A1OID_pkcs_9_at_friendlyName	(SLIM_TKOFF_BASE_A1OID0 + 262)
#define SLIM_TKNAM_A1OID_pkcs_9_at_friendlyName	(SLIM_TKNAM_BASE_A1OID0 + 262)
#define SLIM_TKLEN_A1OID_pkcs_9_at_friendlyName	(9)
#define SLIM_TOKEN_A1OID_pkcs_9_at_friendlyName	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pkcs_9_at_friendlyName))
#define SLIM_TKOFF_A1OID_pkcs_9_at_localKeyId	(SLIM_TKOFF_BASE_A1OID0 + 271)
#define SLIM_TKNAM_A1OID_pkcs_9_at_localKeyId	(SLIM_TKNAM_BASE_A1OID0 + 271)
#define SLIM_TKLEN_A1OID_pkcs_9_at_localKeyId	(9)
#define SLIM_TOKEN_A1OID_pkcs_9_at_localKeyId	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pkcs_9_at_localKeyId))
#define SLIM_TKOFF_A1OID_pkcs_9_at_randomNonce	(SLIM_TKOFF_BASE_A1OID0 + 280)
#define SLIM_TKNAM_A1OID_pkcs_9_at_randomNonce	(SLIM_TKNAM_BASE_A1OID0 + 280)
#define SLIM_TKLEN_A1OID_pkcs_9_at_randomNonce	(9)
#define SLIM_TOKEN_A1OID_pkcs_9_at_randomNonce	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pkcs_9_at_randomNonce))
#define SLIM_TKOFF_A1OID_pkcs_9_at_sequenceNumber	(SLIM_TKOFF_BASE_A1OID0 + 289)
#define SLIM_TKNAM_A1OID_pkcs_9_at_sequenceNumber	(SLIM_TKNAM_BASE_A1OID0 + 289)
#define SLIM_TKLEN_A1OID_pkcs_9_at_sequenceNumber	(9)
#define SLIM_TOKEN_A1OID_pkcs_9_at_sequenceNumber	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pkcs_9_at_sequenceNumber))
#define SLIM_TKOFF_A1OID_sha_1WithRSAEncription	(SLIM_TKOFF_BASE_A1OID0 + 298)
#define SLIM_TKNAM_A1OID_sha_1WithRSAEncription	(SLIM_TKNAM_BASE_A1OID0 + 298)
#define SLIM_TKLEN_A1OID_sha_1WithRSAEncription	(5)
#define SLIM_TOKEN_A1OID_sha_1WithRSAEncription	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_sha_1WithRSAEncription))
#define SLIM_TKOFF_BASE_A1OID1	(SLIM_TKOFF_BASE_A1OID0 + 303)
#define SLIM_TKNAM_BASE_A1OID1	(SLIM_TKNAM_BASE_A1OID0 + SLIM_TKOFF_BASE_A1OID1)
#ifdef SLIM_CONFIG_USE_PKCS12
#define SLIM_TKOFF_A1OID_pbe_SHA_128BitRC4	(SLIM_TKOFF_BASE_A1OID1 + 0)
#define SLIM_TKNAM_A1OID_pbe_SHA_128BitRC4	(SLIM_TKNAM_BASE_A1OID1 + 0)
#define SLIM_TKLEN_A1OID_pbe_SHA_128BitRC4	(10)
#define SLIM_TOKEN_A1OID_pbe_SHA_128BitRC4	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pbe_SHA_128BitRC4))
#define SLIM_TKOFF_A1OID_pbe_SHA_40BitRC4	(SLIM_TKOFF_BASE_A1OID1 + 10)
#define SLIM_TKNAM_A1OID_pbe_SHA_40BitRC4	(SLIM_TKNAM_BASE_A1OID1 + 10)
#define SLIM_TKLEN_A1OID_pbe_SHA_40BitRC4	(10)
#define SLIM_TOKEN_A1OID_pbe_SHA_40BitRC4	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pbe_SHA_40BitRC4))
#define SLIM_TKOFF_A1OID_pbe_SHA_3KeyTripleDES_CBC	(SLIM_TKOFF_BASE_A1OID1 + 20)
#define SLIM_TKNAM_A1OID_pbe_SHA_3KeyTripleDES_CBC	(SLIM_TKNAM_BASE_A1OID1 + 20)
#define SLIM_TKLEN_A1OID_pbe_SHA_3KeyTripleDES_CBC	(10)
#define SLIM_TOKEN_A1OID_pbe_SHA_3KeyTripleDES_CBC	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pbe_SHA_3KeyTripleDES_CBC))
#define SLIM_TKOFF_A1OID_pbe_SHA_2KeyTripleDES_CBC	(SLIM_TKOFF_BASE_A1OID1 + 30)
#define SLIM_TKNAM_A1OID_pbe_SHA_2KeyTripleDES_CBC	(SLIM_TKNAM_BASE_A1OID1 + 30)
#define SLIM_TKLEN_A1OID_pbe_SHA_2KeyTripleDES_CBC	(10)
#define SLIM_TOKEN_A1OID_pbe_SHA_2KeyTripleDES_CBC	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pbe_SHA_2KeyTripleDES_CBC))
#define SLIM_TKOFF_A1OID_pbe_SHA_128BitRC2_CBC	(SLIM_TKOFF_BASE_A1OID1 + 40)
#define SLIM_TKNAM_A1OID_pbe_SHA_128BitRC2_CBC	(SLIM_TKNAM_BASE_A1OID1 + 40)
#define SLIM_TKLEN_A1OID_pbe_SHA_128BitRC2_CBC	(10)
#define SLIM_TOKEN_A1OID_pbe_SHA_128BitRC2_CBC	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pbe_SHA_128BitRC2_CBC))
#define SLIM_TKOFF_A1OID_pbe_SHA_40BitRC2_CBC	(SLIM_TKOFF_BASE_A1OID1 + 50)
#define SLIM_TKNAM_A1OID_pbe_SHA_40BitRC2_CBC	(SLIM_TKNAM_BASE_A1OID1 + 50)
#define SLIM_TKLEN_A1OID_pbe_SHA_40BitRC2_CBC	(10)
#define SLIM_TOKEN_A1OID_pbe_SHA_40BitRC2_CBC	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pbe_SHA_40BitRC2_CBC))
#define SLIM_TKOFF_A1OID_keyBag	(SLIM_TKOFF_BASE_A1OID1 + 60)
#define SLIM_TKNAM_A1OID_keyBag	(SLIM_TKNAM_BASE_A1OID1 + 60)
#define SLIM_TKLEN_A1OID_keyBag	(11)
#define SLIM_TOKEN_A1OID_keyBag	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_keyBag))
#define SLIM_TKOFF_A1OID_pkcs8ShroudedKeyBag	(SLIM_TKOFF_BASE_A1OID1 + 71)
#define SLIM_TKNAM_A1OID_pkcs8ShroudedKeyBag	(SLIM_TKNAM_BASE_A1OID1 + 71)
#define SLIM_TKLEN_A1OID_pkcs8ShroudedKeyBag	(11)
#define SLIM_TOKEN_A1OID_pkcs8ShroudedKeyBag	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pkcs8ShroudedKeyBag))
#define SLIM_TKOFF_A1OID_certBag	(SLIM_TKOFF_BASE_A1OID1 + 82)
#define SLIM_TKNAM_A1OID_certBag	(SLIM_TKNAM_BASE_A1OID1 + 82)
#define SLIM_TKLEN_A1OID_certBag	(11)
#define SLIM_TOKEN_A1OID_certBag	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_certBag))
#define SLIM_TKOFF_A1OID_crlBag	(SLIM_TKOFF_BASE_A1OID1 + 93)
#define SLIM_TKNAM_A1OID_crlBag	(SLIM_TKNAM_BASE_A1OID1 + 93)
#define SLIM_TKLEN_A1OID_crlBag	(11)
#define SLIM_TOKEN_A1OID_crlBag	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_crlBag))
#define SLIM_TKOFF_A1OID_secretBag	(SLIM_TKOFF_BASE_A1OID1 + 104)
#define SLIM_TKNAM_A1OID_secretBag	(SLIM_TKNAM_BASE_A1OID1 + 104)
#define SLIM_TKLEN_A1OID_secretBag	(11)
#define SLIM_TOKEN_A1OID_secretBag	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_secretBag))
#define SLIM_TKOFF_A1OID_safeContentsBag	(SLIM_TKOFF_BASE_A1OID1 + 115)
#define SLIM_TKNAM_A1OID_safeContentsBag	(SLIM_TKNAM_BASE_A1OID1 + 115)
#define SLIM_TKLEN_A1OID_safeContentsBag	(11)
#define SLIM_TOKEN_A1OID_safeContentsBag	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_safeContentsBag))
#define SLIM_TKOFF_A1OID_x509Certificate	(SLIM_TKOFF_BASE_A1OID1 + 126)
#define SLIM_TKNAM_A1OID_x509Certificate	(SLIM_TKNAM_BASE_A1OID1 + 126)
#define SLIM_TKLEN_A1OID_x509Certificate	(10)
#define SLIM_TOKEN_A1OID_x509Certificate	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_x509Certificate))
#define SLIM_TKOFF_A1OID_sdsiCertificate	(SLIM_TKOFF_BASE_A1OID1 + 136)
#define SLIM_TKNAM_A1OID_sdsiCertificate	(SLIM_TKNAM_BASE_A1OID1 + 136)
#define SLIM_TKLEN_A1OID_sdsiCertificate	(10)
#define SLIM_TOKEN_A1OID_sdsiCertificate	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_sdsiCertificate))
#define SLIM_TKOFF_A1OID_x509CRL	(SLIM_TKOFF_BASE_A1OID1 + 146)
#define SLIM_TKNAM_A1OID_x509CRL	(SLIM_TKNAM_BASE_A1OID1 + 146)
#define SLIM_TKLEN_A1OID_x509CRL	(10)
#define SLIM_TOKEN_A1OID_x509CRL	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_x509CRL))
#define SLIM_TKOFF_BASE_A1OID2	(SLIM_TKOFF_BASE_A1OID1 + 156)
#else /* SLIM_CONFIG_USE_PKCS12 */
#define SLIM_TKOFF_BASE_A1OID2	(SLIM_TKOFF_BASE_A1OID1)
#endif /* SLIM_CONFIG_USE_PKCS12 */
#define SLIM_TKNAM_BASE_A1OID2	(SLIM_TKNAM_BASE_A1OID0 + SLIM_TKOFF_BASE_A1OID2)
#ifdef SLIM_CONFIG_USE_PKCS5
#define SLIM_TKOFF_A1OID_pkcs_5_1_pbeWithMD2AndDES_CBC	(SLIM_TKOFF_BASE_A1OID2 + 0)
#define SLIM_TKNAM_A1OID_pkcs_5_1_pbeWithMD2AndDES_CBC	(SLIM_TKNAM_BASE_A1OID2 + 0)
#define SLIM_TKLEN_A1OID_pkcs_5_1_pbeWithMD2AndDES_CBC	(9)
#define SLIM_TOKEN_A1OID_pkcs_5_1_pbeWithMD2AndDES_CBC	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pkcs_5_1_pbeWithMD2AndDES_CBC))
#define SLIM_TKOFF_A1OID_pkcs_5_3_pbeWithMD5AndDES_CBC	(SLIM_TKOFF_BASE_A1OID2 + 9)
#define SLIM_TKNAM_A1OID_pkcs_5_3_pbeWithMD5AndDES_CBC	(SLIM_TKNAM_BASE_A1OID2 + 9)
#define SLIM_TKLEN_A1OID_pkcs_5_3_pbeWithMD5AndDES_CBC	(9)
#define SLIM_TOKEN_A1OID_pkcs_5_3_pbeWithMD5AndDES_CBC	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pkcs_5_3_pbeWithMD5AndDES_CBC))
#define SLIM_TKOFF_A1OID_pkcs_5_4_pbeWithMD2AndRC2_CBC	(SLIM_TKOFF_BASE_A1OID2 + 18)
#define SLIM_TKNAM_A1OID_pkcs_5_4_pbeWithMD2AndRC2_CBC	(SLIM_TKNAM_BASE_A1OID2 + 18)
#define SLIM_TKLEN_A1OID_pkcs_5_4_pbeWithMD2AndRC2_CBC	(9)
#define SLIM_TOKEN_A1OID_pkcs_5_4_pbeWithMD2AndRC2_CBC	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pkcs_5_4_pbeWithMD2AndRC2_CBC))
#define SLIM_TKOFF_A1OID_pkcs_5_6_pbeWithMD5AndRC2_CBC	(SLIM_TKOFF_BASE_A1OID2 + 27)
#define SLIM_TKNAM_A1OID_pkcs_5_6_pbeWithMD5AndRC2_CBC	(SLIM_TKNAM_BASE_A1OID2 + 27)
#define SLIM_TKLEN_A1OID_pkcs_5_6_pbeWithMD5AndRC2_CBC	(9)
#define SLIM_TOKEN_A1OID_pkcs_5_6_pbeWithMD5AndRC2_CBC	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pkcs_5_6_pbeWithMD5AndRC2_CBC))
#define SLIM_TKOFF_A1OID_pkcs_5_10_pbeWithSHA1AndDES_CBC	(SLIM_TKOFF_BASE_A1OID2 + 36)
#define SLIM_TKNAM_A1OID_pkcs_5_10_pbeWithSHA1AndDES_CBC	(SLIM_TKNAM_BASE_A1OID2 + 36)
#define SLIM_TKLEN_A1OID_pkcs_5_10_pbeWithSHA1AndDES_CBC	(9)
#define SLIM_TOKEN_A1OID_pkcs_5_10_pbeWithSHA1AndDES_CBC	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pkcs_5_10_pbeWithSHA1AndDES_CBC))
#define SLIM_TKOFF_A1OID_pkcs_5_11_pbeWithSHA1AndRC2_CBC	(SLIM_TKOFF_BASE_A1OID2 + 45)
#define SLIM_TKNAM_A1OID_pkcs_5_11_pbeWithSHA1AndRC2_CBC	(SLIM_TKNAM_BASE_A1OID2 + 45)
#define SLIM_TKLEN_A1OID_pkcs_5_11_pbeWithSHA1AndRC2_CBC	(9)
#define SLIM_TOKEN_A1OID_pkcs_5_11_pbeWithSHA1AndRC2_CBC	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_pkcs_5_11_pbeWithSHA1AndRC2_CBC))
#define SLIM_TKOFF_BASE_A1OID3	(SLIM_TKOFF_BASE_A1OID2 + 54)
#else /* SLIM_CONFIG_USE_PKCS5 */
#define SLIM_TKOFF_BASE_A1OID3	(SLIM_TKOFF_BASE_A1OID2)
#endif /* SLIM_CONFIG_USE_PKCS5 */
#define SLIM_TKNAM_BASE_A1OID3	(SLIM_TKNAM_BASE_A1OID0 + SLIM_TKOFF_BASE_A1OID3)
#ifdef SLIM_CONFIG_USE_PKCS7
#define SLIM_TKOFF_A1OID_data	(SLIM_TKOFF_BASE_A1OID3 + 0)
#define SLIM_TKNAM_A1OID_data	(SLIM_TKNAM_BASE_A1OID3 + 0)
#define SLIM_TKLEN_A1OID_data	(9)
#define SLIM_TOKEN_A1OID_data	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_data))
#define SLIM_TKOFF_A1OID_signedData	(SLIM_TKOFF_BASE_A1OID3 + 9)
#define SLIM_TKNAM_A1OID_signedData	(SLIM_TKNAM_BASE_A1OID3 + 9)
#define SLIM_TKLEN_A1OID_signedData	(9)
#define SLIM_TOKEN_A1OID_signedData	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_signedData))
#define SLIM_TKOFF_A1OID_envelopedData	(SLIM_TKOFF_BASE_A1OID3 + 18)
#define SLIM_TKNAM_A1OID_envelopedData	(SLIM_TKNAM_BASE_A1OID3 + 18)
#define SLIM_TKLEN_A1OID_envelopedData	(9)
#define SLIM_TOKEN_A1OID_envelopedData	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_envelopedData))
#define SLIM_TKOFF_A1OID_signedAndEnvelopedData	(SLIM_TKOFF_BASE_A1OID3 + 27)
#define SLIM_TKNAM_A1OID_signedAndEnvelopedData	(SLIM_TKNAM_BASE_A1OID3 + 27)
#define SLIM_TKLEN_A1OID_signedAndEnvelopedData	(9)
#define SLIM_TOKEN_A1OID_signedAndEnvelopedData	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_signedAndEnvelopedData))
#define SLIM_TKOFF_A1OID_digestedData	(SLIM_TKOFF_BASE_A1OID3 + 36)
#define SLIM_TKNAM_A1OID_digestedData	(SLIM_TKNAM_BASE_A1OID3 + 36)
#define SLIM_TKLEN_A1OID_digestedData	(9)
#define SLIM_TOKEN_A1OID_digestedData	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_digestedData))
#define SLIM_TKOFF_A1OID_encryptedData	(SLIM_TKOFF_BASE_A1OID3 + 45)
#define SLIM_TKNAM_A1OID_encryptedData	(SLIM_TKNAM_BASE_A1OID3 + 45)
#define SLIM_TKLEN_A1OID_encryptedData	(9)
#define SLIM_TOKEN_A1OID_encryptedData	(ASN1OIDInfo_GetItem(SLIM_TKID_A1OID_encryptedData))
#define SLIM_TKOFF_BASE_A1OID4	(SLIM_TKOFF_BASE_A1OID3 + 54)
#else /* SLIM_CONFIG_USE_PKCS7 */
#define SLIM_TKOFF_BASE_A1OID4	(SLIM_TKOFF_BASE_A1OID3)
#endif /* SLIM_CONFIG_USE_PKCS7 */
#define SLIM_TKNAM_BASE_A1OID4	(SLIM_TKNAM_BASE_A1OID0 + SLIM_TKOFF_BASE_A1OID4)
#define SLIM_TKLEN_TOTAL_A1OID	SLIM_TKOFF_BASE_A1OID4

extern SLIM_ROM slim_char cSlim_TokenName_A1OID[SLIM_TKLEN_TOTAL_A1OID];

extern SLIM_ROM TASN1OIDInfo cSlim_Token_A1OID[SLIM_TOKEN_A1OID_TOKENS];
#define ASN1OIDInfo_GetItem(id)		((TASN1OIDInfo *)&cSlim_Token_A1OID[(id)])
#define ASN1OIDInfo_GetItemName(id)	((slim_char *)cSlim_TokenName_A1OID + ((TToken *)&cSlim_Token_A1OID[(id)])->fOffset)
#define ASN1OIDInfo_GetItemNameLen(id)	(((TToken *)&cSlim_Token_A1OID[(id)])->fLength)

TASN1OIDInfo *ASN1OIDInfo_CaseFindSS(slim_char *in_s, slim_int in_slen);

SLIM_END_C_LINKAGE
#endif
